### PR TITLE
fix: Handle django-cache script so it could run in dragonfly

### LINKED ISSUE #6119: simplify lua_undeclared_keys_shas management
1. move known shas from lua_undeclared_keys_shas to hardcoded table.
2. move lua_force_atomicity_shas to hardcoded table.
3. add 8c4dafdf9b6b7bcf511a0d1ec0518bed9260e16d to the table as well (django-ops)

### PR DESCRIPTION
**Pull request by romange**
automatically.

Fixes #6119

### CODE REVIEW

File: src/server/multi_test.cc [hunk 1]
```diff
@@ -1254,29 +1251,6 @@ TEST_F(MultiTest, EvalShaRo) {
   EXPECT_THAT(resp, ErrArg("Write commands are not allowed from read-only scripts"));
 }
 
-TEST_F(MultiTest, ForceAtomicityFlag) {
```
Comment (romange) [inline src/server/multi_test.cc:1257]: removed as we do not need this feature anymore.

**Review by vyavdoshenko — APPROVED** [review]
lgtm
