### PR TITLE
fix: properly clean tiered state upon flash

### LINKED ISSUE #3252: check-fail in tiering
```
38685➜ Check failure stack trace: ***
38685➜    @     0x556a9fa3585f  google::LogMessageFatal::~LogMessageFatal()
38685➜    @     0x556a9f85e5b8  dfly::tiering::SmallBins::Stash()
38685➜    @     0x556a9f7192a6  dfly::TieredStorage::Stash()
38685➜    @     0x556a9f719846  dfly::TieredStorage::RunOffloading()
38685➜    @     0x556a9f76dd90  dfly::EngineShard::Heartbeat()
38685➜    @     0x556a9f76ee60  dfly::EngineShard::RunPeriodic()
```
source https://github.com/dragonflydb/dragonfly/actions/runs/9745085780/job/26892171819#step:12:658

### PR DESCRIPTION
**Pull request by romange**
The bug was around io pending entries that have not been properly cleaned during flush. This PR simplified the logic around tiered storage handling during flush, it always performs the cleaning in the synchronous part of the command.

In addition, this PR improves error logging in tests if dragonfly process exits with an error. Finally, a test is added that makes sure pending tiered items are flushed during the flash call.

Fixes #3252

### CODE REVIEW

File: src/server/dragonfly_test.cc [hunk 1]
```diff
@@ -362,6 +362,13 @@ TEST_F(DflyEngineTest, MemcacheFlags) {
   ASSERT_EQ(resp, "OK");
   MCResponse resp2 = RunMC(MP::GET, "key");
   EXPECT_THAT(resp2, ElementsAre("VALUE key 42 3", "bar", "END"));
+
```
Comment (romange) [inline src/server/dragonfly_test.cc:365]: just to test that flushdb clears the flags.

File: src/server/tiered_storage.cc [hunk 2]
```diff
@@ -61,24 +61,24 @@ class TieredStorage::ShardOpManager : public tiering::OpManager {
   }
 
   // Called before overriding value with segment
-  void RecordAdded(DbTableStats* stats, const PrimeValue& pv, tiering::DiskSegment segment) {
+  void RecordAdded(DbTableStats* stats, const PrimeValue& pv, size_t tiered_len) {
```
Comment (romange) [inline src/server/tiered_storage.cc:64]: no functional changes, just interface syntactic changes

File: src/server/db_slice.cc [hunk 3]
```diff
@@ -1408,27 +1402,35 @@ void DbSlice::InvalidateSlotWatches(const cluster::SlotSet& slot_ids) {
...
+    } while (cursor);
 
+    CHECK_EQ(db_ptr->stats.tiered_entries, 0u);
+#if 0
     // Wait for delete operations to finish in sync
     while (!async && db_ptr->stats.tiered_entries > 0) {
       LOG_EVERY_T(ERROR, 0.5) << "Long wait for tiered entry delete on flush";
       ThisFiber::SleepFor(1ms);
     }
+#endif
```
Comment (dranikpg) [inline src/server/db_slice.cc:1433]: NOTE: If a read is in progress, you're delete won't be completed immediately

**Review by dranikpg — DISMISSED** [review]
Good catch. But please see the possible check fail

File: src/server/db_slice.cc (hunk 3 above)
Comment (dranikpg) [reply src/server/db_slice.cc:1433]: it has to be zero, because otherwise we clean the db table stats and they become broken

Comment (romange) [reply src/server/db_slice.cc:1433]: @dranikpg thanks, I was not sure about this.
indeed, it may be asynchronous due to pending reads.

I think calling `RecordDeleted` inside SetInMemory is somewhat fragile because `cache_fetched_` may be false, or `IsSnaphotInProgress` can be true and then we never call SetInMemory. Seems more tests around read/delete interactions are needed.

File: src/server/tiered_storage.cc [hunk 4]
```diff
@@ -129,25 +113,7 @@ class TieredStorage::ShardOpManager : public tiering::OpManager {
...
-        continue;
-
-      stats_.total_defrags++;
-
-      // Cut out relevant part of value and restore it to memory
-      string_view sub_value = value.substr(sub_segment.offset - segment.offset, sub_segment.length);
-      SetInMemory(&it->second, dbid, sub_value, sub_segment);
-    }
-  }
+  void Defragment(tiering::DiskSegment segment, string_view value);
```
Comment (romange) [inline src/server/tiered_storage.cc:116]: took the implementation outside

File: src/server/tiered_storage.cc [hunk 5]
```diff
@@ -159,21 +125,7 @@ class TieredStorage::ShardOpManager : public tiering::OpManager {
...
-    if (!modified && !cache_fetched_)
-      return false;
-
-    if (SliceSnapshot::IsSnaphotInProgress())
-      return false;
-
-    SetInMemory(get<OpManager::KeyRef>(id), value, segment);
-    return true;
-  }
+                     bool modified) override;
```
Comment (romange) [inline src/server/tiered_storage.cc:128]: took the implementation outside

**Review by dranikpg — APPROVED** [review]
