### PR TITLE
bug(server): emulate readonly command

### LINKED ISSUE #1003: Cluster emulation : READONLY not implemented
**Describe the bug**
The READONLY command in cluster emulated mode is not implemented, which can generated some migration issues because some libraries use READONLY command just after starting the redis connection to evaluate the possibility to reach a slave replica if needed (for exemple https://github.com/mediocregopher/radix).

**To Reproduce**
1. Start dragonflydb on cluster mode emulated
2. Execute READONLY command
3. see error : (error) unknown command `READONLY`

How i found it : 
I have a project that use https://github.com/mediocregopher/radix with a rediscluster config and tried to migrate to dragonglydb without code rework. At connection I get the error (error) unknown command `READONLY`.

**Expected behavior**
Get "OK" 

**Environment (please complete the following information):**

 - Containerized?:  Docker Compose
 - Dragonfly Version: v1.0.0

### PR DESCRIPTION
**Pull request by ashotland**
For cluster mode.
Simply return OK.

Fixes #1003

### CODE REVIEW

File: src/server/server_family.cc [hunk 1]
```diff
@@ -1262,6 +1264,9 @@ void ServerFamily::Cluster(CmdArgList args, ConnectionContext* cntx) {
     std::string msg = BuildClusterNodeReply(cntx);
     (*cntx)->SendBulkString(msg);
     return;
+  } else if (sub_cmd == "READONLY") {
+    (*cntx)->SendOk();
```
Comment (romange) [inline src/server/server_family.cc:1268]: you have not checked with https://github.com/mediocregopher/radix that it works are not you? :)

it does not fix the issue because this is not a subcommand. it's a separate command that exists only in cluster mode. so you need to register it conditionally only if we run in emulated mode.

Comment (ashotland) [reply src/server/server_family.cc:1268]: correct, have not tested with radix.

File: src/server/server_family.cc [hunk 2]
```diff
@@ -42,6 +42,7 @@ extern "C" {
 #include "server/tiered_storage.h"
 #include "server/transaction.h"
 #include "server/version.h"
+#include "server_family.h"
```
Comment (romange) [inline src/server/server_family.cc:45]: no need

**Review by romange — APPROVED** [review]
