### PR TITLE
chore: Fix all clang build warnings

### LINKED ISSUE #4449: Eliminate clang warnings
`$title`

### PR DESCRIPTION
**Pull request by chakaz**
Also add `-Werror` to clang build in CI.

Fixes #4449

### CODE REVIEW

**Comment by adiholden** [comment]
@chakaz what are the changes in helio?

**Comment by chakaz** [comment]
> @chakaz what are the changes in helio?

https://github.com/romange/helio/pull/372

Without which we can't enable `-Werror` with clang

**Comment by adiholden** [comment]
> > @chakaz what are the changes in helio?
> 
> [romange/helio#372](https://github.com/romange/helio/pull/372)
> 
> Without which we can't enable `-Werror` with clang

Ok. The PR changes LGTM. Lets only get @romange approval for pulling latest helio

File: src/server/stream_family.cc [hunk 1]
```diff
@@ -1807,7 +1807,7 @@ void DestroyGroup(facade::CmdArgParser* parser, Transaction* tx, SinkReplyBuilde
   if (parser->HasNext())
     return builder->SendError(UnknownSubCmd("DESTROY", "XGROUP"));
 
-  auto cb = [&](Transaction* t, EngineShard* shard) {
+  auto cb = [&, &key = key, &gname = gname](Transaction* t, EngineShard* shard) {
```
Comment (kostasrim) [inline src/server/stream_family.cc:1810]: pfff captured structure bindings requiring c++20 extension to compile :scream:

**Comment by chakaz** [comment]
@adiholden we have an OK from @romange :partying_face: 
Please approve

**Review by kostasrim — APPROVED** [review]

**Comment by kostasrim** [comment]
> @adiholden we have an OK from @romange 🥳 Please approve

she is away, I accepted it :smile:
