### PR TITLE
refactor client tracking, fix atomicity, squashing and multi/exec

### LINKED ISSUE #2969: Add support for CLIENT OPTIN
This is sent by rueidis. 

Also fixing this will fix the rueidis failed test `TestSingleClientIntegration`

### PR DESCRIPTION
**Pull request by kostasrim**
* add partial support for `CLIENT CACHING TRUE` (only to be used with TRACKING OPTIN)
* add OPTIN to CLIENT TRACKING command
* refactor client tracking to respect transactional atomicity
* fixed multi/exec and disabled squashing with client tracking
* add tests

Resolves #2969, #2971,  #2997, #2998

P.s. All tests in rueidis TestSingleClientIntegration pass except pub/sub because we don't yet support it see #3001

### CODE REVIEW

File: src/facade/dragonfly_connection.h [hunk 1]
```diff
@@ -294,8 +294,16 @@ class Connection : public util::Connection {
 
   void SetClientTrackingSwitch(bool is_on);
 
+  void LastCommandIsClientCaching();
```
Comment (romange) [inline src/facade/dragonfly_connection.h:297]: please improve the naming. This function sets a variable and yet it has "Is" in its name which implies the opposite.

File: src/server/server_family.cc [hunk 2]
```diff
@@ -450,29 +450,56 @@ void ClientPauseCmd(CmdArgList args, vector<facade::Listener*> listeners, Connec
...
+  if (!rb->IsResp3())
+    return cntx->SendError(
+        "Client caching is currently not supported for RESP2. Please use RESP3.");
+
+  if (args.size() != 1) {
+    return cntx->SendError(kSyntaxErr);
+  }
+
+  CmdArgParser parser{args};
+  if (parser.Check("YES").IgnoreCase()) {
```
Comment (romange) [inline src/server/server_family.cc:494]: can you please explain in the comments what this function does?

File: src/server/main_service.cc [hunk 3]
```diff
@@ -1260,6 +1260,10 @@ void Service::DispatchCommand(CmdArgList args, facade::ConnectionContext* cntx)
     dfly_cntx->transaction->ScheduleSingleHopT(cb);
   }
 
+  if (cntx->conn()) {
```
Comment (romange) [inline src/server/main_service.cc:1263]: I would say that based on the code above ` cntx->conn()` must always be true. is not it the case?

Comment (kostasrim) [reply src/server/main_service.cc:1263]: No, not on ClusterMode, it was crashing here when it tried to deference `conn`

File: src/facade/dragonfly_connection.h [hunk 4]
```diff
@@ -444,8 +452,19 @@ class Connection : public util::Connection {
...
 
-  // a flag indicating whether the client has turned on client tracking.
-  bool tracking_enabled_ = false;
+  struct ClientTracking {
+    // a flag indicating whether the client has turned on client tracking.
+    bool tracking_enabled = false;
+    bool optin = false;
+    // remember if CLIENT CACHING TRUE was the last command
+    // true if prev command was CLIENT CACHING TRUE
+    bool prev_command = false;
```
[the remark this answers is not in the document]
Comment (kostasrim) [reply src/facade/dragonfly_connection.h:461]: Yes! I will add a comment on the code and one here. So, we need to remember the last command executed because the chore with `OPTIN` is that if we call `CLIENT CACHING TRUE` then if the command that follows is a `read command` we track it.

Basically `OPTIN` is conditional caching on demand via `CLIENT CACHING TRUE` which acts as an `once flag` to potentially(since it might not be read only) track the next command.

I used `prev_command` and `last_command` because somehow I had to keep track the last executed command while keeping the change set to the code minimal (within `DispatchCommand`). 

The `prev_command` is the command executed in the previous call of `DispatchCommand`
The `last_command` is the command executed in the `current` call of `DispatchCommand`

If `last_command` is read only && `prev_command` is `CLIENT CACHING TRUE` then we need track the command (these are the semantics I described above).  At the end of the function `DisapatchCommand`, `prev_command` is updated to the 'last_command` and `last_command` is set to false (and only set to `true` when client caching true is called). 

p.s. The bonus is that this only requires to set the `last_command` to true on the call site of `CLIENT CACHING TRUE` avoiding us to explicitly set it to `false` for all other commands. We could do something similar by checking the `cid` and `args` in `DispatchCommand` but this introduces another layer of command parsing (name + args) on the dispatch layer which I am not happy about and for that reason I did not pursue

File: src/facade/dragonfly_connection.cc [hunk 5]
```diff
@@ -1642,13 +1642,29 @@ void Connection::RequestAsyncMigration(util::fb2::ProactorBase* dest) {
 }
 
 void Connection::SetClientTrackingSwitch(bool is_on) {
-  tracking_enabled_ = is_on;
-  if (tracking_enabled_)
+  tracking_info_.tracking_enabled = is_on;
+  if (is_on)
     cc_->subscriptions++;
```
[the remark this answers is not in the document]
Comment (kostasrim) [reply src/facade/dragonfly_connection.cc:1647]: I am not sure how this is supposed to work as it interferes with pub/sub. When I looked at it I thought the same thing for `subscriptions` (also there is a comment that says we can't have more than `2` but we `don't` have any checks around it so I doubt this is a restriction that we enforce). 

In general there is code I would like to rewrite, but these kind of changes are beyond the scope of this PR. 

In this piece above there are no functional changes other than renaming.

File: src/facade/dragonfly_connection.h (hunk 1 above)
Comment (kostasrim) [reply src/facade/dragonfly_connection.h:297]: I agree `is` looks like a question than a statement

File: src/facade/dragonfly_connection.cc (hunk 5 above)
[the remark this answers is not in the document]
Comment (dranikpg) [reply src/facade/dragonfly_connection.cc:1647]: > (also there is a comment that says we can't have more than 2)

Because there is only pubsub and monitor, with tracking it's 3 😆

File: src/facade/dragonfly_connection.h (hunk 1 above)
Comment (dranikpg) [reply src/facade/dragonfly_connection.h:297]: I'd suggest to hide all of this from the general connection interface into a dedicated Tracking().Foo()

File: src/facade/dragonfly_connection.h (hunk 4 above)
[the remark this answers is not in the document]
Comment (dranikpg) [reply src/facade/dragonfly_connection.h:461]: Looking at this struct, maybe client tracking shouldn't be part of the connection code at all, like pubsub or monitoring? We can store information about it in connection state - like we do for other stuff. To track optin, we can introduce a seqnum for every command, and `ClientCaching()` will just do `conn_state.tracking.optin_seqnum = cntx->current_seqnum`

File: src/facade/dragonfly_connection.cc (hunk 5 above)
[the remark this answers is not in the document]
Comment (kostasrim) [reply src/facade/dragonfly_connection.cc:1647]: Sure, but what if you call `3` times `CLIENT TRACKING TRUE` what would the number of `subscriptions would be` ?

for reference we unconditionally call this on a connection:

```
cntx->conn()->SetClientTrackingSwitch(is_on);
```

So if I call `n` times `client tracking true` subscriptions will be equal to `n`

File: src/facade/dragonfly_connection.h (hunk 4 above)
[the remark this answers is not in the document]
Comment (kostasrim) [reply src/facade/dragonfly_connection.h:461]: maybe, in general I would like to refactor some parts of it. Shall we do this on separate PR to at least bake the basic functionality in ?

File: src/facade/dragonfly_connection.cc (hunk 5 above)
[the remark this answers is not in the document]
Comment (dranikpg) [reply src/facade/dragonfly_connection.cc:1647]: it doesn't matter what the value is, unless it's 0 when no messages can be send asynchronously and > 0 if any can be. How many times you count tracking is not important as long as the general rule holds

File: src/facade/dragonfly_connection.h (hunk 4 above)
[the remark this answers is not in the document]
Comment (dranikpg) [reply src/facade/dragonfly_connection.h:461]: Like you wish, but I think it can be done here 🤷🏻‍♂️

[the remark this answers is not in the document]
Comment (romange) [reply src/facade/dragonfly_connection.h:461]: @kostasrim I suspect that the state machine can be simplified, i.e. instead of last and prev fields, to have only
`next_command_tracking`. ClientCaching will set `next_command_tracking` and `DispatchCommand` will unconditionally exchange this var with `false` **before** executing the command. And I agree with @dranikpg  that this should be part of the context state like db_index or multi/exec state.

File: src/facade/dragonfly_connection.cc [hunk 6]
```diff
@@ -254,8 +254,9 @@ thread_local vector<Connection::PipelineMessagePtr> Connection::pipeline_req_poo
 thread_local Connection::QueueBackpressure Connection::tl_queue_backpressure_;
 
 void Connection::QueueBackpressure::EnsureBelowLimit() {
-  ec.await(
-      [this] { return subscriber_bytes.load(memory_order_relaxed) <= subscriber_thread_limit; });
+  ec.await([this] {
+    return done || subscriber_bytes.load(memory_order_relaxed) <= subscriber_thread_limit;
```
Comment (kostasrim) [inline src/facade/dragonfly_connection.cc:258]: And we had a deadlock if this was waiting while the connection fiber was joining

File: src/facade/dragonfly_connection.cc [hunk 7]
```diff
@@ -1114,7 +1117,7 @@ void Connection::HandleMigrateRequest() {
     this->Migrate(dest);
   }
 
-  DCHECK(dispatch_q_.empty());
+  // DCHECK(dispatch_q_.empty());
```
Comment (kostasrim) [inline src/facade/dragonfly_connection.cc:1120]: I have triggered this and I suspect it's not needed, since by the time Migrate returns `dispatch_q_` might be active

File: src/server/transaction.cc [hunk 8]
```diff
@@ -838,13 +838,23 @@ OpStatus Transaction::ScheduleSingleHop(RunnableType cb) {
 
 // Runs in coordinator thread.
 void Transaction::Execute(RunnableType cb, bool conclude) {
+  auto tracking_wrap = [cb, this](Transaction* t, EngineShard* shard) -> RunnableResult {
```
Comment (kostasrim) [inline src/server/transaction.cc:841]: @dranikpg this with the changes in `InvokeCmd` seemed to be the most non intrusive way (to comply with the requirements of the state machine)

File: src/facade/dragonfly_connection.h (hunk 4 above)
[the remark this answers is not in the document]
Comment (kostasrim) [reply src/facade/dragonfly_connection.h]: @dranikpg @romange I refactored the code. However I still do think we need the two variables since there are two commands we need to track (the one executing at the moment via InvokeCmd and the one executed before it such that we can check if the last command was CACHING YES). I added a bunch of comments in the state maching, if you still think it';s doable with a single variable I am happy to reiterate :) It's a small change anyway :)

File: src/server/conn_context.cc [hunk 9]
```diff
@@ -119,6 +119,13 @@ void ConnectionContext::ChangeMonitor(bool start) {
   EnableMonitoring(start);
 }
 
+ConnectionState::ClientTracking& ConnectionContext::ClientTrackingInfo() {
+  if (parent_cntx_) {
+    return parent_cntx_->conn_state.tracking_info_;
```
Comment (kostasrim) [inline src/server/conn_context.cc:124]: That;s for squashing :)

File: src/facade/dragonfly_connection.cc (hunk 7 above)
Comment (romange) [reply src/facade/dragonfly_connection.cc:1120]: @dranikpg  to validate

File: src/facade/dragonfly_connection.cc (hunk 6 above)
Comment (romange) [reply src/facade/dragonfly_connection.cc:258]: the only call I find is here https://github.com/dragonflydb/dragonfly/blob/main/src/facade/dragonfly_connection.cc#L1720

where a connection A waits for the connection B to be below the limit.
can you describe the deadlock  what connection was joining during shutdown?

this fix is most probably incorrect because `done` is not atomic var and this is a multi-threaded function.

File: src/facade/dragonfly_connection.cc [hunk 10]
```diff
@@ -885,6 +886,8 @@ void Connection::ConnectionFlow(FiberSocketBase* peer) {
   // After the client disconnected.
   cc_->conn_closing = true;  // Signal dispatch to close.
   evc_.notify();
+  queue_backpressure_->done = true;
```
Comment (romange) [inline src/facade/dragonfly_connection.cc:889]: so I suggest dchecking on the value of subscriber_bytes first. it should be 0 when connection is shutting down and if it's not we have other bugs.

File: src/server/conn_context.h [hunk 11]
```diff
@@ -147,6 +147,78 @@ struct ConnectionState {
...
+  // is invoked the current_command_ is set to true which is later moved to the prev_command_
+  // when the next command is invoked. This is needed to keep track of the different rules
+  // described above. Stickiness is covered similarly by the multi/exec/discard command which
+  // when called sets the corresponding multi_ variable to true.
+  class ClientTracking {
+   public:
+    // Sets to true when CLIENT TRACKING is ON
+    void SetClientTracking(bool is_on);
+    // Enable tracking on the client
+    void TrackClientCaching();
```
Comment (romange) [inline src/server/conn_context.h:191]: much much clearer now!!!

File: src/server/conn_context.h [hunk 12]
```diff
@@ -147,6 +147,78 @@ struct ConnectionState {
...
+
+    void UpdatePrevAndLastCommand();
+    // Set if OPTIN subcommand is used in CLIENT TRACKING
```
Comment (romange) [inline src/server/conn_context.h:194]: please add empty lines before comments.
also nit: oneliner setters/getters please keep inline class

File: src/server/transaction.cc (hunk 8 above)
Comment (romange) [reply src/server/transaction.cc:841]: 1. I would like to understand why tracking requires transaction semantics (an example will be fine)
2. why cid_ is not enough and we need `invoke_cid_` ?

File: src/server/conn_context.cc [hunk 13]
```diff
@@ -265,4 +272,78 @@ void ConnectionState::ExecInfo::ClearWatched() {
...
+    db_slice.TrackKey(conn_ref, key);
+  }
+
+  return OpStatus::OK;
+}
+
+void ConnectionState::ClientTracking::Track(ConnectionContext* cntx, const CommandId* cid) {
+  auto& info = cntx->ClientTrackingInfo();
+  auto shards = cntx->transaction->GetActiveShards();
+  if ((cid->opt_mask() & CO::READONLY) && cid->IsTransactional() && info.ShouldTrackKeys()) {
```
Comment (romange) [inline src/server/conn_context.cc:334]: @dranikpg  pls review

File: src/server/db_slice.cc [hunk 14]
```diff
@@ -1391,24 +1391,27 @@ void DbSlice::SendInvalidationTrackingMessage(std::string_view key) {
...
-        }
-      }
-    };
-    shard_set->pool()->DispatchBrief(std::move(cb));
-    // remove this key from the tracking table as the key no longer exists
-    client_tracking_map_.erase(key);
+  if (it == client_tracking_map_.end()) {
+    return;
   }
+  auto& client_set = it->second;
```
Comment (romange) [inline src/server/db_slice.cc:1397]: consider `client_tracking_map_.extract(key)` function that can combine find and delete in one call.

File: src/server/db_slice.cc [hunk 15]
```diff
@@ -1391,24 +1391,27 @@ void DbSlice::SendInvalidationTrackingMessage(std::string_view key) {
...
+  // notify all the clients.
+  auto cb = [key = std::string(key), client_set = std::move(client_set)](unsigned idx,
```
Comment (romange) [inline src/server/db_slice.cc:1399]: add a TODO comment about `client_set`, `key` being duplicated because we broadcast `cb`

File: src/server/conn_context.h [hunk 16]
```diff
@@ -147,6 +147,78 @@ struct ConnectionState {
...
+  // described above. Stickiness is covered similarly by the multi/exec/discard command which
+  // when called sets the corresponding multi_ variable to true.
+  class ClientTracking {
+   public:
+    // Sets to true when CLIENT TRACKING is ON
+    void SetClientTracking(bool is_on);
+    // Enable tracking on the client
+    void TrackClientCaching();
+
+    void UpdatePrevAndLastCommand();
```
Comment (romange) [inline src/server/conn_context.h:193]: nit: UdatePrevAndLastCommand name describes the implementation of this function. What it does is advancing the state. So I think it's better call it Tick or Advance or Update

File: src/server/conn_context.cc (hunk 9 above)
Comment (dranikpg) [reply src/server/conn_context.cc:124]: If you access conn_state, don't make it a function on conn_cntx

then you can just use conn_state, you can make it mutable or add a new member like `conn`

https://github.com/dragonflydb/dragonfly/blob/a95419b0c4eaa524347bf7d0a47349f1be07475a/src/server/main_service.cc#L214-L215

File: src/server/conn_context.h [hunk 17]
```diff
@@ -147,6 +147,78 @@ struct ConnectionState {
...
+
+   private:
+    // a flag indicating whether the client has turned on client tracking.
+    bool tracking_enabled_ = false;
+    bool optin_ = false;
+    // remember if CLIENT CACHING TRUE was the last command
+    // true if the previous command invoked is CLIENT CACHING TRUE
+    bool prev_command_ = false;
+    // true if the currently executing command is CLIENT CACHING TRUE
+    bool executing_command_ = false;
```
Comment (romange) [inline src/server/conn_context.h:217]: rename: `executing_command_`  to `track_next_cmd_`

File: src/server/conn_context.h [hunk 18]
```diff
@@ -147,6 +147,78 @@ struct ConnectionState {
...
+    // the tracking requirements, is is set for tracking.
+    void Track(ConnectionContext* cntx, const CommandId* cid);
+
+   private:
+    // a flag indicating whether the client has turned on client tracking.
+    bool tracking_enabled_ = false;
+    bool optin_ = false;
+    // remember if CLIENT CACHING TRUE was the last command
+    // true if the previous command invoked is CLIENT CACHING TRUE
+    bool prev_command_ = false;
```
Comment (romange) [inline src/server/conn_context.h:215]: rename `prev_command_` to `track_current_cmd_`

File: src/server/conn_context.cc [hunk 19]
```diff
@@ -265,4 +272,78 @@ void ConnectionState::ExecInfo::ClearWatched() {
...
+void ConnectionState::ClientTracking::SetClientTracking(bool is_on) {
+  tracking_enabled_ = is_on;
+}
+
+void ConnectionState::ClientTracking::TrackClientCaching() {
+  executing_command_ = true;
+}
+
+void ConnectionState::ClientTracking::UpdatePrevAndLastCommand() {
+  if (prev_command_ && multi_) {
```
[the remark this answers is not in the document]
Comment (dranikpg) [reply src/server/conn_context.cc:284]: We store so much fragile info that needs to be updated everywhere... seqnums would solve all this

File: src/server/conn_context.h [hunk 20]
```diff
@@ -183,6 +255,10 @@ class ConnectionContext : public facade::ConnectionContext {
   // TODO: to introduce proper accessors.
   Transaction* transaction = nullptr;
   const CommandId* cid = nullptr;
+  ConnectionContext* parent_cntx_ = nullptr;
+
+  ConnectionState::ClientTracking& ClientTrackingInfo();
```
Comment (dranikpg) [inline src/server/conn_context.h:260]: See previous comment on whether we can keep this in conn_state

**Review by dranikpg — COMMENTED** [review]
It looks somewhat over engineered to me 😅  We have similar semantics in blocking commands - only that we subscribe with specific commands and not with any.

1. Let's use squashing_info instead of adding a parent field to ConnectionContext or let's use that field for everything - there should be one way of doing things with proper comments, so nobody adds yet a third
2. I'd still suggest to add numbers to commands, because `UpdatePrevAndLastCommand()` appears in many places and we update three whole fileds: prev, executing, multi
3. Track() should be called when we conclude or finish the current multi command, currently we call it for every hop. Not that there are multi-hop read commands, but I think it belongs to all other management code. Invoke-cid should also not be needed with that

**Comment by dranikpg** [comment]
there is a deeper problem with `CLIENT TRACKING OPTIN`

suppose you have
```
MULTI
CLIENT TRACKING OPTIN
GET A
GET B 
GET C
EXEC
```

Now, if you squash the last 3, you loose the order - becuase `GET C` can run first of those three

**Comment by romange** [comment]
lets reject `CLIENT TRACKING OPTIN` in multi

**Comment by kostasrim** [comment]
> in fact, should we even allow `CLIENT` commands inside MULTI?

Only `CLIENT CACHING YES` as it has specific semantics

File: src/server/transaction.cc (hunk 8 above)
Comment (kostasrim) [reply src/server/transaction.cc:841]: > I would like to understand why tracking requires transaction semantics (an example will be fine)

Because invalidation messages must be sent before the transaction concludes. Otherwise, we might accidentally skip them. An example would be:

```
>> CLIENT TRACKING ON
>> GET FOO
>> SET FOO BAR 
>> GET FOO
>> SET FOO BAR
>> GET FOO ---------> might miss Invalidation message
```

A valid execution would be once we call the first `SET` we will send an invalidation message as a separate transaction. Now before that even starts/concludes, the `GET` that follows will get executed first and it will itself issue a separate transaction to send an invalidation message. Now the problem here is, that once we send an invalidation message we remove the key from the tracking map (since we only send invalidation messages once until the key is reread). Then the second invalidation transaction won't work because the key no longer exists in the map and we will never get that second invalidation message.

File: src/server/conn_context.cc [hunk 21]
```diff
@@ -265,4 +265,49 @@ void ConnectionState::ExecInfo::ClearWatched() {
   watched_existed = 0;
 }
 
+bool ConnectionState::ClientTracking::ShouldTrackKeys() const {
+  if (!IsTrackingOn()) {
+    return false;
+  }
+
+  return !optin_ || (seq_num_ == (1 + caching_seq_num_));
+}
```
Comment (dranikpg) [inline src/server/conn_context.cc:274]: Ah, that's what I call elegancy 🎩

File: src/server/main_service.cc [hunk 22]
```diff
@@ -2180,7 +2160,8 @@ void Service::Exec(CmdArgList args, ConnectionContext* cntx) {
       ServerState::tlocal()->exec_freq_count[descr]++;
     }
 
-    if (absl::GetFlag(FLAGS_multi_exec_squash) && state == ExecEvalState::NONE) {
+    if (absl::GetFlag(FLAGS_multi_exec_squash) && state == ExecEvalState::NONE &&
+        !cntx->conn_state.tracking_info_.IsTrackingOn()) {
```
Comment (dranikpg) [inline src/server/main_service.cc:2164]: What if it gets enabled while executing

File: src/server/conn_context.cc [hunk 23]
```diff
@@ -265,4 +265,49 @@ void ConnectionState::ExecInfo::ClearWatched() {
...
+  return OpStatus::OK;
+}
+
+void ConnectionState::ClientTracking::Track(ConnectionContext* cntx, const CommandId* cid) {
+  auto& info = cntx->conn_state.tracking_info_;
+  auto shards = cntx->transaction->GetActiveShards();
+  if ((cid->opt_mask() & CO::READONLY) && cid->IsTransactional() && info.ShouldTrackKeys()) {
+    auto conn = cntx->parent_cntx_ ? cntx->parent_cntx_->conn()->Borrow() : cntx->conn()->Borrow();
+    auto cb = [&, conn](unsigned i, auto* pb) {
+      if (shards.find(i) != shards.end()) {
```
Comment (dranikpg) [inline src/server/conn_context.cc:303]: nit: There is IsActive() so you don't need GetActiveShards()

File: src/server/transaction.h [hunk 24]
```diff
@@ -362,6 +363,16 @@ class Transaction {
     return shard_data_[SidToId(sid)].local_mask;
   }
 
+  void SetConnectionContextAndInvokeCid(ConnectionContext* cntx) {
+    cntx_ = cntx;
+  }
```
Comment (dranikpg) [inline src/server/transaction.h:368]: nit: please rename it then

File: src/server/conn_context.h [hunk 25]
```diff
@@ -183,6 +268,8 @@ class ConnectionContext : public facade::ConnectionContext {
   // TODO: to introduce proper accessors.
   Transaction* transaction = nullptr;
   const CommandId* cid = nullptr;
+  ConnectionContext* parent_cntx_ = nullptr;
```
Comment (dranikpg) [inline src/server/conn_context.h:271]: we don't need this now if we don't support squashing

File: src/server/conn_context.cc [hunk 26]
```diff
@@ -265,4 +265,49 @@ void ConnectionState::ExecInfo::ClearWatched() {
...
+  }
+
+  return OpStatus::OK;
+}
+
+void ConnectionState::ClientTracking::Track(ConnectionContext* cntx, const CommandId* cid) {
+  auto& info = cntx->conn_state.tracking_info_;
+  auto shards = cntx->transaction->GetActiveShards();
+  if ((cid->opt_mask() & CO::READONLY) && cid->IsTransactional() && info.ShouldTrackKeys()) {
+    auto conn = cntx->parent_cntx_ ? cntx->parent_cntx_->conn()->Borrow() : cntx->conn()->Borrow();
```
Comment (dranikpg) [inline src/server/conn_context.cc:301]: Same here, if we don't support squashing, let's dcheck conn_state.squashing_info is false

File: src/server/transaction.h [hunk 27]
```diff
@@ -636,6 +647,8 @@ class Transaction {
     ShardId coordinator_index = 0;
   } stats_;
 
+  ConnectionContext* cntx_{nullptr};
+
```
Comment (dranikpg) [inline src/server/transaction.h:651]: I'll invent something in the future to get rid of this 😆

File: src/facade/dragonfly_connection.cc (hunk 7 above)
Comment (dranikpg) [reply src/facade/dragonfly_connection.cc:1116]: Maybe uncomment this as it's not related

**Review by dranikpg — APPROVED** [review]
Some nits remaining, LGTM

File: src/server/conn_context.cc [hunk 28]
```diff
@@ -265,4 +265,49 @@ void ConnectionState::ExecInfo::ClearWatched() {
...
+  if (conn_ref.IsExpired()) {
+    DVLOG(2) << "Connection expired, exiting TrackKey function.";
+    return OpStatus::OK;
+  }
+
+  DVLOG(2) << "Start tracking keys for client ID: " << conn_ref.GetClientId()
+           << " with thread ID: " << conn_ref.Thread();
+
+  auto& db_slice = slice_args.shard->db_slice();
+  // TODO: There is a bug here that we track all arguments instead of tracking only keys.
```
Comment (dranikpg) [inline src/server/conn_context.cc:287]: ah, found it, yet that's also left 🙂

File: src/server/transaction.cc [hunk 29]
```diff
@@ -691,8 +691,12 @@ void Transaction::RunCallback(EngineShard* shard) {
   }
 
   // Log to journal only once the command finished running
-  if ((coordinator_state_ & COORD_CONCLUDING) || (multi_ && multi_->concluding))
+  if ((coordinator_state_ & COORD_CONCLUDING) || (multi_ && multi_->concluding)) {
     LogAutoJournalOnShard(shard, result);
+    if (cntx_) {
+      cntx_->conn_state.tracking_info_.Track(cntx_, cid_);
```
Comment (romange) [inline src/server/transaction.cc:697]: Again, @dranikpg @kostasrim  would you mind providing an example or an explanation why triggering from the transaction is needed. I think this feature is eventually consistent by definition so I do not understand the reason for this change.

Comment (dranikpg) [reply src/server/transaction.cc:697]: Not sure what you mean... It has to be tracked with keys locked so we don't miss the next immediate update.

Technically it doesn't have to be tracked from transaction. We have the journal for that. But it has to be tracked during the transaction phase

Comment (romange) [reply src/server/transaction.cc:697]: I do not argue, just trying to understand. What do you mean by "missing the next update" ?
can you please give me an example? suppose we won't do it withing the transaction phase, please provide the flow of steps that will lead to incorrect result as seen by a client.

Comment (romange) [reply src/server/transaction.cc:697]: ok, so if A is being read and the rule is to track keys that are being read you should start tracking A immediately.

Got ya. But the whole code around this back and forth looks wrong:
Inside a shard callback we access connection state that is not designed to be accessed from shard threads.
Specifically, `Track` function checks  `if ((cid->opt_mask() & CO::READONLY) && cid->IsTransactional() && info.ShouldTrackKeys())` from the shard thread and then calls `AwaitFiberOnAll(std::move(cb));` on all shards.

Does it mean that if we call MGET on 20 shards, now all 20 shards call Track that checks if we should track and then calls back AwaitFiberOnAll on all shards, overall 20x20 calls?  Do I understand this interaction correctly?

Comment (dranikpg) [reply src/server/transaction.cc:697]: Ahh yes, after I asked Kostas to move the code, I didn't check it's correct 😅 We are already on the thread, we shouldn't be callin AwaitFiberOnAll

> Does it mean that if we call MGET on 20 shards, now all 20 sh

It should be the same as journaling. It is in fact journaling (or replication), just with a filter that sends invalidation except the new data

**Review by dranikpg — DISMISSED** [review]
I think it's correct now. Note there are some unresolved nits by Roman

File: src/server/db_slice.cc (hunk 14 above)
Comment (kostasrim) [reply src/server/db_slice.cc:1405]: doesn't satisfy `extract` requirements (for the `value_type`) and generates a compiler error.

File: src/server/conn_context.cc (hunk 28 above)
Comment (kostasrim) [reply src/server/conn_context.cc:287]: 99.9% it does not affect us and it's not a bug. I created this https://github.com/dragonflydb/dragonfly/issues/3034 for roman to confirm and I will push a quick fix

**Review by dranikpg — APPROVED** [review]

File: src/facade/dragonfly_connection.cc [hunk 30]
```diff
@@ -1119,7 +1118,8 @@ void Connection::HandleMigrateRequest() {
     this->Migrate(dest);
   }
 
-  DCHECK(dispatch_q_.empty());
+  // This triggers on rueidis SingleIntegrationTest
```
Comment (romange) [inline src/facade/dragonfly_connection.cc:1121]: I think this comment can be improved. Explain how it happens that `DCHECK(dispatch_q_.empty());` fails after the migration, "rueidis SingleIntegrationTest" is irrelevant here

File: src/server/conn_context.cc [hunk 31]
```diff
@@ -265,4 +265,43 @@ void ConnectionState::ExecInfo::ClearWatched() {
...
+  for (auto key : args) {
+    DVLOG(2) << "Inserting client ID " << conn_ref.GetClientId()
+             << " into the tracking client set of key " << key;
+    db_slice.TrackKey(conn_ref, key);
+  }
+
+  return OpStatus::OK;
+}
+
+void ConnectionState::ClientTracking::Track(ConnectionContext* cntx, const CommandId* cid) {
```
Comment (romange) [inline src/server/conn_context.cc:297]: this function now is called within the Shard. We have a convention  to name it as `xxxOnShard` to stress it.

File: src/server/conn_context.cc [hunk 32]
```diff
@@ -265,4 +265,43 @@ void ConnectionState::ExecInfo::ClearWatched() {
...
+  auto& info = cntx->conn_state.tracking_info_;
+  if ((cid->opt_mask() & CO::READONLY) && cid->IsTransactional() && info.ShouldTrackKeys()) {
```
Comment (romange) [inline src/server/conn_context.cc:299]: I believe the code can be moved to the coordinator thread, i.e. when we prepare the transaction. the result can be kept as a boolean within transaction. Nothing here is relevant to the shard or the transaction state. we have `Transaction::coordinator_state_` mask that can be used for this.

Comment (romange) [reply src/server/conn_context.cc:299]: actually, see my other comment.

File: src/server/transaction.h (hunk 27 above)
Comment (romange) [reply src/server/transaction.h:645]: No need to wait for the future, I think transactions should not be aware of ConnectionContext. It's a design choice and it is possible to preserve it. Let's introduce a `on_track_cb` that will be passed to transaction if tracking is needed, i.e. if the condition `((cid->opt_mask() & CO::READONLY) && cid->IsTransactional() && info.ShouldTrackKeys())` holds. The callback will call `OpTrackKeys`. This way `ClientTracking::Track` will disappear at all

File: src/server/conn_context.cc (hunk 32 above)
Comment (kostasrim) [reply src/server/conn_context.cc:299]: Well, `info.ShouldTrackeys()` should be called after a command is invoked because that very command might be the client tracking command.

The `callback` approach is neat for removing the `ConnectionContext` alltogether from `transaction` and in fact this is the only change needed (no fancy boolean or coordinator mask) because we just pass a callback which just captures the context :)

File: src/server/CMakeLists.txt [hunk 33]
```diff
@@ -33,14 +33,14 @@ add_library(dfly_transaction db_slice.cc malloc_stats.cc blocking_controller.cc
             common.cc journal/journal.cc journal/types.cc journal/journal_slice.cc
             server_state.cc table.cc  top_keys.cc transaction.cc tx_base.cc
             serializer_commons.cc journal/serializer.cc journal/executor.cc journal/streamer.cc
-            ${TX_LINUX_SRCS} acl/acl_log.cc slowlog.cc
+            ${TX_LINUX_SRCS} acl/acl_log.cc slowlog.cc conn_context.cc channel_store.cc
```
Comment (romange) [inline src/server/CMakeLists.txt:36]: we do not need this move now

File: src/server/main_service.cc [hunk 34]
```diff
@@ -1091,7 +1093,9 @@ std::optional<ErrorReply> Service::VerifyCommandState(const CommandId* cid, CmdA
     if (cmd_name == "SELECT" || absl::EndsWith(cmd_name, "SUBSCRIBE"))
       return ErrorReply{absl::StrCat("Can not call ", cmd_name, " within a transaction")};
 
-    if (cmd_name == "WATCH" || cmd_name == "FLUSHALL" || cmd_name == "FLUSHDB")
+    // for some reason we get a trailing \n\r, and that's why we use StartsWith
```
Comment (romange) [inline src/server/main_service.cc:1096]: do we always have non empty `tail_args` here? 
can you dcheck?

Comment (kostasrim) [reply src/server/main_service.cc:1096]: I don't think we need a `dcheck` because we call `Validate` on the command a few lines above and it internally checks for its arity. `CLIENT` requires at least one argument, so if the `cmd_name` is client we know it `tail_args[0]` is a valid index. 

If you till think I am wrong or I missed something I am happy to add it :)

Comment (romange) [reply src/server/main_service.cc:1096]: DCHECK is a replacement for a comment. What you wrote here is not immediately clear to me from reading the code. When you add a DCHECK, it is clear to a reader that somewhere else something handles the corner cases so that code here can not have empty tail_args. if someone else will change the code there and the invariant won't hold we might catch it with dcheck.

File: src/server/conn_context.cc [hunk 35]
```diff
@@ -88,7 +88,7 @@ ConnectionContext::ConnectionContext(::io::Sink* stream, facade::Connection* own
   acl_commands = std::vector<uint64_t>(acl::NumberOfFamilies(), acl::ALL_COMMANDS);
 }
 
-ConnectionContext::ConnectionContext(const ConnectionContext* owner, Transaction* tx,
+ConnectionContext::ConnectionContext(ConnectionContext* owner, Transaction* tx,
```
Comment (romange) [inline src/server/conn_context.cc:91]: do we still need to remove `const` here?

**Review by romange — COMMENTED** [review]
looks good, left final minor comments.

File: src/server/db_slice.cc [hunk 36]
```diff
@@ -1423,24 +1423,29 @@ void DbSlice::SendInvalidationTrackingMessage(std::string_view key) {
...
-        if ((conn != nullptr) && conn->IsTrackingOn()) {
-          std::string key_str = {key.begin(), key.end()};
-          conn->SendInvalidationMessageAsync({key_str});
-        }
-      }
-    };
-    shard_set->pool()->DispatchBrief(std::move(cb));
-    // remove this key from the tracking table as the key no longer exists
-    client_tracking_map_.erase(key);
+  if (it == client_tracking_map_.end()) {
```
[the remark this answers is not in the document]
Comment (romange) [reply src/server/db_slice.cc:1426]: ping?

**Review by romange — APPROVED** [review]
!!!
