### PR TITLE
fix(sock): Use the updated cancellation cb interface.

### LINKED ISSUE #1939: Epoll sockets don't cancel blocking commands when they close
To reproduce: Use `--force_epoll`. Run `BLPOP key 1234123` and `Ctrl+C`. `redis-cli CLIENT LIST` then displays two clients, not one.

### PR DESCRIPTION
**Pull request by royjacobson**
Fixes #1939

### CODE REVIEW

File: src/facade/dragonfly_connection.cc [hunk 1]
```diff
@@ -369,14 +365,13 @@ void Connection::HandleRequests() {
...
-        break_poll_id_ =
-            socket_->PollEvent(POLLERR | POLLHUP, [this](int32_t mask) { this->OnBreakCb(mask); });
+        socket_->RegisterOnErrorCb([this](int32_t mask) { this->OnBreakCb(mask); });
       }
 
       ConnectionFlow(peer);
 
-      if (break_poll_id_ != UINT32_MAX) {
-        socket_->CancelPoll(break_poll_id_);
+      if (breaker_cb_) {
```
Comment (romange) [inline src/facade/dragonfly_connection.cc:373]: if you do this, you must make sure `CancelOnErrorCb()` can be called multiple times. we had some issues with shutting down a connection and data race around this codepath. you can see I used to reset break_poll_id_ to avoid calling CancelPoll if OnBreakCb was called first.

Comment (romange) [reply src/facade/dragonfly_connection.cc:373]: Also, we must ensure that `OnBreakCb` won't be called once `cc_.reset();` is called. Currently, we have such cases.

Comment (royjacobson) [reply src/facade/dragonfly_connection.cc:373]: About the race with `cc_.reset();` - how does it work with io_uring?

**Comment by royjacobson** [comment]
This seems to still fail:
https://github.com/dragonflydb/dragonfly/actions/runs/6336485574/job/17209646367?pr=1940

But it just silently times out and I'm not sure if it's my fault or not.

**Comment by adiholden** [comment]
@royjacobson I see the regression tests finish with 3 minutes in other CIs and here we get 48 minutes. Does it pass on your laptop?

**Comment by royjacobson** [comment]
> @royjacobson I see the regression tests finish with 3 minutes in other CIs and here we get 48 minutes. Does it pass on your laptop?

Tested locally, `await client.close()` seems to block (?) on my laptop in the `test_tls_insecure` test. Unfortunately don't have time to investigate :/

**Comment by adiholden** [comment]
@royjacobson Thank you, I will take it from here. Best wishes

**Comment by dranikpg** [comment]
Will add https://github.com/romange/helio/pull/155 here once its merged to improve error diagnostics

**Comment by adiholden** [comment]
Hi @dranikpg is this ready? are you still waiting on helio?

**Comment by dranikpg** [comment]
@adiholden 

Sure, I forgot to merge in helio then 😅 I've rebased just now on main which should contain the latest helio pull

**Review by adiholden — APPROVED** [review]

**Comment by dranikpg** [comment]
#1940
