### PR TITLE
fix(tiering): Fix bug in TryGrow

### LINKED ISSUE #5484: test_full_sync failing
test_full_sync is failing:
```
 replica_info = await replica_client.info("ALL")
>           pytest.fail(
                f"Replica did not sync in time. \nmaster: {master_info} \n\nreplica: {replica_info}"
            )
E           Failed: Replica did not sync in time. 
```

https://github.com/dragonflydb/dragonfly/actions/runs/16233894101/job/45841203328

### PR DESCRIPTION
**Pull request by dranikpg**
As simple as that 🤦🏻 I'd add a test, but we already have one that runs one minute+ on average

Fixes #5484 

Reminder after merging: re-enable reg tests

### CODE REVIEW

**Comment by vyavdoshenko** [comment]
@dranikpg 
Why don't you want to reenable the test in this PR? I guess this is the best proof of fixing.

**Comment by dranikpg** [comment]
> Why don't you want to reenable the test in this PR? I guess this is the best proof of fixing.

I disabled the tests that run in the backgroun on CI for main branch (that we get notifications for). Doesn't affect the PR in any way

**Review by vyavdoshenko — APPROVED** [review]

**Comment by dranikpg** [comment]
I found one more bug (more like serious inefficiency) 🤦🏻

File: src/server/tiering/disk_storage.cc [hunk 1]
```diff
@@ -180,9 +180,9 @@ std::error_code DiskStorage::Stash(io::Bytes bytes, StashCb cb) {
   if ((available < 256_MB) && (available < capacity * 0.15) && !grow_pending_) {
     auto ec = TryGrow(256_MB);
     LOG_IF(ERROR, ec && ec != errc::file_too_large) << "Could not call grow :" << ec.message();
-    return ec;
   }
-  return {};
+
+  return {};  // Must succeed after the operation was scheduled to run cleanup
```
Comment (romange) [inline src/server/tiering/disk_storage.cc:185]: lgtm but can you explain this comment? :)

**Review by vyavdoshenko — APPROVED** [review]
lgtm

File: src/server/tiering/disk_storage.cc (hunk 1 above)
Comment (dranikpg) [reply src/server/tiering/disk_storage.cc:185]: Ah it's enlgish without punctuation: Must succeed after the operation was scheduled **,** to run cleanup. 

When we returned the error, the callback was never called, so we never cleaned up (returned the buffer)
