### PR TITLE
fix: prevent inline execution while shard lock is held

### LINKED ISSUE #7103: sigabrt on fuzzing input
[crash-000006.tar.gz](https://github.com/user-attachments/files/26613626/crash-000006.tar.gz)

```
python3 replay_crash.py crashes 000006 127.0.0.1 6379
```

```
./build/dragonfly --port 6379 --proactor_threads 1 --dbfilename=dump --logtostderr
```

```
F20260409 22:49:38.591655 11447 serializer_base.cc:203] Unexpected fiber: AsyncFiber on 0xaaaaac425f9c  std::__detail::__variant::__gen_vtable_impl<>::__visit_invoke()
0xaaaaac4260b8  std::__do_visit<>()
0xaaaaac426138  std::visit<>()
0xaaaaac4245b4  dfly::SerializerBase::RegisterChangeListener()::{lambda()#1}::operator()()
0xaaaaac426e18  std::__invoke_impl<>()
0xaaaaac426a94  std::__invoke_r<>()
0xaaaaac426660  std::_Function_handler<>::_M_invoke()
0xaaaaac61bfe0  std::function<>::operator()()
0xaaaaac60ba10  dfly::DbSlice::CallChangeCallbacks()
0xaaaaac6071d8  dfly::DbSlice::PreUpdateBlocking()
0xaaaaac601ba0  dfly::DbSlice::FindMutableInternal()
0xaaaaac6019d4  dfly::DbSlice::FindMutable()
0xaaaaac08a374  dfly::GenericFamily::OpDel()
0xaaaaac08a598  dfly::CmdDel()::{lambda()#1}::operator()()
0xaaaaac0a1f48  std::__invoke_impl<>()
*** Check failure stack trace: ***
    @     0xaaaaacca6278  google::LogMessage::Fail()
    @     0xaaaaacca6180  google::LogMessage::SendToLog()
    @     0xaaaaacca5980  google::LogMessage::Flush()
    @     0xaaaaacca56b4  google::LogMessage::~LogMessage()
    @     0xaaaaac42560c  dfly::SerializerBase::OnChangeBlocking()
    @     0xaaaaac42455c  _ZZZN4dfly14SerializerBase22RegisterChangeListenerEvENKUltRKNS_9ChangeReqEE_clEtS3_ENKUlT_E_clINS_9DashTableINS_10CompactKeyENS_12CompactValueENS_6detail16PrimeTablePolicyEE8IteratorILb0ELb1EEEEEDaS5_
    @     0xaaaaac426974  _ZSt13__invoke_implIvZZN4dfly14SerializerBase22RegisterChangeListenerEvENKUltRKNS0_9ChangeReqEE_clEtS4_EUlT_E_JRKNS0_9DashTableINS0_10CompactKeyENS0_12CompactValueENS0_6detail16PrimeTablePolicyEE8IteratorILb0ELb1EEEEES6_St14__invoke_otherOT0_DpOT1_
    @     0xaaaaac42655c  _ZSt8__invokeIZZN4dfly14SerializerBase22RegisterChangeListenerEvENKUltRKNS0_9ChangeReqEE_clEtS4_EUlT_E_JRKNS0_9DashTableINS0_10CompactKeyENS0_12CompactValueENS0_6detail16PrimeTablePolicyEE8IteratorILb0ELb1EEEEENSt15__invoke_resultIS6_JDpT0_EE4typeEOS6_DpOSJ_
    @     0xaaaaac425f9c  _ZNSt8__detail9__variant17__gen_vtable_implINS0_12_Multi_arrayIPFNS0_21__deduce_visit_resultIvEEOZZN4dfly14SerializerBase22RegisterChangeListenerEvENKUltRKNS5_9ChangeReqEE_clEtS9_EUlT_E_RKSt7variantIJNS5_9DashTableINS5_10CompactKeyENS5_12CompactValueENS5_6detail16PrimeTablePolicyEE8IteratorILb0ELb1EEESt17basic_string_viewIcSt11char_traitsIcEEEEEJEEESt16integer_sequenceImJLm0EEEE14__visit_invokeESD_ST_
    @     0xaaaaac4260b8  _ZSt10__do_visitINSt8__detail9__variant21__deduce_visit_resultIvEEZZN4dfly14SerializerBase22RegisterChangeListenerEvENKUltRKNS4_9ChangeReqEE_clEtS8_EUlT_E_JRKSt7variantIJNS4_9DashTableINS4_10CompactKeyENS4_12CompactValueENS4_6detail16PrimeTablePolicyEE8IteratorILb0ELb1EEESt17basic_string_viewIcSt11char_traitsIcEEEEEEDcOT0_DpOT1_
    @     0xaaaaac426138  _ZSt5visitIZZN4dfly14SerializerBase22RegisterChangeListenerEvENKUltRKNS0_9ChangeReqEE_clEtS4_EUlT_E_JRKSt7variantIJNS0_9DashTableINS0_10CompactKeyENS0_12CompactValueENS0_6detail16PrimeTablePolicyEE8IteratorILb0ELb1EEESt17basic_string_viewIcSt11char_traitsIcEEEEEENSt13invoke_resultIS6_JDpNSt13__conditionalIX21is_lvalue_reference_vIT0_EEE4typeIRNSt19variant_alternativeILm0ENSt16remove_referenceIDTcl4__ascl7declvalISQ_EEEEE4typeEE4typeEOSZ_EEEE4typeEOS6_DpOSQ_
    @     0xaaaaac4245b4  _ZZN4dfly14SerializerBase22RegisterChangeListenerEvENKUltRKNS_9ChangeReqEE_clEtS3_
    @     0xaaaaac426e18  _ZSt13__invoke_implIvRZN4dfly14SerializerBase22RegisterChangeListenerEvEUltRKNS0_9ChangeReqEE_JtS4_EET_St14__invoke_otherOT0_DpOT1_
    @     0xaaaaac426a94  _ZSt10__invoke_rIvRZN4dfly14SerializerBase22RegisterChangeListenerEvEUltRKNS0_9ChangeReqEE_JtS4_EENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EES8_E4typeEOS9_DpOSA_
    @     0xaaaaac426660  _ZNSt17_Function_handlerIFvtRKN4dfly9ChangeReqEEZNS0_14SerializerBase22RegisterChangeListenerEvEUltS3_E_E9_M_invokeERKSt9_Any_dataOtS3_
    @     0xaaaaac61bfe0  std::function<>::operator()()
    @     0xaaaaac60ba10  dfly::DbSlice::CallChangeCallbacks()
    @     0xaaaaac6071d8  dfly::DbSlice::PreUpdateBlocking()
    @     0xaaaaac601ba0  dfly::DbSlice::FindMutableInternal()
    @     0xaaaaac6019d4  dfly::DbSlice::FindMutable()
    @     0xaaaaac08a374  dfly::GenericFamily::OpDel()
    @     0xaaaaac08a598  _ZZN4dflyL6CmdDelEN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPNS_14CommandContextEENKUlPNS_11TransactionEPNS_11EngineShardEE_clESC_SE_
    @     0xaaaaac0a1f48  _ZSt13__invoke_implIN6facade8OpStatusERKZN4dflyL6CmdDelEN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPNS2_14CommandContextEEUlPNS2_11TransactionEPNS2_11EngineShardEE_JSF_SH_EET_St14__invoke_otherOT0_DpOT1_
    @     0xaaaaac0a04ac  _ZSt8__invokeIRKZN4dflyL6CmdDelEN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPNS0_14CommandContextEEUlPNS0_11TransactionEPNS0_11EngineShardEE_JSD_SF_EENSt15__invoke_resultIT_JDpT0_EE4typeEOSK_DpOSL_
    @     0xaaaaac09e5e0  _ZSt6invokeIRKZN4dflyL6CmdDelEN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPNS0_14CommandContextEEUlPNS0_11TransactionEPNS0_11EngineShardEE_JSD_SF_EENSt13invoke_resultIT_JDpT0_EE4typeEOSK_DpOSL_
    @     0xaaaaac09bc80  _ZN4absl12lts_2025051219functional_internal12InvokeObjectIZN4dflyL6CmdDelENS0_4SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPNS3_14CommandContextEEUlPNS3_11TransactionEPNS3_11EngineShardEE_NSD_14RunnableResultEJSE_SG_EEET0_NS1_7VoidPtrEDpNS1_8ForwardTIT1_E4typeE
    @     0xaaaaac70eb10  absl::lts_20250512::FunctionRef<>::operator()()
    @     0xaaaaac6f9f50  dfly::Transaction::RunCallback()
    @     0xaaaaac6f9400  dfly::Transaction::RunInShard()
    @     0xaaaaabb7fb8c  _ZZN4dfly11EngineShard13PollExecutionEPKcPNS_11TransactionEENKUlS4_bE_clES4_b
    @     0xaaaaabb8070c  dfly::EngineShard::PollExecution()
    @     0xaaaaac6fd0a4  dfly::Transaction::DispatchHop()
*** SIGABRT received at time=1775764178 on cpu 0 ***
PC: @     0xfffff7537608  (unknown)  (unknown)
    @     0xaaaaacd08f14         64  absl::lts_20250512::WriteFailureInfo()
    @     0xaaaaacd0922c         96  absl::lts_20250512::AbslFailureSignalHandler()
    @     0xfffff7ffa7d0       4752  (unknown)
    @     0xfffff74ecb3c         64  raise
    @     0xfffff74d7e00        192  abort
    @     0xaaaaaccb1790        208  google::DumpStackTraceAndExit()
    @     0xaaaaacca6278         16  google::LogMessage::Fail()
    @     0xaaaaacca6180        144  google::LogMessage::SendToLog()
    @     0xaaaaacca5980         80  google::LogMessage::Flush()
    @     0xaaaaacca56b4         32  google::LogMessage::~LogMessage()
    @     0xaaaaac42560c        288  dfly::SerializerBase::OnChangeBlocking()
    @     0xaaaaac42455c         32  dfly::SerializerBase::RegisterChangeListener()::{lambda()#1}::operator()()::{lambda()#1}::operator()<>()
    @     0xaaaaac426974         48  std::__invoke_impl<>()
    @     0xaaaaac42655c         64  std::__invoke<>()
    @     0xaaaaac425f9c         48  std::__detail::__variant::__gen_vtable_impl<>::__visit_invoke()
    @     0xaaaaac4260b8        112  std::__do_visit<>()
    @     0xaaaaac426138         32  std::visit<>()
    @     0xaaaaac4245b4        112  dfly::SerializerBase::RegisterChangeListener()::{lambda()#1}::operator()()
    @     0xaaaaac426e18         16  std::__invoke_impl<>()
    @     0xaaaaac426a94         64  std::__invoke_r<>()
    @     0xaaaaac426660         80  std::_Function_handler<>::_M_invoke()
    @     0xaaaaac61bfe0         64  std::function<>::operator()()
    @     0xaaaaac60ba10        272  dfly::DbSlice::CallChangeCallbacks()
    @     0xaaaaac6071d8        112  dfly::DbSlice::PreUpdateBlocking()
    @     0xaaaaac601ba0        464  dfly::DbSlice::FindMutableInternal()
    @     0xaaaaac6019d4        272  dfly::DbSlice::FindMutable()
    @     0xaaaaac08a374        512  dfly::GenericFamily::OpDel()
    @     0xaaaaac08a598        176  dfly::CmdDel()::{lambda()#1}::operator()()
    @     0xaaaaac0a1f48         32  std::__invoke_impl<>()
    @     0xaaaaac0a04ac         64  std::__invoke<>()
    @     0xaaaaac09e5e0         80  std::invoke<>()
    @     0xaaaaac09bc80        128  absl::lts_20250512::functional_internal::InvokeObject<>()
    @ ... and at least 40 more frames
```

### PR DESCRIPTION
**Pull request by vyavdoshenko**
When `proactor_threads=1` a global transaction like SAVE runs inline on a connection fiber and may yield during file I/O (`OpenWriteFile`/`SaveHeader`). While it is yielded, another connection's write command passes the `CanRunInlined()` check (snapshot callbacks are not registered yet) and enters the TxQueue behind SAVE.  When SAVE resumes and concludes, the inline `PollExecution` drains the queue and executes the queued command on the **connection fiber** instead of the shard-queue fiber - firing `OnChangeBlocking` on the wrong fiber and hitting the DFATAL assertion in `serializer_base.cc:203`.

Changes:
- **`CanRunInlined()`**: add `shard_lock()->IsFree()` check.  While a global transaction holds the shard lock, no command can run inline - it goes through the shard queue instead, so the change callback always fires on the correct fiber.
- **Regression test**: `test_save_with_concurrent_mutations` runs SAVE and SET/DEL concurrently from separate connections with `proactor_threads=1`, reproducing the crash within seconds on a debug build.

Fixes #7103

### CODE REVIEW

File: src/server/transaction.cc [hunk 1]
```diff
@@ -1622,8 +1622,21 @@ void Transaction::CancelBlocking(const std::function<OpStatus(ArgSlice)>& status
...
+  // command on the *connection* fiber instead of the shard-queue fiber.  If the global
+  // transaction registered snapshot change-listeners before concluding, OnChangeBlocking fires
+  // on the wrong fiber and hits the DFATAL assertion.
+  //
+  // Checking that the shard lock is free prevents inlining while a global transaction is in
+  // progress, so the queued command is dispatched through the shard queue instead.
   if (unique_shard_cnt_ == 1 && unique_shard_id_ == ss->thread_index() &&
-      ss->AllowInlineScheduling() && !GetDbSlice(es->shard_id()).HasRegisteredCallbacks()) {
+      ss->AllowInlineScheduling() && !GetDbSlice(es->shard_id()).HasRegisteredCallbacks() &&
+      es->shard_lock()->IsFree()) {
```
Comment (dranikpg) [inline src/server/transaction.cc]: I think `IsGlobal()` is the more correct check because that's the only condition under which it should be effective. And if we ever optimize the tx to have a single hop - then it will be the only correct one.

Not `es->shard_lock()->IsFree()` implies that the command (not yet in progress) will not run, but just schedule. There is no reason to schedule via the shard queue, it can be done inline.

File: src/server/transaction.cc [hunk 2]
```diff
@@ -1622,8 +1622,21 @@ void Transaction::CancelBlocking(const std::function<OpStatus(ArgSlice)>& status
...
+  // (OpenWriteFile, SaveHeader).  While it is yielded another connection's command may enter
+  // CanRunInlined(), pass every check (callbacks are not registered yet), and get placed into
+  // the TxQueue behind the global transaction.  When the global transaction resumes and
+  // concludes, the inline PollExecution continues draining the queue and executes the queued
+  // command on the *connection* fiber instead of the shard-queue fiber.  If the global
+  // transaction registered snapshot change-listeners before concluding, OnChangeBlocking fires
+  // on the wrong fiber and hits the DFATAL assertion.
+  //
+  // Checking that the shard lock is free prevents inlining while a global transaction is in
+  // progress, so the queued command is dispatched through the shard queue instead.
```
Comment (dranikpg) [inline src/server/transaction.cc]: nit: this is very wordy but it has few actual compact conclusions

```
Global transactions like SAVE can change the inling rules, so run them non-inlined. 
This will guarantee that their PollExecution batch executes 
in the right way when the conditions update
```

**Comment by dranikpg** [comment]
It seems like this is relevant to #7087

File: src/server/transaction.cc (hunk 1 above)
Comment (vyavdoshenko) [reply src/server/transaction.cc]: fixed

File: src/server/transaction.cc (hunk 2 above)
Comment (vyavdoshenko) [reply src/server/transaction.cc]: fixed

**Comment by vyavdoshenko** [comment]
This change fixes https://github.com/dragonflydb/dragonfly/pull/7082. The test in this PR passes with this fix.
https://github.com/dragonflydb/dragonfly/issues/7087 can be closed as well.

**Comment by romange** [comment]
The funny thing is that I expect we remove most of the conditions in `CanRunInlined` in v1.39 as with our new serialization algorithm we should be able to order journaling changes after serialisation when running from multiple fibers.

**Review by romange — APPROVED** [review]

**Comment by dranikpg** [comment]
> The funny thing is that I expect we remove most of the conditions in CanRunInlined in v1.39 as with our new serialization algorithm we should be able to order journaling changes after serialisation when running from multiple fibers.

Yes, I thought as well that I can't explain many of the things that are there
