### PR TITLE
fix: Fix unsupported object type rejson-rl in RedisInsight

### LINKED ISSUE #3386: Json values cannot be accessed from Redis Insight
Json values cannot be accessed from [Redis Insight](https://hub.docker.com/r/redis/redisinsight).

image

### PR DESCRIPTION
**Pull request by BagritsevichStepan**
partially fixes #3386

### CODE REVIEW

**Review by kostasrim — APPROVED** [review]

**Review by romange — DISMISSED** [review]

**Review by dranikpg — CHANGES_REQUESTED** [review]
If you run git blame it must have been me who changed this. 

The problem is that SCAN converts its intput into lowercase for the TYPE argument, so it's effectively impossible to SCAN by JSON type now. I didn't know that changing to lowercase will break some tool, so we have to patch SCAN in another way now 🙂

**Comment by romange** [comment]
@dranikpg thanks for providing the context.
In that case, lets add a test in generic_family_test.cc that fixes the casing of type command and write there the context (that there are GUIs that expect type to be upper case) so we won't change it again in 6 months,

File: src/core/compact_object.h [hunk 1]
```diff
@@ -536,6 +539,15 @@ class CompactObjectView {
   CompactObj obj_;
 };
 
+class CompactObjTypeConverter {
+ public:
+  static std::string_view ObjTypeToString(CompactObjType type);
+  static CompactObjType ObjTypeFromString(std::string_view sv);
```
Comment (dranikpg) [inline src/core/compact_object.h:545]: why use sentinels like kInvalid? optional<unsigned> would've fitted so nicely, given that you use it in ScanOpts

File: src/core/compact_object.h [hunk 2]
```diff
@@ -536,6 +539,15 @@ class CompactObjectView {
...
+
+ private:
+  static const std::unordered_map<CompactObjType, std::string_view> kObjTypeToString;
+};
```
Comment (dranikpg) [inline src/core/compact_object.h:549]: Can be just part of the source file, no need to expose it in the header. Also I assume just having two functions like before is perferctly fine, if you don't want to expose them you can keep them in the detail / a separate namespace

File: src/server/common.cc [hunk 3]
```diff
@@ -318,8 +293,7 @@ OpResult<ScanOpts> ScanOpts::TryFrom(CmdArgList args) {
       if (scan_opts.pattern == "*")
         scan_opts.pattern = string_view{};
     } else if (opt == "TYPE") {
-      ToLower(&args[i + 1]);
-      scan_opts.type_filter = ArgS(args, i + 1);
+      scan_opts.type_filter = CompactObjTypeConverter::ObjTypeFromString(ArgS(args, i + 1));
```
Comment (dranikpg) [inline src/server/common.cc:296]: Maybe Redis warns actually 🤔

File: src/core/compact_object.cc [hunk 4]
```diff
@@ -1255,4 +1232,28 @@ MemoryResource* CompactObj::memory_resource() {
   return tl.local_mr;
 }
 
+std::string_view CompactObjTypeConverter::ObjTypeToString(CompactObjType type) {
+  auto it = kObjTypeToString.find(type);
+  if (it != kObjTypeToString.end()) {
+    return it->second;
+  }
+  LOG(ERROR) << "Unsupported type " << type;
```
Comment (dranikpg) [inline src/core/compact_object.cc:1240]: this was a DCHECK(false) = LOG(DFATAL) before

**Review by dranikpg — APPROVED** [review]
Just some suggestions to simplifty the code

File: src/core/compact_object.h (hunk 1 above)
Comment (romange) [reply src/core/compact_object.h:545]: I think using sentinels is a valid choice, not worse than optional.

File: src/core/compact_object.h [hunk 5]
```diff
@@ -536,6 +539,15 @@ class CompactObjectView {
   CompactObj obj_;
 };
 
+class CompactObjTypeConverter {
+ public:
+  static std::string_view ObjTypeToString(CompactObjType type);
+  static CompactObjType ObjTypeFromString(std::string_view sv);
+
+ private:
+  static const std::unordered_map<CompactObjType, std::string_view> kObjTypeToString;
```
Comment (romange) [inline src/core/compact_object.h:548]: sorry but I am against using global hash maps for translating this.
See https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables 
for example.

Please avoid  dynamic allocation at global scope if possible and this use case does not justify this. There is nothing wrong in switch/case. you can use a c array with constant length if that helps you.

File: src/core/compact_object.cc (hunk 4 above)
Comment (BagritsevichStepan) [reply src/core/compact_object.cc:1240]: actually it was `ObjTypeName` function, that I refactored

Comment (BagritsevichStepan) [reply src/core/compact_object.cc:1240]: I think LOG(ERROR) is better for this case, isn't it?

File: src/server/common.cc (hunk 3 above)
Comment (BagritsevichStepan) [reply src/server/common.cc]: Added Log to the `ObjTypeFromString` function

File: src/core/compact_object.cc (hunk 4 above)
Comment (dranikpg) [reply src/core/compact_object.cc:1247]: Ah, my bad, sorry

File: src/core/compact_object.h (hunk 1 above)
Comment (dranikpg) [reply src/core/compact_object.h]: Maybe, but using both can be confusing

File: src/core/compact_object.cc (hunk 4 above)
Comment (dranikpg) [reply src/core/compact_object.cc:1247]: > I think LOG(ERROR) is better for this case, isn't it?

It won't crash a debug build, so you won't uncover bugs

**Review by dranikpg — APPROVED** [review]

File: src/core/compact_object.cc (hunk 4 above)
Comment (romange) [reply src/core/compact_object.cc:1247]: we usually need to log something when a process reaches problematic state.
ObjTypeName logged DFATAL meaning that program is not supposed to reach this state and if it reaches, it's a bug. That implies that precondition is that the argument is valid.

We do not introduce internal APIs that check validity of argument in all functions - it would be a nightmare. 

So as long as it is expected that `type` is valid when calling this function, you can use `LOG(DFATAL)` and return `string_view{}` and drop optional wrapper.

File: src/core/compact_object.cc [hunk 6]
```diff
@@ -1255,4 +1232,31 @@ MemoryResource* CompactObj::memory_resource() {
...
+}
+
+std::optional<CompactObjType> ObjTypeFromString(std::string_view sv) {
+  for (auto& p : kObjTypeToString) {
+    if (absl::EqualsIgnoreCase(sv, p.second)) {
+      return p.first;
+    }
+  }
+
+  LOG(ERROR) << "Unsupported type " << sv;
```
Comment (romange) [inline src/core/compact_object.cc:1258]: similarly you do not log ERROR in low level utility functions that lack context. 
Especially when your API is designed to handle the "unsupported" case by returning nullopt. 

It's the responsibility of the caller that knows the context to either log or reply the error or whatever. 

If it is EXPECTED that `sv` is a valid string type then see my comment above otherwise you can keep the optional in this case.

File: src/core/compact_object.h [hunk 7]
```diff
@@ -9,6 +9,7 @@
 #include <boost/intrusive/list_hook.hpp>
 #include <optional>
 #include <type_traits>
+#include <unordered_map>
```
Comment (romange) [inline src/core/compact_object.h:12]: no need

File: src/core/compact_object.cc (hunk 6 above)
Comment (BagritsevichStepan) [reply src/core/compact_object.cc:1258]: No, everything is okay, I got it.

File: src/server/common.cc [hunk 8]
```diff
@@ -318,8 +293,11 @@ OpResult<ScanOpts> ScanOpts::TryFrom(CmdArgList args) {
       if (scan_opts.pattern == "*")
         scan_opts.pattern = string_view{};
     } else if (opt == "TYPE") {
-      ToLower(&args[i + 1]);
-      scan_opts.type_filter = ArgS(args, i + 1);
+      auto obj_type_as_string = ObjTypeFromString(ArgS(args, i + 1));
+      if (!obj_type_as_string) {
+        return facade::OpStatus::SYNTAX_ERR;
+      }
+      scan_opts.type_filter = obj_type_as_string;
```
Comment (dranikpg) [inline src/server/common.cc:300]: Redis isn't replying anything with wrong types, but I'd support doing so, because we don't have modules and know all your different types ahead

Also, ironically obj_type_as_string is not a string 😄

**Review by dranikpg — DISMISSED** [review]
LGTM

File: src/server/common.cc (hunk 8 above)
Comment (BagritsevichStepan) [reply src/server/common.cc:300]: :skull:

**Review by dranikpg — APPROVED** [review]
