### PR TITLE
fix(transaction): Fix non-transactional multi/exec transaction access

### LINKED ISSUE #5247: transaction crash
The crash can be reproduced with one or multiple proactor_threads.

Recorded traffic: 
[traffic.tar.gz](https://github.com/user-attachments/files/20638718/traffic.tar.gz)

The crash log:
```
F20250607 15:47:28.162160 114027 transaction.cc:521] Check failed: IsAtomicMulti() 
*** Check failure stack trace: ***
    @     0x64f1f3fccd73  google::LogMessage::Fail()
    @     0x64f1f3fcccb9  google::LogMessage::SendToLog()
    @     0x64f1f3fcc46c  google::LogMessage::Flush()
    @     0x64f1f3fd0564  google::LogMessageFatal::~LogMessageFatal()
    @     0x64f1f3b2a364  dfly::Transaction::MultiSwitchCmd()
    @     0x64f1f334c07a  dfly::ConnectionContext::SwitchTxCmd()
    @     0x64f1f35c437f  dfly::Service::Exec()
    @     0x64f1f35c7cfe  _ZZN4dfly7Service8RegisterEPNS_15CommandRegistryEENKUlN4absl12lts_202407224SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEERKNS_14CommandContextEE4_clESB_SE_
    @     0x64f1f35f04b3  _ZN3fu27abi_4006detail10invocation6invokeIRKZN4dfly7Service8RegisterEPNS4_15CommandRegistryEEUlN4absl12lts_202407224SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEERKNS4_14CommandContextEE4_JSG_SJ_EEEDTclcl7forwardIT_Efp_Espcl7forwardIT0_Efp0_EEEOSN_DpOSO_
    @     0x64f1f35eb4de  _ZN3fu27abi_4006detail12type_erasure16invocation_table14function_traitIKFvN4absl12lts_202407224SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEERKN4dfly14CommandContextEEE16internal_invokerINS2_3boxILb1EZNSE_7Service8RegisterEPNSE_15CommandRegistryEEUlSD_SH_E4_SaISP_EEELb1EE6invokeEPKNS2_13data_accessorEmSD_SH_
    @     0x64f1f3ad8a7f  _ZNK3fu27abi_4006detail12type_erasure6tables6vtableINS1_8propertyILb0ELb0EJKFvN4absl12lts_202407224SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEERKN4dfly14CommandContextEEEEEE6invokeILm0EJPKNS2_13data_accessorERKmSE_SI_EEEDcDpOT0_
    @     0x64f1f3ad8b18  _ZN3fu27abi_4006detail12type_erasure7erasureILb1ENS1_6configILb1ELb1ENS_16capacity_defaultEEENS1_8propertyILb0ELb0EJKFvN4absl12lts_202407224SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEERKN4dfly14CommandContextEEEEEE6invokeILm0ERKSN_JSG_SK_EEEDcOT0_DpOT1_
    @     0x64f1f3ad8b96  fu2::abi_400::detail::type_erasure::invocation_table::operator_impl<>::operator()()
    @     0x64f1f3ad4fe1  dfly::CommandId::Invoke()
    @     0x64f1f35bd448  dfly::Service::InvokeCmd()
    @     0x64f1f35bc2e6  dfly::Service::DispatchCommand()
    @     0x64f1f3d0d468  facade::Connection::AsyncOperations::operator()()
    @     0x64f1f3d32334  facade::Connection::AsyncOperations::operator()<>()
    @     0x64f1f3d2f6a9  std::__invoke_impl<>()
    @     0x64f1f3d2af05  std::__invoke<>()
    @     0x64f1f3d2552e  std::__detail::__variant::__gen_vtable_impl<>::__visit_invoke()
    @     0x64f1f3d25ae4  _ZSt10__do_visitINSt8__detail9__variant21__deduce_visit_resultIvEERN6facade10Connection15AsyncOperationsEJRSt7variantIJNS5_14MonitorMessageESt10unique_ptrINS5_10PubMessageENS5_14MessageDeleterEESA_INS5_15PipelineMessageESC_ESA_INS5_17MCPipelineMessageESt14default_deleteISG_EESA_INS5_16AclUpdateMessageESH_ISK_EENS5_23MigrationRequestMessageENS5_17CheckpointMessageENS5_19InvalidationMessageEEEEEDcOT0_DpOT1_
    @     0x64f1f3d25c29  _ZSt5visitIRN6facade10Connection15AsyncOperationsEJRSt7variantIJNS1_14MonitorMessageESt10unique_ptrINS1_10PubMessageENS1_14MessageDeleterEES6_INS1_15PipelineMessageES8_ES6_INS1_17MCPipelineMessageESt14default_deleteISC_EES6_INS1_16AclUpdateMessageESD_ISG_EENS1_23MigrationRequestMessageENS1_17CheckpointMessageENS1_19InvalidationMessageEEEEENSt13invoke_resultIT_JDpNSt13__conditionalIX21is_lvalue_reference_vIT0_EEE4typeIRNSt19variant_alternativeILm0ENSt16remove_referenceIDTcl4__ascl7declvalISR_EEEEE4typeEE4typeEOS10_EEEE4typeEOSP_DpOSR_
    @     0x64f1f3d17c27  facade::Connection::AsyncFiber()
    @     0x64f1f3d1961d  _ZZN6facade10Connection24LaunchAsyncFiberIfNeededEvENKUlvE_clEv
    @     0x64f1f3d1fb4d  _ZSt13__invoke_implIvZN6facade10Connection24LaunchAsyncFiberIfNeededEvEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @     0x64f1f3d1f85e  _ZSt8__invokeIZN6facade10Connection24LaunchAsyncFiberIfNeededEvEUlvE_JEENSt15__invoke_resultIT_JDpT0_EE4typeEOS4_DpOS5_
    @     0x64f1f3d1f58e  _ZSt12__apply_implIZN6facade10Connection24LaunchAsyncFiberIfNeededEvEUlvE_St5tupleIJEEJEEDcOT_OT0_St16integer_sequenceImJXspT1_EEE
    @     0x64f1f3d1f5c8  _ZSt5applyIZN6facade10Connection24LaunchAsyncFiberIfNeededEvEUlvE_St5tupleIJEEEDcOT_OT0_
    @     0x64f1f3d1f645  _ZN4util3fb26detail15WorkerFiberImplIZN6facade10Connection24LaunchAsyncFiberIfNeededEvEUlvE_JEE4run_EON5boost7context5fiberE
    @     0x64f1f3d1eb2d  _ZZN4util3fb26detail15WorkerFiberImplIZN6facade10Connection24LaunchAsyncFiberIfNeededEvEUlvE_JEEC4INS0_19FixedStackAllocatorEEESt17basic_string_viewIcSt11char_traitsIcEENS0_13FiberPriorityERKN5boost7context12preallocatedEOT_OS5_ENKUlONSF_5fiberEE_clESN_
    @     0x64f1f3d204ea  _ZSt13__invoke_implIN5boost7context5fiberERZN4util3fb26detail15WorkerFiberImplIZN6facade10Connection24LaunchAsyncFiberIfNeededEvEUlvE_JEEC4INS4_19FixedStackAllocatorEEESt17basic_string_viewIcSt11char_traitsIcEENS4_13FiberPriorityERKNS1_12preallocatedEOT_OS9_EUlOS2_E_JS2_EESL_St14__invoke_otherOT0_DpOT1_
*** SIGABRT received at time=1749300448 on cpu 0 ***
PC: @     0x7ef18afe2b2c  (unknown)  pthread_kill
    @     0x64f1f4054eae         64  absl::lts_20240722::WriteFailureInfo()
    @     0x64f1f405512a         96  absl::lts_20240722::AbslFailureSignalHandler()
    @     0x7ef18af89330       1776  (unknown)
    @     0x7ef18af8927e         32  raise
    @     0x7ef18af6c8ff        192  abort
    @     0x64f1f3fd7b9e        176  google::DumpStackTraceAndExit()
    @     0x64f1f3fccd73         16  google::LogMessage::Fail()
    @     0x64f1f3fcccb9        160  google::LogMessage::SendToLog()
    @     0x64f1f3fcc46c         80  google::LogMessage::Flush()
    @     0x64f1f3fd0564         32  google::LogMessageFatal::~LogMessageFatal()
    @     0x64f1f3b2a364        224  dfly::Transaction::MultiSwitchCmd()
    @     0x64f1f334c07a         32  dfly::ConnectionContext::SwitchTxCmd()
    @     0x64f1f35c437f        432  dfly::Service::Exec()
    @     0x64f1f35c7cfe         64  dfly::Service::Register()::{lambda()#6}::operator()()
    @     0x64f1f35f04b3         64  fu2::abi_400::detail::invocation::invoke<>()
    @     0x64f1f35eb4de         96  fu2::abi_400::detail::type_erasure::invocation_table::function_trait<>::internal_invoker<>::invoke()
    @     0x64f1f3ad8a7f        112  fu2::abi_400::detail::type_erasure::tables::vtable<>::invoke<>()
    @     0x64f1f3ad8b18        112  fu2::abi_400::detail::type_erasure::erasure<>::invoke<>()
    @     0x64f1f3ad8b96         80  fu2::abi_400::detail::type_erasure::invocation_table::operator_impl<>::operator()()
    @     0x64f1f3ad4fe1        112  dfly::CommandId::Invoke()
    @     0x64f1f35bd448        624  dfly::Service::InvokeCmd()
    @     0x64f1f35bc2e6        528  dfly::Service::DispatchCommand()
    @     0x64f1f3d0d468        208  facade::Connection::AsyncOperations::operator()()
    @     0x64f1f3d32334         32  facade::Connection::AsyncOperations::operator()<>()
    @     0x64f1f3d2f6a9         48  std::__invoke_impl<>()
    @     0x64f1f3d2af05         48  std::__invoke<>()
    @     0x64f1f3d2552e         48  std::__detail::__variant::__gen_vtable_impl<>::__visit_invoke()
    @     0x64f1f3d25ae4         96  std::__do_visit<>()
    @     0x64f1f3d25c29         48  std::visit<>()
    @     0x64f1f3d17c27        400  facade::Connection::AsyncFiber()
    @     0x64f1f3d1961d         32  facade::Connection::LaunchAsyncFiberIfNeeded()::{lambda()#1}::operator()()
    @     0x64f1f3d1fb4d         32  std::__invoke_impl<>()
    @ ... and at least 11 more frames
[1]    114025 IOT instruction (core dumped)  ./dragonfly --dbfilename= --logtostderr --proactor_threads=1 2>&1
```

### PR DESCRIPTION
**Pull request by dranikpg**
Fixes #5247 

Issue:
1. Even when EVAL was non-transational (zero keys and no flags), it still initialized the transaction partially
2. MultiSwitchCmd was still called for non-transational commands, which was ok is the transaction was initialized fully or not at all
3. Combining (1) and (2), EVAL was wrongfully setting up a transation, which was then DCHECKed in (2)

Fix:
1. Correctly filter out zero keys commands
2. Call MultiSwitchCmd only for transactional (CO::Transactional) commands (includes empty eval)
3. Guard better against potential zero keys commands: lmpop, zmpop
4. Small list family cleanup

### CODE REVIEW

File: src/server/transaction.cc [hunk 1]
```diff
@@ -1602,7 +1601,7 @@ OpResult<KeyIndex> DetermineKeys(const CommandId* cid, CmdArgList args) {
 
     if (num_custom_keys == 0 &&
         (absl::StartsWith(name, "ZDIFF") || absl::StartsWith(name, "ZUNION") ||
-         absl::StartsWith(name, "ZINTER"))) {
+         absl::StartsWith(name, "ZINTER") || absl::EndsWith(name, "MPOP"))) {
       return OpStatus::AT_LEAST_ONE_KEY;
```
Comment (dranikpg) [inline src/server/transaction.cc:1605]: Redis error messages are somewhat inconsistent:

> 127.0.0.1:6379> lmpop 0 LEFT COUNT 1
(error) ERR numkeys should be greater than 0
127.0.0.1:6379> zinter 0 WITHSCORES
(error) ERR at least 1 input key is needed for 'zinter' command

Maybe we can just use `at least 1 input key is needed for this command` for all cases?

File: src/server/main_service.cc [hunk 2]
```diff
@@ -1351,6 +1351,7 @@ bool Service::InvokeCmd(const CommandId* cid, CmdArgList tail_args,
   DCHECK(!cid->Validate(tail_args));
 
   ConnectionContext* cntx = cmd_cntx.conn_cntx;
+  cntx->cid = cid;
```
Comment (kostasrim) [inline src/server/main_service.cc:1354]: That should also cover the assignment from SwitchTxCmd :)

File: src/server/list_family.cc [hunk 3]
```diff
@@ -1244,13 +1203,16 @@ optional<pair<string_view, bool>> GetFirstNonEmptyKeyFound(EngineShard* shard, T
 void ListFamily::LMPop(CmdArgList args, const CommandContext& cmd_cntx) {
   auto* response_builder = static_cast<RedisReplyBuilder*>(cmd_cntx.rb);
 
-  LMPopParams params;
-  facade::ErrorReply parse_result = ParseLMPop(args, &params);
+  CmdArgParser parser{args};
```
Comment (kostasrim) [inline src/server/list_family.cc:1206]: nice!

**Review by kostasrim — COMMENTED** [review]
lgtm -- plz wait also for @romange

File: src/server/transaction.cc (hunk 1 above)
Comment (kostasrim) [reply src/server/transaction.cc:1605]: I am fine with that :shrug:
