### PR TITLE
fix(server): Fix SCAN deadlock

### LINKED ISSUE #3232: Eval command does not returns, transaction getting stuck
How to reproduce:

Run the following commands in redis cli:

1. `script load "      local pattern = KEYS[1]\n      local oldest = tonumber(ARGV[1])\n      local cursor = ARGV[2]\n      local count = tonumber(ARGV[3])\n      local result = redis.call(\"SCAN\", cursor, \"MATCH\", pattern, \"COUNT\", count)\n      cursor = result[1]\n      local keys = result[2]\n      for i, key in ipairs(keys) do\n        local to_delete = {}\n        for _, timestamp in ipairs(redis.call('hkeys', key)) do\n          if tonumber(timestamp) <= oldest then\n            table.insert(to_delete, timestamp)\n          end\n        end\n        if #to_delete > 0 then\n          redis.call('hdel', key, unpack(to_delete))\n        end\n      end\n      return cursor\n"
`
2.  debug populate 1000
3. evalsha 591f96f821898bddced228c3fe18d0192691bd05 1 key: 1 0 1000

step 3 does not return causing transaction getting stuck

### PR DESCRIPTION
**Pull request by dranikpg**
Fix #3232 in simplest possible way

We should consider making SCAN a nokey transactional command

### CODE REVIEW

File: src/server/generic_family.cc [hunk 1]
```diff
@@ -609,10 +609,16 @@ uint64_t ScanGeneric(uint64_t cursor, const ScanOpts& scan_opts, StringVec* keys
...
   do {
-    ess->Await(sid, [&] {
+    auto cb = [&] {
       OpArgs op_args{EngineShard::tlocal(), 0, db_cntx};
       OpScan(op_args, scan_opts, &cursor, keys);
-    });
+    };
+
+    // Avoid deadlocking, if called from shard queue script
+    if (EngineShard::tlocal() && EngineShard::tlocal()->shard_id() == sid)
```
Comment (romange) [inline src/server/generic_family.cc:618]: nit: introduce a variable `my_sid = EngineShard::tlocal() ? EngineShard::tlocal()->shard_id() : kInvalidSid`

File: src/server/multi_test.cc [hunk 2]
```diff
@@ -396,13 +396,13 @@ TEST_F(MultiTest, Eval) {
   resp = Run({"eval", "return redis.call('get', 'foo')", "0"});
   EXPECT_THAT(resp, "42");
 
-  Run({"script", "flush"});
+  Run({"script", "flush"});  // Reset global flag from autocorrect
```
Comment (romange) [inline src/server/multi_test.cc:399]: what do you mean by this?

Comment (dranikpg) [reply src/server/multi_test.cc:399]: this is a very fragile test setup, because when we call 

>  resp = Run({"eval", "return redis.call('get', 'foo')", "0"});
  EXPECT_THAT(resp, ErrArg("undeclared"));

with out autocorrect flag, the whole script is automatically transferred to global mode, so all following tests would run the same sha in global mode  (we reuse redis.call(get, foo)) 

So it's a comment why we run script flush

File: src/server/generic_family.cc (hunk 1 above)
Comment (dranikpg) [reply src/server/generic_family.cc:618]: but it's not used anywhere except this if... why have two, if one is enough

File: src/server/multi_test.cc (hunk 2 above)
Comment (romange) [inline src/server/multi_test.cc:399]:
```suggestion
  Run({"script", "flush"});  // Reset global flag due to lua_allow_undeclared_auto_correct effect
```

**Review by romange — DISMISSED** [review]

**Review by romange — APPROVED** [review]

**Comment by romange** [comment]
@dranikpg  what happens once SCAN is nokey transactional? does it mean it's a global transaction?

**Comment by dranikpg** [comment]
> @dranikpg what happens once SCAN is nokey transactional? does it mean it's a global transaction?

No, it just will use the transactional style of running callbacks, so inlined scheduling will exist. However it doesn't fit into the transactional world, because it accesses all keys and is commonly used. Theoretically we shouldn't allow it then in script that don't request undeclared keys
