### PR TITLE
fix(BgSave): async from sync

### LINKED ISSUE #2642: BGSAVE and SAVE commands don't return OK immediately
**Describe the bug**
BGSAVE and SAVE commands doesn't return OK until background operation finishes. Redis BGSAVE works this way therefore a management code written for a Redis won't work well with Dragonfly at the moment.

**To Reproduce**
1. Run BGSAVE ~or SAVE~
2. Client waits to return OK until operation in the background finishes. 

**Expected behavior**
Client must return OK immediately for async nature of the BGSAVE command

**Environment (please complete the following information):**
OS: Fedora 38
Kernel: 6.3.12-200.fc38.x86_64
Containerized?: toolbox
Dragonfly Version: 1.14.4

### PR DESCRIPTION
**Pull request by kostasrim**
resolves #2642

* make BgSave command async

Note that we extend the command by adding `BGSAVE [RDB_TYPE] [NAME] [SCHEDULE]` but in Redis it's `BGSAVE [SCHEDULE]`. Unfortunately, DF supports two rdb_types (df extension and plain redis rdb) and I would like to keep compatibility. 

Furthermore, the option [schedule] is missing. See: #2701

### CODE REVIEW

**Comment by kostasrim** [comment]
TODO: need to add test + some small refactor (maybe)

File: src/server/server_family.h [hunk 1]
```diff
@@ -297,6 +300,10 @@ class ServerFamily {
   std::unique_ptr<util::fb2::FiberQueueThreadPool> fq_threadpool_;
   std::shared_ptr<detail::SnapshotStorage> snapshot_storage_;
 
+  Mutex bg_save_mu_;
+  util::fb2::Fiber bg_save_fb_;
+  bool bg_save_fb_done_ = false;
```
Comment (kostasrim) [inline src/server/server_family.h:305]: I would have loved a polling interface on a fiber, anyway I can move this to separate class for now. ServerFamilly members are exploding :rofl:

File: src/server/server_family.cc [hunk 2]
```diff
@@ -1629,11 +1631,65 @@ void ServerFamily::Memory(CmdArgList args, ConnectionContext* cntx) {
...
+    string_view sub_cmd = ArgS(args, 0);
+    if (sub_cmd == "DF") {
+      new_version = true;
+    } else if (sub_cmd == "RDB") {
+      new_version = false;
+    } else {
+      return cntx->SendError(UnknownSubCmd(sub_cmd, "SAVE"), kSyntaxErrType);
+    }
+  }
+
```
Comment (dranikpg) [inline src/server/server_family.cc:1666]: this a duplicate of Save(), why don't we just call it?

File: src/server/server_family.cc [hunk 3]
```diff
@@ -1629,11 +1631,65 @@ void ServerFamily::Memory(CmdArgList args, ConnectionContext* cntx) {
...
+    if (bg_save_fb_done_) {
+      // non blocking, fiber is in Terminate state
+      bg_save_fb_.Join();
+    }
+    bg_save_fb_done_ = false;
+    bg_save_fb_ = fb2::Fiber("bg_save_fiber", &ServerFamily::BgSaveFb, this, new_version,
+                             std::string(basename), cntx->transaction);
+  }
+  cntx->SendOk();
+}
```
Comment (dranikpg) [inline src/server/server_family.cc:1687]: We already have save exclusivity with `save_mu_`, why do we want to manage bgsave separately? We can store no information at all about it

File: src/server/server_family.cc (hunk 2 above)
Comment (dranikpg) [reply src/server/server_family.cc:1666]: The only downside is that we won't validate arguments 🤷🏻

File: src/server/server_family.cc [hunk 4]
```diff
@@ -1629,11 +1631,65 @@ void ServerFamily::Memory(CmdArgList args, ConnectionContext* cntx) {
   return mem_cmd.Run(args);
 }
 
+void ServerFamily::BgSaveFb(bool new_version, std::string basename,
+                            boost::intrusive_ptr<Transaction> trans) {
+  GenericError ec = DoSave(new_version, basename, trans.get());
```
Comment (adiholden) [inline src/server/server_family.cc:1636]: I think that DoSave should be splited to the checks and init phase and to the wait and finish phase.
This way when you call bgsave you will return error imidiatly if there is some params error or save is already in progress (not only bgsave in progress).
And the bg save fiber will contain only the wait and finish phase

File: src/server/server_family.cc [hunk 5]
```diff
@@ -2634,7 +2690,7 @@ void ServerFamily::Register(CommandRegistry* registry) {
   registry->StartFamily();
   *registry
       << CI{"AUTH", CO::NOSCRIPT | CO::FAST | CO::LOADING, -2, 0, 0, acl::kAuth}.HFUNC(Auth)
-      << CI{"BGSAVE", CO::ADMIN | CO::GLOBAL_TRANS, 1, 0, 0, acl::kBGSave}.HFUNC(Save)
+      << CI{"BGSAVE", CO::ADMIN | CO::GLOBAL_TRANS, -1, 0, 0, acl::kBGSave}.HFUNC(BgSave)
```
Comment (adiholden) [inline src/server/server_family.cc:2693]: please add pytests for several save and bgsave running at the same time

File: src/server/server_family.h [hunk 6]
```diff
@@ -297,6 +311,10 @@ class ServerFamily {
   std::unique_ptr<util::fb2::FiberQueueThreadPool> fq_threadpool_;
   std::shared_ptr<detail::SnapshotStorage> snapshot_storage_;
 
+  Mutex bg_save_mu_;
```
Comment (adiholden) [inline src/server/server_family.h:314]: I think it is not used now

File: src/server/server_family.cc [hunk 7]
```diff
@@ -1329,7 +1330,11 @@ GenericError ServerFamily::DoSave(bool new_version, string_view basename, Transa
       return res->error;
     }
   }
+  return {};
+}
 
+GenericError ServerFamily::PauseUntilSaved(bool new_version, string_view basename,
```
Comment (adiholden) [inline src/server/server_family.cc:1336]: you dont use the params given to this function.. I believe they can be removed

Comment (adiholden) [reply src/server/server_family.cc:1336]: also maybe rename to WaitUntilSaveFinish

File: tests/dragonfly/snapshot_test.py [hunk 8]
```diff
@@ -356,3 +357,20 @@ async def info_in_loop():
...
+
+@dfly_args({**BASIC_ARGS, "dbfilename": "test-bgsave"})
+async def test_bgsave_and_save(async_client: aioredis.Redis):
+    await async_client.execute_command("DEBUG POPULATE 20000")
+
+    await async_client.execute_command("BGSAVE")
+    with pytest.raises(redis.exceptions.ResponseError):
+        await async_client.execute_command("BGSAVE")
+
+    await asyncio.sleep(2)
```
Comment (adiholden) [inline tests/dragonfly/snapshot_test.py:370]: instead of sleep for 2 seconds I suggest use

async def is_saving():
        return "saving:1" in (await async_client.execute_command("INFO PERSISTENCE"))

while not await is_saving():  # wait for server start saving
        asyncio.sleep(0.1)

**Review by adiholden — APPROVED** [review]
