### PR TITLE
fix: remove acl-check and cancel instead when REPLCONF ACK fails to validate

### LINKED ISSUE #2907: `replicaof no one` hangs on replica when connectivity to master is broken
**Describe the bug**
In a failover scenario to the replica instance, when a replica can't connect to its master anymore, `replicaof no one` command fails to return OK but instead hangs for a relatively long time. Observed in another shell that replica seems have accepted the config change and reports as master; so the command actually works. Simple workaround would be handling the timeout and ignoring it; however then it might cause false negatives later when other timeouts happen for more genuine reasons.

**To Reproduce**
1. Setup a master and replica DF.
2. Break the network connectivity between master and replica processes. 
3. Issue `replicaof no one` on the replica node
4. See that the command request hangs for a relatively long time and client times out.

**Expected behavior**
Server must return OK response to the client.

**Environment :**
- Dragonfly Version: 1.16.1

**Additional context**
1.14.5 doesn't have the same issue.

### PR DESCRIPTION
**Pull request by kostasrim**
resolves #2907 

* remove acl-checker which is also the source of this bug
* add a fallback that cancels replication when REPLCONF ACK fail

### CODE REVIEW

**Comment by romange** [comment]
@kostasrim why the acl checker (on replica ? ) calls SendCommandAndReadResponse ?

**Comment by kostasrim** [comment]
> @kostasrim why the acl checker (on replica ? ) calls SendCommandAndReadResponse ?

Because it pings master periodically to auth the connection for ACL changes (because the ACL's of the authed user might change and replication would need to be cancelled)

Snippet :
```
    void CheckAclRoundTrip() {
      if (auto ec = SendCommandAndReadResponse(StrCat("REPLCONF acl-check ", "0")); ec) {
        cntx_->Cancel();
        LOG(INFO) << "Error in REPLCONF acl-check: " << ec.message();
      } else if (!CheckRespIsSimpleReply("OK")) {
        cntx_->Cancel();
        LOG(INFO) << "Error: " << ToSV(LastResponseArgs().front().GetBuf());
      }    
    }


```

**Comment by romange** [comment]
@kostasrim  but if the replication needs to be cancelled why the replica needs to know about this? why not shutdown the connection on a master side?

**Comment by kostasrim** [comment]
> but if the replication needs to be cancelled why the replica needs to know about this? why not shutdown the connection on the master side?

because if we just shutdown the connection we don't really know what happened on the replica side but we should because there was an ACL change that invalidated somehow the ACL's of the user`masterauth && masterpass`. We can't just kill the connection, we want to make sure that the replica is aware of this happened and killing a connection is not necessary an indicator of ACL failure. This is done by redis as well IMO, I made sure we got consistent semantics

**Comment by romange** [comment]
I agree that killing a connection is not an indicator but lets simulate the rest of the flow:
1. The master kills the connection. 
2. Replica does not know why so it tries to reconnect.
3. It authenticates and gets an invalid auth response.

Why this flow is not good?

**Comment by kostasrim** [comment]
> I agree that killing a connection is not an indicator but lets simulate the rest of the flow:
> 
> 1. The master kills the connection.
> 2. Replica does not know why so it tries to reconnect.
> 3. It authenticates and gets an invalid auth response.
> 
> Why this flow is not good?

One issue I can think of is that this introduces a race. Once a connection is killed, there is a very very small window/chance that the ACL's got changed again BEFORE the replica tries to reconnect. So for example, 

1. replication works all good
2. acl changes to the authenticated user for replication 
3. acl-check causes the master to kill replication 
4. acl  changes again to the authenticated user for replication
5. now replica tries to reconnect and it works

You just made an error message disappear.

Another problem is that you just slightly changing the protocol:

We validate commands against the ACL's. The problem is, on reconnect there other commands that are being said that belong to different categories. So, you can also have a failure for some other ACL category that was completely irrelevant of the original flow (I am thinking of PING, because if I recall correctly we ping during reconnect). But any other command called during that flow might cause an ACL failure completely unrelated to the original one.

Also I don't really understand why would you want to funnel the ACL validation in the normal `replication reconnect flow` or how would this have helped with the issue in this PR. Why not keep them separate since they logically differ and there is no really a regression (I doubt that the extra "OK" replies for master are even measurable) or reason to go with a different route (other than the potential to inject more bugs because we missed something like the two examples I give above).

File: src/server/server_family.cc [hunk 1]
```diff
@@ -2598,9 +2598,6 @@ void ServerFamily::ReplConf(CmdArgList args, ConnectionContext* cntx) {
       VLOG(2) << "Received client ACK=" << ack;
       cntx->replication_flow->last_acked_lsn = ack;
       return;
-    } else if (cmd == "ACL-CHECK") {
```
Comment (kostasrim) [inline src/server/server_family.cc:2601]: This breaks replication when replica is of lower version. My two cents is that we don't care for this case since this setup doesn't really make much sense. Let me know if you disagree

File: src/server/replica.cc [hunk 2]
```diff
@@ -893,53 +884,6 @@ void Replica::RedisStreamAcksFb() {
   }
 }
 
-class AclCheckerClient : public ProtocolClient {
```
Comment (kostasrim) [inline src/server/replica.cc:896]: This introduces a small bug if master is an older version that we cover in our tests. The problem is that if ACL of the `masteruser` changes  then `REPLCONF ACK` will start failing silently without noticing and replication will break :( 

I guess this setup is more probably since upgrading from one version to the other would involve a replica copying the data and then being promoted to master. An intermediate solution would be to keep this check for older version masters and deprecate/completely remove at some later point. 

I am open for suggestions

File: src/server/server_family.cc (hunk 1 above)
Comment (romange) [reply src/server/server_family.cc:2601]: please keep the code in master and add a TODO with your anniversary date to remove this code.

Comment (kostasrim) [reply src/server/server_family.cc:2601]: I will add an alarm on my calendar as well :wink:

File: src/server/replica.cc [hunk 3]
```diff
@@ -893,6 +893,7 @@ void Replica::RedisStreamAcksFb() {
   }
 }
 
+// TODO(kostasrim): Remove this on 20/6/2024
```
Comment (romange) [inline src/server/replica.cc:896]: I am totally confused. Should not you remove the replica side checks so that later you will be able to remove master side responses?
Where do you remove acl-check as written in the PR title?

Comment (kostasrim) [reply src/server/replica.cc:896]: Sorry, my bad here. While I was making the changes I realized that the code I introduced above is enough to allow us a smooth transition (that means as long as two subsequent versions of df contain the code below we can remove both the acl-checks and be fine without the clients noticing.

```
      auto info_ptr = server_family_.GetReplicaInfo(dfly_cntx);
      if (info_ptr) {
        info_ptr->cntx.Cancel();
      }
      return;
```

However, I do agree we should remove this now. I will push an update soon.

File: src/server/main_service.cc [hunk 4]
```diff
@@ -1147,7 +1147,10 @@ void Service::DispatchCommand(CmdArgList args, facade::ConnectionContext* cntx)
     // Bonus points because this allows to continue replication with ACL users who got
     // their access revoked and reinstated
     if (cid->name() == "REPLCONF" && absl::EqualsIgnoreCase(ArgS(args_no_cmd, 0), "ACK")) {
-      LOG(ERROR) << "Tried to reply to REPLCONF";
+      auto info_ptr = server_family_.GetReplicaInfo(dfly_cntx);
```
Comment (romange) [inline src/server/main_service.cc:1150]: @adiholden  please help me reviewing these changes

File: src/server/replica.cc (hunk 2 above)
Comment (romange) [reply src/server/replica.cc:896]: this is fine, the use-case is not interesting.

File: src/server/protocol_client.h [hunk 5]
```diff
@@ -116,6 +116,10 @@ class ProtocolClient {
     return sock_.get();
   }
 
+  void SetSocketTimeout(uint32_t msec) {
```
Comment (adiholden) [inline src/server/protocol_client.h:119]: Is this called ?

**Comment by adiholden** [comment]
@kostasrim how does this solves #2907 ?

**Review by adiholden — APPROVED** [review]
