### PR TITLE
fix: heap buffer overflow in StringSet::AddBatch when updating TTL

### LINKED ISSUE #6978: Dragonfly crashes [fuzzer]
**The crash is unstable; try to reproduce it a few times.**

[crash-000000.tar.gz](https://github.com/user-attachments/files/26240852/crash-000000.tar.gz)

```
./build-dbg/dragonfly --port=6379 --logtostderr --proactor_threads=1
```

```
python3 replay_crash.py crashes 000000 127.0.0.1 6379
```

The crash log:
```
*** SIGSEGV received at time=1774435475 on cpu 0 ***
PC: @     0xaaaac1029c7c  (unknown)  mi_heap_malloc
    @     0xaaaac121377c         64  absl::lts_20250512::WriteFailureInfo()
    @     0xaaaac1213a94         96  absl::lts_20250512::AbslFailureSignalHandler()
    @     0xffff805a77d0       4736  (unknown)
    @     0xaaaac10284b0         32  zmalloc_usable
    @     0xaaaac1016618        160  _sdsnewlen
    @     0xaaaac10168b8         16  sdsnewlen
    @     0xaaaac0cec370         32  dfly::StringSet::MakeSetSds()
    @     0xaaaac0ceb420         80  dfly::StringSet::Add()
    @     0xaaaac0617b74        288  dfly::SetFamily::ConvertToStrSet()
    @     0xaaaac060efb8        832  dfly::(anonymous namespace)::OpAdd()
    @     0xaaaac0612b00        192  dfly::(anonymous namespace)::CmdSAdd()::{lambda()#1}::operator()()
    @     0xaaaac061b3d4         32  dfly::Transaction::ScheduleSingleHopT<>()::{lambda()#1}::operator()()
    @     0xaaaac0625450         64  std::__invoke_impl<>()
    @     0xaaaac06245f0         64  std::__invoke<>()
    @     0xaaaac0622b28         80  std::invoke<>()
    @     0xaaaac0620c04        128  absl::lts_20250512::functional_internal::InvokeObject<>()
    @     0xaaaac0c42474         32  absl::lts_20250512::FunctionRef<>::operator()()
    @     0xaaaac0c2d91c        256  dfly::Transaction::RunCallback()
    @     0xaaaac0c329f4        416  dfly::Transaction::ScheduleInShard()
    @     0xaaaac0c2e90c        320  dfly::Transaction::ScheduleInternal()
    @     0xaaaac0c2fefc         48  dfly::Transaction::Execute()
    @     0xaaaac0c2f760         64  dfly::Transaction::ScheduleSingleHop()
    @     0xaaaac061b460        144  dfly::Transaction::ScheduleSingleHopT<>()
    @     0xaaaac0612c04        128  dfly::(anonymous namespace)::CmdSAdd()
    @     0xaaaac0419df4         32  fu2::abi_400::detail::invocation::invoke<>()
    @     0xaaaac040eba0         64  fu2::abi_400::detail::type_erasure::invocation_table::function_trait<>::internal_invoker<>::invoke()
    @     0xaaaac0818f68         96  fu2::abi_400::detail::type_erasure::tables::vtable<>::invoke<>()
    @     0xaaaac0819004        176  fu2::abi_400::detail::type_erasure::erasure<>::invoke<>()
    @     0xaaaac0819080         32  fu2::abi_400::detail::type_erasure::invocation_table::operator_impl<>::operator()()
    @     0xaaaac08163a0         80  dfly::CommandId::Invoke()
    @     0xaaaac07c601c        512  dfly::Service::InvokeCmd()
    @     0xaaaac09e208c       1248  dfly::MultiCommandSquasher::SquashedHopCb()
    @ ... and at least 18 more frames
```

### PR DESCRIPTION
**Pull request by vyavdoshenko**
SADDEX on a member originally added via SADD causes a heap buffer overflow.
SADD allocates SDS strings without extra TTL space (`sdsnewlen`). When SADDEX later finds the same member and calls `ObjUpdateExpireTime`, it writes 4 TTL bytes past the SDS null terminator into unallocated memory, corrupting mimalloc heap metadata.

The crash is non-deterministic — it manifests as SIGSEGV in `mi_heap_malloc` (or `_mi_page_free_collect`) during a subsequent allocation, depending on whether the overflow hits mimalloc padding or adjacent block metadata.

Fixes #6978

### CODE REVIEW

File: src/core/string_set.cc [hunk 1]
```diff
@@ -97,7 +97,14 @@ unsigned StringSet::AddBatch(absl::Span<std::string_view> span, uint32_t ttl_sec
       sds field = MakeSetSds(span[i], ttl_sec);
       AddUnique(field, has_ttl, hash[i]);
     } else if (has_ttl && !keepttl) {
-      ObjUpdateExpireTime(prev, ttl_sec);
+      // We must not call ObjUpdateExpireTime directly on prev because the existing SDS
+      // may have been allocated without TTL space (e.g., via SADD which uses sdsnewlen).
+      // Writing 4 TTL bytes past the null terminator would cause a heap buffer overflow.
+      // Instead, create a new SDS with TTL space and replace the old one.
+      sds field = MakeSetSds(span[i], ttl_sec);
```
Comment (romange) [inline src/core/string_set.cc:104]: please write a test in src/core/string_set_test.cc that uncovers the bug

File: src/server/set_family.cc [hunk 2]
```diff
@@ -944,6 +944,11 @@ OpResult<StringVec> OpPop(const OpArgs& op_args, string_view key, unsigned count
     // Delete the set as it is now empty
     db_slice.DelMutable(op_args.db_cntx, std::move(*find_res));
 
+    // All members may have expired during iteration (lazy expiry), leaving the result empty.
+    if (result.empty()) {
```
Comment (romange) [inline src/server/set_family.cc:975]: this is the only test we need in `set_family_test.cc`. to cover this condition, not the bug in dense_set.cc

File: src/core/string_set.cc (hunk 1 above)
Comment (vyavdoshenko) [reply src/core/string_set.cc:104]: Fixed

File: src/server/set_family.cc (hunk 2 above)
Comment (vyavdoshenko) [reply src/server/set_family.cc:975]: Fixed
