### PR TITLE
fix: race when bumping items while loading a snapshot

### LINKED ISSUE #4554: SIGSEGV with 1.26.2 and cache_mode=true
Opening a new issue because #4497 is closed.

This issue seems not totally fixed.

here is output with Dragonfly 1.26.2 launched with : 
`--dbfilename=dump    - --cache_mode=true    - --vmodule=streamer=1,dflycmd=1,replica=1`

It affects replica instance.
```
I20250204 08:06:42.981666     1 dfly_main.cc:691] Starting dragonfly df-v1.26.2-096fde172300de91850c42dab24aa09ffee254d0
I20250204 08:06:42.981844     1 dfly_main.cc:735] maxmemory has not been specified. Deciding myself....
I20250204 08:06:42.981854     1 dfly_main.cc:744] Found 2.00GiB available memory. Setting maxmemory to 1.60GiB
W20250204 08:06:42.981900     1 dfly_main.cc:368] Weird error 1 switching to epoll
I20250204 08:06:43.059904     1 proactor_pool.cc:147] Running 2 io threads
I20250204 08:06:43.062503     1 dfly_main.cc:272] Listening on admin socket any:9999
I20250204 08:06:43.063760     1 server_family.cc:835] Host OS: Linux 5.14.0-503.22.1.el9_5.x86_64 x86_64 with 2 threads
I20250204 08:06:43.068403     1 snapshot_storage.cc:185] Load snapshot: Searching for snapshot in directory: "/dragonfly/snapshots"
I20250204 08:06:43.073527     1 server_family.cc:1114] Loading /dragonfly/snapshots/dump-summary.dfs
I20250204 08:06:43.087914     6 listener_interface.cc:101] sock[8] AcceptServer - listening on port 6379
I20250204 08:06:43.089705     7 listener_interface.cc:101] sock[7] AcceptServer - listening on port 9999
I20250204 08:06:43.089743     7 listener_interface.cc:101] sock[9] AcceptServer - listening on port 11211
I20250204 08:06:44.393589     6 server_family.cc:1154] Load finished, num keys read: 572201
I20250204 08:06:56.683905     7 server_family.cc:2769] Replicating 10.233.137.19:9999
F20250204 08:06:56.685020     7 db_slice.cc:784] Check failed: fetched_items_.empty() 
*** Check failure stack trace: ***
    @     0x558c1fd18923  google::LogMessage::SendToLog()
    @     0x558c1fd110e7  google::LogMessage::Flush()
    @     0x558c1fd12a6f  google::LogMessageFatal::~LogMessageFatal()
    @     0x558c1f550aef  dfly::DbSlice::FlushDbIndexes()
    @     0x558c1f550c82  dfly::DbSlice::FlushDb()
    @     0x558c1f2d02ba  _ZN4absl12lts_2024011619functional_internal12InvokeObjectIZN4dfly12ServerFamily8DrakarysEPNS3_11TransactionEtEUlS6_PNS3_11EngineShardEE_NS5_14RunnableResultEJS6_S8_EEET0_NS1_7VoidPtrEDpNS1_8ForwardTIT1_E4typeE
    @     0x558c1f590bf9  dfly::Transaction::RunCallback()
    @     0x558c1f5939db  dfly::Transaction::RunInShard()
    @     0x558c1f4d1b60  dfly::EngineShard::PollExecution()
    @     0x558c1f58c7e1  _ZNSt17_Function_handlerIFvvEZN4dfly11Transaction11DispatchHopEvEUlvE1_E9_M_invokeERKSt9_Any_data
    @     0x558c1fafe395  util::fb2::FiberQueue::Run()
    @     0x558c1f5deb70  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberEN4util3fb219FixedStackAllocatorEZNS6_6detail15WorkerFiberImplIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_JEEC4IS7_EESF_RKNS0_12preallocatedEOT_OSG_EUlOS4_E_EEEEvNS1_10transfer_tE
    @     0x558c1fb1d69f  make_fcontext
*** SIGABRT received at time=1738656416 on cpu 1 ***
PC: @     0x7ff0adabe9fc  (unknown)  pthread_kill
[failure_signal_handler.cc : 345] RAW: Signal 11 raised at PC=0x7ff0ada50898 while already in AbslFailureSignalHandler()
*** SIGSEGV received at time=1738656416 on cpu 1 ***
PC: @     0x7ff0ada50898  (unknown)  abort
```

The pod crash "sometimes". Here, it crashed once and is now running correctly : 
```
I20250204 08:07:18.717423     1 server_family.cc:835] Host OS: Linux 5.14.0-503.22.1.el9_5.x86_64 x86_64 with 2 threads
I20250204 08:07:18.721555     1 snapshot_storage.cc:185] Load snapshot: Searching for snapshot in directory: "/dragonfly/snapshots"
I20250204 08:07:18.724478     1 server_family.cc:1114] Loading /dragonfly/snapshots/dump-summary.dfs
I20250204 08:07:18.733318     6 listener_interface.cc:101] sock[8] AcceptServer - listening on port 6379
I20250204 08:07:18.733692     7 listener_interface.cc:101] sock[7] AcceptServer - listening on port 9999
I20250204 08:07:18.733723     7 listener_interface.cc:101] sock[9] AcceptServer - listening on port 11211
I20250204 08:07:20.000798     6 server_family.cc:1154] Load finished, num keys read: 572201
I20250204 08:07:36.684935     7 server_family.cc:2769] Replicating 10.233.137.19:9999
I20250204 08:07:36.743476     7 replica.cc:94] Starting replication
I20250204 08:07:36.743537     7 replica.cc:116] Resolving master DNS
I20250204 08:07:36.743656     7 replica.cc:121] Connecting to master
I20250204 08:07:36.744189     7 replica.cc:126] Greeting
I20250204 08:07:36.744204     7 replica.cc:281] greeting message handling
I20250204 08:07:36.745363     7 replica.cc:360] Master id: 9d33ab3e04153c86a6b2f8f4825a4a7e03b92786, sync id: SYNC1, num journals: 2, version: 3
I20250204 08:07:36.745939     7 replica.cc:193] Main replication fiber started
I20250204 08:07:36.746312     7 replica.cc:741] Sending on flow 9d33ab3e04153c86a6b2f8f4825a4a7e03b92786 SYNC1 1
I20250204 08:07:36.746456     6 replica.cc:741] Sending on flow 9d33ab3e04153c86a6b2f8f4825a4a7e03b92786 SYNC1 0
I20250204 08:07:36.747501     7 replica.cc:724] Sending: DFLY SYNC SYNC1
I20250204 08:07:36.750665     7 replica.cc:569] Started full sync with 10.233.137.19:9999
I20250204 08:07:36.750690     7 replica.cc:573] Waiting for all full sync cut confirmations
I20250204 08:07:36.803468     7 server_family.cc:2769] Replicating 10.233.137.19:9999
I20250204 08:07:36.803522     7 replica.cc:148] Stopping replication
I20250204 08:07:36.809708     6 replica.cc:843] FullSyncDflyFb finished after reading 3067928 bytes
I20250204 08:07:36.815779     7 replica.cc:843] FullSyncDflyFb finished after reading 3485050 bytes
W20250204 08:07:36.815847     7 replica.cc:246] Error syncing with 10.233.137.19:9999 generic:125 Operation canceled
I20250204 08:07:36.815882     7 replica.cc:276] Main replication fiber finished
I20250204 08:07:36.825311     7 replica.cc:94] Starting replication
I20250204 08:07:36.825345     7 replica.cc:116] Resolving master DNS
I20250204 08:07:36.825459     7 replica.cc:121] Connecting to master
I20250204 08:07:36.825807     7 replica.cc:126] Greeting
I20250204 08:07:36.825820     7 replica.cc:281] greeting message handling
I20250204 08:07:36.826691     7 replica.cc:360] Master id: 9d33ab3e04153c86a6b2f8f4825a4a7e03b92786, sync id: SYNC2, num journals: 2, version: 3
I20250204 08:07:36.827033     7 replica.cc:193] Main replication fiber started
I20250204 08:07:36.827302     7 replica.cc:741] Sending on flow 9d33ab3e04153c86a6b2f8f4825a4a7e03b92786 SYNC2 1
I20250204 08:07:36.827404     6 replica.cc:741] Sending on flow 9d33ab3e04153c86a6b2f8f4825a4a7e03b92786 SYNC2 0
I20250204 08:07:36.828095     7 replica.cc:724] Sending: DFLY SYNC SYNC2
I20250204 08:07:36.830502     7 replica.cc:569] Started full sync with 10.233.137.19:9999
I20250204 08:07:36.830538     7 replica.cc:573] Waiting for all full sync cut confirmations
I20250204 08:07:37.742475     7 replica.cc:724] Sending: DFLY STARTSTABLE SYNC2
I20250204 08:07:37.743093     7 replica.cc:843] FullSyncDflyFb finished after reading 75630512 bytes
I20250204 08:07:37.743252     6 replica.cc:843] FullSyncDflyFb finished after reading 56034881 bytes
I20250204 08:07:37.744261     7 replica.cc:589] full sync finished in 917 ms
I20250204 08:07:37.744330     7 replica.cc:679] Transitioned into stable sync
I20250204 08:07:37.745183     7 replica.cc:921] Sending an ACK with offset=17 forced=0
I20250204 08:07:37.745688     6 replica.cc:921] Sending an ACK with offset=18 forced=0
I20250204 08:07:38.745687     7 replica.cc:921] Sending an ACK with offset=64 forced=0
I20250204 08:07:38.745963     6 replica.cc:921] Sending an ACK with offset=36 forced=0
I20250204 08:07:39.745767     7 replica.cc:921] Sending an ACK with offset=139 forced=0
I20250204 08:07:39.746300     6 replica.cc:921] Sending an ACK with offset=104 forced=0
I20250204 08:07:40.746562     7 replica.cc:921] Sending an ACK with offset=209 forced=0
I20250204 08:07:40.746655     6 replica.cc:921] Sending an ACK with offset=172 forced=0
I20250204 08:07:41.245782     7 server_family.cc:2769] Replicating 10.233.137.19:9999
I20250204 08:07:41.245841     7 replica.cc:148] Stopping replication
I20250204 08:07:41.246042     7 replica.cc:703] Exit stable sync
I20250204 08:07:41.246091     7 replica.cc:276] Main replication fiber finished
I20250204 08:07:41.318176     7 replica.cc:94] Starting replication
I20250204 08:07:41.318238     7 replica.cc:116] Resolving master DNS
I20250204 08:07:41.318380     7 replica.cc:121] Connecting to master
I20250204 08:07:41.318848     7 replica.cc:126] Greeting
I20250204 08:07:41.318864     7 replica.cc:281] greeting message handling
I20250204 08:07:41.320183     7 replica.cc:360] Master id: 9d33ab3e04153c86a6b2f8f4825a4a7e03b92786, sync id: SYNC3, num journals: 2, version: 3
I20250204 08:07:41.321235     7 replica.cc:193] Main replication fiber started
I20250204 08:07:41.321892     7 replica.cc:741] Sending on flow 9d33ab3e04153c86a6b2f8f4825a4a7e03b92786 SYNC3 1
I20250204 08:07:41.322031     6 replica.cc:741] Sending on flow 9d33ab3e04153c86a6b2f8f4825a4a7e03b92786 SYNC3 0
I20250204 08:07:41.323082     7 replica.cc:724] Sending: DFLY SYNC SYNC3
I20250204 08:07:41.326880     7 replica.cc:569] Started full sync with 10.233.137.19:9999
I20250204 08:07:41.326922     7 replica.cc:573] Waiting for all full sync cut confirmations
I20250204 08:07:42.240965     7 replica.cc:724] Sending: DFLY STARTSTABLE SYNC3
I20250204 08:07:42.241829     7 replica.cc:843] FullSyncDflyFb finished after reading 75717753 bytes
I20250204 08:07:42.242180     6 replica.cc:843] FullSyncDflyFb finished after reading 55223393 bytes
I20250204 08:07:42.243268     7 replica.cc:589] full sync finished in 921 ms
I20250204 08:07:42.243342     7 replica.cc:679] Transitioned into stable sync
I20250204 08:07:42.244382     7 replica.cc:921] Sending an ACK with offset=256 forced=0
I20250204 08:07:42.245657     6 replica.cc:921] Sending an ACK with offset=203 forced=0
I20250204 08:07:43.245344     7 replica.cc:921] Sending an ACK with offset=281 forced=0
I20250204 08:07:43.246227     6 replica.cc:921] Sending an ACK with offset=222 forced=0
I20250204 08:07:44.245911     7 replica.cc:921] Sending an ACK with offset=383 forced=0
I20250204 08:07:44.246526     6 replica.cc:921] Sending an ACK with offset=299 forced=0
[ last mesage repeating ]
```

### PR DESCRIPTION
**Pull request by kostasrim**
The original issue was submitted in #4497 and we supplied a fix in #4507. However, the fix ignored that the `RdbLoader::Load()` function is run per flow/shard thread and the "poison pill" of updating the loading state at the end of `RdbLoader::Load()` introduced a race condition:

```
shard_set->Add(i, [bc]() mutable {
      namespaces->GetDefaultNamespace().GetCurrentDbSlice().SetLoadInProgress(false);
      bc->Dec();
    }); 
```

Any flow `F` that finished loading its own snapshot first (relatively to the rest of the flows) will call `SetLoadInProgress(false)` on *ALL* shard threads. The consequence of that is that other flows are not yet done (their respective RdbLoader::Load()` is still processing) and next time the use the db slice API will start Bumping up items because now load in progress is false.

The fix is to update the state after all shard flows are done and similarly to update all shard flow `before` we start the `Load()` which shall provide a consistent state/view among all shard threads.

Should resolve #4554

P.s. we might be able to simplify the new db slice state via the global loading state. That's something I will need to follow but I won't do this as part of this PR.

### CODE REVIEW

**Review by romange — COMMENTED** [review]
Maybe I misunderstand something but why do we need to orcherstrate SetLoadInProgress on all the shards? Can we do it locally on each shard? i.e. independently for each shard?

**Comment by kostasrim** [comment]
> Maybe I misunderstand something but why do we need to orcherstrate SetLoadInProgress on all the shards? Can we do it locally on each shard? i.e. independently for each shard?

Good question! Because master and replica might have different number of proactors. So imagine the following case:

Flow 1 -> Sets the shard's 1 loading state to true. 
Flow 2 -> Still hasn't set its local loading state to true (the flow fiber did not even start because the proactor was busy)

Flow 1 had only one item, `Load` finished instantly and now it calls `FinishLoad` which calls `FlushShardAsync` which unfortunately calls `LoadItemsBuffer` on `shard number 2`. Boom, `state loading is false`. In other words, each flow at the end can dispatch to multiple shards which might have not yet have their state updated. And we can't really rely on the order of submissions to the task/shard queue (since we don't have a guarantee of sequential task execution from what you have said in the past -- and I could be wrong here). 

However, saying this, I think there is a better solution! If we call `FlushShardAsync` we can first check if the loading state is updated. If it's not we can set it to true. That way we "save" the first scatter part of the operation (dispatching to all shard threads and update the state). We only keep the "gather" step (updating the state to false after all the loaders completed)

**Comment by romange** [comment]
i did not analyse the code but maybe using a `unsigned` counter instead of boolean in db_slice will simplify things?
i.e. every time we start we increase and when we stop we decrease.

File: src/server/rdb_test.cc [hunk 1]
```diff
@@ -735,4 +735,19 @@ TEST_F(RdbTest, HugeKeyIssue4497) {
   EXPECT_EQ(Run({"flushall"}), "OK");
 }
 
+TEST_F(RdbTest, HugeKeyIssue4554) {
```
Comment (kostasrim) [inline src/server/rdb_test.cc:738]: This fails without my changes.

IMO, I wanted to reproduce via a replication test, because only replication is used on the issue. However, it proved to be a little more difficult than expected for reasons it's hard for me to explain in a few lines. I am fairly positive that this PR will address all the problems but I would like to have a binary asap to sent and verify that we did see the same/similar case on the issue as here.

**Comment by kostasrim** [comment]
> i did not analyse the code but maybe using a `unsigned` counter instead of boolean in db_slice will simplify things? i.e. every time we start we increase and when we stop we decrease.

Now that we have a test I will polish. Let me think and I will get back to you soon

**Comment by kostasrim** [comment]
> > i did not analyse the code but maybe using a `unsigned` counter instead of boolean in db_slice will simplify things? i.e. every time we start we increase and when we stop we decrease.
> 
> Now that we have a test I will polish. Let me think and I will get back to you soon

@romange sequence numbers worked like charm!

File: src/server/rdb_load.cc [hunk 2]
```diff
@@ -2554,6 +2562,8 @@ void RdbLoader::LoadItemsBuffer(DbIndex db_ind, const ItemsBuf& ib) {
   DbContext db_cntx{&namespaces->GetDefaultNamespace(), db_ind, GetCurrentTimeMs()};
   DbSlice& db_slice = db_cntx.GetDbSlice(es->shard_id());
 
+  DCHECK(!db_slice.IsCacheMode());
```
Comment (kostasrim) [inline src/server/rdb_load.cc:2565]: Maybe `CHECK` instead ?

Comment (romange) [reply src/server/rdb_load.cc:2565]: no need

File: src/server/db_slice.h [hunk 3]
```diff
@@ -598,6 +601,7 @@ class DbSlice {
   size_t soft_budget_limit_ = 0;
   size_t table_memory_ = 0;
   uint64_t entries_count_ = 0;
+  size_t load_in_progress_ = 0;
```
Comment (romange) [inline src/server/db_slice.h:604]: nit: use size_t for sizes, unsigned for counters, also maybe change the name to `load_ref_cnt_` ?

File: src/server/db_slice.cc [hunk 4]
```diff
@@ -283,7 +283,6 @@ DbSlice::DbSlice(uint32_t index, bool cache_mode, EngineShard* owner)
       cache_mode_(cache_mode),
       owner_(owner),
       client_tracking_map_(owner->memory_resource()) {
-  load_in_progress_ = false;
```
[the remark this answers is not in the document]
Comment (kostasrim) [reply src/server/db_slice.cc:286]: oh I forgot this, you mentioned in it in the standup

File: src/server/db_slice.h (hunk 3 above)
Comment (kostasrim) [reply src/server/db_slice.h:604]: sure no issue again that! Out of curiosity why unsigned for counter ? (size_t is also unsigned :smile: )

Comment (romange) [reply src/server/db_slice.h:604]: yeah, it's very subjective `size_t` and uint64_t are the same type but size_t tells me it's sizes, lengths etc.
counters - are usually uintxxx, that's how I try to declare types (proper readability aspect)

File: src/server/db_slice.cc [hunk 5]
```diff
@@ -794,7 +794,8 @@ void DbSlice::FlushDbIndexes(const std::vector<DbIndex>& indexes) {
     std::swap(db_arr_[index]->trans_locks, flush_db_arr[index]->trans_locks);
   }
 
-  CHECK(fetched_items_.empty());
+  LOG_IF(DFATAL, fetched_items_.empty())
```
Comment (kostasrim) [inline src/server/db_slice.cc:797]: Since now we don't crash in release I will ask for the logs (just to make sure that we don't have any gaps)

File: src/server/db_slice.h (hunk 3 above)
Comment (kostasrim) [reply src/server/db_slice.h]: Sounds good, I will keep it in mind/ apply the notation. Cheers

File: src/server/db_slice.h [hunk 6]
```diff
@@ -598,6 +601,7 @@ class DbSlice {
   size_t soft_budget_limit_ = 0;
   size_t table_memory_ = 0;
   uint64_t entries_count_ = 0;
+  unsigned load_ref_count_ = 0;
```
Comment (adiholden) [inline src/server/db_slice.h:604]: I think we should add a dcheck that this ref count == 0 when we change server state to active
in Service::SwitchState

File: src/server/main_service.cc [hunk 7]
```diff
@@ -2508,7 +2508,14 @@ GlobalState Service::SwitchState(GlobalState from, GlobalState to) {
   VLOG(1) << "Switching state from " << from << " to " << to;
   global_state_ = to;
 
-  pp_.Await([&](ProactorBase*) { ServerState::tlocal()->set_gstate(to); });
+  pp_.Await([&](ProactorBase*) {
+    ServerState::tlocal()->set_gstate(to);
+    auto* es = EngineShard::tlocal();
+    if (es && to == GlobalState::ACTIVE) {
+      DbSlice& db = namespaces->GetDefaultNamespace().GetDbSlice(es->shard_id());
+      DCHECK(db.IsFetchedItemsEmpty());
```
Comment (adiholden) [inline src/server/main_service.cc:2516]: Ok for this check
but why not checking the load_ref_count_ as I suggested? or better check that if cache mode flag is enabled than db slice is cash mode retuns true.
My concern is that if this logic is not correct for some reason than cache mode will be disabled

File: src/server/main_service.cc [hunk 8]
```diff
@@ -2508,7 +2508,14 @@ GlobalState Service::SwitchState(GlobalState from, GlobalState to) {
   VLOG(1) << "Switching state from " << from << " to " << to;
   global_state_ = to;
 
-  pp_.Await([&](ProactorBase*) { ServerState::tlocal()->set_gstate(to); });
+  pp_.Await([&](ProactorBase*) {
+    ServerState::tlocal()->set_gstate(to);
+    auto* es = EngineShard::tlocal();
+    if (es && to == GlobalState::ACTIVE) {
+      DbSlice& db = namespaces->GetDefaultNamespace().GetDbSlice(es->shard_id());
+      DCHECK(db.IsLoadInProgressZeroInCacheMode());
```
Comment (adiholden) [inline src/server/main_service.cc:2516]: I think it will be more clear if you call this function 
VerifyLoadComplete or IsLoadReferenceCleared
and only check that the counter is 0 in this function regardless of cache mode 
This way we will verify the ref count logic not only in cache mode tests

Comment (adiholden) [reply src/server/main_service.cc]: Wow what a catch with this dcheck.

**Review by adiholden — APPROVED** [review]

File: src/server/main_service.cc (hunk 8 above)
Comment (kostasrim) [reply src/server/main_service.cc]: @adiholden I appreciate you :heart:
