### PR TITLE
fix: zunion and zunionstore zero numkeys bug

### LINKED ISSUE #1442: ZUNION crash on debug builds
**Describe the bug**
The command `ZUNION 0 key` causes dragonfly to crash (but works on release).

**To Reproduce**
1. Build dragonfly with in debug mode
2. Start dragonflydb
3. Connect with redis-cli and type `ZUNION 0 key` (crashes here)

**Expected behavior**
An error for numkeys being `0`

**Environment (please complete the following information):**
 - OS: [ubuntu 22.04]
 - Kernel: 5.19.0-45-generic
 - Containerized?: no
 - Dragonfly Version: [1.4.0]

**Additional context**
I would check all the commands with the form `COMMAND NUMKEYS [Keys...]`

### PR DESCRIPTION
**Pull request by rounaknandanwar**
Fixes #1442

Behaviour after this fix : 
```shell
127.0.0.1:6379> zunion 0 key
(error) ERR syntax error
127.0.0.1:6379> zunionstore out 0  aggregate
(error) ERR syntax error
```

### CODE REVIEW

File: src/server/main_service.cc [hunk 1]
```diff
@@ -859,8 +860,13 @@ void Service::DispatchCommand(CmdArgList args, facade::ConnectionContext* cntx)
 
       if (!dist_trans->IsMulti()) {  // Multi command initialize themself based on their mode.
         if (auto st = dist_trans->InitByArgs(dfly_cntx->conn_state.db_index, args_no_cmd);
-            st != OpStatus::OK)
+            st != OpStatus::OK) {
+          if (cmd_name == "ZUNION" && st == OpStatus::INVALID_INT) {
```
Comment (rounaknandanwar) [inline src/server/main_service.cc:864]: If we don't catch it here explicitly for `zunion`, the error message shown on terminal would be `syntax error` which is not exactly same as redis message.
`zunionstore` also follows the same error message convention.

Comment (romange) [reply src/server/main_service.cc:864]: why the error message text is important for you @rounaknandanwar ?

Comment (kostasrim) [reply src/server/main_service.cc:864]: I would assume consistency with redis. It's not a must have but it's a good thing to be consistent -- makes sense from a UX perspective.

Comment (romange) [reply src/server/main_service.cc:864]: @rounaknandanwar  says that `zunionstore` follows the same convention and yet we do not handle this case here.
Also, I prefer avoid spreading the error handling logic in many places and here it's a new special case that is introduced. Instead I suggest returning a new OpStatus enum and handle it inside   `SendError`

**Comment by romange** [comment]
@rounaknandanwar  thank you for your contribution!

File: src/server/main_service.cc [hunk 2]
```diff
@@ -840,6 +840,7 @@ void Service::DispatchCommand(CmdArgList args, facade::ConnectionContext* cntx)
   intrusive_ptr<Transaction> dist_trans;
 
   bool dispatching_in_multi = under_script || under_multi;
+  string_view cmd_name{cid->name()};
```
Comment (kostasrim) [inline src/server/main_service.cc:843]:
```suggestion
  const string_view cmd_name{cid->name()};
```

File: src/server/main_service.cc (hunk 1 above)
Comment (kostasrim) [reply src/server/main_service.cc:864]: @rounaknandanwar yep, I am in favor of not splitting the error logic as well because it fragments the error handling. My comment was more of what their rational was. But I agree with you, @rounaknandanwar could you plz take care of this.

File: src/server/transaction.cc [hunk 3]
```diff
@@ -1445,12 +1445,14 @@ OpResult<KeyIndex> DetermineKeys(const CommandId* cid, CmdArgList args) {
...
-    // TODO Fix this for Z family functions.
-    // Examples that crash: ZUNION 0 myset
     if (name == "ZDIFF" && num_custom_keys == 0) {
       return OpStatus::INVALID_INT;
     }
 
+    if (name == "ZUNION" && num_custom_keys == 0) {
+      return OpStatus::INVALID_INT;
+    }
+
```
Comment (kostasrim) [inline src/server/transaction.cc:1455]: you can squash those two in one condition:

```
if ((name == "ZUNION" || name == "ZDIFF") && num_custom_keys == 0)
```

**Comment by kostasrim** [comment]
@rounaknandanwar Thank you for this PR

File: src/server/main_service.cc (hunk 1 above)
Comment (rounaknandanwar) [reply src/server/main_service.cc:864]: 1. Yes the intent of the specific message was consistency with redis. Is it a hard requirement to keep the message same ? I can see for other commands as well, we don't exactly replicate the messaging. Example for the command `zunionstore out -1 key`, the error messages are different:
     - Dragonfly : `ERR value is not an integer or out of range`
     - Redis : `ERR at least 1 input key is needed for zunionstore`
     
2. I kind of agree that the error logic should not be fragmented so I was thinking if each command should have its own error handling. But I guess some of the validations are done early because of transaction specific logic so that cannot be achieved completely as @kostasrim pointed out.

3. zunionstore returns the message - `(error) ERR syntax error`. I think I misread it earlier. Should we keep it uniform for zunion as well then ?

4. I discovered another version of zunionstore that crashes - `zunionstore out 0  aggregate`. I can handle this in this PR itself.

Comment (kostasrim) [reply src/server/main_service.cc:864]: Just remove the `if (cmd_name == "ZUNION" && st == OpStatus::INVALID_INT) {`. 

You have basically two choices: 
1. Either add a new error code as @romange suggested in `OpStatus` enum.
2. Leave it as is, which I personally don't mind -- unless @romange has a strong objection (we can't always be 1-1 with redis errors). 

> I discovered another version of zunionstore that crashes - zunionstore out 0  aggregate. I can handle this in this PR itself.

Definitely, it would be a nice additions ;)

File: src/server/zset_family.cc [hunk 4]
```diff
@@ -956,7 +956,7 @@ OpResult<void> FillAggType(string_view agg, SetOpArgs* op_args) {
 
 // Parse functions return the number of arguments read from CmdArgList
 OpResult<unsigned> ParseAggregate(CmdArgList args, bool store, SetOpArgs* op_args) {
-  if (args.size() < 1) {
+  if (args.size() <= 1) {
```
Comment (rounaknandanwar) [inline src/server/zset_family.cc:959]: This fixes the `zunionstore key 0 aggregate` crash

File: src/server/main_service.cc (hunk 1 above)
Comment (rounaknandanwar) [reply src/server/main_service.cc]: Keeping it uniform and showing message as `(error) ERR syntax error` for both `zunion` and `zunionstore`.

File: src/server/main_service.cc (hunk 2 above)
Comment (rounaknandanwar) [reply src/server/main_service.cc]: This is no longer needed since we have removed the explicit handling.

File: src/server/transaction.cc (hunk 3 above)
Comment (rounaknandanwar) [reply src/server/transaction.cc]: Not squashing since we are returning `OpStatus::SYNTAX_ERR`

**Review by romange — APPROVED** [review]
