### PR TITLE
fix(server): hmget non uniqe keys response

### LINKED ISSUE #4743: [BUG] HMGET with none-unique keys
Hi.

Dragonfly Version: v1.27.1

The HMGET command returns a value only for the first unique key.

Reproduce:

```
127.0.0.1:6379> HSET test f1 "hi"
(integer) 1
127.0.0.1:6379> HMGET test f1 f1 f1
1) "hi"
2) (nil)
3) (nil)
```

Expected behavior:

```
127.0.0.1:6379> HSET test f1 "hi"
(integer) 1
127.0.0.1:6379> HMGET test f1 f1 f1
1) "hi"
2) "hi"
3) "hi"
```

Expects behavior similar to that of Redis and KeyDB

### PR DESCRIPTION
**Pull request by adiholden**
fixes #4743

### CODE REVIEW

File: src/server/hset_family.cc [hunk 1]
```diff
@@ -408,10 +408,14 @@ OpResult<vector<OptStr>> OpHMGet(const OpArgs& op_args, std::string_view key, Cm
   if (pv.Encoding() == kEncodingListPack) {
     uint8_t* lp = (uint8_t*)pv.RObjPtr();
 
-    absl::flat_hash_map<string_view, unsigned> reverse;
+    absl::flat_hash_map<string_view, std::vector<size_t>> reverse;
```
Comment (romange) [inline src/server/hset_family.cc:411]: it's gonna be more cpu intensive because for 99.999% of the usecases vector is not needed.
Can you please use InlinedVector instead?

File: src/server/hset_family.cc [hunk 2]
```diff
@@ -408,10 +408,14 @@ OpResult<vector<OptStr>> OpHMGet(const OpArgs& op_args, std::string_view key, Cm
...
     reverse.reserve(fields.size() + 1);
     for (size_t i = 0; i < fields.size(); ++i) {
-      reverse.emplace(ArgS(fields, i), i);  // map fields to their index.
+      auto [res_it, is_inserted] =
```
Comment (romange) [inline src/server/hset_family.cc:414]: you can achieve the same with `reverse[ArgS(fields, i)].push_back(i)`

**Review by romange — APPROVED** [review]
