### PR TITLE
fix(server): rdb loader catch bad alloc

### LINKED ISSUE #1708: bad_alloc on replica when master near maxmemory (cache_mode=true)
**Describe the bug**
Hey, I encountered a `bad_alloc` error when trying several failover scenarios and replicas have a problem syncing with the master when the master is near or at its configured `maxmemory` limit. We are using mostly SET, INCR and EXPIRE commands.

```
F20230816 18:27:38.024061     9 fiberqueue_threadpool.cc:50] Exception std::bad_alloc
*** Check failure stack trace: ***
    @     0x5bc6bec96d23  google::LogMessage::SendToLog()
    @     0x5bc6bec8f4e7  google::LogMessage::Flush()
    @     0x5bc6bec90e6f  google::LogMessageFatal::~LogMessageFatal()
    @     0x5bc6be724726  _ZN4util3fb210FiberQueue3RunEv.cold
    @     0x5bc6be86c6e2  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberENS0_21basic_fixedsize_stackINS0_12stack_traitsEEEZN4util3fb26detail15WorkerFiberImplIZN4dfly11EngineShardC4EPNS9_12ProactorBaseEbP9mi_heap_sEUlvE0_JEEC4IS7_EESt17basic_string_viewIcSt11char_traitsIcEERKNS0_12preallocatedEOT_OSI_EUlOS4_E_EEEEvNS1_10transfer_tE.lto_priv.0
    @     0x5bc6beab6d2f  make_fcontext
*** SIGABRT received at time=1692210458 on cpu 0 ***
PC: @     0x7bac064aa00b  (unknown)  raise
[failure_signal_handler.cc : 332] RAW: Signal 11 raised at PC=0x7bac06489941 while already in AbslFailureSignalHandler()
*** SIGSEGV received at time=1692210458 on cpu 0 ***
PC: @     0x7bac06489941  (unknown)  abort
```

**To Reproduce**
I managed to reproduce this locally as well, using the following steps:

1. Run 2 instances of dragonfly - 16379 (master) and 26379 (replica)
    - `docker run -p 16379:6379 --ulimit memlock=-1 docker.dragonflydb.io/dragonflydb/dragonfly:v1.8.0 --maxmemory=300mb --cache_mode=true`
    - `docker run -p 26379:6379 --ulimit memlock=-1 docker.dragonflydb.io/dragonflydb/dragonfly:v1.8.0 --maxmemory=300mb --cache_mode=true`
2. load data - random INCR keys until master hits maxmemory
    - `redis-benchmark -h localhost -p 16379 -n 10000000 -r 20000000 -t incr` 
this took about 5m for me)
3. attempt to configure replication
    - `redis-cli -u redis://localhost:26379 replicaof host.containers.internal 16379`
    - dragonfly replica will fail with `bad_alloc` error, and master with `io error system:103`

**Expected behavior**
Replica should successfully connect and enter stable sync with master. 

**Environment (please complete the following information):**
 - Containerized?: Yes, Docker locally and Kubernetes (GKE)
 - Dragonfly Version: 1.8.0

**Additional context**
Gist with repro and `INFO ALL` from a production (GKE kubernetes) environment
https://gist.github.com/eidam/b68ec6f2339a0347e9d70fb0c26e9263

### PR DESCRIPTION
**Pull request by adiholden**
While loading rdb snapshot, if oom is reached a bad alloc exception is thrown. Now we catch it and write warning to log.
fixes #1708

### CODE REVIEW

File: src/server/rdb_load.cc [hunk 1]
```diff
@@ -2268,9 +2268,13 @@ void RdbLoader::LoadItemsBuffer(DbIndex db_ind, const ItemsBuf& ib) {
     if (item->expire_ms > 0 && db_cntx.time_now_ms >= item->expire_ms)
       continue;
 
-    auto [it, added] = db_slice.AddOrUpdate(db_cntx, item->key, std::move(pv), item->expire_ms);
-    if (!added) {
-      LOG(WARNING) << "RDB has duplicated key '" << item->key << "' in DB " << db_ind;
+    try {
+      auto [it, added] = db_slice.AddOrUpdate(db_cntx, item->key, std::move(pv), item->expire_ms);
```
Comment (adiholden) [inline src/server/rdb_load.cc:2272]: @romange I did not fail the loading if we are OOM, just writing the warning to log. Do you think we should fail loading?

Comment (royjacobson) [reply src/server/rdb_load.cc:2272]: Personally I prefer to fail

Comment (romange) [reply src/server/rdb_load.cc:2272]: I think, we are missing a bigger picture here. And I am not saying we should not fix this specific point but the big issue is that both master and replica are configured the same way but the replication fails because we are near the capacity at the master.  The master does not fail so why replica fails?

Comment (romange) [reply src/server/rdb_load.cc:2272]: And to @royjacobson  point I agree we should fail here: unrolling the operation is better than proceeding with an inconsistent state, but we also should not get to this point at all in this specific scenario.

Comment (adiholden) [reply src/server/rdb_load.cc:2272]: I updated the changes so that rdb loader load will return error on oom. Note that today if we have error on replica we fail the replica load and on master when using loading from disc we dont fail to start the service if we have errors in rdb loader. If you think we should fail to start the master service on load fail I can do this in a separate PR. 
Also I will continue to investigate why replica fails assuming master and replica has the same memory limit

Comment (romange) [reply src/server/rdb_load.cc:2272]: what do you mean we do not fail when master has errors during load? what happens then? Do we load partial data?

**Review by romange — APPROVED** [review]

File: src/server/rdb_load.cc (hunk 1 above)
Comment (adiholden) [reply src/server/rdb_load.cc:2272]: yes
