### PR TITLE
fix(stream_family): Fix memory tracking for the STREAMs. SECOND PR

### LINKED ISSUE #4898: Bug in stream memory tracking

### PR DESCRIPTION
**Pull request by BagritsevichStepan**
The problem is described in the first PR: #4777

fixes #4898

### CODE REVIEW

File: src/core/compact_object.cc [hunk 1]
```diff
@@ -925,22 +948,16 @@ void CompactObj::SetJson(JsonType&& j) {
...
-    // so the object now consumes less memory than it did before. This DCHECK
-    // is for fanity and to catch any potential issues with our tracking approach.
-    DCHECK(static_cast<int64_t>(u_.r_obj.Size()) >= size);
-  }
-  u_.r_obj.SetSize((u_.r_obj.Size() + size));
+  // We might have a negative size. For example, if we remove a consumer,
+  // the tracker will report a negative net (since we deallocated),
+  // so the object now consumes less memory than it did before. This DCHECK
+  // is for fanity and to catch any potential issues with our tracking approach.
+  u_.r_obj.SetSize(UpdateSize(u_.r_obj.Size(), size));
```
Comment (kostasrim) [inline src/core/compact_object.cc:960]: This is the only functional difference from the other PR. Consider merging them into one if this is just a single line

Comment (BagritsevichStepan) [reply src/core/compact_object.cc:960]: Let's merge the PR for JSON first because I see that the fakeredis tests are failing. It might take some time to understand what the bug is. And then maybe we will need to fix stream memory tracking in other places to pass the tests

Comment (kostasrim) [reply src/core/compact_object.cc:960]: no issue with that -- whatever is more convenient

File: src/server/stream_family.cc [hunk 2]
```diff
@@ -1216,6 +1222,8 @@ OpStatus OpCreate(const OpArgs& op_args, string_view key, const CreateOpts& opts
       if (!res_it)
         return res_it.status();
 
+      mem_tracker.UpdateStartSize();
```
Comment (BagritsevichStepan) [inline src/server/stream_family.cc:1225]: Fixed the same bug here as in JSON memory tracking: we started tracking before the `db_slice.AddNew` call, which can deallocate some memory.

File: src/server/stream_family.cc [hunk 3]
```diff
@@ -1856,6 +1867,9 @@ OpResult<PendingResult> OpPending(const OpArgs& op_args, string_view key, const
   } else {
     result = GetPendingExtendedResult(op_args.db_cntx.time_now_ms, cgroup_res->cg, consumer, opts);
   }
+
+  mem_tracker.UpdateStreamSize(cgroup_res->it->second);
```
Comment (BagritsevichStepan) [inline src/server/stream_family.cc:1871]: Here we are using a mutable iterator, just for safety added memory tracking here. Can be be deleted (e.g., after adding tests).

File: src/server/stream_family.cc [hunk 4]
```diff
@@ -2455,6 +2476,8 @@ void XReadBlock(ReadOpts* opts, Transaction* tx, SinkReplyBuilder* builder,
           result = OpStatus::CANCELLED;
           return OpStatus::OK;
         }
+
+        mem_tracker.UpdateStreamSize(res_it->it->second);
```
Comment (BagritsevichStepan) [inline src/server/stream_family.cc:2480]: `FindOrAddConsumer` can allocate some memory (if consumer were not previously added), that was actually the bug

File: src/server/stream_family.cc [hunk 5]
```diff
@@ -3203,7 +3226,11 @@ variant<bool, facade::ErrorReply> HasEntries2(const OpArgs& op_args, string_view
     return false;
   }
 
-  const CompactObj& cobj = (*res_it)->second;
+  StreamMemTracker mem_tracker;
+
+  absl::Cleanup update_size_cb([&]() { mem_tracker.UpdateStreamSize(res_it->it->second); });
+
+  const CompactObj& cobj = res_it->it->second;
```
Comment (BagritsevichStepan) [inline src/server/stream_family.cc:3233]: Same bug here (changed to FindMutable):
> `FindOrAddConsumer` can allocate some memory (if consumer were not previously added), that was actually the bug

Comment (kostasrim) [reply src/server/stream_family.cc:3233]: Maybe worth adding a comment in code here just in case that `xread` is not really read only because consumers are added if they don't exist

File: src/server/stream_family.cc (hunk 4 above)
Comment (kostasrim) [reply src/server/stream_family.cc:2480]: same here, maybe an inline comment so we don't forget ?

File: src/server/dragonfly_test.cc [hunk 6]
```diff
@@ -454,6 +454,8 @@ TEST_F(DflyEngineTest, OOM) {
 /// Reproduces the case where items with expiry data were evicted,
 /// and then written with the same key.
 TEST_F(DflyEngineTest, Bug207) {
+  GTEST_SKIP() << "Test skipped temporary.";
```
Comment (kostasrim) [inline src/server/dragonfly_test.cc:457]: Did Adi asked you to disable this ?

Also, I would rather have it on separate PR such that it's clear when and where we disabled this

**Review by kostasrim — COMMENTED** [review]
LGTM, very minor comments

File: src/server/dragonfly_test.cc (hunk 6 above)
Comment (BagritsevichStepan) [reply src/server/dragonfly_test.cc:457]: No, I just checked that I'm passing all tests without it. Will remove this and try to pass the ci checks

File: src/server/stream_family.cc (hunk 4 above)
Comment (BagritsevichStepan) [reply src/server/stream_family.cc:2483]: Done

File: src/server/stream_family.cc (hunk 5 above)
Comment (BagritsevichStepan) [reply src/server/stream_family.cc:3238]: Done

**Review by kostasrim — APPROVED** [review]
