### PR TITLE
fix: fix dispatch ordering

### LINKED ISSUE #1245: PubSub out of order confirmations
Hi, congratulations on the release of 1.3.0! I am very excited about the new release.

However, I found there is an out-of-order issue for the SUBSCRIBE/PSUBSCRIBE responses while testing the latest release with my RESP3 client (https://github.com/redis/rueidis) by the following code:

```go
package main

import (
	"context"
	"fmt"
	"github.com/redis/rueidis"
)

func main() {
	client, err := rueidis.NewClient(rueidis.ClientOption{
		InitAddress:  []string{"127.0.0.1:6379"},
		DisableCache: true,
	})
	if err != nil {
		panic(err)
	}
	defer client.Close()
	for _, resp := range client.DoMulti(
		context.Background(),
		client.B().Set().Key("key1").Value("1").Build(),
		client.B().Get().Key("key1").Build(),
		client.B().Subscribe().Channel("ch1").Build(),
		client.B().Set().Key("key2").Value("2").Build(),
		client.B().Get().Key("key2").Build(),
		client.B().Psubscribe().Pattern("ch2").Build(),
	) {
		fmt.Println(resp.ToString())
	}
}

```

This code works will pipeline the following commands to the server in RESP3:
```
SET key1 1
GET key1
SUBSCRIBE ch1
SET key2 2
GET key2
PSUBSCRIBE ch2
```

and it works well with the official redis but easily get failed on the dragonfly.

That is because the dragonfly sends responses in an out-of-order way:

```
redis:
+ OK
$ 1
> subscribe ch1
+ OK
$ 2
> psubscribe ch2
```
```
dragonfly:
+ OK
$ 1
+ OK
$ 2
> psubscribe ch2
> subscribe ch1
```

I believe the out-of-order behavior is a bug because a SUBSCRIBE/PSUBSCRIBE/SSUBSCRIBE command may still result in an ERR response and the correct order is the only way to check if the command succeeded.

### PR DESCRIPTION
**Pull request by dranikpg**
Fixes #1245 

Make subscribe reply immediately. Solves two issues:

1. During pipeline (where requests are part of dispatch q) the subscribe response is pushed back to the dispatch queue, so the client can receive its reply potentially very long after it executed. Most clients (probably?) expect a direct reply

2. Currently the responses are pushed back after all the channel store callbacks have been registered. This means that if a subscribe has many channels with possible suspension points (like `SUBSCRIBE ch1 ... ch10`), then until it gets to subscribe to the tenth, other channels could have received lots of messages.  What is more, its theoretically possible that a client receives a message before the confirmation itself.

### CODE REVIEW

**Comment by dranikpg** [comment]
WTH what probabilistic bug curse is this, #1236 fired again

File: src/facade/dragonfly_connection.cc [hunk 1]
```diff
@@ -542,7 +525,44 @@ void Connection::ConnectionFlow(FiberSocketBase* peer) {
   --stats_->num_conns;
 }
 
-auto Connection::ParseRedis() -> ParserStatus {
+void Connection::DispatchCommand(uint32_t consumed, mi_heap_t* heap) {
+  bool can_dispatch_sync = (consumed >= io_buf_.InputLen());
```
Comment (dranikpg) [inline src/facade/dragonfly_connection.cc:529]: I took it from the previous version. It looks to me like this should actually be a DCHECK. How could we dispatch async if we didn't read fully 🤔

File: src/server/conn_context.cc [hunk 2]
```diff
@@ -134,7 +134,7 @@ vector<unsigned> ChangeSubscriptions(bool pattern, CmdArgList args, bool to_add,
   // removed.
   if (!to_add && conn_state.subscribe_info->IsEmpty()) {
     conn_state.subscribe_info.reset();
-    conn->force_dispatch = false;
+    conn->subscriptions--;
```
Comment (royjacobson) [inline src/server/conn_context.cc:137]:
```suggestion
    CHECK_GT(conn->subscriptions, 0);
    conn->subscriptions--;
```

Comment (dranikpg) [reply src/server/conn_context.cc:137]: its unsigned

Comment (royjacobson) [reply src/server/conn_context.cc:138]: Yeah, but you can still check `conn->subscriptions > 0` to not underflow

File: src/facade/dragonfly_connection.cc [hunk 3]
```diff
@@ -202,39 +197,28 @@ void Connection::DispatchOperations::operator()(const MonitorMessage& msg) {
...
+    arr[i++] = "message";
+  } else {
+    arr[i++] = "pmessage";
+    arr[i++] = pub_msg.pattern;
+  }
+  arr[i++] = pub_msg.Channel();
+  arr[i++] = pub_msg.Message();
+  rbuilder->SendStringArr(absl::Span<string_view>{arr.data(), i},
+                          RedisReplyBuilder::CollectionType::PUSH);
+  VLOG(0) << "Sent data";
```
Comment (romange) [inline src/facade/dragonfly_connection.cc:212]: please remove VLOG

File: src/facade/dragonfly_connection.cc [hunk 4]
```diff
@@ -859,7 +865,7 @@ void Connection::SendAsync(MessageHandle msg) {
   dispatch_q_bytes_.fetch_add(msg.UsedMemory(), memory_order_relaxed);
 
   dispatch_q_.push_back(move(msg));
-  if (dispatch_q_.size() == 1) {
+  if (dispatch_q_.size() == 1 && !cc_->sync_dispatch) {
```
Comment (romange) [inline src/facade/dragonfly_connection.cc:868]: there is a case where you push into an empty `dispatch_q_` and do not wake the fiber?

Comment (dranikpg) [reply src/facade/dragonfly_connection.cc:868]: Well, we can wake it, but it won't fulfill the event condition: not empty and not sync dispatch

Previously all replies were either sync or all were async. This doesn't hold for multi/exec + subscribe (but its not defined either way), but also for `SUBSCRIBE` if we send the replies synchronously. The change is here so we:

1. Maintain the order in pipelined requests
2. Don't have a "race condition": subscribe needs to update channel store pointers on all threads. While it awaits for all threads to complete the callback, some of them might have done it earlier, to that they already start sending messages before the initial ack is send.

Comment (romange) [reply src/facade/dragonfly_connection.cc:872]: I am trying to see if we do not have a deadlock here. I did not deep dive into the exact state machine.
Suppose `dispatch_q_.size() == 1` but `cc_->sync_dispatch` is true. We won't notify.
Now suppose `dispatch_q_.size()` grew to 2 and now `cc_->sync_dispatch` is false. We will never notify.

Comment (dranikpg) [reply src/facade/dragonfly_connection.cc:872]: Sync dispatch always notifies after it finished if dispatch q is not empty

Comment (dranikpg) [reply src/facade/dragonfly_connection.cc:872]: So if we missed a wake here due to cc_->sync_dispatch, then sync dispatch did preempt, so once it wakes up, it will wake

**Review by romange — APPROVED** [review]
