### PR TITLE
fix: delete empty hash after field expiry in FIELDTTL

### LINKED ISSUE #7133: SIGABRT in rdb_save.cc:274
[fuzz-long-resp-crashes-79.zip](https://github.com/user-attachments/files/26697759/fuzz-long-resp-crashes-79.zip)

```
./fuzz/triage_crashes.sh ./build-dbg/dragonfly resp ./fuzz-long-resp-crashes-79.zip
```

```
F20260414 08:28:06.961647   765 rdb_save.cc:274] SaveEntry skipped empty PrimeValue with key: mylist with tag 19
```

### PR DESCRIPTION
**Pull request by vyavdoshenko**
FIELDTTL triggers lazy expiry inside StringMap::Find(), which removes expired fields.  When the last field expires, the hash becomes empty (Size()==0), but the key stays in the database.  A subsequent SAVE hits the DFATAL in SaveEntry (rdb_save.cc:274) because OBJ_HASH does not allow empty values, crashing the server.

The fix mirrors what already exists for sets (DeleteSetIfEmpty) and for HEXPIRE/HPERSIST: after FieldExpireTime() returns, check whether the StringMap is empty and delete the key.

Fixes #7133

### CODE REVIEW

File: src/server/generic_family.cc [hunk 1]
```diff
@@ -897,6 +898,13 @@ OpResult<long> OpFieldTtl(Transaction* t, EngineShard* shard, string_view key, s
   } else {
     DCHECK_EQ(OBJ_HASH, it->second.ObjType());
     res = HSetFamily::FieldExpireTime(db_cntx, it->second, field);
+    if (it->second.Encoding() == kEncodingStrMap2) {
```
Comment (romange) [inline src/server/generic_family.cc]: it should not be done like this this logic should be encapsulated within HSetFamily code.

I suggest expanding `FieldExpireTime` API to return a special result code that says - empty map.
Maybe this is why we have this bug again as we fixed it in the wrong place in the past.

Comment (vyavdoshenko) [reply src/server/generic_family.cc]: fixed

**Review by BorysTheDev — DISMISSED** [review]

File: src/server/hset_family.cc [hunk 2]
```diff
@@ -1227,6 +1227,21 @@ int32_t HSetFamily::FieldExpireTime(const DbContext& db_context, const PrimeValu
...
+bool HSetFamily::DeleteIfEmpty(DbSlice& db_slice, const DbContext& db_cntx, std::string_view key,
+                               const PrimeValue& pv) {
+  if (pv.Encoding() != kEncodingStrMap2)
+    return false;
+
+  if (auto* sm = static_cast<StringMap*>(pv.RObjPtr()); !sm->Empty())
+    return false;
+
+  if (auto res = db_slice.FindMutable(db_cntx, key, OBJ_HASH); res) {
+    db_slice.DelMutable(db_cntx, std::move(*res));
```
Comment (romange) [inline src/server/hset_family.cc:1240]: check out `SetFamily::DeleteSetIfEmpty`. you may need to call `RecordDelete` to propagate the deletion.

**Review by romange — CHANGES_REQUESTED** [review]

File: src/server/hset_family.cc (hunk 2 above)
Comment (vyavdoshenko) [reply src/server/hset_family.cc:1240]: fixed

**Review by romange — APPROVED** [review]
