### PR TITLE
fix(zset_family): Return early if range is expected to be zero

### LINKED ISSUE #5383: zset bugs
## ZLEXCOUNT returns wrong result

To reproduce:
```
ZADD A 0 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
ZLEXCOUNT A - -
```

returns 1 but should return 0.

what's interesting, for shorted items (i.e. `AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA`) , it returns 0.

### PR DESCRIPTION
**Pull request by mkaruza**
There are 2 ranges that can be used but they are always zero. Ranges are (+inf, anything) and (anything, -inf). Check and return early if they are used.

Fixes #5383

### CODE REVIEW

File: src/core/sorted_map.cc [hunk 1]
```diff
@@ -688,6 +688,13 @@ size_t SortedMap::LexCount(const zlexrangespec& range) const {
   if (score_tree->Size() == 0)
     return 0;
 
+  // Ranges that will always be zero
+  if ((range.min == cminstring && range.max == cminstring) ||
```
Comment (romange) [inline src/core/sorted_map.cc]: why it worked inconsistently depending on the item we added?

Comment (mkaruza) [reply src/core/sorted_map.cc]: Shorter objects are encoded as `OBJ_ENCODING_LISTPACK` so logic is handled with redis path while longer objects are SortedMap so we will handle this special case in this function

Comment (mkaruza) [reply src/core/sorted_map.cc]: I'll update test so it test both encodings

File: src/core/sorted_map.cc [hunk 2]
```diff
@@ -688,6 +688,13 @@ size_t SortedMap::LexCount(const zlexrangespec& range) const {
...
+      (range.min == cmaxstring && range.max == cmaxstring) ||
```
Comment (romange) [inline src/core/sorted_map.cc]: Is not it enough that `range.min == cmaxstring`  to return 0?

**Comment by romange** [comment]
Would it be more precise to say that  ` (+inf, anything)` or  `(anything, -inf)`  should return 0?

File: src/core/sorted_map.cc (hunk 2 above)
Comment (mkaruza) [reply src/core/sorted_map.cc]: There is also (min,min).

**Comment by mkaruza** [comment]
> Would it be more precise to say that ` (+inf, anything)` or `(anything, -inf)` should return 0?

Yes, true. I'll update logic.

**Review by romange — APPROVED** [review]
