### PR TITLE
fix: container limits

### LINKED ISSUE #986: Threads and maxmemory autodetection should respect cgroup limits
When launching dragonfly in a container with cgroup memory and cpu limits, maxmemory is set to the host value instead of the limit.

When starting, dragonfly should respect those limits.

### PR DESCRIPTION
**Pull request by talbii**
Dragonfly now respects CGroup limits (memory, CPUs) and uses those instead of the host's limits.

Closes #986.

### CODE REVIEW

File: src/server/dfly_main.cc [hunk 1]
```diff
@@ -438,6 +439,114 @@ bool ShouldUseEpollAPI(const base::sys::KernelVersion& kver) {
...
+  // Begin by reading /proc/self/cgroup
+
+  auto cg = io::ReadFileToString("/proc/self/cgroup");
+  CHECK(cg.has_value());
+
+  // Here, we assume that CGroup v1 is being used. This
+  // is quite likely, as CGroup v1 was introduced back in 2015.
+
+  // strip 0::<path> into just <path>, and newline.
+  auto cgv = std::move(cg.value());
```
Comment (romange) [inline src/server/dfly_main.cc:452]: Please avoid 100% "auto" usage - it hurts readability. In this specific case I would replace "auto" with "string"

File: src/server/dfly_main.cc [hunk 2]
```diff
@@ -438,6 +439,114 @@ bool ShouldUseEpollAPI(const base::sys::KernelVersion& kver) {
...
+  return cgv.substr(3, cgv.length() - 3 - 1);
```
Comment (romange) [inline src/server/dfly_main.cc:453]: I would not want to assume that chgroup starts with zero.
it could also have arbitrary number: https://manpages.ubuntu.com/manpages/bionic/en/man7/cgroup_namespaces.7.html
Please find the second ":" and use it to fetch the path.

File: src/server/dfly_main.cc [hunk 3]
```diff
@@ -438,6 +439,114 @@ bool ShouldUseEpollAPI(const base::sys::KernelVersion& kver) {
   return true;
 }
 
+string get_cgroup_path(void) {
```
Comment (romange) [inline src/server/dfly_main.cc:442]: GetCgroupPath

File: src/server/dfly_main.cc [hunk 4]
```diff
@@ -438,6 +439,114 @@ bool ShouldUseEpollAPI(const base::sys::KernelVersion& kver) {
...
+  // strip 0::<path> into just <path>, and newline.
+  auto cgv = std::move(cg.value());
+  return cgv.substr(3, cgv.length() - 3 - 1);
+  /**
+   * -3: we are skipping the first three characters
+   * -1: we discard the last character (a newline)
+   */
+}
+
+const auto cgroup = "/sys/fs/cgroup/" + get_cgroup_path();
```
Comment (romange) [inline src/server/dfly_main.cc:460]: Please avoid using non-POD global variables as much as possible. It may create weird bugs since they are initialized before `main(..)` starts.

File: src/server/dfly_main.cc [hunk 5]
```diff
@@ -438,6 +439,114 @@ bool ShouldUseEpollAPI(const base::sys::KernelVersion& kver) {
...
+   *
+   * We also use this file to find out how much memory we can use.
+   * However, on LXC this is placed in a different directory:
+   * 3. Checking '/sys/fs/cgroup/memory/memory.limit_in_bytes':
+   * Same idea.
+   */
+
+  using io::Exists;
+
+  return Exists("/.dockerenv") || Exists(cgroup + "/memory.max");
```
Comment (romange) [inline src/server/dfly_main.cc:487]: why checking for .dockerenv? It's not enough to check for `memory.max`?

File: src/server/dfly_main.cc [hunk 6]
```diff
@@ -494,17 +603,30 @@ Usage: dragonfly [FLAGS]
     }
   }
 
+  auto memory = ReadMemInfo().value();
```
Comment (romange) [inline src/server/dfly_main.cc:606]: 1. If ReadMemInfo() returns an error - you will get an exception. We do not rely on exceptions. Please at least check-fail before accessing `.value()`. 
2. I would combine `InsideContainer and ReadContainerMemoryLimits` functions together into `MergeContainerLimitsIfNeeded`  (shorter name is fine too 😄 ).

File: src/server/dfly_main.cc [hunk 7]
```diff
@@ -494,17 +603,30 @@ Usage: dragonfly [FLAGS]
...
-    size_t available = res->mem_avail;
+    size_t available = memory.mem_avail;
     size_t maxmemory = size_t(0.8 * available);
     LOG(INFO) << "Found " << HumanReadableNumBytes(available)
               << " available memory. Setting maxmemory to " << HumanReadableNumBytes(maxmemory);
     absl::SetFlag(&FLAGS_maxmemory, MaxMemoryFlag(maxmemory));
   } else {
-    LOG(INFO) << "Max memory limit is: " << HumanReadableNumBytes(GetFlag(FLAGS_maxmemory).value);
+    auto limit = GetFlag(FLAGS_maxmemory).value;
+    auto hr_limit = HumanReadableNumBytes(limit);
```
Comment (romange) [inline src/server/dfly_main.cc:625]: use string

File: src/server/dfly_main.cc [hunk 8]
```diff
@@ -438,6 +439,114 @@ bool ShouldUseEpollAPI(const base::sys::KernelVersion& kver) {
...
+  return cgv.substr(3, cgv.length() - 3 - 1);
+  /**
+   * -3: we are skipping the first three characters
+   * -1: we discard the last character (a newline)
+   */
+}
+
+const auto cgroup = "/sys/fs/cgroup/" + get_cgroup_path();
+
+bool InsideContainer() {
```
Comment (romange) [inline src/server/dfly_main.cc:462]: in order to avoid declaring cgroup as global - pass it via arguments.

File: src/server/dfly_main.cc [hunk 9]
```diff
@@ -438,6 +439,114 @@ bool ShouldUseEpollAPI(const base::sys::KernelVersion& kver) {
...
+   * 3. Checking '/sys/fs/cgroup/memory/memory.limit_in_bytes':
+   * Same idea.
+   */
+
+  using io::Exists;
+
+  return Exists("/.dockerenv") || Exists(cgroup + "/memory.max");
+}
+
+void ReadContainerMemoryLimits(io::MemInfoData& mdata) {
```
Comment (romange) [inline src/server/dfly_main.cc:490]: mutable arguments should be passed by pointer and be last in order

File: src/server/dfly_main.cc [hunk 10]
```diff
@@ -438,6 +439,114 @@ bool ShouldUseEpollAPI(const base::sys::KernelVersion& kver) {
...
+  auto max = io::ReadFileToString(cgroup + "/memory.max");
+
+  if (max.has_value()) {
+    auto max_val = max.value();
+    if (max_val.find("max") != max_val.npos)
+      return; /*use the host's settings. */
+    else
```
Comment (romange) [inline src/server/dfly_main.cc:497]: else is redundant here and below

File: src/server/dfly_main.cc [hunk 11]
```diff
@@ -438,6 +439,114 @@ bool ShouldUseEpollAPI(const base::sys::KernelVersion& kver) {
...
+
+  /**
+   * In order to check for CPU limits, we check two files:
+   * - /sys/fs/cgroup/cpu.max: this file contains two tokens:
+   *  <a> <b>
+   * where <a> is either max, or some number, and <b> is the size
+   * of a time share. If <a> is not max, then <a>/<b> is the number
+   * of useable CPUs (where a non-integer is treated as a CPU
+   * available for a fraction of a time share)
+   * - /sys/fs/cgroup/cpuset.cpus: this file is either empty,
```
Comment (romange) [inline src/server/dfly_main.cc:524]: you do not do this, do you?
maybe separate into TODO?

File: src/server/dfly_main.cc [hunk 12]
```diff
@@ -438,6 +439,114 @@ bool ShouldUseEpollAPI(const base::sys::KernelVersion& kver) {
...
+  if (high.has_value()) {
+    auto high_val = high.value();
+    if (high_val.find("max") != high_val.npos)
+      return;
+    else
+      CHECK(absl::SimpleAtoi(high.value(), &mdata.mem_avail));
+  }
+}
+
+size_t ReadContainerThreadLimits() {
```
Comment (romange) [inline src/server/dfly_main.cc:513]: what would happen if you do it unconditionally, without IsInContainer check?
it seems redundant, no?

File: src/server/dfly_main.cc (hunk 6 above)
Comment (talbii) [reply src/server/dfly_main.cc:606]: About 1 - before adding this change we still did not check (see: https://github.com/dragonflydb/dragonfly/blob/246f6093db89f1b14e63c20b1ce6cf33e7f2accd/src/server/dfly_main.cc#L500-L501). I did find this odd, but assumed it makes sense as theoretically this should never fail.

About 2 - sounds great, would also avoid global `cgroup` variable.

File: src/server/dfly_main.cc (hunk 2 above)
Comment (talbii) [reply src/server/dfly_main.cc:453]: Interesting. Here it says that cgroups should always start with `0::`

https://docs.kernel.org/admin-guide/cgroup-v2.html#processes

Which one will it be? :thinking: 

BTW, I ran their example and also got `0::`.

**Comment by romange** [comment]
Oh, i see, it's 0 for v2. I have not looked when v2 entered but some
distributions set it off for quite some time so better be on a safe side

File: src/server/dfly_main.cc (hunk 5 above)
Comment (talbii) [reply src/server/dfly_main.cc]: I guess I left that check before adding the `cgroup` variable, it is redundant now.

File: src/server/dfly_main.cc (hunk 12 above)
Comment (talbii) [reply src/server/dfly_main.cc]: True, this logic was merged into a single function.

**Review by romange — APPROVED** [review]
