### PR TITLE
fix(set_family): Update object time during SET FIELDEXPIRE

### LINKED ISSUE #4894: FIELDEXPIRE on sets results in a random TTL
Running immediately after each other on a **set** the following commands resulted in TTL of **37** not **48**:
```
SADD myset field1 field2 field3
(integer) 3
FIELDEXPIRE myset 50 field1
(integer) 1
FIELDTTL myset field1
(integer) 37
```
This is random, sometimes the TTL is **43**, and sometimes **47** , If TTL was set to **10**, the field expires sometimes in 1 second.

I followed by trying on a **hashset** and result were as expected both using FIELDEXPIRE and HEXPIRE the following:
```
HSET myhash field1 "hello" field2 "world" field3 "test"
(integer) 3
FIELDEXPIRE myhash 50 field3
(integer) 1
FIELDTTL myhash field3
(integer) 49
```
```
HSET myhash field1 "hello" field2 "world" field3 "test"
(integer) 3
HEXPIRE myhash 50 FIELDS 1 field3
(integer) 1
FIELDTTL myhash field3
(integer) 49
```

**Environment:**
 - Containerized:  Docker Compose image using `docker.dragonflydb.io/dragonflydb/dragonfly`
   - dragonfly v1.28.1-a87fe66d1a7654b8f2ee2b7fe27687d582230888
   - build time: 2025-03-27 15:04:21

### PR DESCRIPTION
**Pull request by mkaruza**
StringSet object doesn't update time when FIELDEXPIRE is called. It will use base time when object is created. Update object time when we want to expire field in SET object.

Fixes #4894

### CODE REVIEW

File: src/server/set_family.cc [hunk 1]
```diff
@@ -1567,7 +1567,9 @@ vector<long> SetFamily::SetFieldsExpireTime(const OpArgs& op_args, uint32_t ttl_
     pv->InitRobj(OBJ_SET, kEncodingStrMap2, ss);
   }
 
-  return ExpireElements((StringSet*)pv->RObjPtr(), values, ttl_sec);
+  auto ss = static_cast<StringSet*>(pv->RObjPtr());
+  ss->set_time(MemberTimeSeconds(op_args.db_cntx.time_now_ms));
```
Comment (adiholden) [inline src/server/set_family.cc:1571]: should this call be in FieldExpireTime or in SetFieldsExpireTime?
From the logic of hset this call is done in FieldExpireTime flow

Comment (adiholden) [reply src/server/set_family.cc:1571]: yes I understand that. I wrote this comment because from the hset functionality I see that ss->set_time(MemberTimeSeconds is called from the flow of FieldExpireTime used in FIELDTTL

Comment (mkaruza) [reply src/server/set_family.cc:1571]: I'm not sure why set_time is used in hset `FieldExpireTime`. Calculation for object expiration does not depend on object `time_now_` private member variable.

Comment (adiholden) [reply src/server/set_family.cc:1571]: I think that the implementation should be the same for hmap and sets so maybe there is a bug in hmap, lets see.
@romange can you review this?

Comment (romange) [reply src/server/set_family.cc:1571]: so your fix in `SetFamily::SetFieldsExpireTime` is correct - you need to update time_now_ so that the expiry time will be correct and Adi is correct- we should update `time_now_` on every opportunity we touch the data structure, also in `SetFamily::FieldExpireTime` and similarly we should do the same in hset_family.cc

Comment (mkaruza) [reply src/server/set_family.cc:1571]: @romange @adiholden I have looked more closely in code, we are setting `time_now_` in set family. Time will be updated from `StringSetWrapper` constructor. This object is created in function `GetExpiry` in `set_family.cc`.

**Review by adiholden — APPROVED** [review]
