### PR TITLE
fix(migration): Use transactions!

### LINKED ISSUE #3229: db_slice and journal RegisterOnChange method refactoring
We need to refactor RegisterOnChange in a way that removes mutex lock via the LockChangeCb and UnlockChangeCb methods from the Transaction code

### PR DESCRIPTION
**Pull request by dranikpg**
Fixes #3229, but the bigger issue is that migrations didn't use transactions at all the whole time 🤯 

Now we have a global transaction cut to start a migration - registering both the journal and db_slice callbacks while the datastore is under a global lock and no commands are running

### CODE REVIEW

File: src/server/db_slice.cc [hunk 1]
```diff
@@ -1129,16 +1124,14 @@ void DbSlice::FlushChangeToEarlierCallbacks(DbIndex db_ind, Iterator it, uint64_
...
-  lock_guard lk(cb_mu_);  // we need to wait until callback is finished before remove it
-  for (auto it = change_cb_.begin(); it != change_cb_.end(); ++it) {
-    if (it->first == id) {
-      change_cb_.erase(it);
-      return;
-    }
-  }
-  LOG(DFATAL) << "Could not find " << id << " to unregister";
+void DbSlice::CallOnChange(DbIndex id, const ChangeReq& cr) const {
+  FiberAtomicGuard fg;  // Callbacks don't preemept
```
Comment (BorysTheDev) [inline src/server/db_slice.cc:1128]: preempt

File: src/server/db_slice.h [hunk 2]
```diff
@@ -405,17 +405,15 @@ class DbSlice {
 
   using ChangeCallback = std::function<void(DbIndex, const ChangeReq&)>;
 
-  //! Registers the callback to be called for each change.
-  //! Returns the registration id which is also the unique version of the dbslice
-  //! at a time of the call.
+  // Called before every access to an entry with a FindMutable call. Returns version
```
Comment (BorysTheDev) [inline src/server/db_slice.h:408]: could you add a comment that this function should be called in the global transaction only

File: src/server/journal/journal_slice.cc [hunk 3]
```diff
@@ -190,28 +190,25 @@ void JournalSlice::AddLogRecord(const Entry& entry, bool await) {
...
     }
   }
 }
 
 uint32_t JournalSlice::RegisterOnChange(ChangeCallback cb) {
-  // mutex lock isn't needed due to iterators are not invalidated
-  uint32_t id = next_cb_id_++;
-  change_cb_arr_.emplace_back(id, std::move(cb));
-  return id;
+  lock_guard lk(cb_mu_);
```
Comment (BorysTheDev) [inline src/server/journal/journal_slice.cc:202]: Why do you need it. I thought with global transaction we don't need it anymore

Comment (dranikpg) [reply src/server/journal/journal_slice.cc:202]: True, but we still need the mutex for deletes, becase we unregister arbitrarily

Comment (BorysTheDev) [reply src/server/journal/journal_slice.cc:202]: But for db_slice we don't need it?

Comment (dranikpg) [reply src/server/journal/journal_slice.cc:202]: Yes, because there is no code path form those callbacks that can unregister itself

Comment (dranikpg) [reply src/server/journal/journal_slice.cc:202]: Somewhat fragile, I agree

**Comment by dranikpg** [comment]
UPD: we have to use transactions for finalization as well

File: src/core/segment_allocator.cc [hunk 4]
```diff
@@ -14,8 +14,8 @@ SegmentAllocator::SegmentAllocator(mi_heap_t* heap) : heap_(heap) {
   constexpr size_t limit = 1ULL << 35;
   static_assert((1ULL << (kSegmentIdBits + kSegmentShift)) == limit);
   // mimalloc uses 32MiB segments and we might need change this code if it changes.
-  static_assert(kSegmentShift == MI_SEGMENT_SHIFT);
-  static_assert((~kSegmentAlignMask) == (MI_SEGMENT_MASK));
+  //  static_assert(kSegmentShift == MI_SEGMENT_SHIFT);
```
Comment (adiholden) [inline src/core/segment_allocator.cc:17]: we pulled new version of mimalloc
if this assert fails you should clean up your mimalloc build

File: src/server/db_slice.cc (hunk 1 above)
Comment (adiholden) [reply src/server/db_slice.cc:1128]: but soon they will preempt. is there any problem with this design have the callbacks preempting?

File: src/server/cluster/outgoing_slot_migration.cc [hunk 5]
```diff
@@ -240,6 +248,9 @@ void OutgoingMigration::SyncFb() {
 }
 
 bool OutgoingMigration::FinalizeMigration(long attempt) {
+  OnAllShards([this](auto& migration) { server_family_->CancelBlockingOnThread(); });
```
Comment (adiholden) [inline src/server/cluster/outgoing_slot_migration.cc:251]: why do we cancel all blocking commands if we migrate only specific slots? we should cancel only the blocking commands only on this slots

File: src/server/cluster/outgoing_slot_migration.cc [hunk 6]
```diff
@@ -240,6 +248,9 @@ void OutgoingMigration::SyncFb() {
...
+  Transaction::Guard tg{tx_.get()};
```
Comment (adiholden) [inline src/server/cluster/outgoing_slot_migration.cc:252]: why did you change this to use Transaction::Guard? this change means that we will not be able to run f.e the config update command until we finalize the migration

Comment (dranikpg) [reply src/server/cluster/outgoing_slot_migration.cc:252]: We can't finalize a migration in-between a command running, we have to use a global transaction

> means that we will not be able to run f.e the config update command until we finalize the migration

It should be just enqueued in the transaction queue, so it will run immediately after

Comment (dranikpg) [reply src/server/cluster/outgoing_slot_migration.cc:252]: Actually, client pause here is pretty safe from a tranasctional point 🤔 will revert back to it

**Comment by adiholden** [comment]
@dranikpg changes looks good. Lets run this in regression actions before merge

**Review by adiholden — DISMISSED** [review]

**Review by adiholden — APPROVED** [review]

File: src/server/db_slice.cc [hunk 7]
```diff
@@ -1089,19 +1089,7 @@ void DbSlice::ExpireAllIfNeeded() {
...
-  // and journal_slice::RegisterOnChange calls without preemption
-  std::lock_guard lk(cb_mu_);
-
-  uint64_t ver = NextVersion();
-  change_cb_.emplace_back(ver, std::move(cb));
-  DCHECK(std::is_sorted(change_cb_.begin(), change_cb_.end(),
-                        [](auto& a, auto& b) { return a.first < b.first; }));
-
-  return ver;
+  return change_cb_.emplace_back(NextVersion(), std::move(cb)).first;
```
Comment (romange) [inline src/server/db_slice.cc:1092]: so now we return an id of the callback @dranikpg  ?
The description of the function in db_slice.h has not been updated

File: src/server/dflycmd.cc [hunk 8]
```diff
@@ -71,32 +71,6 @@ std::string_view SyncStateName(DflyCmd::SyncState sync_state) {
   return "unsupported";
 }
 
-struct TransactionGuard {
```
Comment (dranikpg) [inline src/server/dflycmd.cc:74]: here
