### PR TITLE
fix(eviction): Limit accumulation deleted bytes during eviction

### LINKED ISSUE #5945: DragonflyDB 1.34.2 stuck at eviction: RSS evicition underflow
**Describe the bug**
Keep getting this error when the service under heavy load, using cache-mode & memory near the max memory limit. The DragonflyDB keep evicting memory even after all memory has been flushed and slow to respond.

`2025-10-20T19:51:03.520615509Z stderr F E20251020 19:51:03.520473    11 engine_shard.cc:752] RSS evicition underflow global_used_rss_memory: 709046272 deleted_bytes_before_rss_update: 833349504
`
Running at Kubernetes 1.32 in EKS using Amazon Linux 2023.8.20250818. Use 2 replicas and DragonflyDB Operator v1.3.0.

```
args:
  - --maxmemory=2048mb
  - --cache_mode=true
  - --proactor_threads=4
...
replicas: 2
  resources:
    limits:
      cpu: 1200m
      memory: 2560Mi
    requests:
      cpu: 1200m
      memory: 2560Mi
```

Fixed the issue by manually killing the pod, the dragonflydb assign the other replica as master. Since it happened multiple times for past days we reverted to 1.33.1 and it is working as expected now.

Here are some metrics from our DragonflyDB Grafana Dashboard

Image
dragonfly_memory_used_bytes{pod=~"$pod"} 

Image
sum(rate(dragonfly_evicted_keys_total{pod=~"$pod"}[5m])) by (pod)

Image
dragonfly_connected_clients{pod=~"$pod"}

Image
irate(dragonfly_reply_duration_seconds{pod=~"$pod"}[1m])

Image
rate(dragonfly_commands_processed_total{pod=~"$pod"}[1m])

**To Reproduce**
Not sure, since we do have other DragonflyDB evicting fine. Seems related to heavy load it gets, because this one is the busiest one.

**Expected behavior**
The eviction only evict some of the memory (not all of them) and stay responsive. No "RSS evicition underflow" error found in the logs.

**Environment (please complete the following information):**
 - OS: Amazon Linux 2023.8.20250818
 - Kernel: Linux ip-10-50-12-64.eu-west-1.compute.internal 6.1.147-172.266.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Aug  7 19:30:40 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
 - Containerized?: EKS Kubernetes
 - Dragonfly Version: 1.34.2

### PR DESCRIPTION
**Pull request by mkaruza**
Cache state variable accumulated_deleted_bytes_during_eviction need to
have upper bound when accumulating to prevent over eviction.

Adjust deleted bytes for each shard between two heartbeats by comparing
previous shard used memory and current shard used memory.

Fixes #5945

### CODE REVIEW

**Comment by mkaruza** [comment]
The problem with https://github.com/dragonflydb/dragonfly/issues/5945 was that once eviction based on used memory is dominating we were accumulating deleted_bytes passing rss memory limit.

Running locally **dragonfly** and **dfly_bench** 

```
./dragonfly --logtostderr --dbfilename= --proactor_threads 2 --maxmemory 2048MB --cache_mode yes
./dfly_bench --qps -1000  --ratio=1:0 --proactor_threads=2 -c 20 --test_time 3600 -d 256:1024
```

image


We see that **accumulated_deleted_bytes** for all shards stay constant i.e. doesn't rise above limit and don't accumulate any more bytes than needed (even when eviction based on used memory is used). While running this test no de fragmentation kicked in - so rss memory was not lowered.

File: src/server/engine_shard.h [hunk 1]
```diff
@@ -228,7 +228,9 @@ class EngineShard {
   struct EvictionTaskState {
     bool rss_eviction_enabled_ = true;
     bool track_deleted_bytes = false;
-    size_t deleted_bytes_before_rss_update = 0;
+    size_t acc_deleted_bytes_during_eviction = 0;  // Bytes that were deleted during eviction
```
Comment (romange) [inline src/server/engine_shard.h]: acc is for accumulated?  if yes, then `// Accumulated bytes that were deleted during eviction`

File: src/server/engine_shard.cc [hunk 2]
```diff
@@ -728,54 +729,78 @@ size_t EngineShard::CalculateEvictionBytes() {
   // state if flag has changed.
   bool rss_eviction_enabled_flag = GetFlag(FLAGS_enable_heartbeat_rss_eviction);
   if (eviction_state_.rss_eviction_enabled_ != rss_eviction_enabled_flag) {
-    eviction_state_.global_rss_memory_at_prev_eviction =
-        eviction_state_.deleted_bytes_before_rss_update = 0;
+    eviction_state_.shard_used_memory_at_prev_eviction =
```
Comment (romange) [inline src/server/engine_shard.cc]: `eviction_state_.Reset();`

File: src/server/engine_shard.cc [hunk 3]
```diff
@@ -728,54 +729,78 @@ size_t EngineShard::CalculateEvictionBytes() {
...
     auto& global_rss_memory_at_prev_eviction = eviction_state_.global_rss_memory_at_prev_eviction;
-    auto& deleted_bytes_before_rss_update = eviction_state_.deleted_bytes_before_rss_update;
+    auto& shard_used_memory_at_prev_eviction = eviction_state_.shard_used_memory_at_prev_eviction;
+    auto& deleted_bytes_at_prev_eviction = eviction_state_.deleted_bytes_at_prev_eviction;
+    auto& acc_deleted_bytes_during_eviction = eviction_state_.acc_deleted_bytes_during_eviction;
+
+    // Cap accumulated total deleted bytes
+    acc_deleted_bytes_during_eviction = std::min(
+        (global_used_rss_memory - rss_memory_threshold_start) / shards_count,
+        eviction_state_.acc_deleted_bytes_during_eviction + deleted_bytes_at_prev_eviction);
```
Comment (romange) [inline src/server/engine_shard.cc]: I am confused about high-level algorithm here.

so for example, if `global_used_rss_memory - rss_memory_threshold_start) / shards_count < eviction_state_.acc_deleted_bytes_during_eviction + deleted_bytes_at_prev_eviction` 
you still decrease `acc_deleted_bytes_during_eviction -= deleted_bytes_at_prev_eviction;` 
which can again undeflow if say `global_used_rss_memory - rss_memory_threshold_start) / shards_count ` is less than `deleted_bytes_at_prev_eviction`. 
In general, it seems that the input here is `shard_rss_over_budget =  (global_used_rss_memory - rss_memory_threshold_start) / shards_count` and `shard_used_memory`.

So first step would be to factor out all these calculations into `eviction_state_.Update(shard_rss_over_budget,  shard_used_memory);`
and explain what `Update` does.

File: src/server/engine_shard.cc [hunk 4]
```diff
@@ -728,54 +729,78 @@ size_t EngineShard::CalculateEvictionBytes() {
...
+
     auto& global_rss_memory_at_prev_eviction = eviction_state_.global_rss_memory_at_prev_eviction;
-    auto& deleted_bytes_before_rss_update = eviction_state_.deleted_bytes_before_rss_update;
+    auto& shard_used_memory_at_prev_eviction = eviction_state_.shard_used_memory_at_prev_eviction;
+    auto& deleted_bytes_at_prev_eviction = eviction_state_.deleted_bytes_at_prev_eviction;
+    auto& acc_deleted_bytes_during_eviction = eviction_state_.acc_deleted_bytes_during_eviction;
+
+    // Cap accumulated total deleted bytes
+    acc_deleted_bytes_during_eviction = std::min(
+        (global_used_rss_memory - rss_memory_threshold_start) / shards_count,
```
Comment (romange) [inline src/server/engine_shard.cc]: what if `global_used_rss_memory< rss_memory_threshold_start` ?

File: src/server/engine_shard.h [hunk 5]
```diff
@@ -226,9 +226,35 @@ class EngineShard {
   };
 
   struct EvictionTaskState {
-    bool rss_eviction_enabled_ = true;
+    void Reset(bool rss_eviction_enabled_flag) {
+      rss_eviction_enabled = rss_eviction_enabled_flag;
+      shard_used_memory_at_prev_eviction = global_rss_memory_at_prev_eviction =
+          acc_deleted_bytes_during_eviction = deleted_bytes_at_prev_eviction = 0;
+    }
+    void AdjustDeletedBytes(size_t shard_rss_over_memory_budget, size_t shard_used_memory) {
```
Comment (romange) [inline src/server/engine_shard.h]: Please write the implementation in cc file.

File: src/server/engine_shard.h [hunk 6]
```diff
@@ -226,9 +226,35 @@ class EngineShard {
...
+      // Adjust deleted bytes w.r.t shard used memory. If we increase shard used
+      // memory in current heartbeat we can invalidate deleted_bytes. Otherwise we adjust deleted
+      // bytes by diff.
+      if (shard_used_memory >= shard_used_memory_at_prev_eviction) {
+        deleted_bytes_at_prev_eviction = 0;
+      } else if (shard_used_memory < shard_used_memory_at_prev_eviction) {
+        auto diff = std::min(deleted_bytes_at_prev_eviction,
+                             shard_used_memory_at_prev_eviction - shard_used_memory);
+        deleted_bytes_at_prev_eviction -= (deleted_bytes_at_prev_eviction - diff);
```
Comment (romange) [inline src/server/engine_shard.h]: this is just a complicated way to write `deleted_bytes_at_prev_eviction =  diff;`, mathematically it's equivalent, imho.

Comment (romange) [reply src/server/engine_shard.h]: to summarize:

```
else  {
  deleted_bytes_at_prev_eviction = std::min(deleted_bytes_at_prev_eviction, shard_used_memory_at_prev_eviction - shard_used_memory);
}
```

File: src/server/engine_shard.cc [hunk 7]
```diff
@@ -727,55 +728,67 @@ size_t EngineShard::CalculateEvictionBytes() {
...
+        global_used_rss_memory > rss_memory_threshold_start
+            ? (global_used_rss_memory - rss_memory_threshold_start) / shards_count
+            : 0;
+
+    // Adjustor or limit number of accumulated deleted bytes
+    eviction_state_.AdjustDeletedBytes(shard_rss_over_memory_budget, UsedMemory());
+
     auto& global_rss_memory_at_prev_eviction = eviction_state_.global_rss_memory_at_prev_eviction;
-    auto& deleted_bytes_before_rss_update = eviction_state_.deleted_bytes_before_rss_update;
+    auto& shard_used_memory_at_prev_eviction = eviction_state_.shard_used_memory_at_prev_eviction;
```
Comment (romange) [inline src/server/engine_shard.cc]: nit, seems that lines 748-768 could also be factored out into a EvictionTaskState function .

I have a question though, `AdjustDeletedBytes` changes `acc_deleted_bytes_during_eviction` and now these lines also change `acc_deleted_bytes_during_eviction`. Can you explain how both parts differ?

Comment (mkaruza) [reply src/server/engine_shard.cc]: I have split now steps into 3 functions:

***AdjustDeletedBytes*** will adjust expected number of deleted bytes with respect to used memory. For example if shard used memory is bigger than from previous heartbeat one we don't expect that these bytes are released in future. Otherwise we adjust it to difference.

**LimitAccumulatedDeletedBytes** limits accumulated deleted bytes to not grow out of bounds.

**AdjustAccumulatedDeletedBytes** adjust accumulated deleted bytes w.r.t to rss memory information. Once rss memory start decreasing we can react to it by lowering accumulated deleted bytes.

File: src/server/engine_shard.cc [hunk 8]
```diff
@@ -727,55 +768,55 @@ size_t EngineShard::CalculateEvictionBytes() {
...
+    // Once the rss memory is lowered we can start also decreasing accumulated total bytes.
+    eviction_state_.AdjustAccumulatedDeletedBytes(global_used_rss_memory);
 
-    LOG_IF(DFATAL, global_used_rss_memory < (deleted_bytes_before_rss_update * shards_count))
-        << "RSS evicition underflow "
-        << "global_used_rss_memory: " << global_used_rss_memory
-        << " deleted_bytes_before_rss_update: " << deleted_bytes_before_rss_update;
+    // Update rss/used memory for this heartbeat
+    eviction_state_.global_rss_memory_at_prev_eviction = global_used_rss_memory;
+    eviction_state_.shard_used_memory_at_prev_eviction = global_used_memory;
```
Comment (romange) [inline src/server/engine_shard.cc]: are you sure you want to assign `shard_used_memory_at_prev_eviction = global_used_memory;` ?
shard is not global
