### PR TITLE
fix(bug): access invalid prime table iterator

### LINKED ISSUE #2276: Bug UB on access invalid prime table iterator
This bug can happen is a very rare case when source and dest key of command belong to the same bucket of dash table.
On commands that have a source and dest key ,we call dash table Find for both source and dest key. On Find we do bumpup therefore we can invalidate the iterator to the one we called Find first if both source and dest keys are on the same bucket.

### PR DESCRIPTION
**Pull request by adiholden**
fixes #2276 
The bug:
When running dragonfly in cache mode we bump up items on dash table when we find them. If we access few items on the callback that reside next to each other we will invalidate the first found iterator.

The fix:
After we bump up entry we insert the key to bump keys set. When checking if we can bump down a key we check the key is not in this set. Once we finish running the transaction callback we clear the set.

### CODE REVIEW

File: src/server/string_family_test.cc [hunk 1]
```diff
@@ -228,6 +228,48 @@ TEST_F(StringFamilyTest, MGetSet) {
...
+
+  resp = Run({"info", "stats"});
+  size_t bumps1 = get_bump_ups(resp.GetString());
+  EXPECT_GT(bumps1, 0);
+  EXPECT_LT(bumps1, 10);  // we assume that some bumps are blocked because items reside next to each
+                          // other in the slot.
+
+  for (int i = 0; i < 10; ++i) {
+    auto get_resp = Run({"get", vec[i]});
+    EXPECT_EQ(get_resp, mget_resp[i]);
```
Comment (adiholden) [inline src/server/string_family_test.cc:265]: this check fails before the fix

File: src/server/db_slice.cc [hunk 2]
```diff
@@ -160,10 +160,18 @@ class PrimeEvictionPolicy {
 
 class PrimeBumpPolicy {
  public:
+  PrimeBumpPolicy(const absl::flat_hash_set<string_view>& bumped_itmes)
```
Comment (romange) [inline src/server/db_slice.cc:163]: itmes -> items

File: src/server/db_slice.cc [hunk 3]
```diff
@@ -442,12 +450,11 @@ pair<PrimeIterator, ExpireIterator> DbSlice::FindExt(const Context& cntx, string
...
       };
 
-      //
       db.prime.CVCUponBump(change_cb_.back().first, res.first, bump_cb);
     }
-
-    res.first = db.prime.BumpUp(res.first, PrimeBumpPolicy{});
+    res.first = db.prime.BumpUp(res.first, PrimeBumpPolicy{bump_items_});
     ++events_.bumpups;
+    bump_items_.insert(key);
```
Comment (romange) [inline src/server/db_slice.cc:457]: I feel uncomfortable that you add string_view to the set since it's not clear here what's the life cycle of the `key` object outside of this function. I suggest that you actually store PrimaryKey. it is possible to use them as references.  another benefit of that - you won't need calling GetSlice in l CanBumpDown and you will be able to check it directly.

Comment (romange) [reply src/server/db_slice.cc:457]: check out `AsRef()` function in compact_object. Also, you will need to take care of key deletions to make it consistent.

File: src/server/db_slice.cc [hunk 4]
```diff
@@ -637,7 +642,7 @@ bool DbSlice::Del(DbIndex db_ind, PrimeIterator it) {
     DbContext cntx{db_ind, GetCurrentTimeMs()};
     doc_del_cb_(key, cntx, it->second);
   }
-
+  bumped_items_.erase(it->first.AsRef());
```
Comment (romange) [inline src/server/db_slice.cc:645]: what about flush operation? maybe DCHECK there that `bumped_items_` are empty?

Comment (adiholden) [reply src/server/db_slice.cc:645]: flushdb ? how is this related?
I am adding items to bumped_items_ when we do find for specific item and remove it when the callback is finished. 
If we perform flushdb there will be no items in bumped_items_ as there is not find op done to none of the keys.
Where do you suggest adding the DCHEKC?

Comment (romange) [reply src/server/db_slice.cc:645]: I meant to add a dcheck that bumped_items_ are indeed empty.

Comment (adiholden) [reply src/server/db_slice.cc:645]: yes I understand that you mean to add DCHEKC(bumped_items_.empty()), but where can I add such a check?
It should be empty when I start a cb and after the cb is finished. When the callback is finished I call the new function OnCbFinish which clears the bumped_items_. There is no funciton that is called at before a callback is invoked so where do you think I do this check?

Comment (adiholden) [reply src/server/db_slice.cc:645]: @romange ping here

**Review by romange — DISMISSED** [review]

**Comment by romange** [comment]
please rebase over master

**Review by romange — APPROVED** [review]
