### PR TITLE
fix(tiering): Fix rdb load backpressure

### LINKED ISSUE #5338: tiered memory management does not respect maxmemory
When a tiered-enabled replica loads from a (regular) master and it has say 30GB maxmemory limit, I see it goes beyond the limit. But then once everything is loaded, I observe how the used memory gradually goes down because the background tiering process offloads entries. At the end the RSS memory goes below 30GB proving that it was possible to do in the first place.

We have an heuristic that determines how aggressive offloading is but it is not enough for replication.
We could use the following hints to improve it:
1. `DashTable::Reserve` to actually preallocate distinct segments to provide the required capacity: needed to account for the table memory and also avoid unnecessary splits. 
2. Account for "used-mem" aux header string to tune the aggressiveness of the offloading.
3. Tune the aggressiveness if we are low on memory.

The dataset I tried had a complex value distribution and not all values are possible to offload.
Pasting here:

```
Values - Total Memory used:
Count: 61235371 Average: 158.3353  StdDev: 1053219.66
Min: 0.0000  Median: 16.7622  Max: 1507328.0000
------------------------------------------------------
[       0,       1 ) 18457932  30.143%  30.143% ######
[      16,      18 ) 31908873  52.109%  82.251% ##########
[      30,      35 ) 3090212   5.046%  87.298% #
[      45,      50 ) 458669   0.749%  88.047%
[      60,      70 ) 2008226   3.280%  91.326% #
[      80,      90 ) 129756   0.212%  91.538%
[      90,     100 ) 2220   0.004%  91.542%
[     100,     120 ) 461297   0.753%  92.295%
[     120,     140 ) 446184   0.729%  93.024%
[     160,     180 ) 420197   0.686%  93.710%
[     180,     200 ) 132542   0.216%  93.926%
[     200,     250 ) 36051   0.059%  93.985%
[     250,     300 ) 173416   0.283%  94.268%
[     300,     350 ) 56368   0.092%  94.360%
[     350,     400 ) 140980   0.230%  94.591%
[     400,     450 ) 115237   0.188%  94.779%
[     500,     600 ) 94222   0.154%  94.933%
[     600,     700 ) 144324   0.236%  95.168%
[     700,     800 ) 86062   0.141%  95.309%
[     800,     900 ) 89417   0.146%  95.455%
[    1000,    1200 ) 41393   0.068%  95.523%
[    1200,    1400 ) 214521   0.350%  95.873%
[    1400,    1600 ) 429142   0.701%  96.574%
[    1600,    1800 ) 353847   0.578%  97.152%
[    2000,    2500 ) 172427   0.282%  97.433%
[    2500,    3000 ) 492477   0.804%  98.237%
[    3000,    3500 ) 356678   0.582%  98.820%
[    3500,    4000 ) 204176   0.333%  99.153%
[    4000,    4500 ) 149553   0.244%  99.397%
[    5000,    6000 ) 186941   0.305%  99.703%
[    6000,    7000 ) 85508   0.140%  99.842%
[    7000,    8000 ) 7936   0.013%  99.855%
[    8000,    9000 ) 32561   0.053%  99.909%
[   10000,   12000 ) 9655   0.016%  99.924%
[   12000,   14000 ) 8840   0.014%  99.939%
[   14000,   16000 ) 33782   0.055%  99.994%
[   16000,   18000 ) 540   0.001%  99.995%
[   20000,   25000 ) 2839   0.005%  99.999%
[   25000,   30000 ) 74   0.000% 100.000%
[   30000,   35000 ) 121   0.000% 100.000%
[   40000,   45000 ) 47   0.000% 100.000%
[   45000,   50000 ) 31   0.000% 100.000%
[   50000,   60000 ) 20   0.000% 100.000%
[   60000,   70000 ) 22   0.000% 100.000%
[   80000,   90000 ) 30   0.000% 100.000%
[   90000,  100000 ) 1   0.000% 100.000%
[  100000,  120000 ) 2   0.000% 100.000%
[  120000,  140000 ) 6   0.000% 100.000%
[  200000,  250000 ) 7   0.000% 100.000%
[  250000,  300000 ) 2   0.000% 100.000%
[  300000,  350000 ) 1   0.000% 100.000%
[  350000,  400000 ) 2   0.000% 100.000%
[  400000,  450000 ) 2   0.000% 100.000%
[  500000,  600000 ) 1   0.000% 100.000%
[ 1400000, 1600000 ) 1   0.000% 100.000%

Items length histogram:
Count: 0 Average: 0.0000  StdDev: 0.00
Min: 0.0000  Median: 0.0000  Max: 0.0000
------------------------------------------------------

___end object histogram___
```

### PR DESCRIPTION
**Pull request by dranikpg**
I was sure it worked before, it was just broken by #4631 🤨 

Fixes #5338

### CODE REVIEW

File: src/server/rdb_load.cc [hunk 1]
```diff
@@ -2652,8 +2647,13 @@ void RdbLoader::CreateObjectOnShard(const DbContext& db_cntx, const Item* item,
...
   }
 
-  if (auto* ts = db_slice->shard_owner()->tiered_storage(); ts)
+  if (auto* ts = db_slice->shard_owner()->tiered_storage(); ts) {
     ts->TryStash(db_cntx.db_index, item->key, &res.it->second);
+
+    // Block, if tiered storage is active, but can't keep up
+    while (db_slice->shard_owner()->ShouldThrottleForTiering())
+      ThisFiber::SleepFor(100us);
+  }
```
Comment (dranikpg) [inline src/server/rdb_load.cc:2656]: I don't like how the shard manages the tiered_storage stats and memory balance of the tiered storage, but that's out of scope for this PR. It's a general memory problem #5378

**Review by romange — APPROVED** [review]
