### PR TITLE
fix(server): Rename confusing flag `replica_reconnect_on_master_restart`

### LINKED ISSUE #3192: create new flag replica no reconnect on master restart
deprecate replica_reconnect_on_master_restart

### PR DESCRIPTION
**Pull request by chakaz**
That was a misleading name, as the logic was the exact opposite (oops :facepalm:)

This PR introduces a new name for the same flag: `break_replication_on_master_restart`

We're keeping the previous flag for now, to make transition easier. We'll remove it in a later Dragonfly version (>= 1.22)

Fixes #3192

### CODE REVIEW

**Review by romange — APPROVED** [review]
We must remember to update our default flags config when we switch our prod version to 1.20+.
@ashotland

**Comment by ashotland** [comment]
@romange - that is going to be easy to miss 

Why not respect the old flag for some time ?

I think muting the flag is worse then making dragonfly fail on unknown flag - better have something explicit IMO.

**Comment by romange** [comment]
The price of missing is not critical. @chakaz  up to you.

File: src/server/replica.cc [hunk 1]
```diff
@@ -38,10 +38,15 @@ ABSL_FLAG(int, master_reconnect_timeout_ms, 1000,
...
           "Use partial sync to reconnect when a replica connection is interrupted.");
-ABSL_FLAG(bool, replica_reconnect_on_master_restart, false,
-          "When in replica mode, and master restarts, break replication from master.");
+ABSL_FLAG(bool, break_replication_on_master_restart, false,
+          "When in replica mode, and master restarts, break replication from master to avoid "
+          "flushing the replica's data.");
 ABSL_DECLARE_FLAG(int32_t, port);
 
+// TODO: Remove this flag on release >= 1.22
+ABSL_RETIRED_FLAG(bool, replica_reconnect_on_master_restart, false,
```
Comment (adiholden) [inline src/server/replica.cc:47]: I agree that if this flag is set to true (not defaule) we should use this flag. We can remove it in 1.22 when we know that all prod instances are updated to use the new flag

**Comment by chakaz** [comment]
Sure, you're all right. Let's keep the old flag with the bad name, and add another one (same behavior, better name).

**Review by romange — APPROVED** [review]

File: src/server/replica.cc [hunk 2]
```diff
@@ -303,7 +308,8 @@ std::error_code Replica::HandleCapaDflyResp() {
   // If we're syncing a different replication ID, drop the saved LSNs.
   string_view master_repl_id = ToSV(LastResponseArgs()[0].GetBuf());
   if (master_context_.master_repl_id != master_repl_id) {
-    if (absl::GetFlag(FLAGS_replica_reconnect_on_master_restart) &&
+    if ((absl::GetFlag(FLAGS_replica_reconnect_on_master_restart) ||
+         absl::GetFlag(FLAGS_break_replication_on_master_restart)) &&
```
Comment (ashotland) [inline src/server/replica.cc:312]: sweet thanks
