### PR TITLE
fix(server): Allow interrupting REPLICAOF commands during full sync

### LINKED ISSUE #1017: Replication - replica should support setting up new master while its in loading state
**Describe the bug**
Today we return error on `replicaof <localhost> <port>` command if replica is in loading state, it returns "ERR Can not execute during LOADING"

**Expected behavior**
on loading state if `replicaof <localhost> <port>` command is executed, start replication with new master

Question:
What should happen if `replicaof no one` is executed during loading state? should we return error? Should we return ok and flush all the data?

.

### PR DESCRIPTION
**Pull request by royjacobson**
Fix #1017

There's still a stage that's not interruptible: When forming the initial connection to the master.
Also fixed 2 crashes (one of them in a DCHECK) in the replication cancelling flow.

I did some stress testing locally, so I'm relatively sure it works. Still a bit unsure about how to test this...

### CODE REVIEW

File: src/server/server_family.cc [hunk 1]
```diff
@@ -1763,18 +1763,39 @@ std::string ServerFamily::BuildClusterNodeReply(ConnectionContext* cntx) const {
...
+      VLOG(1) << "Acquired lock";
+      return true;
+    }
+    if (absl::Now() - start > duration) {
+      return false;
+    }
+    ThisFiber::SleepFor(200ms);
+  }
+}
+
```
Comment (dranikpg) [inline src/server/server_family.cc:1780]: Let's not hurry with quick fixes 🙂 Boost has a timed_mutex for this, but it currently doesn't have a wrapper inside helio. Lets add one https://github.com/romange/helio/blob/master/util/fibers/fiber.h#L73

File: src/server/server_family.cc [hunk 2]
```diff
@@ -1763,18 +1763,39 @@ std::string ServerFamily::BuildClusterNodeReply(ConnectionContext* cntx) const {
...
-    unique_lock lk(replicaof_mu_);
+  // From here until the end of Replica::Start() it's a critical section. We don't want to wait
+  // for the lock too long because that hangs the client, so we try to acquire it for ~2 seconds and
+  // return an error if we can't. We should eventually break up the critical section so we don't
+  // have to hold the lock during the networking parts.
+  unique_lock lk(replicaof_mu_, std::defer_lock);
+  if (!try_lock_for(lk, absl::Seconds(2))) {
+    (*cntx)->SendError("Another replication command in progress");
+    return;
+  }
```
Comment (dranikpg) [inline src/server/server_family.cc:1797]: @adiholden 

I have another suggestion. If the mutex is locked, we force-cancel the replication and wait until we can lock again. And then proceed with the new REPLICAOF command. I guess this is what is expected by users?

For the replica, cancellation should be reliable - stop without any delays and deadlocks. So we don't even need the timed wait 🤔

File: src/server/snapshot.h [hunk 3]
```diff
@@ -136,7 +136,7 @@ class SliceSnapshot {
 
   // version upper bound for entries that should be saved (not included).
   uint64_t snapshot_version_ = 0;
-  uint32_t journal_cb_id_ = 0;
+  atomic_uint32_t journal_cb_id_ = 0;
```
Comment (dranikpg) [inline src/server/snapshot.h:139]: Please add an `std::`, we try to spell out the types in headers

File: src/server/snapshot.cc [hunk 4]
```diff
@@ -78,9 +78,10 @@ void SliceSnapshot::Cancel() {
   VLOG(1) << "SliceSnapshot::Cancel";
 
   CloseRecordChannel();
-  if (journal_cb_id_) {
-    db_slice_->shard_owner()->journal()->UnregisterOnChange(journal_cb_id_);
-    journal_cb_id_ = 0;
+  // Set journal_cb_id_ to 0 and unregister callback, but only once.
+  uint32_t cb_id = journal_cb_id_.load();
+  if (cb_id && journal_cb_id_.compare_exchange_strong(cb_id, 0)) {
+    db_slice_->shard_owner()->journal()->UnregisterOnChange(cb_id);
```
Comment (dranikpg) [inline src/server/snapshot.cc:84]: I always thought the cb-id is accessed only from one thread (but possibly multiple fibers). In what case is it accessed by multiple threads?

**Review by dranikpg — COMMENTED** [review]
Looks good. But I'm not sure all we want to do in case of a timeout is return an error.

> Still a bit unsure about how to test this...

We try to test such cases with `tests/dragonfly/replication_tests.py`. See the disconnect ones or rotating master one. 

But I agree its not that easy, the delay needs to be simulated somehow. Maybe, if we send two REPLICAOF inside a pipeline, its fast enough to interrupt each other?

File: src/server/server_family.cc (hunk 2 above)
Comment (royjacobson) [reply src/server/server_family.cc:1797]: Is there a way to cancel a `Connect()` call? If not then this flow can still block for an annoying amount of time.

File: src/server/snapshot.cc (hunk 4 above)
Comment (royjacobson) [reply src/server/snapshot.cc:84]: You're right, I overreacted with the atomics. The bug was that UnregisterOnChange(cb_id) acquires a global lock so it preempts the fiber but a simple assignment before call should be enough.

File: src/server/server_family.cc (hunk 2 above)
Comment (dranikpg) [reply src/server/server_family.cc:1797]: Yes, the replica has built-in cancellation, that closes sockets. I'm not sure it works right away for connect, but it does for later stages.

You can look at replica->Stop and all the stuff with the context. Its a little difficult unfortunately. There should also be some comments around it and the Context in common.h

We can call replica->Stop without any mutex, so it can guard only the pointer

File: src/server/rdb_save.cc [hunk 5]
```diff
@@ -1032,7 +1032,7 @@ error_code RdbSaver::Impl::ConsumeChannel(const Cancellation* cll) {
     pushed_bytes += ptr->channel_bytes();
   }
 
-  DCHECK(!channel_.TryPop(*record));
```
Comment (adiholden) [inline src/server/rdb_save.cc:1035]: in what case you saw this failing?

File: src/server/server_family.cc (hunk 2 above)
Comment (adiholden) [reply src/server/server_family.cc:1797]: I agree we should cancel the the replication process and wait for the mutex to until we can lock it for the new replicaof command.

File: src/server/rdb_save.cc (hunk 5 above)
Comment (royjacobson) [reply src/server/rdb_save.cc:1035]: I think it invoked undefined behavior already before, but apparently it didn't usually crash?

If you add `DCHECK(record.has_value())` and run the following test case -

```
./dragonfly --port 6000&
export PID1=$!
./dragonfly --port 6001&\
export PID2=$!
sleep 1 && redis-cli -p 6001 replicaof localhost 6000
sleep 10 && kill $PID1 $PID2 # Cleanup
```

It hits the assert immediately

File: src/server/server_family.cc (hunk 2 above)
Comment (royjacobson) [reply src/server/server_family.cc]: I changed the locking/cancelling flow. please take another look :)

File: src/server/replica.cc [hunk 6]
```diff
@@ -142,18 +142,29 @@ bool Replica::Start(ConnectionContext* cntx) {
   ProactorBase* mythread = ProactorBase::me();
   CHECK(mythread);
 
+  auto should_continue = [this, &cntx](const error_code& ec, const char* msg) {
+    if (state_mask_ & R_CANCELLED) {
+      (*cntx)->SendError("replication cancelled");
+      return false;
+    }
```
Comment (dranikpg) [inline src/server/replica.cc:149]: The flag is a valid solution, but we already have the context for such management - you can check with `cntx_.IsCancelled()` whether its cancelled.

To catch the cancellation mid flight, `Switch` should be used with the context below, not `Reset`. The first one checks for pending cancellation and returns it

Comment (royjacobson) [reply src/server/replica.cc:149]: thanks! changed it :)

**Comment by dranikpg** [comment]
Oh sorry, I actually found an issue I missed earlier, which should solve most issues 😓  Its connected to the second part of my previous comment about the context. Please take your time to look at it, ts a bit messy, but everything with interruption is more or less based on it 🙂

1. `cntx_.Reset(absl::bind_front(&Replica::DefaultErrorHandler, this));` is the first thing now that should happen within `Replica->Start`, because `Replica::DefaultErrorHandler` is the handler that closes the socket. Before that, none is bound so nothing happens on cancellation. 

2. The step above `// 4. Init basic context` should use `SwitchErrorHandler` instead of `Reset`. There are examples inside replica.cc.

File: src/server/replica.cc [hunk 7]
```diff
@@ -137,55 +137,58 @@ Replica::~Replica() {
...
   VLOG(1) << "Stopping replication";
   // Mark disabled, prevent from retrying.
-  if (sock_) {
-    sock_->proactor()->Await([this] {
-      state_mask_ = 0;  // Specifically ~R_ENABLED.
-      cntx_.Cancel();   // Context is fully resposible for cleanup.
-    });
-  }
+  state_mask_ = 0;  // Specifically ~R_ENABLED.
+  cntx_.Cancel();   // Context is fully resposible for cleanup.
```
[the remark this answers is not in the document]
Comment (dranikpg) [reply src/server/replica.cc:191]: Either: 
- Lets store the replicas `ProactorBase` upon creation so we don't need to read sock
- Or lets add a mutex and switch the `sock_` ptr only on under it.

[the remark this answers is not in the document]
Comment (royjacobson) [reply src/server/replica.cc:191]: Can't reset the `state_mask_` inside `CloseSocket` because we want to keep the `while(enabled)` loop even when a connection is reset. But I made it atomic and added a mutex. Hope I got it more right this time :)

[the remark this answers is not in the document]
Comment (dranikpg) [reply src/server/replica.cc:191]: True, but we could set some kind of flag whether to reset it or not. Either way, the second option is fine as well

**Review by dranikpg — APPROVED** [review]

File: src/server/replica.cc [hunk 8]
```diff
@@ -137,55 +137,58 @@ Replica::~Replica() {
...
   ec = Greet();
-  if (ec) {
-    (*cntx)->SendError(StrCat("could not greet master ", ec.message()));
-    return false;
-  }
+  RETURN_ON_ERR(check_connection_error(ec, "could not greet master "));
 
   // 4. Init basic context.
-  cntx_.Reset(absl::bind_front(&Replica::DefaultErrorHandler, this));
+  RETURN_ON_ERR(cntx_.SwitchErrorHandler(absl::bind_front(&Replica::DefaultErrorHandler, this)));
```
Comment (adiholden) [inline src/server/replica.cc:178]: same as line 145, right? this is redundant

File: src/server/server_family.cc [hunk 9]
```diff
@@ -1770,11 +1770,10 @@ void ServerFamily::ReplicaOf(CmdArgList args, ConnectionContext* cntx) {
 
   LOG(INFO) << "Replicating " << host << ":" << port_s;
 
-  if (absl::EqualsIgnoreCase(host, "no") && absl::EqualsIgnoreCase(port_s, "one")) {
-    // use this lock as critical section to prevent concurrent replicaof commands running.
-    VLOG(1) << "Acquire replica lock";
-    unique_lock lk(replicaof_mu_);
+  VLOG(1) << "Acquire replica lock";
+  unique_lock lk(replicaof_mu_);
```
Comment (adiholden) [inline src/server/server_family.cc:1774]: please add comment on this mutex what we are trying to protect now

File: src/server/replica.cc (hunk 8 above)
Comment (dranikpg) [reply src/server/replica.cc:178]: Ah, yes, we can just check and return

File: src/server/replica.cc [hunk 10]
```diff
@@ -507,7 +523,7 @@ error_code Replica::InitiatePSync() {
   }
 
   state_mask_ &= ~R_SYNCING;
-  state_mask_ |= R_SYNC_OK;
+  state_mask_.fetch_or(R_SYNC_OK);
```
Comment (adiholden) [inline src/server/replica.cc:526]: can you please update all the settings of state mask to use the atomic api

**Comment by adiholden** [comment]
@royjacobson I gave minor comments. This looks good

**Review by adiholden — DISMISSED** [review]

File: tests/dragonfly/replication_test.py [hunk 11]
```diff
@@ -386,6 +386,52 @@ async def test_rotating_masters(df_local_factory, df_seeder_factory, t_replica,
...
+        except aioredis.exceptions.ResponseError as e:
+            assert e.args[0] == "replication cancelled"
+            return False
+
+    for i in range(40):
+        index = random.choice(range(len(masters)))
+        replication_commands.append(replicate(index))
+    results = await asyncio.gather(*replication_commands)
+    num_successes = sum(results)
+    assert 40 > num_successes, "At least one REPLICAOF must be cancelled"
```
Comment (adiholden) [inline tests/dragonfly/replication_test.py:425]: better to use constant

**Review by adiholden — APPROVED** [review]
