### PR TITLE
fix(server): dont allow snapshoting in tiering mode

### LINKED ISSUE #2434: crash during snapshotting when data tiering is enabled.
We get this unsurprising stacktrace.
`SerializeBucket` must run atomically anyway, so our current approach for loading values transparently won't work here. 
Similarly we would not want to heat these items just because we save them into a snapshot.

It's a solvable problem and not interesting right now since we tackle caching use-case for now.
My interim suggestion - to disable snapshotting functionality if `--tiered_prefix` is provides.

```
    compact_object.cc:856] Check failed: !IsExternal()

    @     0xaaaacd66824c  google::LogMessageFatal::~LogMessageFatal()
    @     0xaaaaccfad758  dfly::CompactObj::GetSlice()
    @     0xaaaaccfad758  dfly::CompactObj::GetSlice()
    @     0xaaaaccdc13c0  dfly::RdbSerializer::SaveValue()
    @     0xaaaaccdc13c0  dfly::RdbSerializer::SaveValue()
    @     0xaaaaccdc150c  dfly::RdbSerializer::SaveEntry()
    @     0xaaaaccdc150c  dfly::RdbSerializer::SaveEntry()
    @     0xaaaaccdc63fc  dfly::SliceSnapshot::SerializeEntry()
    @     0xaaaaccdc63fc  dfly::SliceSnapshot::SerializeEntry()
    @     0xaaaaccdc66b0  dfly::SliceSnapshot::SerializeBucket()
    @     0xaaaaccdc66b0  dfly::SliceSnapshot::SerializeBucket()
    @     0xaaaaccdc67f4  dfly::SliceSnapshot::BucketSaveCb()
    @     0xaaaaccdc67f4  dfly::SliceSnapshot::BucketSaveCb()
```

### PR DESCRIPTION
**Pull request by adiholden**
fixes #2434

### CODE REVIEW

File: src/server/server_family.cc [hunk 1]
```diff
@@ -1287,6 +1287,10 @@ GenericError ServerFamily::DoSave(bool ignore_state) {
 
 GenericError ServerFamily::DoSave(bool new_version, string_view basename, Transaction* trans,
                                   bool ignore_state) {
+  if (shard_set->IsTieringEnabled()) {
```
Comment (chakaz) [inline src/server/server_family.cc:1290]: What about scheduled save? Do you intentionally allow that?

Comment (adiholden) [reply src/server/server_family.cc:1290]: schedule save also calls DoSave. am I missing something here?

Comment (chakaz) [reply src/server/server_family.cc:1290]: Nope, my bad :)
I would however `exit(-1)` (or at least print an error) inside `ServerFamily::SnapshotScheduling()` if `IsTieringEnabled()`, as they make no sense together

**Review by chakaz — APPROVED** [review]
