### PR TITLE
fix(tiering): Handle string that are encoded as LONG LONG objects

### LINKED ISSUE #6521: Crash during RDB load with tiered storage enabled
**Dragonfly crashes during startup while loading an RDB when tiered storage is enabled**

Tested with version - v1.36.0

1. Enable tiered (flash) storage
2. Start Dragonfly with an existing RDB file
3. RDB contains non-string keys
4. Dragonfly crashes during RDB loading

F20260202 13:21:03.376718 3401864 compact_object.cc:1611] Unsupported tag for GetRawString(): 17
*** Check failure stack trace: ***
F20260202 13:21:03.376742 3401867 compact_object.cc:1611] Unsupported tag for GetRawString(): 17F20260202 13:21:03.376957 3401865 compact_object.cc:1611] Unsupported tag for GetRawString(): 17
*** Check failure stack trace: ***
F20260202 13:21:03.376742 3401867 compact_object.cc:1611] Unsupported tag for GetRawString(): 17F20260202 13:21:03.376957 3401865 compact_object.cc:1611] Unsupported tag for GetRawString(): 17
*** Check failure stack trace: ***
    @          0x140e69a  google::LogMessage::SendToLog()
    @          0x140e69a  google::LogMessage::SendToLog()
    @          0x140e69a  google::LogMessage::SendToLog()
    @          0x140678f  google::LogMessage::Flush()
    @          0x140678f  google::LogMessage::Flush()
    @          0x140678f  google::LogMessage::Flush()
    @          0x1408159  google::LogMessageFatal::~LogMessageFatal()
    @          0x1408159  google::LogMessageFatal::~LogMessageFatal()
    @          0x1408159  google::LogMessageFatal::~LogMessageFatal()
    @           0xd5f675  dfly::CompactObj::GetRawString()
    @           0xd5f675  dfly::CompactObj::GetRawString()
    @           0x586edc  dfly::(anonymous namespace)::DetermineSerializationParams()
    @           0x586edc  dfly::(anonymous namespace)::DetermineSerializationParams()
    @           0x5883b0  dfly::TieredStorage::ShouldStash()
    @           0x5883b0  dfly::TieredStorage::ShouldStash()
    @           0xd5f675  dfly::CompactObj::GetRawString()
    @           0x586edc  dfly::(anonymous namespace)::DetermineSerializationParams()
    @           0x58a803  dfly::TieredStorage::TryStash()
    @           0x58a803  dfly::TieredStorage::TryStash()
    @           0x5883b0  dfly::TieredStorage::ShouldStash()
    @           0x53b0e5  dfly::RdbLoader::CreateObjectOnShard()
    @           0x53b0e5  dfly::RdbLoader::CreateObjectOnShard()
    @           0x58a803  dfly::TieredStorage::TryStash()
    @           0x53c5f3  dfly::RdbLoader::LoadKeyValPair()
    @           0x53c5f3  dfly::RdbLoader::LoadKeyValPair()
    @           0x53b0e5  dfly::RdbLoader::CreateObjectOnShard()
    @           0x53ffb2  dfly::RdbLoader::Load()
    @           0x53ffb2  dfly::RdbLoader::Load()
    @           0x63cade  _ZZN4dfly12ServerFamily7LoadRdbERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_16LoadExistingKeysEPNS0_11LoadOptionsEENKUlvE_clEv
    @           0x63cade  _ZZN4dfly12ServerFamily7LoadRdbERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_16LoadExistingKeysEPNS0_11LoadOptionsEENKUlvE_clEv
    @           0x63ce83  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberEN4util3fb219FixedStackAllocatorEZNS6_6detail15WorkerFiberImplIZN4dfly12ServerFamily7LoadRdbERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENSB_16LoadExistingKeysEPNSB_11LoadOptionsEEUlvE_JEEC4IS7_EESt17basic_string_viewIcSF_ENS6_13FiberPriorityERKNS0_12preallocatedEOT_OSN_EUlOS4_E_EEEEvNS1_10transfer_tE
    @           0x53c5f3  dfly::RdbLoader::LoadKeyValPair()
    @           0x63ce83  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberEN4util3fb219FixedStackAllocatorEZNS6_6detail15WorkerFiberImplIZN4dfly12ServerFamily7LoadRdbERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENSB_16LoadExistingKeysEPNSB_11LoadOptionsEEUlvE_JEEC4IS7_EESt17basic_string_viewIcSF_ENS6_13FiberPriorityERKNS0_12preallocatedEOT_OSN_EUlOS4_E_EEEEvNS1_10transfer_tE
    @          0x10780df  make_fcontext
*** SIGABRT received at time=1770018663 on cpu 1 ***
    @          0x10780df  make_fcontext
[failure_signal_handler.cc : 377] RAW: Signal 6 raised at PC=0x7fd42a658e2c while already in AbslFailureSignalHandler()
    @           0x53ffb2  dfly::RdbLoader::Load()
    @           0x63cade  _ZZN4dfly12ServerFamily7LoadRdbERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_16LoadExistingKeysEPNS0_11LoadOptionsEENKUlvE_clEv
    @           0x63ce83  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberEN4util3fb219FixedStackAllocatorEZNS6_6detail15WorkerFiberImplIZN4dfly12ServerFamily7LoadRdbERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENSB_16LoadExistingKeysEPNSB_11LoadOptionsEEUlvE_JEEC4IS7_EESt17basic_string_viewIcSF_ENS6_13FiberPriorityERKNS0_12preallocatedEOT_OSN_EUlOS4_E_EEEEvNS1_10transfer_tE
    @          0x10780df  make_fcontext
[failure_signal_handler.cc : 377] RAW: Signal 6 raised at PC=0x7fd42a658e2c while already in AbslFailureSignalHandler()
PC: @     0x7fd42a658e2c  (unknown)  (unknown)

### PR DESCRIPTION
**Pull request by mkaruza**
Don't get raw string representation of string object that don't have allocated data.

Fixes #6521

### CODE REVIEW

**Comment by romange** [comment]
@copilot  fix pre-commit failures

File: src/server/tiered_storage.cc [hunk 1]
```diff
@@ -89,7 +89,7 @@ tiering::DiskSegment FromCoolItem(const PrimeValue::CoolItem& item) {
 TieredStorage::StashDescriptor DetermineSerializationParams(const PrimeValue& pv) {
   switch (pv.ObjType()) {
     case OBJ_STRING: {
-      if (pv.IsInline())
+      if (pv.IsInline() || pv.IsIntTag())
```
Comment (romange) [inline src/server/tiered_storage.cc]: you can test with `!pv.HasAllocated()` instead and then you do not need `INT_TAG` check
