### PR TITLE
fix(server): Do not crash `HRANDFIELD` if some/all elements expired

### LINKED ISSUE #2108: `StringMap` could crash with `operator+=`
The reason is that, if some elements expired, we may call `Advance()` after we've reached the end.
A repro test:

```cpp
TEST_F(StringMapTest, TtlLoop) {
  EXPECT_TRUE(sm_->AddOrUpdate("k1", "v1", 1));
  EXPECT_TRUE(sm_->AddOrUpdate("k2", "v2", 1));
  sm_->set_time(1);
  auto it = sm_->begin();
  it += 1;
}
```

This affects all calls to `RandomPair()`, including `HRANDFIELD`

### PR DESCRIPTION
**Pull request by chakaz**
The issue is twofold:
1. If all elements are expired, dividing by `Size()` will crash. However, we cannot know this in advance, as `begin()` will actually invalidate all elements, but we're already inside `RandomPair()` which must return a result (it should not be called if *real* size is 0, after expiration)
2. We cannot use `operator +=` before we know how many *real* elements are in the array. Today we do `+= rand() / Size()`, and this in fact is problematic even if `Size()` is non-zero, but is greater than post-expiration size

Unfortunately, this solution will iterate over all elements in map for the multi-random retrieval function, to know how many non-expired elements (if any) are in the list. I don't think it's too bad, as we iterate there anyway (although not necessarily through all)

Fixes #2108 and other bugs.

### CODE REVIEW

**Comment by chakaz** [comment]
One such "more clever solution" would be to change the signature to `optional<pair> RandomPair()`, and also change the signature of `Advance()` to return whether it reached the end (or just check `*this == end()`), and then to change `operator +=` to quietly exit if `end()` was reached.

However this is slightly subtle, and also I'm not a fan of quietly quitting without performing what we were asked for `operator+=`...

**Comment by chakaz** [comment]
I decided to, indeed, go with the slightly more complicated solution. It's not too bad, and definitely a better & safer API.
Will update the desc as well.

File: src/core/string_map.cc [hunk 1]
```diff
@@ -142,6 +162,8 @@ void StringMap::RandomPairsUnique(unsigned int count, std::vector<sds>& keys,
 
 void StringMap::RandomPairs(unsigned int count, std::vector<sds>& keys, std::vector<sds>& vals,
                             bool with_value) {
+  CollectExpired();
```
Comment (romange) [inline src/core/string_map.cc:165]: maybe add a comment, this is `O(n)` function that may slow down `RandomPairs` for large sets?

**Review by romange — COMMENTED** [review]
LGTM!

**Comment by chakaz** [comment]
friendly ping :)
(I only added a comment as you asked)

**Review by romange — APPROVED** [review]
