### PR TITLE
fix: Fix `test_network_disconnect_during_migration` test

### LINKED ISSUE #4207: test_network_disconnect_during_migration with big_value_serialization and compression off
To reproduce check this branch: https://github.com/dragonflydb/dragonfly/actions/runs/12049150090/job/33595305922?pr=4199#step:12:245

and the failure at: https://github.com/dragonflydb/dragonfly/actions/runs/12049150090/job/33595305922?pr=4199#step:12:245

1. Turn big value serialization to the minum
2. Turn compression off

Test fails on the CI and it did not fail for me locally. Although to be honest I haven't run it in a loop so maybe it does :man_shrugging:

### PR DESCRIPTION
**Pull request by chakaz**
There are actually a few failures fixed in this PR, only one of which is a test bug:

* `db_slice_->Traverse()` can yield, causing `fiber_cancelled_`'s value to change
* When a migration is cancelled, it may never finish `WaitForInflightToComplete()` because it has `in_flight_bytes_` that will never reach destination due to the cancellation
* `IterateMap()` with numeric key/values overrode the key's buffer with the value's buffer

Fixes #4207

### CODE REVIEW

**Comment by kostasrim** [comment]
:man_dancing: :rocket:

File: src/server/journal/streamer.cc [hunk 1]
```diff
@@ -79,7 +81,9 @@ void JournalStreamer::Cancel() {
   VLOG(1) << "JournalStreamer::Cancel";
   waker_.notifyAll();
   journal_->UnregisterOnChange(journal_cb_id_);
-  WaitForInflightToComplete();
+  if (!cntx_->IsCancelled()) {
+    WaitForInflightToComplete();
```
Comment (kostasrim) [inline src/server/journal/streamer.cc:85]: I was about to write that maybe we should move `cntx_->IsCancelled()` within `WaitForInFlightToComplete` but then I realized it's only called in this place so not really needed I guess

File: src/server/journal/streamer.cc [hunk 2]
```diff
@@ -41,7 +41,9 @@ JournalStreamer::JournalStreamer(journal::Journal* journal, Context* cntx)
 }
 
 JournalStreamer::~JournalStreamer() {
-  DCHECK_EQ(in_flight_bytes_, 0u);
+  if (!cntx_->IsCancelled()) {
+    DCHECK_EQ(in_flight_bytes_, 0u);
```
Comment (kostasrim) [inline src/server/journal/streamer.cc:45]: How did we not trigger this before ? Or did we just deadlocked because `WaitForInFlightToCOmplete() would never progress` ?

File: src/server/multi_command_squasher.cc [hunk 3]
```diff
@@ -112,6 +112,8 @@ MultiCommandSquasher::SquashResult MultiCommandSquasher::TrySquash(StoredCmd* cm
 
   cmd->Fill(&tmp_keylist_);
   auto args = absl::MakeSpan(tmp_keylist_);
+  if (args.size() == 0)
```
Comment (kostasrim) [inline src/server/multi_command_squasher.cc:115]: Curious, didn't `DetermineKeys` below handle this case or ?


Also general small nits (I do not care if you apply this or not :smile: )

1. `span` contains `empty()` 
2. We can also use `NumArgs()` and avoid the two calls above.

**Review by kostasrim — APPROVED** [review]
LGTM

File: src/server/journal/streamer.cc [hunk 4]
```diff
@@ -215,6 +219,9 @@ void RestoreStreamer::Run() {
       return;
 
     cursor = db_slice_->Traverse(pt, cursor, [&](PrimeTable::bucket_iterator it) {
+      if (fiber_cancelled_)  // Could be cancelled any time as Traverse may preempt
```
Comment (adiholden) [inline src/server/journal/streamer.cc:222]: how can traverse preempt if we dont have the big value serialization merged yet?

Comment (BorysTheDev) [reply src/server/journal/streamer.cc:222]: in the callback

**Comment by adiholden** [comment]
> There are actually a few failures fixed in this PR, only one of which is a test bug.
> 
> Fixes #4207

I suggest to write in the descirtion all the bugs that were fixed

File: src/server/journal/streamer.cc (hunk 4 above)
Comment (adiholden) [reply src/server/journal/streamer.cc:222]: which callback can preempt?

Comment (BorysTheDev) [reply src/server/journal/streamer.cc:222]: by the way I think we can use snapshot_version_ instead of fiber_canceled_ because we always process them together

Comment (BorysTheDev) [reply src/server/journal/streamer.cc:222]: > which callback can preempt?

db_slice_->FlushChangeToEarlierCallbacks(0 /*db_id always 0 for cluster*/,
                                               DbSlice::Iterator::FromPrime(it), snapshot_version_);

Comment (BorysTheDev) [reply src/server/journal/streamer.cc:222]: also WriteBucket(it); can yield

File: src/server/journal/streamer.cc (hunk 2 above)
Comment (chakaz) [reply src/server/journal/streamer.cc:45]: idk why we didn't trigger this before, but indeed this dead locks

File: src/server/multi_command_squasher.cc (hunk 3 above)
Comment (chakaz) [reply src/server/multi_command_squasher.cc:115]: Switched to use `empty()`, thanks!
Re/ `NumArgs()`, that's a feature of the command, not the args

File: src/server/journal/streamer.cc (hunk 4 above)
Comment (adiholden) [reply src/server/journal/streamer.cc:222]: so I think the if fiber_cancelled_ should be also after call to FlushChangeToEarlierCallbacks

**Comment by BorysTheDev** [comment]
@chakaz I think we also need to add update next methods
  void OutgoingMigration::SliceSlotMigration::Cancel() {
    cntx_.Cancel();
    streamer_.Cancel();
  }

~OutgoingMigration::SliceSlotMigration::SliceSlotMigration() {
    Cancel();
    cntx_.JoinErrorHandler();
  }

File: src/server/journal/streamer.cc (hunk 4 above)
Comment (BorysTheDev) [reply src/server/journal/streamer.cc:222]: why?

**Comment by chakaz** [comment]
Test now passes, and I think I responded to / applied all comments. PTAL :)

**Comment by BorysTheDev** [comment]
@chakaz Please run tests a couple of times more, because sometimes they are passed even with bug

**Review by BorysTheDev — DISMISSED** [review]

**Review by BorysTheDev — APPROVED** [review]
