### PR TITLE
fix(server_family): `GetMetrics` should show commands in lowercase

### LINKED ISSUE #862: INFO command output should use consistent letter cases

### PR DESCRIPTION
**Pull request by lsvmello**
Closes #862

I've ran `INFO ALL` locally and the only section that showed IN CAPS was `cmdstat_COMMAND`.

So I 'lowercased' all commands on `GetMetrics()` and fixed the `replication_test.py` accordingly.
Also checked that Redis behaves the same.

### CODE REVIEW

File: src/server/server_family.cc [hunk 1]
```diff
@@ -1658,7 +1659,7 @@ Metrics ServerFamily::GetMetrics() const {
   Mutex mu;
 
   auto cmd_stat_cb = [&dest = result.cmd_stats_map](string_view name, const CmdCallStats& stat) {
-    auto& [calls, sum] = dest[string{name}];
+    auto& [calls, sum] = dest[string{absl::AsciiStrToLower(name)}];
```
Comment (kostasrim) [inline src/server/server_family.cc:1662]:
```suggestion
    auto& [calls, sum] = dest[absl::AsciiStrToLower(name)];
```

**Review by kostasrim — DISMISSED** [review]
Hi @lsvmello! Thank you for your contribution :rocket: 

I left a very minor comment.

@dranikpg let me know if you had something else in mind with #862

**Comment by dranikpg** [comment]
I don't know if we want all command stats to be in lowercase, I mean that we use(d) inconsistent naming for sections in INFO ALL. Some were camel (Transaction), come were caps (STATS, MEMORY), etc

**Comment by kostasrim** [comment]
> I don't know if we want all command stats to be in lowercase, I mean that we use(d) inconsistent naming for sections in INFO ALL. Some were camel (Transaction), come were caps (STATS, MEMORY), etc

Oh I see and I also did notice that this was an old issue. Anyway, their changes are only for two command stats:

```
# Commandstats         
cmdstat_COMMAND:calls=2,usec=50894,usec_per_call=25447             
cmdstat_INFO:calls=1,usec=2043,usec_per_call=2043
```
I can live with lowercase `COMMAND and INFO` so I personally don't mind moving forward with this PR unless there is some strong objection. 

Also looking on the `camelCase` or `CAPS` it seems now that the naming of each category is coherent (First letter capital followed by all lower case) so I guess we can close the issue as well?

**Comment by lsvmello** [comment]
I've added the change requested and rebased the branch.
