### PR TITLE
fix(server): saving is not a server state

### LINKED ISSUE #2597: Server crashes after issuing `replicaof no one`
**Describe the bug**
Process crashes after issuing `replicaof no one` while it's replica of another node.

**To Reproduce**
1. Issue `replicaof no one` on the node while it's replica of another node 
2. Server crashes with logs below

```
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]: I20240215 09:20:31.842679    81 server_family.cc:2123] Replicating no:one
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]: I20240215 09:20:31.843235    77 replica.cc:629] Exit stable sync
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]: W20240215 09:20:31.843266    77 replica.cc:237] Error stable sync with thanos-dragonfly-eu-3.aiven-metrics.aiven.local:17673 generic:125 Operation canceled
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]: F20240215 09:20:31.843624    81 server_family.cc:2142] Check failed: service_.SwitchState(GlobalState::LOADING, GlobalState::ACTIVE).first == GlobalState::ACTIVE Server is set to replica no one, yet state is not active!
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]: *** Check failure stack trace: ***
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]:     @           0xc7f9f7  (unknown)
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]:     @           0xc77426  (unknown)
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]:     @           0xc78cb9  (unknown)
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]:     @           0x5f029f  (unknown)
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]:     @           0x5f04d4  (unknown)
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]:     @           0x79903b  (unknown)
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]:     @           0x593c19  (unknown)
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]:     @           0x59951c  (unknown)
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]:     @           0x886fc9  (unknown)
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]:     @           0x8871ac  (unknown)
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]:     @           0x88ac38  (unknown)
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]:     @           0x88af09  (unknown)
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]:     @           0x88bee2  (unknown)
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]:     @           0xc26e01  (unknown)
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]:     @           0xc272d3  (unknown)
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]:     @     0x7f82aed3d18f  make_fcontext
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]: *** SIGABRT received at time=1707988831 on cpu 13 ***
Feb 15 09:20:31 thanos-dragonfly-eu-5 taskset[75]: PC: @     0x7f82ae57e884  (unknown)  __pthread_kill_implementation
Feb 15 09:20:33 thanos-dragonfly-eu-5 systemd[1]: dragonfly.service: Main process exited, code=dumped, status=6/ABRT
```
**Expected behavior**
Server shouldn't crash after such logs

**Environment (please complete the following information):**
 - OS: Fedora 38
 - Kernel: 6.3.12-200.fc38.x86_64
 - Containerized?: toolbox
 - Dragonfly Version: 1.14.1

### PR DESCRIPTION
**Pull request by adiholden**
fixes #2597 
The bug:
server crashed because when replicaof no one was executed the replica was creating a snapshot and there for the server state was not active but saving.
check fail -server_family.cc:2142] Check failed: service_.SwitchState(GlobalState::LOADING, GlobalState::ACTIVE).first == GlobalState::ACTIVE Server is set to replica no one, yet state is not active!
The fix:
1. remove saving from server states
2. move save stage controller to be a member of server family

### CODE REVIEW

File: src/server/detail/save_stages_controller.h [hunk 1]
```diff
@@ -19,16 +17,28 @@ class Service;
 
 namespace detail {
 
+class SnapshotStorage;
+
+struct LastSaveInfo {
```
Comment (romange) [inline src/server/detail/save_stages_controller.h:22]: nit: since we return it from a ServerFamily function, it can be declared outside `detail` namespace

File: src/server/server_family.h [hunk 2]
```diff
@@ -167,14 +156,15 @@ class ServerFamily {
...
+  detail::LastSaveInfo GetLastSaveInfo() const;
 
   // Load snapshot from file (.rdb file or summary.dfs file) and return
   // future with error_code.
   util::fb2::Future<GenericError> Load(const std::string& file_name);
 
   bool IsSaving() const {
-    return is_saving_.load(std::memory_order_relaxed);
+    std::lock_guard lk(save_mu_);
+    return save_controller_ && save_controller_->IsSaving();
```
Comment (romange) [inline src/server/server_family.h:167]: seems that this function is now used only for tests. 
I think that returning bool(save_controller_) is enough for this

File: src/server/detail/save_stages_controller.h [hunk 3]
```diff
@@ -102,12 +118,11 @@ struct SaveStagesController : public SaveStagesInputs {
 
   void RunStage(void (SaveStagesController::*cb)(unsigned));
 
-  size_t GetSaveBuffersSize();
-
  private:
   absl::Time start_time_;
   std::filesystem::path full_path_;
   bool is_cloud_;
+  bool is_saving_ = false;
```
Comment (romange) [inline src/server/detail/save_stages_controller.h:125]: i think it's not really needed. see my comment below

File: src/server/server_family.h (hunk 2 above)
Comment (adiholden) [reply src/server/server_family.h:167]: actually .. I debuged the test for a while to understand that I do need it, as it takes some time for the save executed command to be scheduled in the transaction queue. If I dont have this is_saving_ set after the scheduling the test SaveFlush fails as it will schedule flushall before the save

Comment (dranikpg) [reply src/server/server_family.h:167]: Let's not complicate real code for testing reasons (especially without comments or TEST prefix), we have lot's of other ways to check if saving is in progress. For example check `tl_slice_snapshots`, which should be easiest. We can also check transaction metrics

File: tests/dragonfly/snapshot_test.py [hunk 4]
```diff
@@ -125,21 +125,21 @@ async def test_dbfilenames(
 
 @pytest.mark.slow
 @dfly_args({**BASIC_ARGS, "dbfilename": "test-cron", "snapshot_cron": "* * * * *"})
-async def test_cron_snapshot(tmp_path: Path, async_client: aioredis.Redis):
+async def test_cron_snapshot(tmp_dir: Path, async_client: aioredis.Redis):
```
Comment (dranikpg) [inline tests/dragonfly/snapshot_test.py:128]: my bad 😅  ... but why did it pass 🤔

File: src/server/detail/save_stages_controller.h [hunk 5]
```diff
@@ -19,16 +17,28 @@ class Service;
...
+
 struct SaveStagesInputs {
   bool use_dfs_format_;
   std::string_view basename_;
   Transaction* trans_;
   Service* service_;
-  std::atomic_bool* is_saving_;
   util::fb2::FiberQueueThreadPool* fq_threadpool_;
   LastSaveInfo* last_save_info_ ABSL_GUARDED_BY(save_mu_);
   util::fb2::Mutex* save_mu_;
```
Comment (dranikpg) [inline src/server/detail/save_stages_controller.h:41]: Just a though I realize now (and not while extracting this class), it'd be more convenient if returned LastSaveInfo just by value from `Save()` instead of passing a mutex by pointer

File: tests/dragonfly/replication_test.py [hunk 6]
```diff
@@ -1999,3 +1999,29 @@ async def send_setex():
...
+    await c_replica.execute_command(f"REPLICAOF localhost {master.port}")
+    await wait_available_async(c_replica)
+
+    async def save_replica():
+        await c_replica.execute_command("save")
+
+    save_task = asyncio.create_task(save_replica())
+    await asyncio.sleep(0.1)  # let save start
+    await c_replica.execute_command("replicaof no one")
+    await save_task
```
Comment (dranikpg) [inline tests/dragonfly/replication_test.py:2025]: Once we assert `replicaof no one` returns `OK`  and doesn't crash, the test is over. We can kill the replica and cancel the save task (it'll be knocked out with an error either way)

Comment (dranikpg) [reply tests/dragonfly/replication_test.py:2025]: Maybe we can busy loop on `saving_metric > 0` to start quicker? Not to save time _here_, but to be able to use much less than 100k keys (we rarely use such large values like 100k in pytests + debug)

File: tests/dragonfly/snapshot_test.py (hunk 4 above)
Comment (adiholden) [reply tests/dragonfly/snapshot_test.py:128]: it did not. the slow tests are not running in regression tests

**Review by romange — APPROVED** [review]

File: tests/dragonfly/replication_test.py (hunk 6 above)
Comment (adiholden) [reply tests/dragonfly/replication_test.py]: I updated the test to use 10k keys and a busy loop. I do want to want to wait for the save to finish and not just exit after issue replicaof no one, this test will check that saving will finish after promotion to master and not only try to reproduce a specific crash we had
