### PR TITLE
fix(server): Do not return empty array after expiration

### LINKED ISSUE #2102: `hgetall` after entry expiration briefly returns an empty key/value
```
127.0.0.1:6379> hsetex k 10 k1 v1
(integer) 1
```

wait >10 s

```
127.0.0.1:6379> hgetall k
1) ""
2) ""
127.0.0.1:6379> hgetall k
(empty array)
```

Obviously, the middle part, where we return `["", ""]` is flawed..

### PR DESCRIPTION
**Pull request by chakaz**
Fixes #2102

### CODE REVIEW

**Review by kostasrim — APPROVED** [review]

File: src/server/hset_family.cc [hunk 1]
```diff
@@ -565,14 +565,15 @@ OpResult<vector<string>> OpGetAll(const OpArgs& op_args, string_view key, uint8_
     DCHECK_EQ(pv.Encoding(), kEncodingStrMap2);
     StringMap* sm = GetStringMap(pv, op_args.db_cntx);
 
-    res.resize(sm->Size() * (keyval ? 2 : 1));
+    // Some items could have expired, yet accounted for in Size(), so reserve() might overshoot
+    res.reserve(sm->Size() * (keyval ? 2 : 1));
```
Comment (adiholden) [inline src/server/hset_family.cc:569]: this fix does fix the issue #2104 , but check out other places this Size function is used.
f.e I see that hlen returns the Size, and also I see that HRADFIELD uses this function and also ignores the expire time of items so it will return items that passed the ttl.
Dont you think that part of this fix Size should expire the entries?

Comment (chakaz) [reply src/server/hset_family.cc:569]: It's problematic to change the semantics of `Size()`, as (a) it's `const`, and (b) developers don't expect such method to be slow.
Indeed I'll search for other similar use cases as you mentioned (good catch!), but I think we should generally prefer `.reserve()` over `.resize()`, unless we have a good reason. It's also faster for most cases as it does not construct the objects only to be reassigned later.

**Review by adiholden — APPROVED** [review]

File: src/server/hset_family.cc (hunk 1 above)
Comment (chakaz) [reply src/server/hset_family.cc:569]: I'll follow up on your above comment in separate PRs, there are a few issues that we need to fix here.
