### PR TITLE
fix: support json v1 dot path

### LINKED ISSUE #1456: Redis Insight calls JSON keys with a dot instead of the root $
**Describe the bug**
Redis Insight (v2) sets the following command to read a Json Key: "JSON.GET" "key" "." 
It sets a dot "." as root path and not a "$". This generates a syntax error with Dragonfly DB and no output in Insight (undefined).

This is probably not a real bug of Dragonfly DB, but for compatibility reasons it should work. 

**To Reproduce**
1. open redis-cli with fireflydb (version 1.4)
2. `JSON.SET doc $ '{"a":2}'`
3. `JSON.GET doc .`
4. ERR syntax error appears

.. or Open Redis Insight (v2), start the Profiler and get a json key.

redis_insight_v2

**Expected behavior**
For compatibility reasons and the fact that Redis Insight is used by many developers, the dot should work and be considered as root $. 

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Dragonfly Version: 1.4

### PR DESCRIPTION
**Pull request by dranikpg**
Fixes #1456 

There is a special optimization for root level set that doesn't parse the path. It already checks both "." and "$". This is why it failed only for get commands

### CODE REVIEW

File: src/server/json_family_test.cc [hunk 1]
```diff
@@ -1005,4 +1005,15 @@ TEST_F(JsonFamilyTest, Set) {
...
 
+TEST_F(JsonFamilyTest, LegacyV1) {
+  string json = R"({"key":[1,2,3,4]})";
+
+  auto resp = Run({"JSON.SET", "json1", ".", json});
+  EXPECT_THAT(resp, "OK");
+
+  // JSON.GET key "." is the same as JSON.GET key "$"
+  resp = Run({"JSON.GET", "json1", "."});
+  EXPECT_THAT(resp, absl::StrCat("[", absl::StripAsciiWhitespace(json), "]"));
```
Comment (chakaz) [inline src/server/json_family_test.cc:1016]: There's no whitespace in `json`, right? Can we remove the call to `StripAsciiWhitespace()`?

File: src/server/json_family.cc [hunk 2]
```diff
@@ -84,6 +84,16 @@ string JsonTypeToName(const JsonType& val) {
   return std::string{};
 }
 
+JsonExpression ParseJsonPath(string_view path, error_code* ec) {
```
Comment (kostasrim) [inline src/server/json_family.cc:87]:
```suggestion
JsonExpression ParseJsonPath(string_view path, error_code& ec) {
```

Comment (kostasrim) [reply src/server/json_family.cc:87]: The reason I like `ref` instead of  a `pointer` is that the second can be used to denote an optional value (meaning that it can be a `nullptr`) -- that's from Sean Parent suggestion. Also bonus point, you don't need to dereference :)

**Review by kostasrim — COMMENTED** [review]
Good work :man_cook:

File: src/server/json_family.cc (hunk 2 above)
Comment (chakaz) [reply src/server/json_family.cc:87]: I agree, and I also raised this when I first started contributing to this project.
The reason why we take pointers is due to the fact that the old Google Style Guide (which our project follows) used to only allow either `const&` or mutable pointers. There are some pros to that, but it doesn't matter because Google switched away from it. But since our code base was developed with this in mind, @romange said we should continue with this.

Comment (kostasrim) [reply src/server/json_family.cc:87]: That makes sense. @dranikpg ignore me then.

**Review by kostasrim — DISMISSED** [review]

File: src/server/json_family.cc (hunk 2 above)
Comment (kostasrim) [reply src/server/json_family.cc:87]: also for completion do we have a reference to the version of google style of code we use? 

Because from https://google.github.io/styleguide/cppguide.html#Inputs_and_Outputs

```
input/output parameters should usually be references (which cannot be null). 
```

Comment (chakaz) [reply src/server/json_family.cc:87]: I don't know. I remember Google making those changes a couple of years ago, when I still worked there :)
I can't even find any place that archives the old versions, although admittedly I haven't looked too hard

**Review by kostasrim — APPROVED** [review]

**Review by chakaz — APPROVED** [review]
