### PR TITLE
fix(server): handle running script load inside multi

### LINKED ISSUE #4071: crash in muti/exec transaction
To reproduce:
```
./dragonfly --logtostderr   --proactor_threads=2
```

and then:

```
MULTI
SCRIPT LOAD 'return 42'
EXEC
```

### PR DESCRIPTION
**Pull request by adiholden**
fix #4071 
2 bugs found in the flow:
1. we did not use the interperter borrowed in the script load command before running the multi transaction
2. we call InitByArgs for each command in multi transaction. in this flow Transaction::shard_data_ must not be resized to 1. (see comment here - https://github.com/dragonflydb/dragonfly/blob/f8b3fa0d7bf1d95674f80eef826ffd66f5a57659/src/server/transaction.cc#L343) When calling script load we resized it to 1 leading to the crash.

### CODE REVIEW

File: src/server/common.cc [hunk 1]
```diff
@@ -453,4 +455,29 @@ void ThreadLocalMutex::unlock() {
   }
 }
 
+BorrowedInterpreter::BorrowedInterpreter(Transaction* tx, ConnectionContext* cntx) {
```
Comment (romange) [inline src/server/common.cc:458]: passing `ConnectionState` is more precise

File: src/server/conn_context.cc [hunk 2]
```diff
@@ -72,6 +72,13 @@ size_t StoredCmd::NumArgs() const {
   return sizes_.size();
 }
 
+std::string StoredCmd::FirstArg() const {
+  if (sizes_.size() == 0) {
+    return "";
```
Comment (romange) [inline src/server/conn_context.cc:77]:
```suggestion
    return {};
```

File: src/server/main_service.cc [hunk 3]
```diff
@@ -2255,10 +2212,10 @@ void Service::Exec(CmdArgList args, Transaction* tx, SinkReplyBuilder* builder,
   cntx->last_command_debug.exec_body_len = exec_info.body.size();
 
   // The transaction can contain scripts, determine their presence ahead to customize logic below.
-  ExecEvalState state = DetermineEvalPresense(exec_info.body);
+  ExecScriptUse state = DetermineScriptPresense(exec_info.body);
 
   // We borrow a single interpreter for all the EVALs inside. Returned by MultiCleanup
```
Comment (romange) [inline src/server/main_service.cc:2217]: please update the comment as well

File: src/server/transaction.cc [hunk 4]
```diff
@@ -399,10 +399,12 @@ OpStatus Transaction::InitByArgs(Namespace* ns, DbIndex index, CmdArgList args)
   }
 
   if ((cid_->opt_mask() & CO::NO_KEY_TRANSACTIONAL) > 0) {
-    if ((cid_->opt_mask() & CO::NO_KEY_TX_SPAN_ALL) > 0)
+    if (((cid_->opt_mask() & CO::NO_KEY_TX_SPAN_ALL) > 0) || IsActiveMulti()) {
```
Comment (romange) [inline src/server/transaction.cc:402]: can you please add a comment for these conditions?

**Review by romange — COMMENTED** [review]
lgtm

File: src/server/transaction.cc (hunk 4 above)
Comment (romange) [reply src/server/transaction.cc:405]: I suspect it's sub-optimal. I suspect that we resize shard data when we schedule the lock ahead transactions. I agree that we should not shrink it. If we revert this condition the test you added will fail?

@dranikpg  Can you please review the change in this function specifically?

Comment (dranikpg) [reply src/server/transaction.cc:405]: Surely we can't enable all shards, it's a misunderstanding of what goes on

We use the NO_KEY_TRANSACTIONAL flag to make commands without keys transactional. Why? To replicate them via the journal. In fact, it was Adi who introduced this 🙂  https://github.com/dragonflydb/dragonfly/pull/1114

Putting order aside, any shard fits us to transfer replication data. So for active multi, let's find the first shard that has keylocks aquired and enable it. The only question now is linearizability - if we use differnet shards for script loads, they can arrive in a different order

If that's a problem, we have to always schedule on shard X if we find SCRIPT LOAD, or make it global.

--- 

By the way, it's a bug with NO_KEY_TX_SPAN_ALL as well... It's used by ft.search as a cheap read-only alternative to GLOBAL. I will take over the search issue.

File: src/server/transaction.cc [hunk 5]
```diff
@@ -976,7 +978,7 @@ string Transaction::DEBUG_PrintFailState(ShardId sid) const {
 void Transaction::EnableShard(ShardId sid) {
   unique_shard_cnt_ = 1;
   unique_shard_id_ = sid;
-  shard_data_.resize(1);
+  shard_data_.resize(IsActiveMulti() ? shard_set->size() : 1);
```
Comment (adiholden) [inline src/server/transaction.cc:981]: As today we have in UnlockMulti a check for 
DCHECK_EQ(shard_data_.size(), shard_set->size());
I understand that we excpect that this array size will be shard_set->size() when running multi command, so that we do not shrink it when running some command in multi. Therefore the fix now is to resize it to shard_set->size() if IsActiveMulti()

Comment (adiholden) [reply src/server/transaction.cc:981]: @dranikpg please comment / approve

Comment (dranikpg) [reply src/server/transaction.cc:981]: It turns out I fixed the issue I mentioned already 🤦🏻🤦🏻🤦🏻🤦🏻 The resize is the only fix needed 👍🏻 
https://github.com/dragonflydb/dragonfly/pull/2279

**Review by dranikpg — APPROVED** [review]

File: src/server/transaction.cc (hunk 5 above)
Comment (romange) [reply src/server/transaction.cc:981]: @adiholden  when IsActiveMulti() is true, is it true that shard_data is already non-empty before the resize?
I am trying to understand preconditions

Comment (dranikpg) [reply src/server/transaction.cc:981]: Yes, it's non-empty, as it was used for scheduling

Comment (romange) [reply src/server/transaction.cc:981]: nit: 
I prefer `if (shard_data_.empty()) shard_data_.resize(1); ` as being less intrusive.

Comment (dranikpg) [reply src/server/transaction.cc:981]: The convention in tx code is what Adi used
