### PR TITLE
fix(server): Fix QUIT not shutting down connection

### LINKED ISSUE #170: QUIT does not disconnect once subscribed
`QUIT` terminates the connection.

```
% nc localhost 6379
PING
+PONG
QUIT
+OK
%
```

`QUIT` does not terminate the connection anymore after a `SUBSCRIBE`. Instead, it waits for another line/command, and then the connection gets terminated.

```
% nc localhost 6379
PING
+PONG
SUBSCRIBE foo
*3
$9
subscribe
$3
foo
:1
QUIT
+OK
PING
%
```

The issue was detected with by https://github.com/pascaldekloe/redis/issues/4.

### PR DESCRIPTION
**Pull request by dranikpg**
Fixes #170

### CODE REVIEW

File: src/facade/dragonfly_connection.cc [hunk 1]
```diff
@@ -698,6 +698,10 @@ auto Connection::FromArgs(RespVec args, mi_heap_t* heap) -> Request* {
   return req;
 }
 
+void Connection::RequestShutdown() {
```
Comment (romange) [inline src/facade/dragonfly_connection.cc:701]: I understand why you introduced this function (btw, you are welcome to shoot a pr to helio and change the visibility).

However, i think word Request is misleading. Maybe ShutdownSelf?

File: tests/dragonfly/server_family_test.py [hunk 2]
```diff
@@ -0,0 +1,20 @@
+import pytest
+import redis
+
+def test_quit(connection):
+    connection.send_command("QUIT")
+    assert connection.read_response() == b'OK'
+
+    with pytest.raises(redis.exceptions.ConnectionError) as e:
```
Comment (romange) [inline tests/dragonfly/server_family_test.py:8]: what's the purpose of these 2 lines?

Comment (dranikpg) [reply tests/dragonfly/server_family_test.py:8]: The upper two?
To send a QUIT and check it actually responds OK...?
The lower one - the most reliable way to check redis is really discontented - try sending something down the connection. Without the fix, this code would hang

File: src/facade/dragonfly_connection.cc (hunk 1 above)
Comment (dranikpg) [reply src/facade/dragonfly_connection.cc:701]: I thought of just overriding Shutdown in the child - but there is a struct called the same. Request like the verb, not the noun
But lets use your suggestion

Comment (romange) [reply src/facade/dragonfly_connection.cc:701]: yeah, I misunderstood request.

File: tests/dragonfly/server_family_test.py (hunk 2 above)
Comment (romange) [reply tests/dragonfly/server_family_test.py:8]: ok. why would this hang btw? where does it block?

**Comment by romange** [comment]
LGTM

File: tests/dragonfly/server_family_test.py (hunk 2 above)
Comment (dranikpg) [reply tests/dragonfly/server_family_test.py:8]: In the last read response. Because this is low level, we can manually read the connection even if we don't expect anything. Without the fix, the connection is still open, so it waits

**Review by romange — APPROVED** [review]
