### PR TITLE
bug(server): global command stalls on server load with pipeline mode

### LINKED ISSUE #1797: High load of pipelined commands stalls global transactions
Try to establish replication between two instances while loading the master instance with `memtier_benchmark --pipeline=10`.

Effect:
```
I20230904 15:48:20.940745 80211 dflycmd.cc:574] Registered replica 127.0.0.1:6380
I20230904 15:48:21.036273 80213 dflycmd.cc:242] Got DFLY FLOW 10ebb040d7e3c038a277607030ac70059d0a17eb SYNC1 2
I20230904 15:48:21.036520 80214 dflycmd.cc:242] Got DFLY FLOW 10ebb040d7e3c038a277607030ac70059d0a17eb SYNC1 0
I20230904 15:48:21.039652 80212 dflycmd.cc:242] Got DFLY FLOW 10ebb040d7e3c038a277607030ac70059d0a17eb SYNC1 1
I20230904 15:48:21.048694 80211 dflycmd.cc:283] Got DFLY SYNC SYNC1
<-- Transaction guard cannot be scheduled while the pipelined commands are running -->
I20230904 15:48:27.723248 80211 dflycmd.cc:85] Transaction guard engaged
I20230904 15:48:27.727368 80211 dflycmd.cc:89] Releasing transaction guard
```

### PR DESCRIPTION
**Pull request by adiholden**
fixes #1797 
the bug: global command is not able to schedule into txq when high load pipelined commands. Only after the load finish the global transaction gets scheduled into the txq. The reason for this is when we start a global transaction we set the shard lock and all the transactions start to enter the txq. They compete with the global tx on the order they are inserted into the queue to preserve transaction atomicity. Because the global tx needs to be inserted to all shard queues its chance to schedule with order with all the other transactions is low. 
the solution: lock the global transaction inside the schedule in shard, locking closer to scheduling decreases the number of transactions in the queue and the competition on ordering correctly has higher chance now.

### CODE REVIEW

File: src/server/server_family.cc [hunk 1]
```diff
@@ -1400,6 +1401,7 @@ void ServerFamily::Info(CmdArgList args, ConnectionContext* cntx) {
     append("defrag_task_invocation_total", m.shard_stats.defrag_task_invocation_total);
     append("eval_io_coordination_total", m.eval_io_coordination_cnt);
     append("eval_shardlocal_coordination_total", m.eval_shardlocal_coordination_cnt);
+    append("cancle_tx_schedule", m.cancled_tx_schedule_cnt);
```
Comment (romange) [inline src/server/server_family.cc:1404]: `tx_schedule_cancel_total`

File: src/server/server_family.h [hunk 2]
```diff
@@ -67,6 +67,7 @@ struct Metrics {
   uint64_t ooo_tx_transaction_cnt = 0;
   uint64_t eval_io_coordination_cnt = 0;
   uint64_t eval_shardlocal_coordination_cnt = 0;
+  uint64_t cancled_tx_schedule_cnt = 0;
```
Comment (romange) [inline src/server/server_family.h:70]: cancled -> canceled

**Comment by romange** [comment]
I understand tx reordering approach did not work. Why?

**Comment by adiholden** [comment]
> I understand tx reordering approach did not work. Why?

1. I believe that we should be very careful with reordering , not just check that the tx is not ooo but did not start running yet, but maybe if it is in the queue this means it didnt start running as we remove from the queue when starting to run a transaction (continues transactions). So this needs more deep understanding of the flow of pulling from txq
2. There change for reordering is not so simple as this change as the queue is a vector and does not have the api for pushing in the middle of the queue. It is not that big of a dill but requires more changes. This PR is very small and simple and fixes this specific senario.
We can working on reordering but I need to go deeper in to the code of the polling to make sure I am not creating any bugs there.

**Review by romange — APPROVED** [review]
