### PR TITLE
fix(search): emit complete field params in FT.INFO and BuildRestoreCommand

### LINKED ISSUE #7013: FT.INFO omits vector field parameters in attributes
`FT.INFO` returns vector fields without their parameters (`algorithm`, `dim`, `data_type`, `distance_metric`, `M`, `ef_construction`).

Reproduce:

```
FT.CREATE test ON HASH PREFIX 1 doc: SCHEMA text TEXT embedding VECTOR HNSW 10 TYPE FLOAT32 DIM 4 DISTANCE_METRIC COSINE M 16 EF_CONSTRUCTION 200
FT.INFO test
```

DragonflyDB df-dev — attributes section:

```
1. identifier
2. embedding
3. attribute
4. embedding
5. type
6. VECTOR
```

Competitor - attributes section:

```
1. identifier
2. embedding
3. attribute
4. embedding
5. type
6. VECTOR
7. algorithm
8. HNSW
9. data_type
10. FLOAT32
11. dim
12. 4
13. distance_metric
14. COSINE
15. M
16. 16
17. ef_construction
18. 200
```

Impact:

`redisvl` uses `FT.INFO` to reconstruct the index schema in `SearchIndex.from_existing()`. Without vector parameters, the vector field is silently dropped from the schema.

This breaks `langchain-redis` `RedisVectorStore` with `from_existing=True` — any `similarity_search()` call raises `KeyError: 'embedding'`.

### PR DESCRIPTION
**Pull request by vyavdoshenko**
Fix FT.INFO to return complete field parameters and fix BuildRestoreCommand serialization issues.

Fixes #7013

- Problem 1: Parse and store `TYPE` (FLOAT32/FLOAT64/BFLOAT16) for VECTOR fields
- Problem 2: Emit all VECTOR params in FT.INFO (algorithm, data_type, dim, distance_metric, M, ef_construction)
- Problem 3: Emit TAG params in FT.INFO (SEPARATOR, CASESENSITIVE)
- Problem 4: Emit TEXT param in FT.INFO (WITHSUFFIXTRIE)
- Problem 5: Already fixed before
- Problem 6: Return `stopwords_list` as a top-level field in FT.INFO when explicitly configured
- Problem 7: Intentionally skipped - `default_score` is deprecated and unused by client libraries

Additionally, fixes two pre-existing bugs in BuildRestoreCommand:
- TEXT `WITH_SUFFIXTRIE` was serialized with the wrong name (underscore), silently dropped on restore
- TAG `WITHSUFFIXTRIE` was not serialized at all, lost on restore/replication

### CODE REVIEW

File: src/server/search/search_family.cc [hunk 1]
```diff
@@ -111,6 +111,8 @@ search::SchemaField::VectorParams ParseVectorParams(CmdArgParser* parser) {
     } else if (parser->Check("INITIAL_CAP", &params.capacity)) {
     } else if (parser->Check("M", &params.hnsw_m)) {
     } else if (parser->Check("EF_CONSTRUCTION", &params.hnsw_ef_construction)) {
+    } else if (parser->Check("TYPE")) {
+      params.data_type = absl::AsciiStrToUpper(parser->Next<string_view>());
```
Comment (dranikpg) [inline src/server/search/search_family.cc:117]: it's actually true, you will silently accept any datatype and act as if we support it, yet we support only float32

Comment (dranikpg) [reply src/server/search/search_family.cc:117]: it's misleading at least

File: src/server/search/search_family.cc [hunk 2]
```diff
@@ -1641,7 +1645,38 @@ void CmdFtInfo(CmdArgList args, CommandContext* cmd_cntx) {
...
-    if (field_info.type == search::SchemaField::NUMERIC) {
+    if (field_info.type == search::SchemaField::VECTOR) {
+      auto& vparams = std::get<search::SchemaField::VectorParams>(field_info.special_params);
+      info.emplace_back("algorithm");
+      info.emplace_back(vparams.use_hnsw ? "HNSW" : "FLAT");
+      info.emplace_back("data_type");
+      info.emplace_back(vparams.data_type);
+      info.emplace_back("dim");
+      info.emplace_back(std::to_string(vparams.dim));
+      info.emplace_back("distance_metric");
```
Comment (dranikpg) [inline src/server/search/search_family.cc:1681]: ah, I remember unifying this with the code above, so the function returns vector<string> and then the two callsites decide to either concatenate it or to put it out as an array like here, but not needed here

File: src/server/search/search_family.cc (hunk 1 above)
Comment (vyavdoshenko) [reply src/server/search/search_family.cc:117]: Yes, but we need this parameter to be saved to have the ability to recreate the index later from outside the dragonfly
