### PR TITLE
fix(server): Set lower timeouts for Replica::ConnectAndAuth()

### LINKED ISSUE #1032: Updating master on a replica causes errors
**Describe the bug**

When the master instance of a replica is terminated, and a command to update to the master
is issued. Sometimes, These commands seem to cause timeouts on the client along with the following
errors on the replica.

```
➜  dragonfly-operator git:(tar/resource-update) ✗ kubectl logs health-test-3
I20230403 07:30:32.091861     1 init.cc:56] dragonfly running in opt mode.
I20230403 07:30:32.091902     1 dfly_main.cc:476] Starting dragonfly df-v1.1.1-9b03b2cfd1499b987975698edb004acaf573ac9a
I20230403 07:30:32.091917     1 dfly_main.cc:499] maxmemory has not been specified. Deciding myself....
I20230403 07:30:32.091960     1 dfly_main.cc:504] Found 23.84GiB available memory. Setting maxmemory to 19.08GiB
I20230403 07:30:32.115703    14 proactor.cc:426] IORing with 1024 entries, allocated 102720 bytes, cq_entries is 2048
I20230403 07:30:32.131925     1 proactor_pool.cc:66] Running 12 io threads
I20230403 07:30:32.145551     1 server_family.cc:419] Data directory is "/data"
I20230403 07:30:32.145905    16 listener_interface.cc:96] sock[39] AcceptServer - listening on port 6379
I20230403 07:30:52.944465    16 replica.cc:563] Started full sync
I20230403 07:30:52.959640    16 replica.cc:582] Full sync finished in 58 ms
I20230403 07:30:52.959893    16 replica.cc:659] Transitioned into stable sync
I20230403 07:30:53.157919    16 replica.cc:678] Exit stable sync
W20230403 07:30:53.157953    16 replica.cc:249] Error full sync system:103 Software caused connection abort
E20230403 07:33:03.635744    16 replica.cc:209] Error connecting system:110
E20230403 07:33:03.756654    21 replica.cc:754] Bad FLOW response -ERR syncid not found
E20230403 07:33:03.756819    25 replica.cc:754] Bad FLOW response -ERR syncid not found
E20230403 07:33:03.756908    24 replica.cc:754] Bad FLOW response -ERR syncid not found
E20230403 07:33:03.757125    17 replica.cc:754] Bad FLOW response -ERR syncid not found
E20230403 07:33:03.757162    14 replica.cc:754] Bad FLOW response -ERR syncid not found
E20230403 07:33:03.757261    19 replica.cc:754] Bad FLOW response -ERR syncid not found
E20230403 07:33:03.757357    18 replica.cc:754] Bad FLOW response -ERR syncid not found
E20230403 07:33:03.757875    22 replica.cc:754] Bad FLOW response -ERR syncid not found
E20230403 07:33:03.758107    15 replica.cc:754] Bad FLOW response -ERR syncid not found
E20230403 07:33:03.758194    16 replica.cc:754] Bad FLOW response -ERR syncid not found
E20230403 07:33:03.759543    23 replica.cc:754] Bad FLOW response -ERR syncid not found
E20230403 07:33:03.759578    20 replica.cc:754] Bad FLOW response -ERR syncid not found
W20230403 07:33:03.759912    17 replica.cc:234] Error syncing generic:125 Operation canceled
W20230403 07:33:03.845757    19 replica.cc:234] Error syncing generic:125 Operation canceled
W20230403 07:33:03.933781    24 replica.cc:234] Error syncing generic:125 Operation canceled
I20230403 07:33:06.562381    20 dflycmd.cc:474] Registered replica 10.244.0.10:6379
I20230403 07:33:06.695430    21 dflycmd.cc:474] Registered replica 10.244.0.7:6379
I20230403 07:33:06.715792    20 dflycmd.cc:291] Started full sync with replica 10.244.0.10:6379
I20230403 07:33:06.733628    20 dflycmd.cc:330] Transitioned into stable sync with replica 10.244.0.10:6379
I20230403 07:33:06.796116    21 dflycmd.cc:291] Started full sync with replica 10.244.0.7:6379
I20230403 07:33:06.799985    21 dflycmd.cc:330] Transitioned into stable sync with replica 10.244.0.7:6379
I20230403 07:33:09.830744    20 dflycmd.cc:513] Disconnecting from replica 10.244.0.10:6379
```

**To Reproduce**
1. Insert records using `command`
2. Query records using `command`

**Expected behavior**
`replicaOf` commands should work as expected.

**Screenshots**

### PR DESCRIPTION
**Pull request by royjacobson**
Fix #1032 

The problem turned out to be that we call `Replica->Stop()` while holding the global replication mutex. The `Stop()` call was blocked because the previous replication fiber was trying to reconnect and it was stuck in the `ConnectAndAuth()` stage of the `MainReplicationFb` mainloop.

This kind of fixes the issue by setting timeouts for our replication sockets: 20 seconds for the initial connection and 1 second for any subsequent re-connection attempt. These timeouts can be configured with flags. So now the previous replica will stop faster and won't block the command for 2 minutes.

### CODE REVIEW

File: src/server/replica.cc [hunk 1]
```diff
@@ -286,11 +291,19 @@ error_code Replica::ResolveMasterDns() {
...
 }
 
-error_code Replica::ConnectAndAuth() {
+error_code Replica::ConnectAndAuth(std::chrono::milliseconds connect_timeout_ms) {
   ProactorBase* mythread = ProactorBase::me();
   CHECK(mythread);
   sock_.reset(mythread->CreateSocket());
-  RETURN_ON_ERR(sock_->Connect(master_context_.endpoint));
+
+  // We want a timeout for the initial connection because this stage might be blocking.
```
Comment (dranikpg) [inline src/server/replica.cc:299]: "Might be blocking" is not very specific, other parts block too 😅

**Review by dranikpg — APPROVED** [review]

**Review by dranikpg — APPROVED** [review]
