### PR TITLE
fix(sort): delete destination key when SORT STORE produces empty result

### LINKED ISSUE #7105: sigabrt in rdb_save.cc:273
[crash-000000.tar.gz](https://github.com/user-attachments/files/26615122/crash-000000.tar.gz)

[crash-000001.tar.gz](https://github.com/user-attachments/files/26615126/crash-000001.tar.gz)

```
./build/dragonfly --port 6379 --proactor_threads 1 --dbfilename=dump
```

```
python3 fuzz/replay_crash.py fuzz/artifacts/resp/default/crashes 000000 127.0.0.1 6379
```
or
```
python3 fuzz/replay_crash.py fuzz/artifacts/resp/default/crashes 000001 127.0.0.1 6379
```

```
F20260410 00:26:30.393450 72799 rdb_save.cc:273] SaveEntry skipped empty PrimeValue with key: $.arr[0] with tag 19
*** Check failure stack trace: ***
    @     0xaaaaacca6278  google::LogMessage::Fail()
    @     0xaaaaacca6180  google::LogMessage::SendToLog()
    @     0xaaaaacca5980  google::LogMessage::Flush()
    @     0xaaaaacca56b4  google::LogMessage::~LogMessage()
    @     0xaaaaac3a048c  dfly::RdbSerializer::SaveEntry()
    @     0xaaaaac436f58  _ZN4dfly13SliceSnapshot14SerializeEntryEmtRKNS_10CompactKeyERKNS_12CompactValueE.localalias
    @     0xaaaaac436b1c  dfly::SliceSnapshot::SerializeBucketLocked()
    @     0xaaaaac425000  dfly::SerializerBase::ProcessBucketInternal()
    @     0xaaaaac424d24  dfly::SerializerBase::ProcessBucket()
    @     0xaaaaac438304  _ZZN4dfly13SliceSnapshot16IterateBucketsFbEbENKUlT_E_clINS_9DashTableINS_10CompactKeyENS_12CompactValueENS_6detail16PrimeTablePolicyEE8IteratorILb0ELb1EEEEEDaS1_
    @     0xaaaaac438440  _ZN4dfly9DashTableINS_10CompactKeyENS_12CompactValueENS_6detail16PrimeTablePolicyEE15TraverseBucketsIZNS_13SliceSnapshot16IterateBucketsFbEbEUlT_E_EENS3_10DashCursorESA_OS8_
    @     0xaaaaac436110  dfly::SliceSnapshot::IterateBucketsFb()
    @     0xaaaaac4353c8  _ZZN4dfly13SliceSnapshot5StartEbNS0_13SnapshotFlushEENKUlvE_clEv
    @     0xaaaaac43a034  _ZSt13__invoke_implIvZN4dfly13SliceSnapshot5StartEbNS1_13SnapshotFlushEEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @     0xaaaaac439c7c  _ZSt8__invokeIZN4dfly13SliceSnapshot5StartEbNS1_13SnapshotFlushEEUlvE_JEENSt15__invoke_resultIT_JDpT0_EE4typeEOS5_DpOS6_
    @     0xaaaaac439778  _ZSt12__apply_implIZN4dfly13SliceSnapshot5StartEbNS1_13SnapshotFlushEEUlvE_St5tupleIJEEJEEDcOT_OT0_St16integer_sequenceImJXspT1_EEE
    @     0xaaaaac4397bc  _ZSt5applyIZN4dfly13SliceSnapshot5StartEbNS1_13SnapshotFlushEEUlvE_St5tupleIJEEEDcOT_OT0_
    @     0xaaaaac43983c  _ZN4util3fb26detail15WorkerFiberImplIZN4dfly13SliceSnapshot5StartEbNS4_13SnapshotFlushEEUlvE_JEE4run_EON5boost7context5fiberE
    @     0xaaaaac438fe4  _ZZN4util3fb26detail15WorkerFiberImplIZN4dfly13SliceSnapshot5StartEbNS4_13SnapshotFlushEEUlvE_JEEC4INS0_19FixedStackAllocatorEEESt17basic_string_viewIcSt11char_traitsIcEENS0_13FiberPriorityERKN5boost7context12preallocatedEOT_OS6_ENKUlONSG_5fiberEE_clESO_
    @     0xaaaaac43aac0  _ZSt13__invoke_implIN5boost7context5fiberERZN4util3fb26detail15WorkerFiberImplIZN4dfly13SliceSnapshot5StartEbNS8_13SnapshotFlushEEUlvE_JEEC4INS4_19FixedStackAllocatorEEESt17basic_string_viewIcSt11char_traitsIcEENS4_13FiberPriorityERKNS1_12preallocatedEOT_OSA_EUlOS2_E_JS2_EESM_St14__invoke_otherOT0_DpOT1_
    @     0xaaaaac43a888  _ZSt8__invokeIRZN4util3fb26detail15WorkerFiberImplIZN4dfly13SliceSnapshot5StartEbNS5_13SnapshotFlushEEUlvE_JEEC4INS1_19FixedStackAllocatorEEESt17basic_string_viewIcSt11char_traitsIcEENS1_13FiberPriorityERKN5boost7context12preallocatedEOT_OS7_EUlONSH_5fiberEE_JSO_EENSt15__invoke_resultISL_JDpT0_EE4typeESM_DpOST_
    @     0xaaaaac43a6f4  _ZSt6invokeIRZN4util3fb26detail15WorkerFiberImplIZN4dfly13SliceSnapshot5StartEbNS5_13SnapshotFlushEEUlvE_JEEC4INS1_19FixedStackAllocatorEEESt17basic_string_viewIcSt11char_traitsIcEENS1_13FiberPriorityERKN5boost7context12preallocatedEOT_OS7_EUlONSH_5fiberEE_JSO_EENSt13invoke_resultISL_JDpT0_EE4typeESM_DpOST_
    @     0xaaaaac43a448  _ZN5boost7context6detail12fiber_recordINS0_5fiberEN4util3fb219FixedStackAllocatorEZNS5_6detail15WorkerFiberImplIZN4dfly13SliceSnapshot5StartEbNSA_13SnapshotFlushEEUlvE_JEEC4IS6_EESt17basic_string_viewIcSt11char_traitsIcEENS5_13FiberPriorityERKNS0_12preallocatedEOT_OSC_EUlOS3_E_E3runEPv
    @     0xaaaaac43a128  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberEN4util3fb219FixedStackAllocatorEZNS6_6detail15WorkerFiberImplIZN4dfly13SliceSnapshot5StartEbNSB_13SnapshotFlushEEUlvE_JEEC4IS7_EESt17basic_string_viewIcSt11char_traitsIcEENS6_13FiberPriorityERKNS0_12preallocatedEOT_OSD_EUlOS4_E_EEEEvNS1_10transfer_tE
    @     0xfffff7f90a40  make_fcontext
    @     0xfffff7f90a40  make_fcontext
*** SIGABRT received at time=1775769990 on cpu 0 ***
PC: @     0xfffff7537608  (unknown)  (unknown)
    @     0xaaaaacd08f14         64  absl::lts_20250512::WriteFailureInfo()
    @     0xaaaaacd0922c         96  absl::lts_20250512::AbslFailureSignalHandler()
    @     0xfffff7ffa7d0       4752  (unknown)
    @     0xfffff74ecb3c         64  raise
    @     0xfffff74d7e00        192  abort
    @     0xaaaaaccb1790        208  google::DumpStackTraceAndExit()
    @     0xaaaaacca6278         16  google::LogMessage::Fail()
    @     0xaaaaacca6180        144  google::LogMessage::SendToLog()
    @     0xaaaaacca5980         80  google::LogMessage::Flush()
    @     0xaaaaacca56b4         32  google::LogMessage::~LogMessage()
    @     0xaaaaac3a048c        288  dfly::RdbSerializer::SaveEntry()
    @     0xaaaaac436f58        288  dfly::SliceSnapshot::SerializeEntry()
    @     0xaaaaac436b1c        208  dfly::SliceSnapshot::SerializeBucketLocked()
    @     0xaaaaac425000        320  dfly::SerializerBase::ProcessBucketInternal()
    @     0xaaaaac424d24         96  dfly::SerializerBase::ProcessBucket()
    @     0xaaaaac438304         32  dfly::SliceSnapshot::IterateBucketsFb()::{lambda()#1}::operator()<>()
    @     0xaaaaac438440         48  dfly::DashTable<>::TraverseBuckets<>()
    @     0xaaaaac436110        304  dfly::SliceSnapshot::IterateBucketsFb()
    @     0xaaaaac4353c8        208  dfly::SliceSnapshot::Start()::{lambda()#1}::operator()()
    @     0xaaaaac43a034         48  std::__invoke_impl<>()
    @     0xaaaaac439c7c         32  std::__invoke<>()
    @     0xaaaaac439778         48  std::__apply_impl<>()
    @     0xaaaaac4397bc         48  std::apply<>()
    @     0xaaaaac43983c         96  util::fb2::detail::WorkerFiberImpl<>::run_()
    @     0xaaaaac438fe4         64  util::fb2::detail::WorkerFiberImpl<>::WorkerFiberImpl<>()::{lambda()#1}::operator()()
    @     0xaaaaac43aac0         80  std::__invoke_impl<>()
    @     0xaaaaac43a888         64  std::__invoke<>()
    @     0xaaaaac43a6f4         80  std::invoke<>()
    @     0xaaaaac43a448         80  boost::context::detail::fiber_record<>::run()
    @     0xaaaaac43a128         32  boost::context::detail::fiber_entry<>()
```

### PR DESCRIPTION
**Pull request by vyavdoshenko**
- SORT ... STORE with an empty result (e.g. LIMIT offset beyond list size) stored an empty QList in the database instead of deleting the destination key
- Empty OBJ_LIST with ROBJ_TAG is not allowed by `TagAllowsEmptyValue()`, so SAVE/BGSAVE crashed with DFATAL in `RdbSerializer::SaveEntry()`
- Now `OpStore` checks for empty result: frees the QList and deletes the destination key

Fixes #7105

### CODE REVIEW

File: src/server/generic_family.cc [hunk 1]
```diff
@@ -1725,6 +1725,15 @@ OpResult<uint32_t> OpStore(const OpArgs& op_args, std::string_view key, Iterator
   }
   len = ql_v2->Size();
 
+  if (len == 0) {
+    CompactObj::DeleteMR<QList>(ql_v2);
+    auto it_res = op_args.GetDbSlice().FindMutable(op_args.db_cntx, key);
+    if (IsValid(it_res.it)) {
+      op_args.GetDbSlice().DelMutable(op_args.db_cntx, std::move(it_res));
```
Comment (BorysTheDev) [inline src/server/generic_family.cc:1732]: it is strange to me to move the iterator

**Review by BorysTheDev — APPROVED** [review]
