### PR TITLE
fix: fix expiration processing for set command

### LINKED ISSUE #3418: memcache mode does not accept unix timestamp
**Describe the bug**
The memcache protocol support specifying the expiration time in unix timestamp format:
https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L139
The Dragonfly accepts unix timestamp as seconds of expiration.

**To Reproduce**
<details>
  <summary>Dockerfile</summary>

```Dockerfile
FROM php:7.4
RUN apt-get -qq update && apt-get -qq --yes install libmemcached-dev zlib1g-dev \
    && pecl channel-update pecl.php.net \
    && pecl install memcached \
    && docker-php-ext-enable memcached
```
</details>
<details>
  <summary>compose.yaml</summary>

```yaml
services:
  php:
    build:
      context: .
    tty: true
    volumes:
      - ./test.php:/test.php
  memcached:
    image: memcached:latest
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.20.1
    ulimits:
      memlock: -1
    command: [
      "--max_log_size=20",
      "--memcached_port=11211",
      "--maxmemory=1gb",
      "--cache_mode=true",
      "--alsologtostderr=true",
      "--dbnum=1",
      "--proactor_threads=1"
    ]
```
</details>
<details>
  <summary>test.php</summary>

```php
<?php

$memcached = new Memcached();
$memcached->addServers([['host' => 'memcached','port' => '11211',]]);

$dragonfly = new Memcached();
$dragonfly->addServers([['host' => 'dragonfly','port' => '11211',]]);

echo "memcached set " . time() . " +10s\n";
$memcached->set('key', time() + 10, time() + 10);

echo "dragonfly set " . time() . " +10s\n";
$dragonfly->set('key', time() + 10, time() + 10);

sleep(9);
echo "\nAfter 9 seconds\n";
echo 'memcached ' . $memcached->get('key') . "\n";
echo 'dragonfly ' . $dragonfly->get('key') . "\n";

sleep(2);
echo "\nAfter 11 seconds\n";
echo 'memcached ' . $memcached->get('key') . "\n";
echo 'dragonfly ' . $dragonfly->get('key') . "\n";
```
</details>

```bash
docker compose up --detach --build
docker compose exec php php test.php
```

**Expected behavior**
The key expires after the unix timestamp.

**Additional context**
```
memcached set 1722444217 +10s
dragonfly set 1722444217 +10s

After 9 seconds
memcached 1722444227
dragonfly 1722444227

After 11 seconds
memcached
dragonfly 1722444227
```

### PR DESCRIPTION
**Pull request by BorysTheDev**
fix #3418 
fix a corner case when SET is applied with an already expired timestamp: if the key already exists it will be removed

### CODE REVIEW

File: src/server/string_family.cc [hunk 1]
```diff
@@ -787,9 +787,19 @@ void StringFamily::Set(CmdArgList args, ConnectionContext* cntx) {
       if (abs_ms < 0)
         return cntx->SendError(InvalidExpireTime("set"));
 
-      // Redis reports just OK in this case
-      if (rel_ms < 0)
+      // Remove existed key if the key is expired already
+      if (rel_ms < 0) {
+        cntx->transaction->ScheduleSingleHop([key](const Transaction* tx, EngineShard* es) {
```
Comment (kostasrim) [inline src/server/string_family.cc:792]: This is also a bug in redis `SET` (because as you noticed there could be the case that an object already exists without expiry and it won't be deleted). However, (I think) we might be able to skip this code and fall back `SetGeneric(cntx, sparams, key, value);` because it should be able to handle already expired values. If it doesn't then it might make sense to to handle this case there instead and not (explicitly) here?

Comment (BorysTheDev) [reply src/server/string_family.cc:792]: In redis if key is exist without expiration and you set with expired time the key will be deleted

File: src/facade/memcache_parser.cc [hunk 2]
```diff
@@ -38,6 +38,15 @@ MP::CmdType From(string_view token) {
 
 using TokensView = absl::Span<std::string_view>;
 
+bool TokenToExpireTs(std::string_view token, std::uint32_t* expire_ts) {
+  static constexpr uint32_t month = 60 * 60 * 24 * 30;
```
Comment (romange) [inline src/facade/memcache_parser.cc:42]: pls remove  static and rename to `kExpireLimit`. The limit is according to their documentation?

File: src/facade/memcache_parser.cc [hunk 3]
```diff
@@ -38,6 +38,15 @@ MP::CmdType From(string_view token) {
...
+  auto res = absl::SimpleAtoi(token, expire_ts);
+  if (res && (*expire_ts <= month)) {
+    *expire_ts += time(nullptr);
```
Comment (romange) [inline src/facade/memcache_parser.cc:45]: if token is beyond the limit, do we you still want to return success?
seems like a bug because you will return a relative number and return success

File: src/facade/memcache_parser.h [hunk 4]
```diff
@@ -52,7 +52,7 @@ class MemcacheParser {
       uint64_t delta;           // for DECR/INCR commands.
     };
 
-    uint32_t expire_ts = 0;  // relative time in seconds.
+    uint32_t expire_ts = 0;  // unix time in seconds.
```
Comment (romange) [inline src/facade/memcache_parser.h:55]: if it's unit time in seconds, should it still be uint32_t?

File: src/facade/memcache_parser_test.cc [hunk 5]
```diff
@@ -30,7 +30,7 @@ TEST_F(MCParserTest, Basic) {
   EXPECT_EQ(MemcacheParser::OK, st);
   EXPECT_EQ("a", cmd_.key);
   EXPECT_EQ(1, cmd_.flags);
-  EXPECT_EQ(20, cmd_.expire_ts);
```
Comment (romange) [inline src/facade/memcache_parser_test.cc:33]: that's flaky. you count that the command and the check run in the same second.

File: src/facade/memcache_parser.cc (hunk 3 above)
Comment (romange) [reply src/facade/memcache_parser.cc:45]: I also do not understand why to add current time in the parser. why not keep the relative time and make the adjustment at later time during the command processing.

File: src/facade/memcache_parser.h (hunk 4 above)
Comment (romange) [reply src/facade/memcache_parser.h:55]: why do you need to do this here? what's the exact command that demands this?

File: src/facade/memcache_parser.cc (hunk 2 above)
Comment (kostasrim) [reply src/facade/memcache_parser.cc:42]: Yes see https://www.php.net/manual/en/memcached.expiration.php

Maybe it's also worth adding a comment :)

File: src/facade/memcache_parser.cc (hunk 3 above)
Comment (kostasrim) [reply src/facade/memcache_parser.cc:45]: He is converting it to unix time since epoch if it's less than a month in seconds. See my other comment

File: src/server/string_family.cc (hunk 1 above)
Comment (kostasrim) [reply src/server/string_family.cc:792]: That's what I am saying. But instead of issuing a single hop that deletes the key here you can really in the operation below. That way you have a single path of execution that handles all the cases

File: src/facade/memcache_parser.cc (hunk 2 above)
Comment (romange) [reply src/facade/memcache_parser.cc:42]: definitely worth adding the link and the comment. I still think we should not add time_now inside parser.

Comment (kostasrim) [reply src/facade/memcache_parser.cc:42]: I agree, also I wanted to add the same comment (to include the link) but somehow I messed this up :(

File: src/facade/memcache_parser.cc [hunk 6]
```diff
@@ -118,6 +118,13 @@ MP::Result ParseValueless(TokensView tokens, MP::Command* res) {
 
 }  // namespace
 
+uint32_t MemcacheParser::Command::ExpireTsToUnixTime() const {
```
Comment (romange) [inline src/facade/memcache_parser.cc:121]: please make it `uint64_t`

File: src/server/main_service.cc [hunk 7]
```diff
@@ -1566,9 +1566,10 @@ void Service::DispatchMC(const MemcacheParser::Command& cmd, std::string_view va
       args.emplace_back(store_opt, strlen(store_opt));
     }
 
-    if (cmd.expire_ts && memcmp(cmd_name, "SET", 3) == 0) {
-      char* next = absl::numbers_internal::FastIntToBuffer(cmd.expire_ts, ttl);
-      args.emplace_back(ttl_op, 2);
+    const uint32_t expire_ts = cmd.ExpireTsToUnixTime();
```
Comment (romange) [inline src/server/main_service.cc:1569]: uint64_t

File: src/facade/memcache_parser.cc (hunk 6 above)
Comment (BorysTheDev) [reply src/facade/memcache_parser.cc:121]: in documentation it;s uint32 but ok

File: src/server/string_family.cc (hunk 1 above)
Comment (romange) [reply src/server/string_family.cc:792]: this code should not be here. Again, lets not confuse parsing and execution.
For redis SET command, there are other options like NX, XX that affect how the command is executed. For example, with NX and past time, I assume it should be a NOOP.  Therefore, I think you should move the logic into SetCmd code.

Comment (romange) [reply src/server/string_family.cc:792]: Also, to reduce code duplication, I suggest that you expose OpDel in generic_family.h similarly to how we expose OpExists there.

Comment (BorysTheDev) [reply src/server/string_family.cc:793]: I can not move this logic into setcmd code because we generate a SET command and after that execute it as Redis command

Comment (romange) [reply src/server/string_family.cc:793]: I am not sure I understand why it can not be moved to SetCmd code.
you generate `SET key val EXAT ...` for memcached flow. It will be executed inside SetCmd code. The same is true for the Redis SET command.

**Review by romange — APPROVED** [review]

File: src/server/string_family.cc (hunk 1 above)
Comment (BorysTheDev) [reply src/server/string_family.cc:793]: I need to calculate is it relative or unit time before I create SET command and after that it will be executed as SetCmd

Comment (kostasrim) [reply src/server/string_family.cc:793]: @romange what if we call SetCmd with a timevalue that is already expired? My suggestion is to handle this operation in db_slice (I am not sure what happens if you call AddOrFind with a value that is already expired but it's worth checking). In other words my idea is, when you try to insert an expired value you just deleted. That way the flow above in SetCmd remains the same. 

Also I agree with @romange we should have one flow, and do not execute the Hop here (that's what I meant in my OG comment above)

Comment (BorysTheDev) [reply src/server/string_family.cc:793]: We can make a separate fix, for all SET family commands because there will be more changes and it's 2 different tasks

Comment (kostasrim) [reply src/server/string_family.cc:793]: Well it's already merged so it's a separate task anyway, I am just thinking out loud
