### PR TITLE
fix(cluster): Support `FLUSHALL` while slot migration is in progress

### LINKED ISSUE #3132: FLUSHALL during slot migration causes assert failure
```cpp
auto DashTable<_Key, _Value, Policy>::Traverse(Cursor curs, Cb&& cb) -> Cursor {
  ...

  // We fix bid and go over all segments. Once we reach the end we increase bid and repeat.
  do {
    SegmentType* s = segment_[sid];
    assert(s);
```

Open questions:
1. Should we forbid running FLUSHALL when a migration takes place?
2. Could this `assert` happen also in other flows / scenarios?

### PR DESCRIPTION
**Pull request by chakaz**
Fixes #3132

Also do a small refactor to move cancellation logic into `RestoreStreamer`.

### CODE REVIEW

File: src/server/journal/streamer.cc [hunk 1]
```diff
@@ -244,14 +249,21 @@ RestoreStreamer::~RestoreStreamer() {
...
+  fiber_cancelled_ = true;
   if (sver != 0) {
-    fiber_cancelled_ = true;
     db_slice_->UnregisterOnChange(sver);
     JournalStreamer::Cancel();
   }
 }
 
 bool RestoreStreamer::ShouldWrite(const journal::JournalItem& item) const {
+  if (item.cmd == "FLUSHALL" || item.cmd == "FLUSHDB") {
```
Comment (BorysTheDev) [inline src/server/journal/streamer.cc:260]: it's not only about flushALL and flushDB. We have several more global commands. You can find a list in TransactionData::IsGlobalCmd()

Comment (chakaz) [reply src/server/journal/streamer.cc:260]: We have special handling for `FLUSH*` commands in replication as well, because these are the only commands which actually drop a db table.
Generally speaking, global commands are not supposed to be sent via migration, and so it wouldn't make sense to break a connection when we get them (it's even worse, as `DFLYCLUSTER` is one of those commands, so an attempt to even query the status of a migration will kill it..)

File: src/server/cluster/outgoing_slot_migration.cc [hunk 2]
```diff
@@ -126,11 +126,21 @@ MigrationState OutgoingMigration::GetState() const {
   return state_;
 }
 
+void OutgoingMigration::ClearSlotRanges() {
+  shard_set->pool()->AwaitFiberOnAll([this](util::ProactorBase* pb) {
+    if (auto* shard = EngineShard::tlocal(); shard) {
+      shard->db_slice().FlushSlots(GetSlots());
```
Comment (BorysTheDev) [inline src/server/cluster/outgoing_slot_migration.cc:132]: why do we do flushslot for outgoing migration, but not for incoming?

Comment (chakaz) [reply src/server/cluster/outgoing_slot_migration.cc]: that's just me being incompetent :( please ignore, thanks

Comment (kostasrim) [reply src/server/cluster/outgoing_slot_migration.cc]: @chakaz you are so far away from `incompetent`....

File: src/server/journal/streamer.cc [hunk 3]
```diff
@@ -244,14 +249,21 @@ RestoreStreamer::~RestoreStreamer() {
...
+    // On FLUSH* we restart the migration
+    CHECK(dest_ != nullptr);
+    dest_->Shutdown(SHUT_RDWR);
```
Comment (BorysTheDev) [inline src/server/journal/streamer.cc:263]: I think we need another mechanism to stop migration. because we could have sent already FIN so we get data race in this case

File: src/server/journal/streamer.cc [hunk 4]
```diff
@@ -188,9 +188,14 @@ RestoreStreamer::RestoreStreamer(DbSlice* slice, cluster::SlotSet slots, journal
                                  Context* cntx)
     : JournalStreamer(journal, cntx), db_slice_(slice), my_slots_(std::move(slots)) {
   DCHECK(slice != nullptr);
+  db_array_ = slice->databases();  // Inc ref to make sure DB isn't deleted while we use it
 }
 
 void RestoreStreamer::Start(io::AsyncSink* dest, bool send_lsn) {
+  dest_ = static_cast<util::FiberSocketBase*>(dest);
```
[the remark this answers is not in the document]
Comment (chakaz) [reply src/server/journal/streamer.cc:195]: I'd want a non-down cast as well. The challenge is that if we do that, we can't override `Start()` (base class uses a sink)

[the remark this answers is not in the document]
Comment (BorysTheDev) [reply src/server/journal/streamer.cc:195]: we can provide another method, I don't see any point to repeat interface

File: src/server/journal/streamer.cc (hunk 3 above)
Comment (chakaz) [reply src/server/journal/streamer.cc:263]: I think that the use case of supporting a FLUSHALL done right with a migration finalization is not really interesting. As long as it doesn't crash - we're in a good place, consistency is pretty much bonus points
having said that, what other mechanism do you have in mind?

File: src/server/journal/streamer.cc (hunk 4 above)
[the remark this answers is not in the document]
Comment (chakaz) [reply src/server/journal/streamer.cc]: turns out we can just replace the whole interface (including parent) to use sockets, so problem solved :)

File: src/server/journal/streamer.cc (hunk 3 above)
Comment (BorysTheDev) [reply src/server/journal/streamer.cc:263]: I think we need to provide context into restore_streamer and set error there, and set handler for error that stop migration

**Comment by chakaz** [comment]
@BorysTheDev ready for your review :pray:

**Review by BorysTheDev — APPROVED** [review]
