### PR TITLE
fix: test_replicaof_reject_on_load crash on stop

### LINKED ISSUE #2769: replication_test.py::test_replicaof_reject_on_load crash on stop
(venv) ➜  ~/dragonflydb/dragonfly/tests git:(main) ✗  pytest -xvs  dragonfly/replication_test.py::test_replicaof_reject_on_load
============================================================================================================ test session starts =============================================================================================================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.0.0 -- /home/adi/venv/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.10.12', 'Platform': 'Linux-5.15.0-97-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.1.2', 'pluggy': '1.0.0'}, 'Plugins': {'metadata': '2.0.4', 'icdiff': '0.8', 'repeat': '0.9.1', 'json-report': '1.5.0', 'asyncio': '0.20.1', 'emoji': '0.2.0'}}
rootdir: /home/adi/dragonflydb/dragonfly/tests, configfile: pytest.ini
plugins: metadata-2.0.4, icdiff-0.8, repeat-0.9.1, json-report-1.5.0, asyncio-0.20.1, emoji-0.2.0
asyncio: mode=auto
collected 1 item                                                                                                                                                                                                                             

dragonfly/replication_test.py::test_replicaof_reject_on_load[df_seeder_factory0-df_factory0] --- Random seed: 465895612481113714, check: 20 ---

--------------------------------------------------------------------------------------------------------------- live log call ----------------------------------------------------------------------------------------------------------------
[2024-03-25 11:57:38.431 DEBUG] Starting instance with arguments --dbfilename= --jsonpathv2 --maxmemory=8G --vmodule=dragonfly_connection=1,accept_server=1,listener_interface=1,main_service=1,rdb_save=1,replica=1,cluster_family=1 --port=-1 --num_shards=15 from /home/adi/dragonflydb/dragonfly/build-dbg/dragonfly
[2024-03-25 11:57:38.432 DEBUG] Starting instance with arguments --dbfilename=dump_hxCQbjfJwl --jsonpathv2 --maxmemory=8G --vmodule=dragonfly_connection=1,accept_server=1,listener_interface=1,main_service=1,rdb_save=1,replica=1,cluster_family=1 --port=-1 --num_shards=15 from /home/adi/dragonflydb/dragonfly/build-dbg/dragonfly
[2024-03-25 11:57:38.606 DEBUG] Process started after 0.17 seconds. port=34937
[2024-03-25 11:57:38.614 DEBUG] Process started after 0.00 seconds. port=46723
[2024-03-25 11:57:38.616 DEBUG] Running ops:None deviation:0.1
...............................................................................................................................................................................................................................................................................
cpu time 0.6193568706512451 batches 271 commands 27100
[2024-03-25 11:57:40.248 DEBUG] Filling took: 1.6325626373291016, QPS: 16599.67
[2024-03-25 11:57:40.254 DEBUG] Stopping instance on 46723
[2024-03-25 11:57:40.300 DEBUG] Starting instance with arguments --dbfilename=dump_hxCQbjfJwl --jsonpathv2 --maxmemory=8G --vmodule=dragonfly_connection=1,accept_server=1,listener_interface=1,main_service=1,rdb_save=1,replica=1,cluster_family=1 --port=-1 --num_shards=15 from /home/adi/dragonflydb/dragonfly/build-dbg/dragonfly
[2024-03-25 11:57:40.428 DEBUG] Process started after 0.12 seconds. port=38489
WWWW[2024-03-25 11:57:40.489 DEBUG] Stopping instance on 34937
38489➜ 11:57:40.500000 2465479 protocol_client.cc:284] Socket error system:103
38489➜ 11:57:40.500003 2465480 protocol_client.cc:284] Socket error system:103
38489➜ 11:57:40.500025 2465486 protocol_client.cc:284] Socket error system:103
38489➜ 11:57:40.500031 2465484 protocol_client.cc:284] Socket error system:103
38489➜ 11:57:40.500046 2465490 protocol_client.cc:284] Socket error system:103
38489➜ 11:57:40.500031 2465492 protocol_client.cc:284] Socket error system:103
38489➜ 11:57:40.500059 2465491 protocol_client.cc:284] Socket error system:103
38489➜ 11:57:40.500135 2465489 protocol_client.cc:284] Socket error system:103
34937➜    @     0x5620a8b41411  google::LogMessage    @     0x5620a8b4    @     0x5620a8b    @     0x5620a8614a88  facade::Connection::Migrate()
34937➜    @     0x5620a82ee18d  dfly::DflyCmd::Run()
34937➜    @     0x5620a8060d0d  dfly::ServerFamily::Dfly()
34937➜    @     0x5620a8048b38  _ZZN4dfly12_GLOBA    @     0x5620a808    @     0x5620a807b69e     @     0x5620a846    @     0x5620a8    @     0x5620a846    @     0x5620a845d819    @     0x5620a7    @     0x5620a8618ac1  _ZSt8__invokeIRKZN6facade10Connection10ParseRedis    @     0x5620a8618356  _ZSt6invokeIRKZN6facade10Connection10ParseRedisEPNS0_16SinkReplyBuilderEEUlvE_JEENSt13invoke_resultIT_JDpT0_EE4typeEOS8_DpOS9_
34937➜    @     0x5620a8617962  _ZN4absl12lts_2023080219functional_internal12InvokeObjectIZN6facade10Connection10ParseRedisEPNS3_16SinkReplyBuilderEEUlvE_vJEEET0_NS1_7VoidPtrEDpNS1_8ForwardTIT1_E4typeE
34937➜    @     0x5620a861bf95  absl::lts_20230802::FunctionRef<>::operator()()
34937➜    @     0x5620a8610d56  facade::Connection::DispatchCommand()
34937➜    @     0x5620a86112ce  facade::Connection::ParseRedis()
34937➜    @     0x5620a860ffaf  facade::Connection::ConnectionFlow()
34937➜    @     0x5620a8aae696  util::ListenerInterface::RunSingleConnection()
34937➜    @     0x5620a8aacd32  _ZZZN4util17ListenerInterface13Ru    @     0x5620a8ab33d2  _ZSt13__invoke_implIvZZN4util17ListenerInterfa    @        @  PC: @      @     0x562    @     0x56    @   [2024-03-25 11:57:40.726 DEBUG] Stopping instance on 38489

### PR DESCRIPTION
**Pull request by kostasrim**
resolves #2769

The problem is that we are shutting down master. During this flow, we iterate and shutdown all of the listeners and then we give a chance for the currently executing commands to finish with `DispatchTracker`. However, this is problematic, because internally it traverses all of the connections in all shards and sends `SendCheckPoint` messages. When this happens, it forces the connection that handles the replica to activate its `dispatch_fiber_`.  If this happens before we `Migrate` the connection in the replication flow (dflycmd) then we will trigger the CHECK that asserts that the dispatch_fiber is not actve (it was never launched). 

Unfortunately this is based on timing and therefore it requires two things:

1. Migrate might fail if `dispatch_fiber` is active. In that case do no crash but return false to indicate that the migration was not successful. 
2. After we migrate, we might find ourselves with the socket closed (because of the shutdown signal process/flow). We need to check that the socket is open. If it's not, it means that it was shutdown by the signal flow (because after we finish with DispatchTracker, we start iterating over all of the connections in all of the shards and shut them down.

### CODE REVIEW

**Comment by kostasrim** [comment]
@adiholden I did not supply a fix for pytests and the crashed instance. We need to think about this because `proc.kill()` && `proc.terminate()` do not return a value so we need another chore. I will fix this in a separate PR and I created an issue here: #2819

File: src/facade/dragonfly_connection.cc [hunk 1]
```diff
@@ -1418,15 +1418,23 @@ void Connection::ShutdownSelf() {
...
+bool Connection::Migrate(util::fb2::ProactorBase* dest) {
   // Migrate is used only by replication, so it doesn't have properties of full-fledged
   // connections
   CHECK(!cc_->async_dispatch);
-  CHECK_EQ(cc_->subscriptions, 0);    // are bound to thread local caches
-  CHECK_EQ(self_.use_count(), 1u);    // references cache our thread and backpressure
-  CHECK(!dispatch_fb_.IsJoinable());  // can't move once it started
+  CHECK_EQ(cc_->subscriptions, 0);  // are bound to thread local caches
+  CHECK_EQ(self_.use_count(), 1u);  // references cache our thread and backpressure
+  if (dispatch_fb_.IsJoinable()) {  // can't move once it started
```
Comment (adiholden) [inline src/facade/dragonfly_connection.cc:1427]: what is triggering the dispatch_fb_ creation on shutdown?

Comment (kostasrim) [reply src/facade/dragonfly_connection.cc:1427]: This https://github.com/dragonflydb/dragonfly/blob/main/src/facade/dragonfly_listener.cc#L301 which calls `SendCheckpoint`. See also: https://github.com/dragonflydb/dragonfly/blob/main/src/facade/dragonfly_listener.cc#L301 and https://github.com/dragonflydb/dragonfly/blob/main/src/facade/dragonfly_listener.cc#L455 

Moreover, this is what I was telling you about migrations. In this flow, we migrate and it happens that the traversal fiber happens before the migration and so when we migrate the dispatch fiber is already started. Now, if we remove this check and cancel the migration, it could also be the case that another fiber run which killed the socket (after PreShutdown and DispatchTracker) and I have seen this being triggered and that's why I checked for the socket to be active. 

Of course, it could be the case that traversal happened `after migration` but before the connection is relinked to the thread local and in that case we would probably deadlock or loose some important message being send from the traversal.

**Review by adiholden — APPROVED** [review]

**Comment by adiholden** [comment]
@kostasrim can you merge this?
