### PR TITLE
fix(reply_builder): Flush if last message didn't reply and flush but supose to

### LINKED ISSUE #5139: PUBSUB Messages Sent As Command Replies
**Describe the bug**
We are running into situations where we are seeing pubsub messages being sent to a client as a reply to a command, which of course it has no knowledge of cause errors to be thrown and the parent process to crash

#### Normal Case

```txl
--- 
COMMAND FOUND

LAST COMMAND:  {
  command: Command {
    name: 'unsubscribe',
    inTransaction: false,
    isResolved: false,
    transformed: true,
    replyEncoding: 'utf8',
    errorStack: undefined,
    args: [ 'auth-provider-service' ],
    callback: undefined,
    resolve: [Function (anonymous)],
    reject: [Function (anonymous)],
    promise: Promise {
      <pending>,
      [Symbol(async_id_symbol)]: 35633,
      [Symbol(trigger_async_id_symbol)]: 35578
    }
  },
  stream: undefined,
  select: 0
}

CURRENT REPLY unsubscribe,auth-provider-service,0
---
```

#### Error Case

```txl

--- 
NO Command Found

LAST Command:  {
  command: Command {
    name: 'unsubscribe',
    inTransaction: false,
    isResolved: true,
    transformed: true,
    replyEncoding: 'utf8',
    errorStack: undefined,
    args: [ 'auth-provider-service' ],
    callback: undefined,
    resolve: [Function (anonymous)],
    reject: [Function (anonymous)],
    promise: Promise {
      0,
      [Symbol(async_id_symbol)]: 9614,
      [Symbol(trigger_async_id_symbol)]: 9559
    }
  },
  stream: undefined,
  select: 0
}

CURRENT REPLY message,auth-provider-service,["cache_purge","682618652697514c436c5b61:AuthUser:auth-provider-service:0", "_id":"682618652697514c436c5b61","email":"novella.okuneva@yahoo.com","externalids":],"password":"5Kraig97","salt":"404b3dbdc6","permissionsMeta":[],"enterprise_permissions":[],"enterprise_ids":[],"enterprise_member":[],"groups":[],"firstname":"Robert","lastname":"Cremin","accounts":["a3e5c12368"],"ip":"225.908.218.3","ua":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36","isbanned":false,"otp":{"backupCodes":[]},"deactivated":[],"auth_roles":[],"auth_permissions":[],"_created":"2025-05-15T16:37:57.220Z","_modified":"2025-05-15T16:37:57.220Z","__v":0,"user_id":"682618652697514c436c5b61","roles":[],"permissions":[],"pk":"682618652697514c436c5b61","type":"user","id":"682618652697514c436c5b61"}]
---
```

**To Reproduce**
We haven't been able to reproduce this in small or isolated setups. It happens in our larger applications and integration test.
It seems to be fairly consistent during our shutdown routines that will unsubscribe from a channel before issuing a `QUIT` command. The `quit` and `unsubscribe` are the only commands that show up in these errors

**Expected behavior**
PubSub messages should not be sent as replies to normal commands

**Environment (please complete the following information):**
 - OS: Arch Linux 
 - Kernel: `Linux 5.10.235-1-MANJARO #1 SMP PREEMPT Fri Mar 28 09:51:32 UTC 2025 x86_64 GNU/Linux`
 - Containerized?: Docker (dragonfly official image)
 - Dragonfly Version: 1.29.0

**Additional context**
We have migrated from redis, to keydb and now migrating from keydb to dragonfly. Aside from swapping the severs, nothing about our applications have changed, and dragon fly is the only one to have this problem. It seems like when a client issues a quit command, dragonfly is sending messages to the wrong client as replies rather than a message. Generally setting io threads to 1 will silence the problem which suggests there may be some cross talk between threads in particular when a client connection quits / drops.

Our applications have 2 active connections. 1 for subscribing to a channel, and 1 for publishing to that channel in addition to issuing regular commands. 

Or test suites run several ( 3-5 ) processes in parallel. each process is an in instance of the application creating its own connections, and publishing and subscribing to the same pubsub channel name.

We are running Node.JS w/ IORedis as the driver. I'm not sure how helpful it is, but we are getting to this point in the driver code 

https://github.com/redis/ioredis/blob/40ae7ee6348a833b6dbb55187e352bd3eca13255/lib/DataHandler.ts#L235-L238

> Command queue state error. If you can reproduce this, please report it

### PR DESCRIPTION
**Pull request by mkaruza**
When connection is subscribed to channel we are receiving async messages and sending them back to client. When UNSUBSCRIBE is received on same connection it can happen that we are starting to send back data in batch mode. In batch mode we will be aggregating responses until flush. Last message in queue should flush during reply but if it didn't (i.e. PubSub message was discarded) we are going to flush manually.

Fixes #5139 #5251

### CODE REVIEW

**Comment by romange** [comment]
The question below is not intended to block the potential fix in this pr.

@dranikpg  Do you remember why we need `SetBatchMode` at all at this point? Now that we have `ReplyScope` could it be that we can just avoid setting `SetBatchMode(dispatch_q_.size() > 1);` which waits for the next command to be processed and its reply flushed. I am asking because this surely increases the reply latency if the next command is still in the dispatch_q_. 

Another question to both of you - why the reply has not been flushed eventually? if `dispatch_q_.size() > 1` I would imagine that even if the client is blocked, the next commands in the queue will trigger flushing so why it does not happen? Also, could it happen with more usecases besides `unsubscribe`?

File: src/facade/dragonfly_connection.cc [hunk 1]
```diff
@@ -1653,7 +1653,8 @@ void Connection::AsyncFiber() {
       // We keep the batch mode enabled as long as the dispatch queue is not empty, relying on the
       // last command to reply and flush. If it doesn't reply (i.e. is a control message like
       // migrate), we have to flush manually.
-      if (dispatch_q_.empty() && !msg.IsReplying()) {
+      bool is_replaying = msg.IsReplying();
```
Comment (romange) [inline src/facade/dragonfly_connection.cc]: is_replaying -> is_replying

File: src/facade/dragonfly_connection.cc [hunk 2]
```diff
@@ -1664,9 +1665,16 @@ void Connection::AsyncFiber() {
         return;  // don't set conn closing flag
       }
 
+      auto replies_recorded_before = reply_builder_->RepliesRecorded();
       cc_->async_dispatch = true;
       std::visit(async_op, msg.handle);
       cc_->async_dispatch = false;
+      // If last msg in queue was replaying but nothing was replied during dispatch
```
Comment (romange) [inline src/facade/dragonfly_connection.cc]: replying

**Review by romange — APPROVED** [review]

**Comment by dranikpg** [comment]
> Another question to both of you - why the reply has not been flushed eventually

It will be flushed. The problem is that the client waits for a reply (in that case for an unsubscribe) before sending any new commands, so it's esentially a deadlock. There are no new commands, it happens with dispatch_q.empty

> Do you remember why we need SetBatchMode at all at this point? Now that we have ReplyScope ...

Yes and no. We'll have to experiment with it, also with the internal buffer size. If I send 10 fast commands with short replies (i.e OK) in a pipleline, do we really want to reply separately?  Nothing I can tell about the optimal internal buffer / socket buffer / send calls ratio 🤷🏻‍♂️

**Comment by dranikpg** [comment]
Also 🤨 `ReplyScope` didn't make any functional difference in socket access. Not sure I understant the 

> Now that we have

part
