### PR TITLE
fix(hset_family): Ensure empty hash sets are removed

### LINKED ISSUE #4856: Save empty key fatal error on empty hash
**Describe the bug**
When we delete expired fields from hashset from the flow of `hexists key filed` the hashset may become empty.
When snapshotting if we see empty key from type hashset we print dfatal
SaveEntry skipped empty PrimeValue with key: <key> with tag

**To Reproduce**
1. Insert records using `hsetex key 1 f v`
2. Query records using `hexists key f`
3. Start save using `save df`

-  We should delete the key if invoking hexists makes the hset empty (as we do in hget)
- Find if we have other command flows that expire hashset and make sure we delete the keys in this flows as well
- Fix the error print of "SaveEntry skipped empty PrimeValue with key: <key> with tag" , the type is not actually printed to log

### PR DESCRIPTION
**Pull request by abhijat**
When a search operation is performed on a hash set, expired fields are removed as a side effect.
If at the end of such an operation the hash set becomes empty, its key is removed from the database.

fixes #4856

### CODE REVIEW

File: src/server/hset_family.cc [hunk 1]
```diff
@@ -166,7 +166,32 @@ OpStatus IncrementValue(optional<string_view> prev_val, IncrByParam* param) {
...
+}
+
+void DoCleanup(StringMap* sm, DbSlice& db_slice, const DbContext& cntx, std::string_view key) {
+  if (!sm->Empty()) {
+    return;
+  }
+
+  if (auto it = db_slice.FindMutable(cntx, key, OBJ_HASH); it) {
+    it->post_updater.Run();
+    db_slice.Del(cntx, it->it);
```
Comment (adiholden) [inline src/server/hset_family.cc:178]: when we delete from database we need to write a journal change which will sent to replica
RecordJournal(op_args, "DEL"sv, ArgSlice{key});

Comment (abhijat) [reply src/server/hset_family.cc:178]: should this be added to places like https://github.com/dragonflydb/dragonfly/blob/f6ebfe0debe5e81ec1b53479c35a9c30e1214b43/src/server/hset_family.cc#L413 too? It is missing there.

Comment (adiholden) [reply src/server/hset_family.cc:178]: No. This OpDel is called from the transaction execution of hdel. The hdel command will be propagated to the replica part of the transaction framework. But in your flow the hgetall f.e if you delete the key you will need to manually call RecordJournal

Comment (abhijat) [reply src/server/hset_family.cc:178]: Got it, thanks. Will add journal change

File: src/server/hset_family.cc [hunk 2]
```diff
@@ -443,10 +484,16 @@ OpResult<vector<OptStr>> OpHMGet(const OpArgs& op_args, std::string_view key, Cm
...
-      auto it = sm->Find(ToSV(fields[i]));
-      if (it != sm->end()) {
+      if (auto it = FindWithCleanup(
+              {.sm = sm, .db_slice = db_slice, .op_args = op_args, .key = key}, ToSV(fields[i]));
+          it != sm->end()) {
         result[i].emplace(it->second, sdslen(it->second));
       }
+
+      // If the set is empty, FindWithCleanup will have removed the key
+      if (sm->Empty()) {
```
Comment (adiholden) [inline src/server/hset_family.cc:494]: If FindWithCleanup removed the key, is sm still valid or was it deallocated?

File: src/server/hset_family.cc [hunk 3]
```diff
@@ -166,8 +166,43 @@ OpStatus IncrementValue(optional<string_view> prev_val, IncrByParam* param) {
...
+    db_slice.Del(op_args.db_cntx, it->it);
+    if (op_args.shard->journal()) {
+      RecordJournal(op_args, "DEL"sv, {key});
+    }
+  }
+}
+
+bool ContainsWithCleanup(HSetCleanupCtx ctx, const std::string_view field) {
+  const bool found = ctx.sm->Contains(field);
+  ctx.DelKeyIfEmpty();
```
Comment (adiholden) [inline src/server/hset_family.cc:196]: This is a blocking function as RecordJournal can preempt
1. Lets rename this function to have suffix Blocking
2. If the key was deleted we should not access sm anymore

Comment (adiholden) [reply src/server/hset_family.cc:196]: if I am not wrong with number 2, we need to find a way to enforce that callers will not access sm after calling this functions

File: src/server/hset_family.cc (hunk 2 above)
Comment (abhijat) [reply src/server/hset_family.cc:494]: Good point, oddly enough in the debugger the pointer is still valid although its size is 0 and `entries_` table is empty although the block of memory seems to have been freed. It doesn't seem safe though.

I will look into this further.

File: src/server/hset_family.cc (hunk 3 above)
Comment (abhijat) [reply src/server/hset_family.cc:198]: Now we set `sm` to nullptr if the key is deleted.

Comment (abhijat) [reply src/server/hset_family.cc:198]: Another approach could be to consume the input pointer (by always setting to null) and return the string map pointer wrapped in a type such as variant or optional to signify that the string map is no longer valid, but nothing guarantees that the caller will not attempt to use the returned pointer without a check.

File: src/server/hset_family.cc [hunk 4]
```diff
@@ -166,8 +166,45 @@ OpStatus IncrementValue(optional<string_view> prev_val, IncrByParam* param) {
   param->emplace<int64_t>(new_val);
 
   return OpStatus::OK;
+}
+
+struct HSetCleanupCtx {
```
[the remark this answers is not in the document]
Comment (abhijat) [reply src/server/hset_family.cc:171]: It is a double pointer to signal the user that the pointer may be invalidated as discussed in https://github.com/dragonflydb/dragonfly/pull/4873#discussion_r2026765887 

If the key is deleted, then we set the pointer to null. As mentioned in https://github.com/dragonflydb/dragonfly/pull/4873#discussion_r2026967346 though, it is tricky to avoid accidental usage.

File: src/server/hset_family.cc [hunk 5]
```diff
@@ -510,12 +561,13 @@ OpResult<string> OpGet(const OpArgs& op_args, string_view key, string_view field
 
   DCHECK_EQ(pv.Encoding(), kEncodingStrMap2);
   StringMap* sm = GetStringMap(pv, op_args.db_cntx);
-  auto it = sm->Find(field);
-
-  if (it == sm->end())
-    return OpStatus::KEY_NOTFOUND;
+  if (const auto it = FindWithCleanupBlocking(
```
[the remark this answers is not in the document]
Comment (abhijat) [reply src/server/hset_family.cc:564]: Initially in this PR I had the approach to do an empty check + delete using RAII as in https://github.com/dragonflydb/dragonfly/commit/f72ff337f5eb8c5f9db822e9a68f8f47cf6ad7c4 - but we discussed later and to make sure the key is always deleted for future commands I combined the check and deletion into one. 

I will look into changing to make things simpler.

[the remark this answers is not in the document]
Comment (abhijat) [reply src/server/hset_family.cc]: I tried to simplify it a bit, it can be made simpler by arming the delete object by hand but that leaves the possibility of new code not ensuring delete of empty keys cc @adiholden

File: src/server/hset_family.cc (hunk 2 above)
Comment (abhijat) [reply src/server/hset_family.cc]: In the latest version of the code, the map is not accessed after delete because delete is performed during scope exit of the function.

**Review by adiholden — APPROVED** [review]

File: src/server/hset_family.cc [hunk 6]
```diff
@@ -264,6 +264,62 @@ OpStatus OpIncrBy(const OpArgs& op_args, string_view key, string_view field, Inc
   return OpStatus::OK;
 }
 
+struct KeyCleanup {
+  using CleanupFuncT = std::function<void(std::string_view)>;
+  explicit KeyCleanup(CleanupFuncT func, const std::string_view key_view)
```
[the remark this answers is not in the document]
Comment (abhijat) [reply src/server/hset_family.cc:269]: I try to use `const` with views when I remember because even `string_view` can be made to point to some other string in the function body and `const` protects against that. 

It's probably not something that happens often so I am fine to remove it, but I used `const` deliberately here.

File: src/server/hset_family.cc [hunk 7]
```diff
@@ -264,6 +264,62 @@ OpStatus OpIncrBy(const OpArgs& op_args, string_view key, string_view field, Inc
...
+  void arm() {
+    armed = true;
+  }
+
+  CleanupFuncT f;
+  std::string key;
+  bool armed{false};
+};
+
+void DeleteKey(DbSlice& db_slice, const OpArgs& op_args, std::string_view key) {
```
[the remark this answers is not in the document]
Comment (abhijat) [reply src/server/hset_family.cc:287]: I kept it as a function because it is used twice.

File: src/server/hset_family.cc [hunk 8]
```diff
@@ -570,18 +631,15 @@ OpResult<vector<string>> OpGetAll(const OpArgs& op_args, string_view key, uint8_
   // and the enconding is guaranteed to be a DenseSet since we only support expiring
   // value with that enconding.
   if (res.empty()) {
-    // post_updater will run immediately
-    auto it = db_slice.FindMutable(op_args.db_cntx, key).it;
-
-    db_slice.Del(op_args.db_cntx, it);
+    DeleteKey(db_slice, op_args, key);
```
[the remark this answers is not in the document]
Comment (abhijat) [reply src/server/hset_family.cc:634]: Not sure but earlier in the PR discussion it was mentioned we should write to journal when we delete the key. Should we not do this in this case? 

This is in the `HGetGeneric -> OpGetAll` code path. Will it be replicated by itself, considering it is a read command?

[the remark this answers is not in the document]
Comment (kostasrim) [reply src/server/hset_family.cc:634]: > Not sure but earlier in the PR discussion it was mentioned we should write to journal when we delete the key. Should we not do this in this case?

Yes we should but I am skeptical before those changes it seems that we did not write explicitly and we do now. 

I will need to check at the flow and get back to you

File: src/server/hset_family.cc (hunk 6 above)
[the remark this answers is not in the document]
Comment (kostasrim) [reply src/server/hset_family.cc:269]: ohhh yeah that makes sense! nvm

File: src/server/hset_family.cc (hunk 8 above)
[the remark this answers is not in the document]
Comment (kostasrim) [reply src/server/hset_family.cc:634]: Wow that was an actual bug. Mind if we also add a replication test for this ?

**Review by kostasrim — APPROVED** [review]
lgtm. Plz follow up with:

1. Change the log for snapshot as per Adi's comment
