### PR TITLE
fix: Clarify logging for snapshots loading.

### LINKED ISSUE #1309: Clarify logs for snapshot loading
We print INFO logs for each separate .dfs file loaded. Accumulate them so we only print 1 at the actual end of snapshot loading.

### PR DESCRIPTION
**Pull request by royjacobson**
Close #1309.

Example output:
```
I20230529 15:37:32.397684 291516 server_family.cc:635] Loading /home/roy/work/dragonfly/build-dbg/dump-2023-05-29T15:37:31-summary.dfs
I20230529 15:37:32.400419 291520 listener_interface.cc:96] sock[53] AcceptServer - listening on port 6379
I20230529 15:37:32.402602 291519 server_family.cc:678] Load finished, num keys read: 2000
```

### CODE REVIEW

File: src/server/server_family.cc [hunk 1]
```diff
@@ -725,9 +732,10 @@ error_code ServerFamily::LoadRdb(const std::string& rdb_file) {
     RdbLoader loader{&service_};
     ec = loader.Load(&fs);
     if (!ec) {
-      LOG(INFO) << "Done loading RDB, keys loaded: " << loader.keys_loaded();
-      LOG(INFO) << "Loading finished after "
-                << strings::HumanReadableElapsedTime(loader.load_time());
+      VLOG(1) << "Done loading RDB from " << rdb_file << ", keys loaded: " << loader.keys_loaded();
+      VLOG(1) << "Loading finished after " << strings::HumanReadableElapsedTime(loader.load_time());
+      if (keys_loaded)
+        *keys_loaded = loader.keys_loaded();
```
Comment (dranikpg) [inline src/server/server_family.cc:738]: Ah, finally 🌟  Seeing 32 messages on 16 cores was a little annoying 😄

File: src/server/server_family.h [hunk 2]
```diff
@@ -173,7 +173,7 @@ class ServerFamily {
 
   void SyncGeneric(std::string_view repl_master_id, uint64_t offs, ConnectionContext* cntx);
 
-  std::error_code LoadRdb(const std::string& rdb_file);
+  std::error_code LoadRdb(const std::string& rdb_file, size_t* keys_loaded = nullptr);
```
Comment (dranikpg) [inline src/server/server_family.h:176]: I always liked the rust'y/modern cpp style with `io::Result<size_t>` a little more than passing pointers, but it can be a little inconvenient at times without the proper utils around it. No need to change, just a suggestion

**Review by dranikpg — APPROVED** [review]

**Review by dranikpg — APPROVED** [review]
