### PR TITLE
fix(server): Wrong replication state

### LINKED ISSUE #1132: replication: `stable sync` status without a full sync
**Describe the bug**

For https://github.com/dragonflydb/dragonfly-operator/pull/59, The Operator needs a way to know
if a replica has done a full sync, and is under stable sync before moving to rolling out another replica
so that we maintain high availability.

Looking at [the code](https://github.com/dragonflydb/dragonfly/blob/ba19cc1047ebc337a209a35c7968984a7d202690/src/server/server_family.cc#L2000) for `role`, There seems to be an error where `stable sync` can be returned even
when a full sync hasn't happened yet. (cc: @ashotland)

Parallelly, We also need this information to be under `info replication` as [go-redis](https://github.com/redis/go-redis) 
only supports the `info` command. This makes it easy for the Operator.

**Expected behavior**

- Reply `stable sync` only when there a full sync has happened
- Add this `stable sync` information into the `info replication` command.

### PR DESCRIPTION
**Pull request by royjacobson**
@Pothulapati said in #1132 that we sometimes return the wrong value for the replication state.
I think I understood where it can go wrong. I changed the calculation to be more rebust and added a basic test.

close #1132

### CODE REVIEW

File: src/server/replica.cc [hunk 1]
```diff
@@ -1229,7 +1229,8 @@ Replica::Info Replica::GetInfo() const {
     res.host = master_context_.host;
     res.port = master_context_.port;
     res.master_link_established = (state_mask_.load() & R_TCP_CONNECTED);
-    res.sync_in_progress = (state_mask_.load() & R_SYNCING);
+    res.full_sync_in_progress = (state_mask_.load() & R_SYNCING);
+    res.full_sync_done = (state_mask_.load() & R_SYNC_OK);
```
Comment (ashotland) [inline src/server/replica.cc:1233]: I am not very familiar with those state flags so trust it translates to the semantics of those member variables.

File: src/server/server_family.cc [hunk 2]
```diff
@@ -1988,17 +1988,20 @@ void ServerFamily::Role(CmdArgList args, ConnectionContext* cntx) {
...
     (*cntx)->SendBulkString(rinfo.host);
     (*cntx)->SendBulkString(absl::StrCat(rinfo.port));
-    if (rinfo.sync_in_progress) {
+    if (rinfo.full_sync_done) {
+      (*cntx)->SendBulkString("stable_sync");
+    } else if (rinfo.full_sync_in_progress) {
       (*cntx)->SendBulkString("full_sync");
-    } else if (!rinfo.master_link_established) {
-      (*cntx)->SendBulkString("connecting");
+    } else if (rinfo.master_link_established) {
```
Comment (ashotland) [inline src/server/server_family.cc:2001]: Consider 
disconnected -> connecting -> full_sync -> stable_sync
or
connecting -> handshaking -> full_sync -> stable_sync

**Review by ashotland — APPROVED** [review]
LGTM - minor suggestions. Thanks!

File: src/server/server_family.cc (hunk 2 above)
Comment (royjacobson) [reply src/server/server_family.cc:2001]: I chose `preparation` because it's the term used in `ReplicaRoleInfo::ReplicaRoleInfo` and in `SyncState::PREPARATION`. Do you still prefer handshaking?

Comment (ashotland) [reply src/server/server_family.cc:2001]: Nope :)
