### PR TITLE
fix: Fix a corruption when connection writes interleaving messages

### LINKED ISSUE #924: Response Race On Subscription
Responses from DragonflyDB corrupt sometimes when subscribing to a channel that encounters a publish at the same time.

The following line dump shows how a subscription count is lost or overwritten by the message (array) that follows.

[lost-subs-count.txt](https://github.com/dragonflydb/dragonfly/files/10944753/lost-subs-count.txt)

Specifically, the response was:

```resp
*3
$9
subscribe
$28
channel-18126908833894131297
*3
$7
message
…
```

… while it should have been:

```resp
*3
$9
subscribe
$28
channel-18126908833894131297
:1
*3
$7
message
…
```

…, with ":1" included.

This is not the only scenario. I just got lucky while recording. Sometimes a redundant "*3" appears before another message array, as in "*3\r\n*3\r\n$7message…". Followup on #316.

### PR DESCRIPTION
**Pull request by romange**
Fixes #924

### CODE REVIEW

File: src/facade/dragonfly_connection.h [hunk 1]
```diff
@@ -54,14 +54,21 @@ class Connection : public util::Connection {
 
   struct PubMessage {
     // if empty - means its a regular message, otherwise it's pmessage.
-    std::string_view pattern;
-    std::string_view channel;
-    std::shared_ptr<const std::string> message;  // ensure that this message would out live passing
-                                                 // between different threads/fibers
+    std::string pattern;
+    std::shared_ptr<std::string> channel;
+    std::shared_ptr<std::string> message;  // ensure that this message would out live passing
```
Comment (dranikpg) [inline src/facade/dragonfly_connection.h:59]: In the future we should probably just wrap this whole type into one shared ptr

**Review by dranikpg — APPROVED** [review]

File: src/facade/dragonfly_connection.h (hunk 1 above)
Comment (romange) [reply src/facade/dragonfly_connection.h:59]: yeah, it's not possible due to `pattern` field that is unique for each psubscriber.
we could only wrap (message,channel) together
