### PR TITLE
fix(server): deadlock with replicaof inside multi

### LINKED ISSUE #4663: Hung replica
Hello, I have been having the problem for many months where the dragonfly process randomly hangs completely. The process does not die but it is impossible to connect to that instance.
I have installed the "debug" version and I have managed to capture a strace of the process in this case. I attach the content of the strace.

In this situation you cannot connect to the node and it starts generating dumps in the directory that is not configured for that purpose, it is as if it had started with a configuration that is not the one specified in the original startup.

In the logs (which I also attach) there is nothing that indicates an error.

Hmmm, has the ability to attach files been disabled?

### PR DESCRIPTION
**Pull request by adiholden**
fixes #4663 
The bug:
when `replicaof` is running in multi command the tx scheduling done when we start executing the multi tx while the 
`replicaof` command takes a mutex to prevent concurrent replicaof commands at the same time.

This may lead to deadlock if `tx1` is scheduled first but `tx2` takes the replication mutex first.

Notes:
`replicaof` command should not run in multi tx, we do support this because sentinel uses it but actually the other commands runinig in this multi tx are not transactional (config, client), therefore running the tx in non atomic mode has the same affect in this flow.

The fix:
if we have an admin command running inside multi tx, use none atomic mode for this tx.

### CODE REVIEW

**Review by romange — APPROVED** [review]

File: src/server/main_service.cc [hunk 1]
```diff
@@ -656,9 +658,13 @@ Transaction::MultiMode DeduceExecMode(ExecScriptUse state,
   if (!transactional && exec_info.watched_keys.empty())
     return Transaction::NOT_DETERMINED;
 
+  if (contains_admin_cmd) {
+    multi_mode = Transaction::NON_ATOMIC;
```
Comment (kostasrim) [inline src/server/main_service.cc:662]: Wouldn't this break multi/exec that contain admin commands but should run atomically ?

Comment (adiholden) [reply src/server/main_service.cc:662]: As discussed f2f this does brakes atomicity but we do not exepect admin commands with transactional commands.
Having said that we can change this back once we refactor replication code and remove the mutex non cpu ops
