### PR TITLE
fix(server): fix JSON.MGET implementation (#849)

### LINKED ISSUE #849: JSON.MGET not working as intended
**Describe the bug**
JSON.MGET not working as intended 

**To Reproduce**
dragonfly> JSON.SET doc1 $ '{"a":1, "b": 2, "nested": {"a": 3}, "c": null}'
OK
dragonfly> JSON.SET doc2 $ '{"a":4, "b": 5, "nested": {"a": 6}, "c": null}'
OK

dragonfly> JSON.MGET doc1 doc2 $..a
EXPECTED:
1) "[1,3]"
2) "[4,6]"
GOT:
1
3

### PR DESCRIPTION
**Pull request by iko1**
Fixes #849

### CODE REVIEW

File: src/server/json_family.cc [hunk 1]
```diff
@@ -884,33 +884,50 @@ OpResult<vector<OptLong>> OpArrIndex(const OpArgs& op_args, string_view key,
...
 // Returns string vector that represents the query result of each supplied key.
-OpResult<vector<OptString>> OpMGet(const OpArgs& op_args, const vector<string_view>& keys,
-                                   JsonExpression expression) {
-  vector<OptString> vec;
-  for (auto& it : keys) {
-    // OpResult<JsonType> result = GetJson(op_args, it);
-    OpResult<JsonType*> result = GetJson(op_args, it);
-    if (!result) {
-      vec.emplace_back();
+vector<OptString> OpMGet(JsonExpression& expression, const Transaction* t, EngineShard* shard) {
```
Comment (romange) [inline src/server/json_family.cc:887]: why `expression` is passed by mutable reference, @iko1 ?
the reason I am asking is if it's been mutated then there is a potential data-race since `OpMGet` is called in parallel from multiple threads.

Comment (romange) [reply src/server/json_family.cc:887]: so either lets change it to const ref or pass it by value

File: src/server/json_family.cc [hunk 2]
```diff
@@ -1101,29 +1120,46 @@ void JsonFamily::MGet(CmdArgList args, ConnectionContext* cntx) {
...
+      results[indx] = move(res[j]);
+    }
+  }
+
+  (*cntx)->StartArray(results.size());
+  for (auto& it : results) {
+    if (!it) {
+      (*cntx)->SendNull();
+    } else {
+      (*cntx)->SendSimpleString(*it);
```
Comment (romange) [inline src/server/json_family.cc:1161]: I think it's better to use SendBulkString here

File: src/server/json_family.cc [hunk 3]
```diff
@@ -884,33 +884,50 @@ OpResult<vector<OptLong>> OpArrIndex(const OpArgs& op_args, string_view key,
...
 // Returns string vector that represents the query result of each supplied key.
-OpResult<vector<OptString>> OpMGet(const OpArgs& op_args, const vector<string_view>& keys,
-                                   JsonExpression expression) {
-  vector<OptString> vec;
-  for (auto& it : keys) {
-    // OpResult<JsonType> result = GetJson(op_args, it);
-    OpResult<JsonType*> result = GetJson(op_args, it);
-    if (!result) {
-      vec.emplace_back();
+vector<OptString> OpMGet(JsonExpression&& expression, const Transaction* t, EngineShard* shard) {
```
Comment (romange) [inline src/server/json_family.cc:887]: i do not see a good reason to pass `JsonExpression&& ` over `JsonExpression`

File: src/server/json_family.cc [hunk 4]
```diff
@@ -884,33 +884,50 @@ OpResult<vector<OptLong>> OpArrIndex(const OpArgs& op_args, string_view key,
...
+  auto args = t->GetShardArgs(shard->shard_id());
+  DCHECK(!args.empty());
+  vector<OptString> respone(args.size());
```
Comment (romange) [inline src/server/json_family.cc:890]: respone -> responce

**Review by romange — APPROVED** [review]

**Comment by romange** [comment]
Thanks, @iko1 !
