### PR TITLE
fix: enforce strong consistency in channel_store

### LINKED ISSUE #4659: test_cluster_sharded_pub_sub failed
99% sure the test is a little racy. Will jump on this on the first chance https://github.com/dragonflydb/dragonfly/actions/runs/13517488144/job/37769144898#step:6:4085

### LINKED ISSUE #4724: test_cluster_sharded_pubsub_shard_commands failed
This test failed on [CI](https://github.com/dragonflydb/dragonfly/actions/runs/13712970075/job/38352821395).

While we should be subscribed to two channels only one channel is returned with `SHARDCHANNELS`.

### PR DESCRIPTION
**Pull request by kostasrim**
Channel store uses a `read-copy-update` to distribute the changes of the channel store to all proactors. The problem is that we use `memory_order_relaxed` to load the new pointer to the channel store for each proactor which `*does not guarantee*` that we fetch the latest value of the channel store. Hence, the fix is to use sequencial consistency such to force fetch the latest value of the channel store. Should fix #4724

Fixes #4659 and #4724

### CODE REVIEW

File: src/server/channel_store.cc [hunk 1]
```diff
@@ -152,7 +153,7 @@ unsigned ChannelStore::SendMessages(std::string_view channel, facade::ArgRange m
       it++;
     }
   };
-  shard_set->pool()->DispatchBrief(std::move(cb));
+  shard_set->pool()->AwaitBrief(std::move(cb));
```
Comment (adiholden) [inline src/server/channel_store.cc:156]: This funciton is called inside DbSlice::DeleteExpiredStep which we asume do not preempt but now this breaks this assumption

Comment (kostasrim) [reply src/server/channel_store.cc:156]: :thinking: Then we can:

1. Use `DispatchBrief` only when called by `DeleteExpiredStep`
2. Ditch strong consistency when sending messages via publish and add a sleep to the test

I rather opt in for (1).

Other than that good catch! 

Wdyt ? @adiholden

File: src/server/channel_store.cc [hunk 2]
```diff
@@ -124,8 +124,9 @@ unsigned ChannelStore::SendMessages(std::string_view channel, facade::ArgRange m
 
   // Make sure none of the threads publish buffer limits is reached. We don't reserve memory ahead
   // and don't prevent the buffer from possibly filling, but the approach is good enough for
-  // limiting fast producers. Most importantly, we can use DispatchBrief below as we block here
```
Comment (adiholden) [inline src/server/channel_store.cc:127]: I actually dont understand the comment that was removed.. what is "we block here"

Comment (kostasrim) [reply src/server/channel_store.cc:127]: I removed it because I replaced DispatchBrief with AwaitBrief

Comment (kostasrim) [reply src/server/channel_store.cc:127]: but ignore, what is important is to the semantic right. I will adjust the comment

File: src/server/channel_store.cc [hunk 3]
```diff
@@ -323,7 +324,9 @@ void ChannelStoreUpdater::Apply() {
   // queued SubscribeMaps in the freelist are no longer in use.
   shard_set->pool()->AwaitBrief([](unsigned idx, util::ProactorBase*) {
     ServerState::tlocal()->UpdateChannelStore(
-        ChannelStore::control_block.most_recent.load(memory_order_relaxed));
+        // Do not use memory_order_relaxed, we need to fetch the latest value of
+        // the control block
+        ChannelStore::control_block.most_recent.load());
```
Comment (adiholden) [inline src/server/channel_store.cc:329]: please use explicitly the memory order you want use

File: src/server/channel_store.cc (hunk 1 above)
Comment (adiholden) [reply src/server/channel_store.cc:156]: I think we should add sleep to the test case as from what I understand the publish does not guaranties to send the message to all subscribers but that the message was queued to be sent.
Also when sending the message we use the conn->SendPubMessageAsync which I think also does not guarantee that after you call AwaitBrief here the massege was already sent

Comment (kostasrim) [reply src/server/channel_store.cc:156]: Sounds good

**Review by adiholden — APPROVED** [review]

**Comment by romange** [comment]
I am pretty sure we used `DispatchBrief` by design. What is a strongly consistent publish? Is Redis publish strongly consistent?
 A server can not not when a client will read its notifications so how do you define it?

File: tests/dragonfly/cluster_test.py [hunk 4]
```diff
@@ -2970,6 +2969,9 @@ async def test_cluster_sharded_pub_sub(df_factory: DflyInstanceFactory):
     consumer.ssubscribe("kostas")
 
     await c_nodes[0].execute_command("SPUBLISH kostas hello")
+    # We need to sleep cause we use DispatchBrief internally. Otherwise we can't really gurantee
```
Comment (romange) [inline tests/dragonfly/cluster_test.py:2972]: you can not guarantee in any case. how do you know that the message arrive to the client? maybe he is in australia?

**Comment by kostasrim** [comment]
> I am pretty sure we used `DispatchBrief` by design. What is a strongly consistent publish? Is Redis publish strongly consistent? A server can not not when a client will read its notifications so how do you define it?

What I mean by "strongly consistent" is that after I get an `ok` from `publish` I know dragonfly has `processed and sent` this messages to all the subscribers something that we can't guarantee now. So it was not about "guarantee a delivery" but more of "gurantee that dragonfly sent the messages to all the subscribers if any"
