### PR TITLE
fix: lsn check failure

### LINKED ISSUE #4048: LSN mismatch during replication
https://github.com/dragonflydb/dragonfly/actions/runs/11663767594/job/32472896823

```

.39993➜    @          0x13cd72a         64  absl::lts_20240116::WriteFailureInfo()

39993➜    @          0x13cd99c        112  absl::lts_20240116::AbslFailureSignalHandler()

39993➜    @     0x7f9c03319420       2208  (unknown)

39993➜    @          0x1349819         16  google::LogMessage::Fail()

.39993➜    @          0x1349760        160  google::LogMessage::SendToLog()

39993➜    @          0x1348f55         80  google::LogMessage::Flush()

39993➜    @          0x134cc6c         32  google::LogMessageFatal::~LogMessageFatal()
.
39993➜    @           0xba3e79        592  dfly::TransactionReader::NextTxData()

.39993➜    @           0xb07f57        480  dfly::DflyShardReplica::StableSyncDflyReadFb()

39993➜    @           0xb2a475         64  std::__invoke_impl<>()

39993➜    @           0xb291f2         64  std::__invoke<>()

39993➜    @           0xb280c9         48  std::__apply_impl<>()
.
39993➜    @           0xb2810e         48  std::apply<>()

39993➜    @           0xb281a9        112  util::fb2::detail::WorkerFiberImpl<>::run_()

39993➜    @           0xb2706f         80  util::fb2::detail::WorkerFiberImpl<>::WorkerFiberImpl<>()::{lambda()#1}::operator()()

39993➜    @           0xb2c2b6         80  std::__invoke_impl<>()

.39993➜    @           0xb2be6b         80  std::__invoke<>()

39993➜    @           0xb2b847         80  std::invoke<>()

.39993➜    @           0xb2b0c2         80  boost::context::detail::fiber_record<>::run()

39993➜    @           0xb2a594         48  boost::context::detail::fiber_entry<>()

```

### PR DESCRIPTION
**Pull request by kostasrim**
Test `test_bug_in_json_memory_tracking` failed because it used `StaticSeeder` which uses `debug populate` which is non transactional. 

* rename StaticSeeder to DebugPopulateSeeder to show intent
* add a DCHECK in debug populate that triggers if there is a registered replica that hasn't reached stable sync
* small cleanup

fixes #4048

Also `test_disconnect_replica` was failing months ago but I run this for more than 5 hours without any success.

### CODE REVIEW

File: src/server/multi_command_squasher.cc [hunk 1]
```diff
@@ -168,8 +168,7 @@ bool MultiCommandSquasher::ExecuteStandalone(facade::RedisReplyBuilder* rb, Stor
   return true;
 }
 
-OpStatus MultiCommandSquasher::SquashedHopCb(Transaction* parent_tx, EngineShard* es,
-                                             RespVersion resp_v) {
+OpStatus MultiCommandSquasher::SquashedHopCb(EngineShard* es, RespVersion resp_v) {
```
Comment (kostasrim) [inline src/server/multi_command_squasher.cc:171]: `parent_tx` was not used.

File: src/server/multi_command_squasher.cc [hunk 2]
```diff
@@ -258,11 +256,6 @@ bool MultiCommandSquasher::ExecuteSquashed(facade::RedisReplyBuilder* rb) {
         shard_set->AddL2(i, cb);
     }
     bc->Wait();
-#else
```
Comment (kostasrim) [inline src/server/multi_command_squasher.cc:261]: removed dead code

File: src/server/transaction.cc [hunk 3]
```diff
@@ -1129,7 +1129,7 @@ bool Transaction::ScheduleInShard(EngineShard* shard, bool execute_optimistic) {
     DVLOG(3) << "Lock granted " << lock_granted << " for trans " << DebugId();
 
     // Check if we can run immediately
-    if (shard_unlocked && execute_optimistic && lock_granted) {
+    if (lock_granted && execute_optimistic) {
```
Comment (kostasrim) [inline src/server/transaction.cc:1132]: `lock_granted = shard_unlocked && keys_unlocked;` so checking explicitly for `shard_unlocked` is redundant

File: src/server/server_family.h [hunk 4]
```diff
@@ -266,6 +266,18 @@ class ServerFamily {
 
   void UpdateMemoryGlobalStats();
 
+  // Return true if no replicas are registered or if all replicas reached stable sync
+  // Used in debug populate to DCHECK insocsistent flows that violate transaction gurantees
+  bool AreAllReplicasInStableSync() const {
+    auto roles = dfly_cmd_->GetReplicasRoleInfo();
```
Comment (adiholden) [inline src/server/server_family.h:272]: I think this function takes several mutexes and better we use it not so frequently therefor I sugget to do the check in debug populate only when we start the debug populate and we can also do when we finish.
Not for every command invokation

Comment (kostasrim) [reply src/server/server_family.h:272]: No objection, my rationale was that we don't care since it's not used in production. Happy to change that though.

Comment (adiholden) [reply src/server/server_family.h:272]: you are right it does not affect prod but it might slow the debug populate in our tests

**Review by adiholden — APPROVED** [review]
