### PR TITLE
fix: Fix deadlock in the transaction code.

### LINKED ISSUE #945: brpop does not work as expected
The issue is when multiple BRPOP transactions (TX1, TX2) enter a watching state on keys `k0`, `k1`, `k2` and 
TX3 that does the same is being just scheduled.
 
1. LPUSH -> k2 notifies TX1. TX1 blocks tx-queue on shard-2 and starts unblocking.
2. TX1 unblocks itself from all shards, removes itself from the watch queues  
and starts the execution flow (schedules Find on all keys) .
2. LPUSH -> k0 notifies TX2 because TX2 now is the first one in the watch queue on shard-0.
3. TX2 blocks the tx-queue on shard-0 and also starts executing the flow.
4. Someone pushes `k1` on shard-1.
5. TX1 finds k0 (first key in order) and snatches it (correctly).
7. meanwhile the scheduled TX3 that is unblocked on shard 1,  (TX1 blocked 2, TX2 blocks 0) - executes `find(k1)` and finds `k1.
8. TX2 finds k1 (k0 was popped) and snatches it.
9. TX3 expects to pop k1 but does not find it.

The use-case in question is reproduced reliably in unit-test.

### PR DESCRIPTION
**Pull request by romange**
The deadlock happenned during the brpop flow where we access shard_data.local_data from both coordinator and shard threads. Originally, shard_data.local_data was not designed for concurrent access so I used ARMED bit to deduplicate callback runs for each shard. The problem is that with BRPOP it could happen, the ExecuteAsync would do "=| ARMED" and in parallel NotifySuspended would apply " |= AWAKED" in the shard thread, and both R/M/W operations would corrupt each other.

Therefore, I separated now completely shard-local local_data mask and is_armed boolean. Moreover, since now we use atomics for is_armed, I increased PerShardData size to 64 bytes to avoid false cache sharding betweenn PerShardData objects.

Fixes #945

### CODE REVIEW

File: src/server/transaction.cc [hunk 1]
```diff
@@ -798,24 +801,38 @@ void Transaction::ExecuteAsync() {
...
+    // this callback should fail from time to time with non-atomic txs in debug mode because we
+    // clear the shard_data_ array.
+    DCHECK(!this->shard_data_.empty());
+
+    // TODO: to document why we need seqlock_. I suspect I added it to guard shard_data
+    // for multi-command transactions. Specifically, if we resize shard_data_ by coordinator thread
+    // and this callback is executed by engine shard thread, we may access invalid memory.
+    // I think the approach is still broken because we may read seqlock_ and pause, then
+    // the coordinator will progress, exit the WaitForShardCallbacks and will resize shard_data_
+    // and then this callback will call IsArmedInShard and will have invalid memory access.
```
Comment (dranikpg) [inline src/server/transaction.cc:813]: True, WaitForShardCallbacks is the following:
```py
await run_count == 0
# <-- gap here
seqlock++
```

so we can increase the seqlock in DecreaseRunCnt instead

File: src/server/transaction.cc [hunk 2]
```diff
@@ -798,24 +801,38 @@ void Transaction::ExecuteAsync() {
...
+      DVLOG(3) << "PollExecCb " << DebugId() << " sid(" << shard->shard_id() << ") "
+               << run_count_.load(memory_order_relaxed);
+
+      // We verify that this callback is still relevant.
+      // If we still have the same sequence number and tx is armed, meaning
+      // the coordinator thread has not crossed WaitForShardCallbacks barrier (WRONG!).
+      // Otherwise, this callback is redundant. We may still call PollExecution but
+      // we should not pass this to it since it can be in undefined state for this callback.
+      // TODO: I am pretty sure we can achieve both seqlock and refcount semantics
+      // with a single run_count_ atomic.
```
Comment (dranikpg) [inline src/server/transaction.cc:827]: Partially, you can introduce "epochs", so that run_cnt value will be `epoch * 1000 + real run_cnt`.
Otherwise, you miss the case where coordinator re-arms for second hop and you'll miss the 0 from the old callback

File: src/server/transaction.h [hunk 3]
```diff
@@ -275,6 +276,12 @@ class Transaction {
 
     PerShardData() = default;
 
+    // this is the only variable that is accessed by both shard and coordinator threads.
+    std::atomic_bool is_armed{false};
+
+    // We pad with some memory so that atomic loads won't cause false sharing betweem threads.
+    char pad[48];  // to make sure PerShardData is 64 bytes and takes full cacheline.
+
```
Comment (dranikpg) [inline src/server/transaction.h:284]: I would re-thing the memory layout to optimize for storage + less allocations

File: src/server/transaction.h [hunk 4]
```diff
@@ -397,7 +406,7 @@ class Transaction {
   void WaitForShardCallbacks() {
     run_ec_.await([this] { return 0 == run_count_.load(std::memory_order_relaxed); });
 
-    seqlock_.fetch_add(1, std::memory_order_acq_rel);
+    seqlock_.fetch_add(1, std::memory_order_release);
```
Comment (dranikpg) [inline src/server/transaction.h:409]: 🤨

**Review by dranikpg — DISMISSED** [review]

**Review by dranikpg — APPROVED** [review]
