### PR TITLE
fix: prevents Dragonfly from blocking in epoll during snapshotting

### LINKED ISSUE #3895: Snapshotting in Epoll blocks Dragonfly threads
**Describe the bug**
#2642  #2702 
Saw that someone had mentioned a related issue before, and there was a related tighter, but it still seems to be an issue at this point.

**To Reproduce**
1. Example execution bgsave
2. Then all client access behaviors are blocked, such as info, set can not return the success flag properly.
3. the OK result is returned until bgsave has finished.

**Expected behavior**
1. The bgsave process must not block client access, as this would interrupt business operations and may affect the ability of the monitoring system to incorrectly interpret the state of the instance.
2. Is it done in an asynchronous manner? It looks like df doesn't support it yet.

**Screenshots**
image
image
image
```
> bgsave
OK
> set dba 1

(Here I hit enter a couple times to make a blocking interval distinction)

OK
(14.42s)

> bgsave async
(error) ERR Unknown subcommand or wrong number of arguments for 'ASYNC'. Try SAVE HELP.
```

**Environment (please complete the following information):**
 - OS: [Debian GNU/Linux 11]
 - Kernel: Linux  5.10.0-30-amd64 #1 SMP Debian 5.10.218-1 (2024-06-01) x86_64 GNU/Linux
 - Containerized?: [Physical machine direct deployment]
 - Dragonfly Version: [df-v1.23.0]

**Additional context**
This situation should still be serious, it will directly affect the access to the client instance that has a backup plan, when the `bgsave` blocked all access, including the `metrics` data retrieval. I think this situation is not reasonable if put into the production environment. If the amount of data to follow more and more large, the impact of time will become longer, which will affect the business of data access for a long time. For Online to provide services to the business, I think this is unacceptable.  I hope it can be fixed soon. Please let me know if I'm missing something or if I'm not doing it right, thank you.

### PR DESCRIPTION
**Pull request by romange**
The problem - we used file write in non-direct mode when writing snapshots in epoll mode. As a result - lots of data was cached into OS memory. But then during the rename operation, when we rename "xxx.dfs.tmp" into "xxx.dfs", the OS flushes the file caches and the thread is stuck in OS system call rename for a long time.

The fix - to use DIRECT mode and to avoid caching the data into OS caches at all.

Fixes #3895

### CODE REVIEW

File: src/server/server_family.cc [hunk 1]
```diff
@@ -1651,9 +1650,11 @@ GenericError ServerFamily::DoSaveCheckAndStart(bool new_version, string_view bas
 }
 
 GenericError ServerFamily::WaitUntilSaveFinished(Transaction* trans, bool ignore_state) {
+  VLOG(1) << "WaitUntilSaveFinished";
   save_controller_->WaitAllSnapshots();
   detail::SaveInfo save_info;
 
+  VLOG(1) << "Before WaitUntilSaveFinished::Finalize";
```
Comment (dranikpg) [inline src/server/server_family.cc:1657]: Two vlogs be a little noisy 🤷🏻‍♂️

**Review by dranikpg — APPROVED** [review]
Good catch

File: src/server/server_family.cc (hunk 1 above)
Comment (romange) [reply src/server/server_family.cc:1657]: these are printed are only during saves and it's a vlog :)

**Review by dranikpg — APPROVED** [review]
