### PR TITLE
fix: add missing barrier to fix reads in the coordinator fiber

### LINKED ISSUE #997: Crash due to data race
I'm running a redis cluster with rps ~ 240k; and when start trying with dragonfly, I got coredump frequently (process lived no more than 30minutes).

The dragonfly/redis mostly uses command HGET to get data. Commands pattern
- hget: >99.9%
- hset/hdel/hgetall/smembers/sadd/srem/ping: <0.1%

Below is what getting from console log

> mimalloc: error: thread 0x21e1a520: corrupted thread-free list
> mimalloc: error: thread 0x21e1a520: corrupted thread-free list
> mimalloc: error: thread 0x21e19010: corrupted thread-free list
> mimalloc: error: thread 0x21e19010: corrupted thread-free list
> mimalloc: error: thread 0x21e18eb0: corrupted thread-free list
> *** SIGBUS received at time=1679890128 on cpu 2 ***
> [failure_signal_handler.cc : 332] RAW: Signal 11 raised at PC=0x68cf34 while already in AbslFailureSignalHandler()
> PC: @           0x68ab90  (unknown)  _mi_free_block_mt
>     @           0x7524cc       4928  absl::lts_20230125::AbslFailureSignalHandler()
>     @     0xffffb4915804         32  (unknown)
>     @           0x51980c         32  _ZNSt17_Function_handlerIFN6facade8OpStatusEPN4dfly11TransactionEPNS2_11EngineShardEEZNS3_18ScheduleSingleHopTIZNS2_10HSetFamily4HGetEN4absl12lts_202301254SpanINSC_IcEEEEPNS2_17ConnectionContextEEUlS4_S6_E_EEDTclfp_fpTLDnEEEOT_EUlS4_S6_E_E10_M_managerERSt9_Any_dataRKSN_St18_Manager_operation
>     @           0x5e4640        208  dfly::Transaction::RunQuickie()
>     @           0x5e4978        112  dfly::Transaction::ScheduleUniqueShard()
>     @           0x5e7870        160  std::_Function_handler<>::_M_invoke()
>     @           0x644638        240  util::fibers_ext::FiberQueue::Run()
>     @           0x5c8260        256  boost::fibers::worker_context<>::run_()
>     @           0x5c7984  (unknown)  boost::context::detail::fiber_entry<>()

Also trying to get the coredump file but still not successfully.
systemd threw msgs like this "**_systemd-coredump[xxxxxxx]: Failed to get EXE, ignoring: No such process_**"

**Run command**
`./dragonfly-latest --bind 0.0.0.0 --dbnum 1 --proactor_threads 12 --maxmemory 5368709120 --port 3800 --save_schedule "*:30" --dbfilename dump.rdb --df_snapshot_format=false --dir /data/redis-3800/ --log_dir /data/redis-3800/  >/data/redis-3800/console.log 2>&1 &`

**Environment:**
 - OS: [Amazon Linux 3 (AL2023)]
 - Kernel: 6.1.15-28.43.amzn2023.aarch64
 - EC2 instance c7g.4xlarge (ARM64)
 - Dragonfly Version: [latest code as of 2023-03-27]

Pls help to check.
Tks.

### PR DESCRIPTION
**Pull request by romange**
1. Adds memory barriers around `run_count_` so that the coordinator thread won't read stale data.
2. (unrelated to the fix): Replaces transaction callback with `FunctionRef` that does not allocate like `std::function`.

Fixes #997.

### CODE REVIEW

**Comment by romange** [comment]
My regression tests on ARM64 pass.

File: src/server/transaction.cc [hunk 1]
```diff
@@ -756,8 +760,9 @@ void Transaction::Schedule() {
 // Runs in coordinator thread.
 void Transaction::Execute(RunnableType cb, bool conclude) {
   DCHECK(coordinator_state_ & COORD_SCHED);
+  DCHECK(!cb_ptr_);
 
-  cb_ = std::move(cb);
+  cb_ptr_ = &cb;
```
Comment (chakaz) [inline src/server/transaction.cc:765]: Unless I'm missing something here, this is unsafe. You're taking a ref to a local var.
Perhaps you intended to copy it to a local member of a non-pointer type?
I realize you'd like to know if it's initialized, so you can have the member be of type std::optional<RunnableType>

BTW note that this is somewhat risky, as now callers to this API must make sure that their callable outlive the inner object, but I don't know this API so it might be OK.

Comment (romange) [reply src/server/transaction.cc:765]: The lifetime of `cb_/cb_ptr_` is only for during of `ScheduleSingleHop/Execute`.

Comment (romange) [reply src/server/transaction.cc:765]: It's true that we could use `std::optional` here but at the end I use `FunctionRef` to accept lambdas which by itself is valid only during the call of these functions.

Comment (chakaz) [reply src/server/transaction.cc:765]: Sure, if the lifetime of `cb_ptr_` is only for the duration of these methods then there's no issue. I didn't realize that, but reading the code now - it makes sense. Sorry about the noise :)

BTW, in the previous version (with `std::function`) the lambdas were moved into the `Transaction` object, so they could have theoretically had a longer lifetime than the function call. I'm not sure if that's what you implied in "... lambdas which by itself is valid only during the call of these functions", but anyway, that's obviously irrelevant.

**Review by dranikpg — APPROVED** [review]

File: src/server/transaction.h [hunk 2]
```diff
@@ -471,7 +478,7 @@ class Transaction {
   // Reverse argument mapping for ReverseArgIndex to convert from shard index to original index.
   std::vector<uint32_t> reverse_index_;
 
-  RunnableType cb_;                   // Run on shard threads
+  RunnableType* cb_ptr_ = nullptr;    // Run on shard threads
```
[the remark this answers is not in the document]
Comment (romange) [reply src/server/transaction.h:481]: It's not pissible to "reset" it or to clear it. I could use optional but decided to use a pointer instead.

File: src/server/transaction.cc (hunk 1 above)
Comment (romange) [reply src/server/transaction.cc:765]: yes, they could - and we paid for it with unnecessary allocation, which I discovered when fixing the bug.
These allocations by themselves are not awful, but their pattern is - to always malloc in one thread and free in another. This puts an unnecessary load on malloc library to move free lists from thread to thread.
those `cb_ = nullptr` are the assignments that reset the function object.
