### PR TITLE
fix(server): Add deprecated/removed lua table functions

### LINKED ISSUE #888: table.getn is missing
**Describe the bug**
Dragonfly `table` module misses `table.getn` function present in Redis

**To Reproduce**
Run the following: `redis-cli  eval "return table.getn{10,2,4}" 0` returns 3 with redis and an error in DF.

Note that DF misses the following methods from the "table" module: `setn`, `getn`, `foreach`, `foreachi`.
because lua deprecated them. it's not clear we need to support all of them

### PR DESCRIPTION
**Pull request by dranikpg**
Fixes #888

### CODE REVIEW

**Review by romange — APPROVED** [review]

File: src/core/interpreter_polyfill.h [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+
+#pragma once
+
+extern "C" {
+#include <lauxlib.h>
+#include <lua.h>
+#include <lualib.h>
+
+// TODO: Fix checktab
+#define aux_getn(L, n, w) (luaL_len(L, n))
```
Comment (dranikpg) [inline src/core/interpreter_polyfill.h:14]: I have no clue what this is and in what cases its error is better than the errors thrown by the raw length function. 

https://github.com/lua/lua/blob/cf08915d62e338c987b71c078b148490510e9fe7/ltablib.c#L46

Comment (dranikpg) [reply src/core/interpreter_polyfill.h:14]: The solutions are:
- copy the checktab code with its dependencies 
- check manually for the table type (which excludes metatable objects that act like tables?)

I chose the second because of simplicity

**Review by romange — APPROVED** [review]
