### PR TITLE
fix(cluster): Don't miss updates in FLUSHSLOTS

### LINKED ISSUE #2771: FLUSHSLOTS bug
When running DFLYCLUSTER FLUSHSLOTS <range_start> <range_end> we want to delete all the slots data in given range.
To do this we create a fiber which will traverse the dash table and if the key belong to this slot and the bucket version is <= version time of the command it will be deleted.
The problem with this implementation is that if while yielding from this fiber we insert new entry to a bucket in which there is a key to be removed as it is in the flush slot range we will update the bucket version hence when we will get to this bucket in the traverse we will not delete the slot data.

### PR DESCRIPTION
**Pull request by chakaz**
This PR registers for PreUpdate() from inside the `FLUSHSLOTS` fiber so that any attempt to update a to-be-deleted key will work as expected (first delete, then apply the change).

This fixes several issues:

* Any attempt to touch bucket B (like insert a key), where another key in B should be removed, caused us to _not_ remove the latter key
* Commands which use an existing value but not completely override then, like `APPEND` and `LPUSH` did not treat the key as removed but instead used the original value

Fixes #2771

### CODE REVIEW

File: src/server/cluster/cluster_family_test.cc [hunk 1]
```diff
@@ -739,27 +648,24 @@ TEST_F(ClusterFamilyTest, FlushSlots) {
                                                   _, "total_writes", _, "memory_bytes", _)))));
 }
 
+TEST_F(ClusterFamilyTest, FlushSlotsAndImmediatelySetValue) {
+  for (string_view count : {"1", "10", "100", "1000", "10000", "100000"}) {
+    ConfigSingleNodeCluster(GetMyId());
+
+    EXPECT_EQ(Run({"debug", "populate", count, "key", "4"}), "OK");
+    EXPECT_THAT(Run({"cluster", "keyslot", "key:0"}), IntArg(2592));
```
Comment (adiholden) [inline src/server/cluster/cluster_family_test.cc:656]: please add
EXPECT_EQ(Run({"get", "key:0"}), "xxxx");

File: src/server/cluster/cluster_family_test.cc [hunk 2]
```diff
@@ -739,27 +648,24 @@ TEST_F(ClusterFamilyTest, FlushSlots) {
...
+    EXPECT_EQ(Run({"dflycluster", "flushslots", "2592", "2592"}), "OK");
+    // key:0 should have been removed, so APPEND will end up with key:0 == ZZZZ
+    EXPECT_THAT(Run({"append", "key:0", "ZZZZ"}), IntArg(4));
+    EXPECT_EQ(Run({"get", "key:0"}), "ZZZZ");
+
```
Comment (adiholden) [inline src/server/cluster/cluster_family_test.cc:661]: maybe you can also run dbsize and dflycluster getslotinfo slots 2592 2592 before after flushslots and check that actually deleted all slot 2592 and only them

**Review by adiholden — APPROVED** [review]
