### PR TITLE
fix(server):Return an error, instead of crashing, for requests trying to rename a key to the same key.

### LINKED ISSUE #850: DF crash when Rename command using source and destination names are the same

### PR DESCRIPTION
**Pull request by chakaz**
Fixes #850

### CODE REVIEW

**Comment by ashotland** [comment]
Hi @chakaz - thanks for your contribution!

Please see 
https://redis.io/commands/rename/

Specifically:
>= 3.2.0: The command no longer returns an error when source and destination names are the same.

Also pleas check the ci test failure

File: src/server/generic_family_test.cc [hunk 1]
```diff
@@ -199,6 +199,14 @@ TEST_F(GenericFamilyTest, RenameNx) {
   ASSERT_EQ(Run({"get", "y"}), x_val);
 }
 
+TEST_F(GenericFamilyTest, RenameSameName) {
+  const char kKey[] = "key";
```
Comment (romange) [inline src/server/generic_family_test.cc:203]: what if the key does not exist? what's the expected behavior in that case?

Comment (chakaz) [reply src/server/generic_family_test.cc:203]: That's a good comment!

Documentation doesn't specifically mention this, but a local test with a redis server shows that an error (ERR no such key) is returned. I'll modify the change to behave the same.

**Review by romange — APPROVED** [review]
