### PR TITLE
chore(search): fix numeric index query in rev order

### LINKED ISSUE #3500: Ram overflow error when querying number range
start: 1723161599
end: 1723075200

query:

`"FT.SEARCH" "sales-orders-idx" @createdAt:[1723161599 1723075200]" "LIMIT" "0" "2"`

when i query small number @createdAt[2 0] no error

image

### PR DESCRIPTION
**Pull request by dranikpg**
Fixes #3500 

Invalid range query caused right tree iterator to be less than left, thus making the `for (left_it ++ != right_it)` loop endless

### CODE REVIEW

File: src/server/search/search_family_test.cc [hunk 1]
```diff
@@ -433,15 +433,12 @@ TEST_F(SearchFamilyTest, Numbers) {
...
-
-  /*
-  TODO: Breaks the parser
-  EXPECT_THAT(Run({"ft.search", "i1", "(@i:[1 3] ! @i:[2 2]) @j:[7 7]"}),
-              DocIds(vector<string>{"i1j7", "i3j7"}));
-  */
+  // Test empty range
+  EXPECT_THAT(Run({"ft.search", "i1", "@i:[9 1]"}), AreDocIds());
+  EXPECT_THAT(Run({"ft.search", "i1", "@j:[5 0]"}), AreDocIds());
+  EXPECT_THAT(Run({"ft.search", "i1", "@i:[7 1] @j:[6 2]"}), AreDocIds());
```
Comment (BagritsevichStepan) [inline src/server/search/search_family_test.cc:441]: I would add some ranges with doubles

**Review by BagritsevichStepan — APPROVED** [review]
