### PR TITLE
fix: do not crash upon inconsistent expire iterator

### LINKED ISSUE #4656: Crash inside DbSlice::DeleteExpiredStep
**Describe the bug**

```
Feb 24 17:35:05 dragonfly[2242]: W20250224 17:35:05.476962  2244 dragonfly_connection.cc:1030] Pipeline buffer over limit: pipeline_bytes 128738606 queue_size 670, conside...
Feb 24 17:35:13 dragonfly[2242]: F20250224 17:35:13.737923  2244 db_slice.cc:1239] Check failed: !prime_it.is_done()                                                        
Feb 24 17:35:13 dragonfly[2242]: *** Check failure stack trace: ***                                                                                                         
Feb 24 17:35:13 dragonfly[2242]:     @     0x555556185923  google::LogMessage::SendToLog()                                                                                  
Feb 24 17:35:13 dragonfly[2242]:     @     0x55555617e0e7  google::LogMessage::Flush()                                                                                      
Feb 24 17:35:13 dragonfly[2242]:     @     0x55555617fa6f  google::LogMessageFatal::~LogMessageFatal()                                                                      
Feb 24 17:35:13 dragonfly[2242]:     @     0x5555559dba53  _ZN4dfly9DashTableINS_10CompactObjENS_12ExpirePeriodENS_6detail17ExpireTablePolicyEE8TraverseIRZNS_7DbSlice17Del>
Feb 24 17:35:13 dragonfly[2242]:     @     0x5555559dbe83  dfly::DbSlice::DeleteExpiredStep()                                                                               
Feb 24 17:35:13 dragonfly[2242]:     @     0x555555957687  dfly::EngineShard::RetireExpiredAndEvict()                                                                       
Feb 24 17:35:13 dragonfly[2242]:     @     0x555555958bc8  dfly::EngineShard::Heartbeat()                                                                                   
Feb 24 17:35:13 dragonfly[2242]:     @     0x555555953c23  dfly::RunFPeriodically()                                                                                         
Feb 24 17:35:13 dragonfly[2242]:     @     0x555555954468  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberEN4util3fb219FixedStackAllocatorEZNS6_6detail>
Feb 24 17:35:13 dragonfly[2242]:     @     0x555555f8aa8f  make_fcontext                                                                                                    
Feb 24 17:35:13 dragonfly[2242]: *** SIGABRT received at time=1740418513 on cpu 1 ***                                                                                       
Feb 24 17:35:13 dragonfly[2242]: PC: @     0x7ffff7c9eb1c  (unknown)  pthread_kill                                                                                        
```

**Additional context**
v1.25.6

### PR DESCRIPTION
**Pull request by romange**
Fixes #4656

### CODE REVIEW

File: src/server/db_slice.cc [hunk 1]
```diff
@@ -1311,17 +1311,24 @@ auto DbSlice::DeleteExpiredStep(const Context& cntx, unsigned count) -> DeleteEx
...
       return;
 
     result.traversed++;
     time_t ttl = ExpireTime(it) - cntx.time_now_ms;
     if (ttl <= 0) {
       auto prime_it = db.prime.Find(it->first);
-      CHECK(!prime_it.is_done());
-      result.deleted_bytes += prime_it->first.MallocUsed() + prime_it->second.MallocUsed();
-      ExpireIfNeeded(cntx, prime_it);
+      if (prime_it.is_done()) {  // A workaround for the case our tables are inconsistent.
```
Comment (kostasrim) [inline src/server/db_slice.cc:1322]: Do we understand under what conditions the tables are inconsistent ?

**Review by adiholden — APPROVED** [review]

File: src/server/db_slice.cc (hunk 1 above)
Comment (romange) [reply src/server/db_slice.cc:1322]: no
