### PR TITLE
fix(rename-command): Fix subtle UB when renaming commands

### LINKED ISSUE #2131: Dragonfly 1.12.0 does not accept renamed commands longer than 15 chars
**Describe the bug**
Title. This is a regression from Dragonfly 1.11.0, where it used to work.

**To Reproduce**
1. `./dragonfly  --logtostderr --rename_command save=abcdefghijklmnop`
2. In a different terminal: 
```
redis-cli
127.0.0.1:6379> abcdefghijklmnop
(error) ERR unknown command `ABCDEFGHIJKLMNOP
```

3. `./dragonfly  --logtostderr --rename_command save=abcdefghijklmno`
4. In a different terminal: 
```
redis-cli
127.0.0.1:6379> abcdefghijklmno
OK
```

**Expected behavior**
Command renames should work when they're longer than 15 chars. I think it's ok to have a sane length limit, but 15 seems too short, I guess there's a "2 bytes" bug somewhere.

**Environment (please complete the following information):**
 - OS: Fedora 38
 - Kernel: Linux toolbox 6.5.8-100.fc37.x86_64
 - Containerized?: Fedora toolbox container
 - Dragonfly Version: 1.12.0

### PR DESCRIPTION
**Pull request by chakaz**
In practive, commands larger than SSO would not work.

Fixes #2131

### CODE REVIEW

File: src/server/command_registry.cc [hunk 1]
```diff
@@ -117,7 +117,7 @@ void CommandRegistry::Init(unsigned int thread_count) {
 }
 
 CommandRegistry& CommandRegistry::operator<<(CommandId cmd) {
-  auto k = cmd.name();
+  string k = string(cmd.name());
```
Comment (chakaz) [inline src/server/command_registry.cc:120]: The bug was really in line 129, where the result of the trinary expression was of type `string` (because `StrCat()` returns `string`), which would then make `k` point to an invalid `string` in all cases, even when `is_sub_command` is `false`

Comment (adiholden) [reply src/server/command_registry.cc:120]: @kostasrim did you chek the restricted command with this changes? If dragonfly starts with ACL as restricted command and someone issues ACL subcommand will it still be restricted?

Comment (chakaz) [reply src/server/command_registry.cc:120]: Nice catch!
(unrelated to this change though, but nice!)

Comment (romange) [reply src/server/command_registry.cc:120]: nice catch, Shahar.

**Review by adiholden — APPROVED** [review]

File: src/server/command_registry.cc (hunk 1 above)
Comment (kostasrim) [reply src/server/command_registry.cc:120]: @adiholden nope but it should be a straightforward fix. I will take care of it
