### PR TITLE
fix(tls): User friendly logging of OpenSSL errors

### LINKED ISSUE #1588: crash on access problem to TLS key file
Had a premission error (file was only readable by root) and got this error:
```
F20230724 12:04:10.363903  1352 dragonfly_listener.cc:77] Check failed: 1 == SSL_CTX_use_PrivateKey_file(ctx, tls_key_file.c_str(), 1) (1 vs. 0) 
*** Check failure stack trace: ***
    @     0x5627f4e7ca21  google::LogMessage::Fail()
    @     0x5627f4e7c967  google::LogMessage::SendToLog()
    @     0x5627f4e7c13c  google::LogMessage::Flush()
    @     0x5627f4e7ffb4  google::LogMessageFatal::~LogMessageFatal()
    @     0x5627f49d668d  facade::(anonymous namespace)::CreateSslServerCntx()
```

### PR DESCRIPTION
**Pull request by royjacobson**
Fixes #1588 

cc @Abhra303

### CODE REVIEW

File: src/server/protocol_client.cc [hunk 1]
```diff
@@ -51,18 +53,35 @@ using absl::StrCat;
 namespace {
 
 #ifdef DFLY_USE_SSL
+
+void PrintSSLError() {
```
Comment (kostasrim) [inline src/server/protocol_client.cc:57]: You implemented this and the `SSL_CHECK` macro twice. Maybe to avoid duplication you can move that in a header `sslerror.h` (or any other name) ?

**Review by kostasrim — APPROVED** [review]

File: src/server/protocol_client.cc (hunk 1 above)
Comment (royjacobson) [reply src/server/protocol_client.cc]: done

**Review by kostasrim — APPROVED** [review]
