### PR TITLE
fix: QUIT pipeline flush

### LINKED ISSUE #6516: v1.36.0 breaks many tests in BullMQ
**Describe the bug**
This new version has introduced some regression that breaks many many tests in BullMQ. I cannot really see a pattern here yet, maybe you can point it out easier than us. But is seems like it is closing connections when
we do some operations maybe in LUA scripts or something...

**To Reproduce**
Try to run BullMQ test suite with dragonflyDB
https://github.com/taskforcesh/bullmq/actions/runs/21482055900/job/61880800894?pr=3654

**Expected behavior**
All tests should pass as they normally have been doing.

**Screenshots**

**Environment (please complete the following information):**
 - OS:  Ubuntu
  24.04.3
  LTS
 - Kernel: # Command: `uname -a`
 - Containerized?:Github Actions
 - Dragonfly Version: [e.g. 1.36.0]

**Reproducible Code Snippet**
```
# Minimal code snippet to reproduce this bug
```

**Additional context**

### PR DESCRIPTION
**Pull request by vyavdoshenko**
Summary:
- Fix the QUIT command in the pipeline, closing the socket before replies are flushed
- Fix key expiration being completely disabled during GLOBAL-mode Lua scripts (EVAL with allow-undeclared-keys)
- Rewrite BullMQ CI workflow to build from source

Changes:
- main_service.cc: Remove ShutdownSelfBlocking() from QUIT handler to avoid closing socket mid-pipeline
- dragonfly_connection.cc: Move socket shutdown to AsyncFiber after dispatch loop exits and replies are flushed
- connection_test.py: Add test_quit_in_pipeline regression test
- bullmq-tests.yml: Build Dragonfly from source instead of using the weekly container image

Success test run: https://github.com/dragonflydb/dragonfly/actions/runs/21563003843/job/62129895726

Partially Fixes #6516

### CODE REVIEW

File: src/facade/dragonfly_connection.cc [hunk 1]
```diff
@@ -1725,6 +1725,14 @@ void Connection::AsyncFiber() {
   }
 
   DCHECK(cc_->conn_closing || reply_builder_->GetError());
+
+  // If a command (e.g. QUIT) called CloseConnection(), the reply builder has an error
+  // but the socket is still open. Shut it down now that all replies have been flushed,
+  // which also wakes up the IoLoop blocked on socket reads.
+  if (reply_builder_->GetError() && !cc_->conn_closing) {
+    ShutdownSelfBlocking();
```
Comment (romange) [inline src/facade/dragonfly_connection.cc]: It's not a good fix  but you found a problem. I will think how to fix it better!
cc'ing @dranikpg  - as well.
we do not want to "catch" quit condition based on these symptoms for sure.

File: src/server/db_slice.cc [hunk 2]
```diff
@@ -1292,9 +1292,11 @@ DbSlice::PrimeItAndExp DbSlice::ExpireIfNeeded(const Context& cntx, PrimeIterato
...
   int64_t expire_time = ExpireTime(expire_it->second);
 
-  // Never do expiration on replica or if expiration is disabled or global lock was taken.
-  if (int64_t(cntx.time_now_ms) < expire_time || owner_->IsReplica() || !expire_allowed_ ||
-      !shard_owner()->shard_lock()->Check(IntentLock::Mode::EXCLUSIVE)) {
+  // Never do expiration on replica or if expiration is disabled.
+  // Note: we no longer skip expiration when a global (EXCLUSIVE) shard lock is held,
+  // because sub-commands within a global transaction (e.g. EVAL in GLOBAL mode) execute
+  // sequentially and won't hold iterators across calls, so deletion is safe.
+  if (int64_t(cntx.time_now_ms) < expire_time || owner_->IsReplica() || !expire_allowed_) {
```
[the remark this answers is not in the document]
Comment (romange) [reply src/server/db_slice.cc]: can you please explain what are you fixing here?

File: tests/dragonfly/connection_test.py [hunk 3]
```diff
@@ -1565,3 +1565,63 @@ async def test_issue_6165_squash_invalid_syntax(async_client):
     res = await pip.execute(raise_on_error=False)
     assert res[0] == True  # SET key1
     assert isinstance(res[1], aioredis.ResponseError)  # INVALID SYNTAX
+
+
+@dfly_args({"proactor_threads": "2", "pipeline_squash": 1})
+async def test_quit_in_pipeline(df_server: DflyInstance):
+    """
+    Regression test: when QUIT is pipelined together with other commands
```
Comment (romange) [inline tests/dragonfly/connection_test.py:1573]: the test can be simplified. why do you need SET for issuing DELs? is it important to the test?
in general, lets minimize it to whatever is necessary to reproduce the bug.

Also, please consider using `async_client` with `pipeline(Transaction=False)` interface - see `run_pipeline_mode` for example

File: src/server/db_slice.cc (hunk 2 above)
[the remark this answers is not in the document]
Comment (vyavdoshenko) [reply src/server/db_slice.cc]: Dragonfly doesn't remove the keys in Lua scripts because of EXCLUSIVE condition. BullMQ tests check the expired keys during the run, and these tests fail. From my understanding, it's safe to remove the expired keys even during EVAL execution.

[the remark this answers is not in the document]
Comment (dranikpg) [reply src/server/db_slice.cc]: I missed when this check was added. This is bad design. We already have `Transaction::Guard` that bans expiry by explicitly disabling it. We should see in the git history for what case this was added and fix it instead

File: src/facade/dragonfly_connection.cc (hunk 1 above)
Comment (dranikpg) [reply src/facade/dragonfly_connection.cc]: Having a control message or a safe shutdown function that sets flags and wakes up would probably be the easiest

File: tests/dragonfly/connection_test.py (hunk 3 above)
Comment (dranikpg) [reply tests/dragonfly/connection_test.py:1573]: Yes, we use sockets only if we're not okay with how the client sends/receives data. It seems like this test can easily be changed to just redis-py usage

File: src/server/db_slice.cc (hunk 2 above)
[the remark this answers is not in the document]
Comment (dranikpg) [reply src/server/db_slice.cc]: Given that nothing from the tests failed we don't know what it was added for 🙂 But it can be some tricky corner case for migrations or any of the new code we added last year

File: .github/workflows/bullmq-tests.yml [hunk 4]
```diff
@@ -10,62 +9,65 @@ jobs:
...
+          cd ${GITHUB_WORKSPACE}/build && ninja dragonfly
+
+      - name: Install Node.js
         run: |
           wget -q https://unofficial-builds.nodejs.org/download/release/v22.12.0/node-v22.12.0-linux-x64-glibc-217.tar.xz
           tar -xf node-v22.12.0-linux-x64-glibc-217.tar.xz
-          sudo cp -r node-v22.12.0-linux-x64-glibc-217/* /usr/local/
-          sudo apt install yarn jq
+          cp -r node-v22.12.0-linux-x64-glibc-217/* /usr/local/
+          apt-get update && apt-get install -y jq
```
Comment (glevkovich) [inline .github/workflows/bullmq-tests.yml]: nit:
versions repeat 3 times, its less maintainable and readable, and error prune. I suggest to use environment variables::

```
NODE_VER="v22.12.0"
NODE_DIST="node-${NODE_VER}-linux-x64-glibc-217"
          
wget -q https://unofficial-builds.nodejs.org/download/release/${NODE_VER}/${NODE_DIST}.tar.xz
tar -xf ${NODE_DIST}.tar.xz
cp -r ${NODE_DIST}/* /usr/local/
```

File: .github/workflows/bullmq-tests.yml [hunk 5]
```diff
@@ -10,62 +9,65 @@ jobs:
...
+      - name: Start Dragonfly
+        run: |
+          ${GITHUB_WORKSPACE}/build/dragonfly \
+            --alsologtostderr \
+            --cluster_mode=emulated \
+            --lock_on_hashtags \
+            --default_lua_flags=allow-undeclared-keys \
+            --dbfilename= \
+            --port 6379 &
+          sleep 3
```
Comment (glevkovich) [inline .github/workflows/bullmq-tests.yml]: nit: consider a safer / faster approach:
`timeout 15s bash -c 'until redis-cli -p 6379 PING; do sleep 0.1; done'`

File: .github/workflows/bullmq-tests.yml [hunk 6]
```diff
@@ -10,62 +9,65 @@ jobs:
...
         run: |
-          mkdir -p $GITHUB_WORKSPACE/../bullmq
-          cd $GITHUB_WORKSPACE/../bullmq
-          # TODO: Use BullMQ latest release instead of our fork:
-          # DOWNLOAD_URL=$(curl -s https://api.github.com/repos/taskforcesh/bullmq/releases/latest | jq -r '.tarball_url')
-          # echo "Downloading latest BullMQ release from ${DOWNLOAD_URL}"
-          # wget -O bullmq.tar.gz ${DOWNLOAD_URL}
-          # tar -zxvf bullmq.tar.gz
-          # mv taskforcesh-bullmq-* bullmq
+          mkdir -p /tmp/bullmq && cd /tmp/bullmq
```
Comment (glevkovich) [inline .github/workflows/bullmq-tests.yml]: Are you intentionally using /tmp/ ? As far as i know Guthub actions knows how to handle disk IO better, with better disk performance when using $GITHUB_WORKSPACE. I suggest tohave the repo in $GITHUB_WORKSPACE/bullmq .

File: src/server/db_slice.cc (hunk 2 above)
[the remark this answers is not in the document]
Comment (romange) [reply src/server/db_slice.cc]: > Dragonfly doesn't remove the keys in Lua scripts because of EXCLUSIVE condition. BullMQ tests check the expired keys during the run, and these tests fail. From my understanding, it's safe to remove the expired keys even during EVAL execution.

We need a unit test for this. In dragonfly_test or multi_test  - that verifies the correct behavior. I suggest taking it out of this PR and do it separately

[the remark this answers is not in the document]
Comment (dranikpg) [reply src/server/db_slice.cc]: https://github.com/dragonflydb/dragonfly/pull/4967
https://github.com/dragonflydb/dragonfly/pull/5151
https://github.com/dragonflydb/dragonfly/issues/5169

[the remark this answers is not in the document]
Comment (kostasrim) [reply src/server/db_slice.cc]: @dranikpg bad design or not we just added a new bug here. 

`Heartbeat` will not `skip` expirations on keys that are locked. So for multi hop transactions this will break the state. 

In other words, this change should break `ExpireIfNeeded` + heartbeat unless I am missing something

[the remark this answers is not in the document]
Comment (kostasrim) [reply src/server/db_slice.cc]: oh hold that for for the global lock (shard lock), just a second

[the remark this answers is not in the document]
Comment (kostasrim) [reply src/server/db_slice.cc]: Ok now I remember: 

The bug:
entries were expired at the time of transitioning from full sync to stable sync leading to journal changes not propagated to replica.
The fix:

[the remark this answers is not in the document]
Comment (kostasrim) [reply src/server/db_slice.cc]: This change will break data parity for replication

[the remark this answers is not in the document]
Comment (kostasrim) [reply src/server/db_slice.cc]: > Given that nothing from the tests failed we don't know what it was added for 🙂 But it can be some tricky corner case for migrations or any of the new code we added last year

I know why cause I helped with that investigation and I now remember. In short, we break data parity in replication

[the remark this answers is not in the document]
Comment (kostasrim) [reply src/server/db_slice.cc]: and a small rant to myself -- ALWAYS leave a comment for cases like that. Otherwise we all question the rationale and some corner cases which do not have unit tests are hard to verify :/ 

always always leave a comment

[the remark this answers is not in the document]
Comment (dranikpg) [reply src/server/db_slice.cc]: But don't we already skip the heartbeat if a global lock is acquired?

[the remark this answers is not in the document]
Comment (kostasrim) [reply src/server/db_slice.cc]: hmm actually this is also true 🤔 (and I think I added that check) + all the changes that made heartbeat non-preemptive (i.e. `atomic`).

I will take a look again a little later but it seems you are right

[the remark this answers is not in the document]
Comment (vyavdoshenko) [reply src/server/db_slice.cc]: @dranikpg @kostasrim
I suggest to continue discussion here: https://github.com/dragonflydb/dragonfly/pull/6524
I will remove this change here.

File: .github/workflows/bullmq-tests.yml (hunk 4 above)
Comment (romange) [reply .github/workflows/bullmq-tests.yml]: Also, please consider using the github action that installs node https://github.com/actions/setup-node

File: .github/workflows/bullmq-tests.yml [hunk 7]
```diff
@@ -10,62 +9,65 @@ jobs:
...
-#          cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja
-#          ninja dragonfly
-#          ./dragonfly --alsologtostderr --cluster_mode=emulated --lock_on_hashtags --dbfilename= &
+      - name: Start Dragonfly
+        run: |
+          ${GITHUB_WORKSPACE}/build/dragonfly \
+            --alsologtostderr \
+            --cluster_mode=emulated \
+            --lock_on_hashtags \
+            --default_lua_flags=allow-undeclared-keys \
```
Comment (romange) [inline .github/workflows/bullmq-tests.yml:57]: do we need `default_lua_flags` here?

File: .github/workflows/bullmq-tests.yml [hunk 8]
```diff
@@ -10,62 +9,65 @@ jobs:
...
           cd bullmq
-          pwd
           yarn install
           yarn build
 
       - name: Run BullMQ tests
         run: |
-          cd $GITHUB_WORKSPACE/../bullmq/bullmq
+          cd /tmp/bullmq/bullmq
           BULLMQ_TEST_PREFIX={b} yarn test
```
Comment (romange) [inline .github/workflows/bullmq-tests.yml:73]: if some tests fail but many pass, consider using `--testPathIgnorePatterns` or equivalent to establish a green base line. this will also give us clarity what tests need to be investigated

File: tests/dragonfly/connection_test.py [hunk 9]
```diff
@@ -1565,3 +1565,63 @@ async def test_issue_6165_squash_invalid_syntax(async_client):
...
+    pipeline = ""
+    for i in range(NUM_KEYS):
+        pipeline += resp_encode("DEL", f"{{b}}:pqt:k{i}")
+    pipeline += resp_encode("QUIT")
+    s.sendall(pipeline.encode())
+
+    # Read all responses: NUM_KEYS ":1\r\n" for DELs + "+OK\r\n" for QUIT
+    data = b""
+    try:
+        while True:
```
[the remark this answers is not in the document]
Comment (vyavdoshenko) [reply tests/dragonfly/connection_test.py]: Not actual, test simpified

File: tests/dragonfly/connection_test.py (hunk 3 above)
Comment (vyavdoshenko) [reply tests/dragonfly/connection_test.py:1573]: Test simplified. Please take a look.

File: .github/workflows/bullmq-tests.yml (hunk 5 above)
Comment (vyavdoshenko) [reply .github/workflows/bullmq-tests.yml]: Fixed

File: .github/workflows/bullmq-tests.yml (hunk 6 above)
Comment (vyavdoshenko) [reply .github/workflows/bullmq-tests.yml]: Fixed

File: .github/workflows/bullmq-tests.yml (hunk 4 above)
Comment (vyavdoshenko) [reply .github/workflows/bullmq-tests.yml]: @glevkovich - Fixed.

@romange
actions/setup-node doesn't work in our container — Node 20+ requires glibc >= 2.28, but ubuntu-dev:20-gcc14 has glibc 2.17. That's why we use unofficial builds with the glibc-217 suffix.

File: .github/workflows/bullmq-tests.yml (hunk 7 above)
Comment (vyavdoshenko) [reply .github/workflows/bullmq-tests.yml:57]: `--default_lua_flags=allow-undeclared-keys` is needed because some BullMQ tests (4 tests) intentionally access keys not passed via KEYS[] (e.g., the Telemetry Flows error-handling test does redis.call('GET', 'invalidQueue:invalidParentId') where that key is not in KEYS[]). Without this flag, Dragonfly rejects undeclared key access.

File: .github/workflows/bullmq-tests.yml (hunk 8 above)
Comment (vyavdoshenko) [reply .github/workflows/bullmq-tests.yml:73]: Why? I would like to merge this PR and https://github.com/dragonflydb/dragonfly/pull/6524 PR. All tests must be green after these PRs.

Comment (romange) [reply .github/workflows/bullmq-tests.yml:73]: we do not run dragonfly with bullmq with `--default_lua_flags=allow-undeclared-keys` in production.
so once we identify the problematic tests we can check with bullmq maintainers what we can do.

File: .github/workflows/bullmq-tests.yml (hunk 7 above)
Comment (romange) [reply .github/workflows/bullmq-tests.yml:57]: see below. we can  maybe fix the tests by respecting `BULLMQ_TEST_PREFIX` or we can exclude them. in any case `allow-undeclared-keys` may hide real problems. we can keep it as is and follow up later.

**Review by romange — APPROVED** [review]
