### PR TITLE
fix: deadlock in Heartbeat()

### LINKED ISSUE #3472: test_network_disconnect_small_buffer deadlock
see https://github.com/dragonflydb/dragonfly/actions/runs/10299101135/job/28505690954 + logs

### PR DESCRIPTION
**Pull request by kostasrim**
The problem is that we lock the same mutex `db_slice.GetSerializationMutex()` twice on the same fiber.

We first lock it in `RetireExpiredAndEvict()` and then eventually we write the expired items on the journal via (in the call path of `ExpireIfNeeded`) a call to `RecordExpired` which will apply the callbacks registered by the snapshot. These callbacks, acquire the same mutex:

```
  384 void SliceSnapshot::OnJournalEntry(const journal::JournalItem& item, bool await) {                 
  385   // To enable journal flushing to sync after non auto journal command is executed we call         
  386   // TriggerJournalWriteToSink. This call uses the NOOP opcode with await=true. Since there is no  
  387   // additional journal change to serialize, it simply invokes PushSerializedToChannel.            
  388   std::unique_lock lk(db_slice_->GetSerializationMutex());                                         
  389   if (item.opcode != journal::Op::NOOP) {                                                          
  390     serializer_->WriteJournalEntry(item.data);
  391   }  
  392 
```

Fixes #3472 and #3464

* acquire and immediately release db_slice.GetSerializationMutex() in Heartbeat()

### CODE REVIEW

**Comment by kostasrim** [comment]
@dranikpg courtesy of deadlock <<<ME>>>> :face_exhaling: :facepalm:

File: src/server/engine_shard.cc [hunk 1]
```diff
@@ -633,8 +633,10 @@ void EngineShard::Heartbeat() {
 void EngineShard::RetireExpiredAndEvict() {
   // TODO: iterate over all namespaces
   DbSlice& db_slice = namespaces.GetDefaultNamespace().GetDbSlice(shard_id());
-  // Some of the functions below might acquire the lock again so we need to unlock it
-  std::unique_lock lk(db_slice.GetSerializationMutex());
+  // Some of the functions below might acquire the same lock again so we need to unlock it
+  // asap. We won't yield before we relock the mutex again, so the code below is atomic
+  // in respect to preemptions.
+  { std::unique_lock lk(db_slice.GetSerializationMutex()); }
```
Comment (dranikpg) [inline src/server/engine_shard.cc:639]: 1. So to understand, please comment why we acquire it - i.e. just to check none is in progress
2. We can test the atomicity with FiberAtomicGuard (just disarm it beofre TriggerJournalWriteToSink)

**Review by dranikpg — DISMISSED** [review]

File: src/server/engine_shard.cc (hunk 1 above)
Comment (kostasrim) [reply src/server/engine_shard.cc:639]: >We can test the atomicity with FiberAtomicGuard (just disarm it beofre TriggerJournalWriteToSink)
I manually unlock it before, we acquired the lock in the for loop above. I will add a comment

Comment (dranikpg) [reply src/server/engine_shard.cc:639]: > I manually unlock it before, we acquired the lock in the for loop above. I will add a comment

I mean to ensure for future code changes

Comment (kostasrim) [reply src/server/engine_shard.cc:639]: What I am trying to say here, is that the `FiberGuard` won't add much because we lock the same mutex within the for loop. The bug was not that we forget to unlock it before we call TriggerJournalWriteToSink, but before it, in the for loop above.

Comment (kostasrim) [reply src/server/engine_shard.cc:639]: What am I missing in your suggestion ?

**Review by dranikpg — APPROVED** [review]
Discussed privately. +1 to removing the locks somewhere in the future 🙂
