### PR TITLE
fix(server): Fix path concatenation in save

### LINKED ISSUE #480: dir argument is sensitive to the trailing slash
if we pass `--dir /foo` then dragonfly tries to save `/foodump...` which is incorrect. 
if we provide the unexisting directory we silently switch to none.

the expected behavior: 
1. it should verify that `/foo` is indeed a directory and join with it the filename correctly.
2. in case `/foo` does not exist, it should at least output an error that the passed directory does not exist. maybe even exit with the error.

### PR DESCRIPTION
**Pull request by dranikpg**
Fix #480

### CODE REVIEW

File: src/server/server_family.cc [hunk 1]
```diff
@@ -895,7 +895,7 @@ error_code ServerFamily::DoSave(bool new_version, Transaction* trans, string* er
     snapshots.resize(1);
 
     ExtendFilenameWithShard(now, -1, &filename);
-    path += filename;
+    path /= filename;
```
Comment (romange) [inline src/server/server_family.cc:898]: maybe add a comment saying that `/=` is important because it appends to a directory as opposed to a string.

**Review by romange — APPROVED** [review]
