### PR TITLE
fix: crash during migration when connection is closing

### LINKED ISSUE #2905: crash during migration
The stack is below.
The original run is here: https://github.com/dragonflydb/dragonfly/actions/runs/8687966303/job/23822589772?pr=2889#step:12:1651

```
41939➜ 11:20:33.147712 34150 listener_interface.cc:238] sock[14] After HandleRequests
38999➜ 11:20:33.147707 34135 dragonfly_connection.cc:1068] [3] Got event 8208 2 0 system:0
38999➜ 11:20:33.147722 34134 listener_interface.cc:238] sock[15] After HandleRequests
38999➜ 11:20:33.147756 34134 listener_interface.cc:246] sock[15] Closing connection
41939➜ 11:20:33.147756 34148 protocol_client.cc:288] Socket error system:103
38999➜ 11:20:33.147663 34136 dragonfly_connection.cc:552] Connection::OnShutdown
41939➜ 11:20:33.147663 34149 protocol_client.cc:288] Socket error system:103
38999➜ 11:20:33.148373 34134 listener_interface.cc:203] Listener - 38999 waiting for 4 connections to close
41939➜ 11:20:33.147759 34150 listener_interface.cc:246] sock[14] Closing connection
38999➜ 11:20:33.148381 34135 listener_interface.cc:343] Migrated 0x380c0150f80 from 3 to 2 0x7f866afbbf00
38999➜ 11:20:33.148425 34135 listener_interface.cc:328] Migrating 0x380c0150b80 from 34135(2) 0x7f866afbbf00 to 34134
38999➜ 11:20:33.148438 34135 dragonfly_connection.cc:562] Check failed: !cc_->conn_closing 
41939➜ 11:20:33.149036 34150 protocol_client.cc:288] Socket error system:103
41939➜ 11:20:33.149076 34150 main_service.cc:2427] Switching state from LOADING to ACTIVE
41939➜ 11:20:33.149139 34150 replica.cc:225] Error syncing with localhost:38999 system:103 Software caused connection abort
41939➜ 11:20:33.149147 34148 protocol_client.cc:257] Could not shutdown socket system:107
38999➜ Check failure stack trace: ***
38999➜    @     0x55c907b49d40  google::LogMessage::Fail()
38999➜    @     0x55c907b50f33  google::LogMessage::SendToLog()
38999➜    @     0x55c907b496f7  google::LogMessage::Flush()
38999➜    @     0x55c907b4b07f  google::LogMessageFatal::~LogMessageFatal()
38999➜    @     0x55c9076c0f5c  facade::Connection::OnPreMigrateThread()
38999➜    @     0x55c907af5c85  util::ListenerInterface::Migrate()
```

### PR DESCRIPTION
**Pull request by kostasrim**
resolves #2905 

The problem is that DF might be shutting down (which sets the connection_closing to true) and a call to `Migrate` will trigger the check that the connection is not closing. The fix is simple: just return false when Migrate is called and the connection is closing.

* Return false when Migrate is called on a closing connection

### CODE REVIEW

File: src/facade/dragonfly_connection.cc [hunk 1]
```diff
@@ -1456,6 +1456,10 @@ bool Connection::Migrate(util::fb2::ProactorBase* dest) {
     return false;
   }
 
+  if (cc_->conn_closing) {
```
Comment (romange) [inline src/facade/dragonfly_connection.cc:1459]: seems that it can be merged into the condition at line 1455

**Review by romange — APPROVED** [review]
