### PR TITLE
fix: race condition during flush slots

### LINKED ISSUE #7058: test_replicate_disconnect_cluster failes
https://github.com/dragonflydb/dragonfly/actions/runs/23893422815/job/69672130574

### PR DESCRIPTION
**Pull request by BorysTheDev**
fixes: #7058

Fixes a race in cluster FLUSHSLOTS where the async traversal could capture the version threshold too late and delete keys inserted immediately after the flush started.

### CODE REVIEW

**Comment by BorysTheDev** [comment]
augment review

**Comment by BorysTheDev** [comment]
augment review

File: src/server/db_slice.cc [hunk 1]
```diff
@@ -898,8 +871,53 @@ void DbSlice::FlushSlotsFb(const cluster::SlotSet& slot_ids) {
...
+      }
+    } else {
+      for (auto it : std::get<PrimeTable::BucketSet>(req).buckets()) {
+        if (!it.is_done() && it.GetVersion() < next_version)
+          process_bucket(it);
+      }
+    }
+  };
+
+  uint64_t cb_id = RegisterOnChange(std::move(on_change));
```
Comment (dranikpg) [inline src/server/db_slice.cc:917]: this is a good catch, 
you can see that there is a commented out DCHECK in RegisterOnChange

```
DCHECK(!owner_->shard_lock()->IsFree())
```

I commented it out because I saw that flush slots is using the API wrongly - it should subscribe only from a transaction. 

Please uncomment it

**Review by dranikpg — DISMISSED** [review]

**Review by dranikpg — APPROVED** [review]
