### PR TITLE
fix: stream memory tracking

### LINKED ISSUE #4028: MEMORY USAGE for STREAM keys always return (integer) 0
**Describe the bug**
MEMORY USAGE for STREAM keys always return (integer) 0

**To Reproduce**
Steps to reproduce:
1. Create stream using `XADD test-stream * just test`
2. Query stream size `MEMORY USAGE test-stream`
3. Result `(integer) 0`

**Expected behavior**
1. Create stream using `XADD test-stream * just test`
2. Query stream size `MEMORY USAGE test-stream`
3. Result `(integer) 4736`  (example from redis_version:7.2.6)

**Environment (please complete the following information):**
 - OS: `Ubuntu 24.04`
 - Kernel: `Linux 6.8.0-47-generic #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 22:03:50 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux`
 - Containerized?: `Docker version 27.3.1, build ce12230` `image: 'docker.dragonflydb.io/dragonflydb/dragonfly:v1.24.0'`
 - Dragonfly Version: v1.24.0

### PR DESCRIPTION
**Pull request by kostasrim**
Stream memory tracking was a noop. This PR fixes that.

Resolves #4028

### CODE REVIEW

File: src/core/compact_object.cc [hunk 1]
```diff
@@ -107,9 +107,95 @@ size_t MallocUsedZSet(unsigned encoding, void* ptr) {
...
+  /* Now we have to add the listpacks. The last listpack is often non
+   * complete, so we estimate the size of the first N listpacks, and
+   * use the average to compute the size of the first N-1 listpacks, and
+   * finally add the real size of the last node. */
+  raxIterator ri;
+  raxStart(&ri, s->rax_tree);
+  raxSeek(&ri, "^", nullptr, 0);
+  size_t lpsize = 0;
+  size_t samples = 0;
+  while (samples < s->length && raxNext(&ri)) {
```
Comment (kostasrim) [inline src/core/compact_object.cc:147]: Taken as is from Valkey, I just simplified it a little bit

File: src/core/compact_object.cc [hunk 2]
```diff
@@ -108,8 +108,51 @@ size_t MallocUsedZSet(unsigned encoding, void* ptr) {
...
+
+  raxIterator ri;
+  raxStart(&ri, s->rax_tree);
+  raxSeek(&ri, "^", nullptr, 0);
+  size_t lpsize = 0;
+  while (raxNext(&ri)) {
+    auto* lp = (unsigned char*)ri.data;
+    lpsize += zmalloc_size(lp);
+  }
+  raxStop(&ri);
```
Comment (chakaz) [inline src/core/compact_object.cc:125]: I'm not entirely sure how streams work, but I guess this operation is not O(1), right?
All other types' memory usage is very quick, and I think(?) this is a requirement

Comment (kostasrim) [reply src/core/compact_object.cc:125]: nope what you see here is not O(1) as it requires traversing the radix tree. Valkey approximates this with sampling. 

> All other types' memory usage is very quick, and I think(?) this is a requirement
Yes I agree for other types is more trivial but it's a data structure we don't control (we would need to change the radix tree to include how much memory it consumes and make this a constant operation). 

I am open to suggestions on how we can improve here

Comment (chakaz) [reply src/core/compact_object.cc:125]: First, you should verify if this is indeed a requirement. I _think_ it is, but it doesn't mean I'm right :)
Look in which flows we call this, and if it could be in hot paths etc.

If it is, then perhaps we should keep some cache for this value, and update it on the modification operations. We do something similar in Json, look for `JsonMemTracker`.

Comment (romange) [reply src/core/compact_object.cc:125]: it is a requirement. but this PR is not a high priority compared to other tasks (big value serialization)

Comment (kostasrim) [reply src/core/compact_object.cc:125]: > If it is, then perhaps we should keep some cache for this value, and update it on the modification operations. We do something similar in Json, look for JsonMemTracker.

Yep +1

> it is a requirement. but this PR is not a high priority compared to other tasks (big value serialization)
+1

File: src/core/compact_object.cc [hunk 3]
```diff
@@ -811,6 +810,13 @@ void CompactObj::SetJsonSize(int64_t size) {
   }
 }
 
+void CompactObj::SetStreamSize(int64_t size) {
+  if (size < 0) {
+    DCHECK(static_cast<int64_t>(u_.r_obj.Size()) >= size);
```
Comment (chakaz) [inline src/core/compact_object.cc:815]: Can you add a comment explaining this? I don't understand, and a negative size isn't intuitive to me

File: src/server/stream_family.cc [hunk 4]
```diff
@@ -603,6 +603,28 @@ int StreamTrim(const AddTrimOpts& opts, stream* s) {
...
+    start_size_ = zmalloc_used_memory_tl;
+  }
+
+  void SetStreamSize(PrimeValue& pv) const {
+    const size_t current = zmalloc_used_memory_tl;
+    int64_t diff = static_cast<int64_t>(current) - static_cast<int64_t>(start_size_);
+    // If the diff is 0 it means the object use the same memory as before. No action needed.
+    if (diff == 0) {
+      return;
+    }
```
Comment (chakaz) [inline src/server/stream_family.cc:618]: Why is this needed? It doesn't seem like setting the same size has any performance implications, no?

File: src/server/stream_family.cc [hunk 5]
```diff
@@ -1379,6 +1414,8 @@ OpStatus OpSetId2(const OpArgs& op_args, string_view key, const streamID& sid) {
   if (!res_it)
     return res_it.status();
 
+  StreamMemTracker mem_tracker;
```
Comment (chakaz) [inline src/server/stream_family.cc:1417]: Would it make sense to "attach" such memory trackers per object, and let the d'tor do the size diff calculation?

File: src/core/compact_object.cc (hunk 3 above)
Comment (kostasrim) [reply src/core/compact_object.cc:815]: Yes! It's similar to Json, maybe we deallocate some part of the stream (let's say because you deleted a consumer), so the net will be negative.

File: src/server/stream_family.cc (hunk 4 above)
Comment (kostasrim) [reply src/server/stream_family.cc:618]: It's not, just me overengineering this condition when the function below covers it :)

File: src/server/stream_family.cc (hunk 5 above)
Comment (kostasrim) [reply src/server/stream_family.cc:1417]: The problem with the trackers is that it's not always possible to do the memory calculation at the end of the function (the destructor). This was mostly apparent with `json` because some commands would add temporary allocations inbetween which would affect the tracking accuracy. To mitigate this effect, we needed precise control for polling the difference on the heap, pretty much similarly to what I do here.

However, this is not really needed in a lot of places, especially for Streams (they have way less temporary waste mostly because they don't involve the non standard allocator behaviour we observed with json). 

Therefore, I will do a quick revamp and add a destructor.

Lastly, my plan is, once we get good coverage for all `objects` (meaning here all data types that we don't properly track and require a MemTracker) I would like to abstract them all under a `single interface` such that we don't get `JsonMemTracker`, `StreamMemTracker` etc but only `MemoryTracker` which will satisfy all the requirements for all the data types. The reason I haven't introduced such a generic interface yet is simply because I can't forsee all the requirements the types we don't properly track (my two cents would be that mostly we need either destructor tracking or manual tracking via a function).

Long rant, just thinking out loud of the long term goal here and the cleanness of the codebase

Comment (kostasrim) [reply src/server/stream_family.cc:1417]: Also another downside that comes to my mind, is that we might not want to track at all (let's say because of an early return or an error). In that case, we would need to `disable the tracker when it destructs` which bloats the code far more than a single function

File: src/core/compact_object.cc (hunk 3 above)
Comment (chakaz) [reply src/core/compact_object.cc:824]: Now I realize that this function accepts a **delta** and not a real size. I'd strongly recommend renaming it to reflect that. Definitely the argument (call it `delta`), but also the name (maybe `AddStreamSize()`?)

File: src/server/stream_family.cc (hunk 5 above)
Comment (chakaz) [reply src/server/stream_family.cc:1413]: Sure, makes sense.

File: src/core/compact_object.cc (hunk 3 above)
Comment (kostasrim) [reply src/core/compact_object.cc:824]: Yes or `IncrementStreamSize` although `Increment` means "increasing" and it;s not very accurate :smile:

Comment (chakaz) [reply src/core/compact_object.cc:824]: Indeed increment, to me, sounds like it's ever increasing. You could `Add()` negative numbers though

File: tests/dragonfly/memory_test.py [hunk 6]
```diff
@@ -28,6 +29,12 @@ async def test_rss_used_mem_gap(df_server: DflyInstance, type, keys, val_size, e
     min_rss = 3 * 1024 * 1024 * 1024  # 3gb
     max_unaccounted = 200 * 1024 * 1024  # 200mb
 
+    # There is a big rss spike when this test is ran in one the gh runners (not the self hosted)
+    # and it fails. This rss spike is not observed locally or on our self host runner so
+    # this adjustment is mostly for CI
```
Comment (chakaz) [inline tests/dragonfly/memory_test.py:34]: It's fine to break this down to another PR, but this to me means we still don't track all stream usage.. no?
It could be something ephemeral which makes it harder to catch locally

**Review by chakaz — APPROVED** [review]

File: tests/dragonfly/memory_test.py (hunk 6 above)
Comment (kostasrim) [reply tests/dragonfly/memory_test.py:34]: > but this to me means we still don't track all stream usage. 
I would say maybe because the RSS spike is not necessarily correlated with us not properly tracking memory but also due some pages not being properly released by the allocator. I tried `MEMORY DECOMMIT` but it did not have an effect. The difference in memory on both my `machine and on our own gh runner` is less than 50mb so based on that I would say we do track it pretty accurately. But I could be wrong as I have been many times in the past :smile:
