### PR TITLE
fix: big value serialization corner cases

### LINKED ISSUE #3414: `dragonfly/replication_test.py::test_replication_all` fails sporadically
[Example](https://github.com/dragonflydb/dragonfly/actions/runs/10129412325)

### PR DESCRIPTION
**Pull request by kostasrim**
There are some problematic flows. First we did not handle deletions, so all sorts of consistency issues could arise while calling `DbSlice::Traverse()` and `DbSlice::Del()`. Second, we did not handle `FlushAll` (same as before, `Traverse()` preempts and `FlushAll()` kicks in. Third we did not handle expirations. 

Fixes #3414

* lock DbSlice during FlushAll
* lock DbSlice on expiration and heartbeat flows
* lock DbSlice on Del()
* some small refactoring

### CODE REVIEW

File: src/server/engine_shard_set.cc [hunk 1]
```diff
@@ -605,6 +605,11 @@ void EngineShard::Heartbeat() {
   if (IsReplica())  // Never run expiration on replica.
     return;
 
+  // TODO: iterate over all namespaces
+  DbSlice& db_slice = namespaces.GetDefaultNamespace().GetDbSlice(shard_id());
+  // Some of the functions below might acquire the lock again so we need to unlock it
+  std::unique_lock lk(db_slice.GetSerializationMutex());
```
Comment (kostasrim) [inline src/server/engine_shard_set.cc:611]: Are we sure that `ABSL_LOCKS_EXCLUDED` work as intended ? Because I injected a deadlock here that violated the invariant of `ABSL_LOCKS_EXLUDED` and it deadlocked spectacularly (neither a compiler or runtime error). From a quick the macros used `__attribute__` but IMO I did not see any safeguard in practice which makes me question if I did something wrong or if those are not really that useful.

Comment (kostasrim) [reply src/server/engine_shard_set.cc:611]: I guess I will need to do some further reading when I get a chance. Two important links:

1. https://releases.llvm.org/3.5.0/tools/clang/docs/ThreadSafetyAnalysis.html
2. https://releases.llvm.org/3.5.0/tools/clang/docs/ThreadSafetyAnalysis.html#limitations

Comment (kostasrim) [reply src/server/engine_shard_set.cc:611]: I need to check if we use  `-Wthread-safety` because otherwise the analysis is not run. Also it's static_analysis (I was also concerned if this had any runtime impact)

Comment (chakaz) [reply src/server/engine_shard_set.cc:611]: @kostasrim the `ABSL_*` checks are compile time only.
They are only enabled in clang, are you using that locally?

Comment (kostasrim) [reply src/server/engine_shard_set.cc:611]: discussed internally. attaching the issue for completeness https://github.com/dragonflydb/dragonfly/issues/3448

**Comment by kostasrim** [comment]
I am not particular happy with the manual use of the locks but at least we get a base line with a few bug fixes. IMO we need a better solution because this manual control is `fragile`. 

P.s. I thought that this PR introduced a deadlock because `disconnect_small_buffer` was getting stack on some of my manual reg test runs -- but I was wrong. It failed randomly somewhere else as well: https://github.com/dragonflydb/dragonfly/actions/runs/10254955198/job/28370827115

**Comment by kostasrim** [comment]
p.s.2 I run this a couple of times, I haven't seen the `replication failures` :)

**Comment by kostasrim** [comment]
a few test runs:

https://github.com/dragonflydb/dragonfly/actions/runs/10254985671 
https://github.com/dragonflydb/dragonfly/actions/runs/10261402718
https://github.com/dragonflydb/dragonfly/actions/runs/10262564084

File: src/server/db_slice.cc [hunk 2]
```diff
@@ -481,6 +482,13 @@ OpResult<DbSlice::PrimeItAndExp> DbSlice::FindInternal(const Context& cntx, std:
 
   if (caching_mode_ && IsValid(res.it)) {
     if (!change_cb_.empty()) {
+      {
+        // We need this because we might not be able to acquire this lock within
+        // CallChangeCallbacks and if this happens then Capture Version Change
+        // might be invalid, since the bucket might change after we block waiting
+        // for the lock to be available.
+        std::unique_lock lk(local_mu_);
```
Comment (chakaz) [inline src/server/db_slice.cc:490]: I don't understand - why release the lock before calling `CVCUponBump()`?
And why can't we acquire this lock inside it?

Comment (kostasrim) [reply src/server/db_slice.cc:490]: Because `CVCUponBump()`  acquires the same lock (`CallChangeCallbacks` below does it) so it will deadlock. 

Furthermore, `CVCUponBump` captures the version change meaning that it `logically tries to insert` an element. Logically, meaning that it does not perform any insertion but it calculates which buckets might change upon the insertion and we serialize those buckets via the callbacks when the bucket version is less than the one registered in the callback. Then we can safely make the change.

The problem lies within `CVCUponBump` which first makes this logical calculation above and then it applies the callbacks. However, the callbacks might fail to acquire the lock because someone else might already have acquired this lock and by the time we wake up we might have the wrong calculation (since some other fiber might wake up, do the same calculation and bump up the version). 

By locking above, we guarantee than when we wake up, we will acquire the lock again within the callback.

Comment (chakaz) [reply src/server/db_slice.cc:490]: This seems fragile...
What if one of the callbacks preempt, and the segment changes structure before the next callbacks are called? It could then be called with invalid parameters, no?
I think that a more robust solution would be to mark `CallChangeCallbacks()` as `EXCLUSIVE_LOCKS_REQUIRED` (which means the mutex must be held when calling it), and then lock it before each of the calls. Here you'll hold the mutex locked and not release it, thus you won't deadlock.
wdyt?

Comment (kostasrim) [reply src/server/db_slice.cc:490]: > What if one of the callbacks preempt, and the segment changes structure before the next callbacks are called? It could then be called with invalid parameters, no?

This can't happen because we hold the lock when we preempt.

> I think that a more robust solution would be to mark CallChangeCallbacks() as EXCLUSIVE_LOCKS_REQUIRED 

IMO that's what I had in mind so I couldn;t agree more :100:

Comment (chakaz) [reply src/server/db_slice.cc]: > This can't happen because we hold the lock when we preempt.
> 

But we don't hold it throughout the preemptions, right? We hold it in each preemption within each callback, but there could be multiple.
Anyway, looks like we agree on a solution :)

Comment (kostasrim) [reply src/server/db_slice.cc]: Yes but the whole block is atomic implicitly, once the lock is released after the preemption it will be acquired by the same fiber until it applies all the callbacks (which each one might preempt). The reason is that upon releasing the lock, the fiber is not put to sleep but rather it continues and it just calls the next callback which immediately reacquires the lock(when we release the lock we just update the waiting queue, but this merely wakes up a fiber and activates it on the scheduler -- we don't switch to another fiber upon release)

File: src/server/db_slice.cc [hunk 3]
```diff
@@ -572,6 +575,9 @@ OpResult<DbSlice::AddOrFindResult> DbSlice::AddOrFindInternal(const Context& cnt
   auto status = res.status();
   CHECK(status == OpStatus::KEY_NOTFOUND || status == OpStatus::OUT_OF_MEMORY) << status;
 
+  FetchedItemsRestorer fetched_restorer(&fetched_items_);
+  std::unique_lock lk(local_mu_);
+
```
[the remark this answers is not in the document]
Comment (kostasrim) [reply src/server/db_slice.cc:580]: I tend to avoid manually unlocking locks until there is a good reason. I rather have RAII do it for me but I am always open for discussions :smile:

[the remark this answers is not in the document]
Comment (chakaz) [reply src/server/db_slice.cc:580]: I meant _using_ RAII, i.e. add a scope for `lk` which includes the call to callbacks and ends after that

File: src/server/db_slice.cc (hunk 2 above)
Comment (chakaz) [reply src/server/db_slice.cc]: I agree that we won't switch fibers when we unlock here, until the first preemption. But the first preemption will switch fibers, at which point we're in the danger zone

File: src/server/db_slice.cc (hunk 3 above)
[the remark this answers is not in the document]
Comment (kostasrim) [reply src/server/db_slice.cc:580]: ohhh sure! happy to do that. I won't merge this now anyway, I want to test this more :)

File: src/server/db_slice.cc (hunk 2 above)
Comment (kostasrim) [reply src/server/db_slice.cc]: but we hold the lock when we preempt no ? What am I missing here?
