### PR TITLE
fix(server): Save element expirations for hash sets & sets

### LINKED ISSUE #2052: Set and hash field expirations are not persisted after restart
**Describe the bug**
When using Dragonfly-specific functionality that enables setting expiration for fields, i.e HSETEX and SADDEX, the expiration is not persisted after restarting Dragonfly.

**To Reproduce**
```
HSETEX myhash 30 foo bar

restart Dragonfly
sleep 30;
HGET myhash foo
bar  < --- field foo still exists
```

**Expected behavior**
```
HSETEX myhash 30 foo bar

restart Dragonfly
sleep 30;
HGET myhash foo
(nil)
```

**Environment (please complete the following information):**
 - Dragonfly Version: Dragonfly HEAD

### PR DESCRIPTION
**Pull request by chakaz**
Fixes #2052

### CODE REVIEW

File: src/server/rdb_load.cc [hunk 1]
```diff
@@ -465,9 +467,14 @@ void RdbLoaderBase::OpaqueObjLoader::operator()(const JsonType& json) {
...
+  size_t increment = 1;
+  if (rdb_type_ == RDB_TYPE_SET_WITH_EXPIRY) {
+    increment = 2;
+  }
+
+  size_t len = ltrace->blob_count() / increment;
 
-  bool is_intset = true;
+  bool is_intset = (rdb_type_ == RDB_TYPE_HASH);
   if (len <= SetFamily::MaxIntsetEntries()) {
```
Comment (adiholden) [inline src/server/rdb_load.cc:478]: I think the condition (rdb_type_ == RDB_TYPE_HASH && ltrace->blob_count() < SetFamily::MaxIntsetEntries()) will be more clear here.
you will not need the increment logic above

File: src/server/rdb_load.cc [hunk 2]
```diff
@@ -505,9 +512,10 @@ void RdbLoaderBase::OpaqueObjLoader::CreateSet(const LoadTrace* ltrace) {
       return true;
     });
   } else {
-    bool use_set2 = GetFlag(FLAGS_use_set2);
+    bool use_set2 = GetFlag(FLAGS_use_set2) || rdb_type_ == RDB_TYPE_SET_WITH_EXPIRY;
```
Comment (adiholden) [inline src/server/rdb_load.cc:515]: maybe we should print an error use_set2 is false and rdb_type_ is RDB_TYPE_SET_WITH_EXPIRY

File: src/server/rdb_load.cc (hunk 1 above)
Comment (chakaz) [reply src/server/rdb_load.cc:478]: I do need the increment logic for incrementing the loop, but I moved that below. Otherwise, SG.

File: src/server/rdb_load.cc [hunk 3]
```diff
@@ -525,18 +533,36 @@ void RdbLoaderBase::OpaqueObjLoader::CreateSet(const LoadTrace* ltrace) {
...
+            string_view ttl_str = ToSV(seg[i + 1].rdb_var);
+            if (!absl::SimpleAtoi(ttl_str, &ttl_time)) {
+              LOG(ERROR) << "Can't parse set TTL " << ttl_str;
+              ec_ = RdbError(errc::rdb_file_corrupted);
+              return;
+            }
+
+            if (ttl_time != -1) {
+              if (ttl_time < set->time_now()) {
+                continue;
```
[the remark this answers is not in the document]
Comment (adiholden) [reply src/server/rdb_load.cc:555]: I think it makes sense to create set Add api that will get ephoc time and not ttl.
Yes I dont want replicas to not load some of the set values we can fix this is a seprate PR but I that the fix should not be in rdb_load i.e we should not check if we are replica in rdb load and based on this load/not load some values but instead the set structor itself should not remove entries if the server is a replica

File: src/server/rdb_load.cc [hunk 4]
```diff
@@ -514,6 +509,8 @@ void RdbLoaderBase::OpaqueObjLoader::CreateSet(const LoadTrace* ltrace) {
   } else {
     bool use_set2 = GetFlag(FLAGS_use_set2) || rdb_type_ == RDB_TYPE_SET_WITH_EXPIRY;
     if (use_set2) {
+      LOG_IF(ERROR, !GetFlag(FLAGS_use_set2))
```
Comment (adiholden) [inline src/server/rdb_load.cc:512]: please also print the key in the error.
I actually think that in this case we either need to use the other set impl or not load this entry. 
What will be the reason for user to disable use_set2 ? if we have a bug there / cuasing a crash. So I think we should respect the flag and not use set2

File: src/server/rdb_load.cc (hunk 3 above)
[the remark this answers is not in the document]
Comment (chakaz) [reply src/server/rdb_load.cc:555]: Sure, let's do that in another PR though

File: src/server/rdb_load.cc (hunk 4 above)
Comment (chakaz) [reply src/server/rdb_load.cc:512]: If set2 is disabled, we use Redis implementation of set, which does not support field expiration.
What do you think we should do in that case? Drop the expiration data and load everything?

Comment (adiholden) [reply src/server/rdb_load.cc:512]: So we should either not load the key or we can drop the expiration data.. both options looks ok to me

Comment (chakaz) [reply src/server/rdb_load.cc]: It's easier to drop the data (I think), so I went with that
And I also fixed an existing bug (iterating an empty set crashes), but honestly I'm not sure how to reproduce it so it might be an unreachable bug
