### PR TITLE
fix(cluster-migration): Support cancelling migration right after starting it

### LINKED ISSUE #2968: deadlock if slot migration is canceled after beggining

### PR DESCRIPTION
**Pull request by chakaz**
This fixes a few small places, but most importantly it does not allow a migration to start before both the outgoing and incoming side received the updated config. This solves a few edge cases.

Fixes #2968

### CODE REVIEW

File: src/server/cluster/outgoing_slot_migration.cc [hunk 1]
```diff
@@ -94,8 +100,12 @@ void OutgoingMigration::Finish(bool is_error) {
     const auto new_state = is_error ? MigrationState::C_ERROR : MigrationState::C_FINISHED;
     state_.store(new_state);
     shard_set->pool()->AwaitFiberOnAll([this](util::ProactorBase* pb) {
-      if (const auto* shard = EngineShard::tlocal(); shard)
-        slot_migrations_[shard->shard_id()]->Cancel();
+      if (const auto* shard = EngineShard::tlocal(); shard) {
+        auto& migration = slot_migrations_[shard->shard_id()];
```
Comment (BorysTheDev) [inline src/server/cluster/outgoing_slot_migration.cc:104]: the better name is flow or flow_migration or shard_migration

File: tests/dragonfly/cluster_test.py [hunk 2]
```diff
@@ -955,31 +955,14 @@ async def test_config_consistency(df_local_factory: DflyInstanceFactory):
       ]
     """
 
-    # push config only to source node
+    # Push config to the target node first, so that it won't reject the migration which will lead to errors
```
Comment (BorysTheDev) [inline tests/dragonfly/cluster_test.py:958]: we can not guarantee that config will be sent to the target node, because we can have 2 or more simultaneous migrations, so incoming and outgoing migration can be in the config

File: src/server/cluster/outgoing_slot_migration.cc [hunk 3]
```diff
@@ -106,7 +116,12 @@ MigrationState OutgoingMigration::GetState() const {
 
 void OutgoingMigration::SyncFb() {
   // we retry starting migration until "cancel" is happened
-  while (state_.load() != MigrationState::C_FINISHED) {
+  while (true) {
+    auto state = state_.load();
+    if (state == MigrationState::C_FINISHED || state == MigrationState::C_ERROR) {
```
Comment (BorysTheDev) [inline src/server/cluster/outgoing_slot_migration.cc:121]: Error is the reason to restart migration, only finished state tell us to stop

File: src/server/cluster/cluster_family.cc [hunk 4]
```diff
@@ -835,6 +835,19 @@ void ClusterFamily::InitMigration(CmdArgList args, ConnectionContext* cntx) {
...
     return cntx->SendError(err->MakeReply());
 
+  bool found = false;
+  for (const auto& known_migration : cluster_config()->GetIncomingMigrations()) {
+    // TODO: also compare slot ranges (in an order-agnostic way)
+    if (known_migration.node_id == source_id) {
+      found = true;
+      break;
+    }
+  }
```
Comment (BorysTheDev) [inline src/server/cluster/cluster_family.cc:845]: find_if is better

File: src/server/cluster/outgoing_slot_migration.cc [hunk 5]
```diff
@@ -57,11 +57,16 @@ class OutgoingMigration::SliceSlotMigration : private ProtocolClient {
       return;
     }
 
+    if (cancelled_) {
+      return;
+    }
+
     streamer_.Start(Sock());
```
Comment (BorysTheDev) [inline src/server/cluster/outgoing_slot_migration.cc:64]: it can't be true, because we work with this code in one thread, and we can not cancel it before start

File: src/server/cluster/cluster_family.cc (hunk 4 above)
Comment (chakaz) [reply src/server/cluster/cluster_family.cc]: Switched to `any_of()` :)

File: tests/dragonfly/cluster_test.py (hunk 2 above)
Comment (chakaz) [reply tests/dragonfly/cluster_test.py]: As discussed, it's fine for the config to arrive in any order, but it won't _start_ until both sides received it.
I updated the C++ and test code as we discussed.

File: src/server/cluster/outgoing_slot_migration.cc (hunk 5 above)
Comment (chakaz) [reply src/server/cluster/outgoing_slot_migration.cc:64]: It can happen - when we add the outgoing migration to the list, and then yield in this function (like when connecting, etc) and in another fiber it is cancelled.
This is actually reproducible in the cancel test after ~10 attempts :)

File: src/server/cluster/cluster_family.cc [hunk 6]
```diff
@@ -814,8 +814,7 @@ bool RemoveIncomingMigrationImpl(std::vector<std::shared_ptr<IncomingSlotMigrati
 void ClusterFamily::RemoveIncomingMigrations(const std::vector<MigrationInfo>& migrations) {
   lock_guard lk(migration_mu_);
   for (const auto& m : migrations) {
-    auto was_removed = RemoveIncomingMigrationImpl(incoming_migrations_jobs_, m.node_id);
-    DCHECK(was_removed);
```
Comment (chakaz) [inline src/server/cluster/cluster_family.cc:818]: This could actually be `false` if we yield somewhere in the process, like when locking the above mutex

File: src/server/cluster/outgoing_slot_migration.cc (hunk 5 above)
Comment (BorysTheDev) [reply src/server/cluster/outgoing_slot_migration.cc:64]: I see. Could you add a comment here?

**Review by BorysTheDev — DISMISSED** [review]

**Review by BorysTheDev — APPROVED** [review]
