### PR TITLE
fix: evict open connections for users not present in the updated ACL

### LINKED ISSUE #2003: ACL Load does not evict open connections
`ACL LOAD` is used to load the contents of an ACL file into DF.

The issue is that some of the previously existed users might not exist anymore. These users, might already have open connections with DF, creating a security hole in the system. 

The fix should be simple/straightforward, use `EvictOpenConnectionsOnAllProactors` to evict all open connections from users that no longer exist in the newly loaded ACL file.

For example:

Users before new ACL file loaded:
1. default
2. mike
3. ada

Users after new ACL file loaded:
1. default
2. ada

Therefore, we should evict all open connections from the user `mike`.

### PR DESCRIPTION
**Pull request by azuredream**
Fixes #2003

### CODE REVIEW

File: src/server/acl/acl_family.cc [hunk 1]
```diff
@@ -247,12 +247,25 @@ std::optional<facade::ErrorReply> AclFamily::LoadToRegistryFromFile(std::string_
...
     registry.clear();
   }
+  // Evict open connections for users not present in the updated ACL
+  for (const auto& [username, _] : registry) {
+    if (username == "default")
+      continue;
+    if (!usernames_set.contains(username)) {
+      EvictOpenConnectionsOnAllProactors(username);
+    }
+  }
```
Comment (kostasrim) [inline src/server/acl/acl_family.cc:268]: The second `for-loop` won't work because the registry is `cleared` on line `258`. 

Furthermore, I don't like that we call `EvictOpenConnectionsOnAllProactors` for each `username`. We can do that in one pass for all the connections:

Introduce a new function, `EvictOpenConnectionsOnAllProactorsWithUsers` and add an extra argument `absl::flat_hash_set` which is then captured in the `close_cb`. Then replace `ctx->authed_username == user`, with `contains`. That way we call this function once:

`EvictOpenConnectionsOnAllProactors(usernames_set)`. (Bonus points if you can merge the functionality with the current function -- not mandatory though :stuck_out_tongue: )

Furthermore, I realized that `redis` is evicting all open connections even when there are common usernames.

I would suggest to:

1. remove the `username_set`, and use the newly function directly `EvictOpenConnectionsOnAllProactors(registry)`
2. remove lines 283 - 285 since all open connections are evicted

Comment (azuredream) [reply src/server/acl/acl_family.cc]: Thank you for the detailed guidance. 
Just to clarify, `Registry` is a map, not a set. Here are three potential solutions, please let me know which one you prefer. I updated my PR by option 2.

1. An overloaded `EvictOpenConnectionsOnAllProactors(const absl::flat_hash_set<std::string_view>& users_set)`.
    Generate a `username_set` from register before calling.
2. `EvictOpenConnectionsOnAllProactorsWithRegistry(const UserRegistry::RegistryType& registry)`.
3. `EvictOpenConnectionsOnAllProactorsWithUsers(const absl::flat_hash_map<std::string_view, User>& users_map)`. 

Tested `./dragonfly --aclfile ./test_acl --alsologtostderr` in GDB on the server side. 
Since we close all the connections, `ACL LOAD` prints an "Error" to the client, which can be optimized.  
_127.0.0.1:6379> ACL LOAD
Error: Server closed the connection
127.0.0.1:6379> ACL list
1) user peter off nopass +@NONE
2) user default on nopass +@ALL +ALL
3) user amy off nopass +@NONE_

I can also add unit test for this use case if you could give me some adivce.

Comment (kostasrim) [reply src/server/acl/acl_family.cc]: Hi @azuredream, thank you so much for the changes! They are :fire: 

I like the (2) approach! 

For what you ask:
> _127.0.0.1:6379> ACL LOAD Error: Server closed the connection

This is good and on par with redis! 

Maybe a small nit, is to `exclude` default, since this user can't be removed by the system and therefore, there is no point to evict them. So maybe, add an extra check:

```
ctx->authed_username != "default" && registry.contains(ctx->authed_username)  
```

Comment (kostasrim) [reply src/server/acl/acl_family.cc]: p.s. no need to do add anything else, I will approve :) 

p.s.2 if you fancy making changes and learning the codebase, you can add a test in `acl_family.py` as well but I leave that up to you!

**Review by kostasrim — APPROVED** [review]

**Comment by kostasrim** [comment]
Tested this locally as well -- all ACL tests pass. Good work @azuredream and thank you for your contribution :rocket: :fire:
