### PR TITLE
fix: Allow readonly commands in replica script

### LINKED ISSUE #1391: cannot use lua scripting on slave replica
Dragonfly lastest version.

On a replica which is read only (and it's perfectly fine) we cannot use lua scripting. For example the simple example in the redis doc is not working:

127.0.0.1:6379> EVAL "return redis.call('SET', KEYS[1], ARGV[1])" 1 foo bar
(error) ERR Error running script (call to d8f2fad9f8e86a53d2a6ebd960b33c4972cacc37): @user_script:2: -READONLY You can't write against a read only replica.

this is a blocker for adoption for us (we heavily rely on this)

### PR DESCRIPTION
**Pull request by dranikpg**
Fixes #1391

It looks that long ago we planned to distinguish scripts read-only status ahead, so all of them were marked as write. Found this comment:

>   // TODO: to determine whether the script is RO by scanning all "redis.p?call" calls
  // and checking whether all invocations consist of RO commands.
  // we can do it once during script insertion into script mgr.

For now I've removed any categorization into read-only or not. Write commands will fail as usual.

### CODE REVIEW

File: src/server/main_service.cc [hunk 1]
```diff
@@ -723,8 +723,7 @@ bool Service::VerifyCommand(const CommandId* cid, CmdArgList args, ConnectionCon
     return false;
   }
 
-  bool is_write_cmd = (cid->opt_mask() & CO::WRITE) ||
-                      (under_script && dfly_cntx->conn_state.script_info->is_write);
```
Comment (dranikpg) [inline src/server/main_service.cc:727]: The second part always evaluated to true

**Review by romange — APPROVED** [review]

**Review by romange — APPROVED** [review]
