### PR TITLE
fix: Do not use `cc_` in connection if it's null

### LINKED ISSUE #3776: test failed replication_test.py::test_take_over_counters
investigate https://github.com/dragonflydb/dragonfly/actions/runs/10993785520/job/30521012937

### PR DESCRIPTION
**Pull request by chakaz**
This is a rare condition, which we know can happen during shutdown (see [here](https://github.com/dragonflydb/dragonfly/pull/3873#issue-2568503374))

Hopefully fixes #3776 but we couldn't reproduce it to make sure.

### CODE REVIEW

File: src/facade/dragonfly_connection.cc [hunk 1]
```diff
@@ -1428,20 +1428,24 @@ std::string Connection::DebugInfo() const {
 
   absl::StrAppend(&info, "address=", uint64_t(this), ", ");
   absl::StrAppend(&info, "phase=", phase_, ", ");
-  absl::StrAppend(&info, "dispatch(s/a)=", cc_->sync_dispatch, " ", cc_->async_dispatch, ", ");
-  absl::StrAppend(&info, "closing=", cc_->conn_closing, ", ");
+  if (cc_) {
```
Comment (romange) [inline src/facade/dragonfly_connection.cc:1431]: maybe add a comment about this rare condition.

**Review by romange — APPROVED** [review]
