### PR TITLE
fix: propagate memcached flags to replica

### LINKED ISSUE #1758: support memcache flags during snapshotting and replication
memcache has additional `flags` property for each its entries. 
We maintain it in a separate datastructure `mc_flags`.  

1. SAVE/LOAD procedures do not support them because it's not part of the standard Redis datastrcutures
2. Also the replication ignores them. 

We have a user that runs Dragonfly in memcached mode and H/A and asks for those features to improve the availability of their deployment.

### PR DESCRIPTION
**Pull request by romange**
Fixes #1758

### CODE REVIEW

File: src/server/string_family.cc [hunk 1]
```diff
@@ -688,6 +688,10 @@ void SetCmd::RecordJournal(const SetParams& params, string_view key, string_view
   if (params.flags & SET_STICK) {
     cmds.push_back("STICK");
   }
+  if (params.memcache_flags) {
+    cmds.push_back("_FLAGS");
```
Comment (dranikpg) [inline src/server/string_family.cc:692]: Tricky 😄 Maybe call it at least MC_FLAGS or smth similar?

**Review by dranikpg — APPROVED** [review]

**Review by dranikpg — APPROVED** [review]
