### PR TITLE
fix: bitop do not add dst key if result is empty

### LINKED ISSUE #3528: bitop not tmp1 tmp2 inconsistent result
Start an empty dragonfly instance and run:

```
bitop not tmp1 tmp2
get tmp1
```
will return `""`

in `Valkey` will return `nil`

### PR DESCRIPTION
**Pull request by kostasrim**
There are two bugs:

Bug 1:

```
bitop not does_not_exist tmp2
get does_not_exist
```
Should return `nill` and not `""` 

Bug 2:
```
setup master and replica and then:

on master do: hset foo bar val -> bitop not foo bar -> get foo returns WRONGTYPE
on replica do GET foo returns ""

Now state_of(master) != state_of(replica)
```

Bug 3:
```
hset foo bar val -> bitop not foo bar -> get foo returns WRONGTYPE
```

when `get foo` should return `nill`, that is `bitop` acts as a `blind update` similar to `set` command

resolves #3528

### CODE REVIEW

File: src/server/bitops_family.cc [hunk 1]
```diff
@@ -343,8 +343,14 @@ std::string ElementAccess::Value() const {
 
 void ElementAccess::Commit(std::string_view new_value) const {
   if (shard_) {
-    element_iter_->second.SetString(new_value);
-    post_updater_.Run();
+    if (new_value.empty() && IsNewEntry()) {
```
Comment (adiholden) [inline src/server/bitops_family.cc:346]: I think we should delete it even if its not a new entry
set x y
bitop not x key
get x
should also return nil

File: src/server/bitops_family.cc [hunk 2]
```diff
@@ -1159,7 +1165,7 @@ void BitOp(CmdArgList args, ConnectionContext* cntx) {
   cntx->transaction->Execute(std::move(shard_bitop), false);  // we still have more work to do
   // All result from each shard
   const auto joined_results = CombineResultOp(result_set, op);
-  // Second phase - save to targe key if successful
+  // Second phase - save to target key if successful
```
Comment (adiholden) [inline src/server/bitops_family.cc:1168]: check the replication journal code line 1185. need to fix this also

File: src/server/bitops_family.cc (hunk 1 above)
Comment (kostasrim) [reply src/server/bitops_family.cc]: I also added a test and confirmed the behaviour with Valkey. good catch

File: src/server/bitops_family.cc (hunk 2 above)
Comment (kostasrim) [reply src/server/bitops_family.cc:1168]: Wow. I blindly did not both with the journal because I `thought that we replicate the same command always`. But in this context, we do not. What we do instead is we take the result of the operation and call `SET` directly which is a `very nice` optimization since we don't now need to run the command on the replica but rather do an `update` on the result directly.

This is a nice pattern/optimization to know. +1

File: src/server/bitops_family.cc [hunk 3]
```diff
@@ -343,8 +343,14 @@ std::string ElementAccess::Value() const {
 
 void ElementAccess::Commit(std::string_view new_value) const {
   if (shard_) {
-    element_iter_->second.SetString(new_value);
-    post_updater_.Run();
+    if (new_value.empty()) {
+      // No need to run, it was a new entry and it got removed
+      post_updater_.Cancel();
```
Comment (adiholden) [inline src/server/bitops_family.cc:348]: I think you should run the post updater here as this might be not a new entry

File: src/server/bitops_family.cc [hunk 4]
```diff
@@ -1176,7 +1182,15 @@ void BitOp(CmdArgList args, ConnectionContext* cntx) {
         }
 
         if (shard->journal()) {
-          RecordJournal(t->GetOpArgs(shard), "SET", {dest_key, op_result});
+          if (op_result.empty()) {
```
Comment (adiholden) [inline src/server/bitops_family.cc:1185]: also if find_res == OpStatus::OK

File: src/server/bitops_family.cc (hunk 3 above)
Comment (kostasrim) [reply src/server/bitops_family.cc:348]: yep +1. I wish we could run it unconditionally though (but we can't because we have an assertion within it :(

File: src/server/bitops_family.cc (hunk 4 above)
Comment (kostasrim) [reply src/server/bitops_family.cc:1185]: my question here would be if the result is not ok why do we `RecordJournal` ?

Comment (adiholden) [reply src/server/bitops_family.cc:1185]: we should not

**Comment by romange** [comment]
As a general remark - I suggest adding comments around points that raised discussions in the PR so that future selves could understand the intent

File: src/server/bitops_family.cc (hunk 4 above)
Comment (kostasrim) [reply src/server/bitops_family.cc:1185]: we had another bug then :stuck_out_tongue:

Comment (kostasrim) [reply src/server/bitops_family.cc:1185]: setup master and replica and then:

1. on master do: hset foo bar val -> bitop not foo bar -> get foo returns WRONGTYPE 
2. on replica do GET foo returns ""

Now state_of(master) != state_of(replica)

Comment (kostasrim) [reply src/server/bitops_family.cc]: I added this on the issue + supplied the fix + added a replication test case so we don't break it again

**Comment by kostasrim** [comment]
> As a general remark - I suggest adding comments around points that raised discussions in the PR so that future selves could understand the intent

yep +1. I added a comment + the tests

File: tests/dragonfly/replication_test.py [hunk 5]
```diff
@@ -2661,3 +2661,23 @@ async def check_master_status():
...
+    master = df_factory.create()
+    replica = df_factory.create()
+    df_factory.start_all([master, replica])
+
+    c_replica = replica.client()
+    await c_replica.execute_command(f"REPLICAOF localhost {master.port}")
+    await wait_available_async(c_replica)
+
+    c_master = master.client()
+    await c_master.execute_command(f"HSET foo bar val")
```
Comment (adiholden) [inline tests/dragonfly/replication_test.py:2677]: I would add this as a subtest case of def test_rewrites

Comment (adiholden) [reply tests/dragonfly/replication_test.py:2677]: you will check there that del foo was sent

File: tests/dragonfly/replication_test.py [hunk 6]
```diff
@@ -2661,3 +2661,23 @@ async def check_master_status():
...
+    await c_master.execute_command(f"BITOP not foo 1")
+
+    with pytest.raises(redis.exceptions.ResponseError):
+        await c_replica.execute_command(f"GET foo")
```
Comment (adiholden) [inline tests/dragonfly/replication_test.py:2681]: also this is not very robust because you dont know if replica already got the journal change or not, it could return error because foo is not a string and not because it was deleted

File: tests/dragonfly/replication_test.py (hunk 5 above)
Comment (kostasrim) [reply tests/dragonfly/replication_test.py:2677]: hmm I did not know that `bitops` acts as a blind update. I tested this with Valkey, so if the operation returns `WRONG_TYPE` we should still `delete the key`. I will add this to the logic + comment + move this to rewrite

Comment (kostasrim) [reply tests/dragonfly/replication_test.py:2677]: So the fix above is also incorrect `if (find_res == OpStatus::OK)`!

File: tests/dragonfly/replication_test.py [hunk 7]
```diff
@@ -673,6 +673,18 @@ async def check_expire(key):
         await skip_cmd()
         # Check BITOP turns into SET
         await check("BITOP OR kdest k1 k2", r"SET kdest 1100")
+        c_master = master.client()
```
Comment (adiholden) [inline tests/dragonfly/replication_test.py:676]: why do you need this line

File: tests/dragonfly/replication_test.py [hunk 8]
```diff
@@ -673,6 +673,18 @@ async def check_expire(key):
...
+        # See gh issue #3528
+        await c_master.execute_command(f"HSET foo bar val")
+        await skip_cmd()
+        await check("BITOP NOT foo tmp", r"DEL foo")
+        await c_master.execute_command(f"DEL foo")
```
Comment (adiholden) [inline tests/dragonfly/replication_test.py:681]: does foo exists in master at this point? why do you need del foo?

**Review by adiholden — APPROVED** [review]
