### PR TITLE
fix: skip empty objects on load and replication

### LINKED ISSUE #3504: Allow loading empty objects
Today we reject loading empty objects, as logically they should never exist in the first place.
However, there are examples in which empty objects could exist (due to per-element expiration), which we should handle:

1. Get an empty StringMap on node A
2. Replicate A to node B, we have also a StringMap there, but with expiration_used_ = false
3. Replica B to A, it will be loaded as a listpack as we don't have info about expiration
4. We have an empty listpack on A, replicate again to B

We should take the following actions:

- [ ] Create some function to determine, for all object types, if they are empty (string, hashmap, list, etc)
- [ ] Do not serialize empty objects to replica/rdb
- [ ] In `DbSlice` API (`Find`, `AddOrFind`, ...) check if objects are empty. If so, remove them.
- [ ] When loading (replica/rdb), check if the loaded object is empty, and if so do not add it to the data store

### PR DESCRIPTION
**Pull request by kostasrim**
fixes #3504

* skip empty objects in rdb save
* skip empty objects in rdb load
* delete empty keys in FindReadOnly

### CODE REVIEW

File: src/server/rdb_save.cc [hunk 1]
```diff
@@ -337,6 +337,13 @@ error_code RdbSerializer::SelectDb(uint32_t dbid) {
 // Called by snapshot
 io::Result<uint8_t> RdbSerializer::SaveEntry(const PrimeKey& pk, const PrimeValue& pv,
                                              uint64_t expire_ms, DbIndex dbid) {
+  string_view key = pk.GetSlice(&tmp_str_);
+  // We skip empty entries of any PrimeValue
+  if (pv.Size() == 0) {
+    LOG(WARNING) << "SaveEntry skipped empty PrimeValue with key: " << key;
```
Comment (kostasrim) [inline src/server/rdb_save.cc:343]: I am not using `LOG_EVER_N` since this is a *very* rare error

**Comment by kostasrim** [comment]
@chakaz shall we also fix `restore` and add a `unit test` for this ?

File: src/server/rdb_save.cc (hunk 1 above)
Comment (chakaz) [reply src/server/rdb_save.cc:343]: Perhaps this should be an ERROR so that we know to look into that?

File: tests/dragonfly/replication_test.py [hunk 2]
```diff
@@ -2411,3 +2411,33 @@ async def test_replicate_old_master(
...
+@pytest.mark.asyncio
+async def test_empty_hash_as_zipmap_bug(df_factory: DflyInstanceFactory):
+    master = df_factory.create()
+    master.start()
+    replica = df_factory.create()
+    replica.start()
+
+    c_master = master.client()
+    await c_master.execute_command("HSET foo a_field a_value")
+    await c_master.execute_command("HSETEX foo 5 b_field b_value")
```
Comment (chakaz) [inline tests/dragonfly/replication_test.py:2425]: Can we use shorter timeouts to not make tests too slow?

File: tests/dragonfly/replication_test.py [hunk 3]
```diff
@@ -2411,3 +2411,33 @@ async def test_replicate_old_master(
...
+    await c_master.execute_command("HDEL foo a_field")
+    async with async_timeout.timeout(15):
+        while True:
+            await asyncio.sleep(5)
+            res = await c_master.execute_command("HGETALL foo")
+            if res == []:
+                break
```
Comment (chakaz) [inline tests/dragonfly/replication_test.py:2432]: Looks like a good candidate for `assert_eventually`

File: src/server/rdb_save.cc [hunk 4]
```diff
@@ -337,6 +337,13 @@ error_code RdbSerializer::SelectDb(uint32_t dbid) {
 // Called by snapshot
 io::Result<uint8_t> RdbSerializer::SaveEntry(const PrimeKey& pk, const PrimeValue& pv,
                                              uint64_t expire_ms, DbIndex dbid) {
+  string_view key = pk.GetSlice(&tmp_str_);
```
Comment (chakaz) [inline src/server/rdb_save.cc:340]: Looks like we only need this inside the `if`, so maybe insert it there?
This could save an unneeded allocation (that's rarely needed for the sad path)

File: tests/dragonfly/replication_test.py [hunk 5]
```diff
@@ -2411,3 +2411,33 @@ async def test_replicate_old_master(
     assert await c_replica.execute_command("get", "k1") == "v1"
 
     await disconnect_clients(c_master, c_replica)
+
+
+@pytest.mark.asyncio
+async def test_empty_hash_as_zipmap_bug(df_factory: DflyInstanceFactory):
```
Comment (chakaz) [inline tests/dragonfly/replication_test.py:2417]: Can you kindly make sure that this test passes even if the code on the save path does not change?

Comment (kostasrim) [reply tests/dragonfly/replication_test.py:2417]: Can you plz elaborate what you mean here?

Comment (kostasrim) [reply tests/dragonfly/replication_test.py:2417]: This test won't pass without the fix since the replica will now contain an empty hashmap ?

File: src/server/rdb_save.cc (hunk 4 above)
Comment (kostasrim) [reply src/server/rdb_save.cc:340]: it's also used later in line 365 but I agree

File: tests/dragonfly/replication_test.py (hunk 5 above)
Comment (chakaz) [reply tests/dragonfly/replication_test.py:2417]: This PR attempts to fix both loading of an empty set in an RDB file (which shouldn't happen)
and also not saving an RDB file to begin with.

I wanted you to comment out the changes in `RdbSerializer::SaveEntry` so that we can confirm this works for bad RDB files?
I suspect that it won't, but I'd love to be surprised :)

Comment (kostasrim) [reply tests/dragonfly/replication_test.py:2417]: Yes the test won't pass without the changes in `SaveEntry()`

```
2440     # Key does not exist in replica because we skipped it                                                                                                                                                     
2441     assert await c_replica.execute_command(f"EXISTS foo") == 0 
```

Because we replicate an empty key. Now with the changes in `SaveEntry`, we no longer do that,

Comment (kostasrim) [reply tests/dragonfly/replication_test.py:2417]: Why would this test pass in the first place without the changes ?

Comment (chakaz) [reply tests/dragonfly/replication_test.py:2417]: We want to write resilient code.
For example, if we have another bug - similar to this but other - we want to be able to load it.
So we need to support loading all kinds of data types which are empty (lists, hashes, etc), and handle them correctly without failing the load.

So yeah, we want to fix the save side (which you did, awesome), but also fix the load side to be more robust (that will likely require some more handling I'm afraif)

Comment (kostasrim) [reply tests/dragonfly/replication_test.py:2417]: dude, I was completely out of context :rofl: . When you said comment out `SaveEntry` I did not understand you wanted to test the `rdb loader` only so I blindly answered the test will fail because I assumed that the test would run `without any of the changes introduced by this PR). You are right we got a bug which is easy to handle and I will fix soon

**Comment by kostasrim** [comment]
`rdb_test` shall fail, I will fix it tomorrow

File: src/server/db_slice.cc [hunk 6]
```diff
@@ -537,6 +549,9 @@ OpResult<DbSlice::PrimeItAndExp> DbSlice::FindInternal(const Context& cntx, std:
   // We do not use TopKey feature, so disable it until we redesign it.
   // db.top_keys.Touch(key);
 
+  if (DelEmptyPrimeValue(cntx, Iterator(res.it, StringOrView::FromView(key)))) {
```
Comment (kostasrim) [inline src/server/db_slice.cc:552]: Everything goes through this so we should be ok

File: tests/dragonfly/replication_test.py [hunk 7]
```diff
@@ -2411,3 +2411,21 @@ async def test_replicate_old_master(
...
+    await asyncio.sleep(2)
+
+    @assert_eventually
+    async def check_if_empty():
+        assert await async_client.execute_command("HGETALL foo") == []
+
+    await check_if_empty()
+
+    # Key does not exist and it's empty
+    assert await async_client.execute_command(f"EXISTS foo") == 0
```
Comment (dranikpg) [inline tests/dragonfly/replication_test.py:2431]: This clearly doesn't belong to replication test 🙂

File: src/server/rdb_load.cc [hunk 8]
```diff
@@ -2467,6 +2467,11 @@ void RdbLoader::LoadItemsBuffer(DbIndex db_ind, const ItemsBuf& ib) {
       stop_early_ = true;
       break;
     }
+    if (!pv.TagAllowsEmptyValue() && pv.Size() == 0) {
+      LOG(ERROR) << "Found empty key: " << item->key << " in DB " << db_ind << " rdb_type "
+                 << item->val.rdb_type;
+      continue;
+    }
```
Comment (dranikpg) [inline src/server/rdb_load.cc:2474]: Did you try replicating from our previous version with empry hsets? The fail is triggered _before_ your code in FromOpaque, so it won't help

File: tests/dragonfly/replication_test.py (hunk 7 above)
Comment (kostasrim) [reply tests/dragonfly/replication_test.py:2431]: Originally, I had the exact same chore as you did (see previous commits) however with the recent changes, we won't even reach that stage. I can move it, any particular place you want ?

File: src/server/rdb_load.cc (hunk 8 above)
Comment (kostasrim) [reply src/server/rdb_load.cc:2474]: That's actually a good suggestion -- let's make it a test 👍

File: tests/dragonfly/replication_test.py (hunk 7 above)
Comment (dranikpg) [reply tests/dragonfly/replication_test.py:2431]: I assume this belongs to the previous comment. But why can't we have instances already running that have empty listpacks

Comment (dranikpg) [reply tests/dragonfly/replication_test.py:2431]: Not sure, maybe generic test or anything

Comment (dranikpg) [reply tests/dragonfly/replication_test.py:2431]: maybe start a hash_test

File: tests/dragonfly/replication_test.py (hunk 5 above)
Comment (kostasrim) [reply tests/dragonfly/replication_test.py]: I was blindly got confused here. My fix was correct all along, in fact I introduced a full replication test that passes by loading an empty rdb file with the previous changes. 

I have no clue why the hell I got confused twice here.

File: src/server/rdb_load.cc [hunk 9]
```diff
@@ -2463,6 +2463,11 @@ void RdbLoader::LoadItemsBuffer(DbIndex db_ind, const ItemsBuf& ib) {
   for (const auto* item : ib) {
     PrimeValue pv;
     if (ec_ = FromOpaque(item->val, &pv); ec_) {
+      if ((*ec_).value() == errc::empty_key) {
+        LOG(ERROR) << "Found empty key: " << item->key << " in DB " << db_ind << " rdb_type "
+                   << item->val.rdb_type;
+        continue;
+      }
       LOG(ERROR) << "Could not load value for key '" << item->key << "' in DB " << db_ind;
```
Comment (dranikpg) [inline src/server/rdb_load.cc:2471]: nit: if we already touch this part, let's log ec as well in the "Could not load" part, maybe we'll need it in the future

File: tests/dragonfly/hash_family_test.py [hunk 10]
```diff
@@ -0,0 +1,21 @@
...
+
+
+@pytest.mark.asyncio
+async def test_empty_hash_as_zipmap_bug(async_client):
+    await async_client.execute_command("HSET foo a_field a_value")
+    await async_client.execute_command("HSETEX foo 1 b_field b_value")
+    await async_client.execute_command("HDEL foo a_field")
+
+    await asyncio.sleep(2)
+
```
Comment (dranikpg) [inline tests/dragonfly/hash_family_test.py:13]: why sleep, what are you waiting for? 🔍

File: tests/dragonfly/replication_test.py [hunk 11]
```diff
@@ -2411,3 +2411,66 @@ async def test_replicate_old_master(
...
+    cpu = platform.processor()
+    if cpu != "x86_64":
+        pytest.skip(f"Supported only on x64, running on {cpu}")
+
+    dfly_version = "v1.21.2"
+    released_dfly_path = download_dragonfly_release(dfly_version)
+
+    master = df_factory.create(path=released_dfly_path)
+    master.clear_max_chunk_flag()
+    master.start()
```
Comment (dranikpg) [inline tests/dragonfly/replication_test.py:2427]: I added version parameter recently to create, so we don't have to call clear_max_chuk_flag manually

File: tests/dragonfly/replication_test.py [hunk 12]
```diff
@@ -2411,3 +2411,66 @@ async def test_replicate_old_master(
...
+    c_replica = replica.client()
+    await c_replica.execute_command(f"REPLICAOF localhost {master.port}")
+    async with async_timeout.timeout(10):
+        await wait_for_replicas_state(c_replica)
+    assert await c_replica.execute_command(f"EXISTS foo") == 0
+    assert await c_replica.execute_command("REPLTAKEOVER 1") == "OK"
+    role, node = await c_replica.execute_command("role")
+    assert role == "master"
+
+    await close_clients(c_master, c_replica)
```
Comment (dranikpg) [inline tests/dragonfly/replication_test.py:2476]: you could've just spawned two more replicas (current version) and done to avoid this manual code

```py
instances = [old1, old2, old3, new1]
for a, b in zip(instances, instances[1:]):
  # replicate a to b
```

File: tests/dragonfly/replication_test.py [hunk 13]
```diff
@@ -2411,3 +2411,66 @@ async def test_replicate_old_master(
...
+
+@pytest.mark.asyncio
+async def test_empty_hash_map_replicate_old_master(df_factory):
+    cpu = platform.processor()
+    if cpu != "x86_64":
+        pytest.skip(f"Supported only on x64, running on {cpu}")
+
+    dfly_version = "v1.21.2"
+    released_dfly_path = download_dragonfly_release(dfly_version)
+
```
Comment (dranikpg) [inline tests/dragonfly/replication_test.py:2424]: maybe leave a comment somwhere that v1.21.2 (and before) has a known issue with hsetex not deleting the key, etc... because the person who'll be reading it in a year  has to follow a bunch of git blame links to even find out what this is about

Comment (dranikpg) [reply tests/dragonfly/replication_test.py:2424]: nit: the usual `@dfly_args({"proactor_threads": 1})` reminder (we really need to set a global limit)

**Review by dranikpg — DISMISSED** [review]

File: tests/dragonfly/hash_family_test.py (hunk 10 above)
Comment (kostasrim) [reply tests/dragonfly/hash_family_test.py:13]: accidental!

**Review by dranikpg — APPROVED** [review]
Much simpler and more effective tests now 👍🏻

File: tests/dragonfly/replication_test.py (hunk 7 above)
Comment (romange) [reply tests/dragonfly/replication_test.py]: @dranikpg  @kostasrim  why it's not a unit test?
