### PR TITLE
fix(server): Fix Lua & Zset issue

### LINKED ISSUE #713: Support laravel horizon
**Describe the bug**
Hey! I created a simple application with [laravel horizon](https://laravel.com/docs/9.x/horizon) and try to use it with **dragonflydb** as queue-driver. Currently it's working with **redis 6.2.6** or **keydb 6.3.1**.

I have 2 containers - `app_laravel` and `app_laravel_horizon`. First is simple api, with **GET** route `/api/test` that push `TestJob` job to queue and then `app_laravel_horizon` workers process this job. 

**To Reproduce**

1. Run command `docker network create app_test_network`
2. Create docker-compose.yml file with 3 containers -  `app_laravel`, `app_laravel_horizon`, and `redis_master` with password `redistestpassword`
3. Run command `docker compose -f ./docker-compose.yml up` 

```
version: '3.8'

x-sysctls-config: &sysctls-config
  sysctls:
    - net.core.somaxconn=65535
    - kernel.shmmax=33554432
    - kernel.shmall=16777216
    - kernel.msgmax=65535
    - kernel.msgmnb=65535

x-logging-local: &logging-local
  logging:
    driver: local
    options:
      max-size: "10m"
      max-file: 3

networks:
  app_test_network:
    external:
      name: app_test_network

services:
  redis_master:
    image: 'bitnami/redis:6.2.6'
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=redistestpassword
    networks:
      - app_test_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
    <<: *sysctls-config
    <<: *logging-local

#  redis_master:
#    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
#    ports:
#      - 6379:6379
#    environment:
#      - REDIS_REPLICATION_MODE=master
#      - REDIS_PASSWORD=redistestpassword
#    command:
#      - "--requirepass=redistestpassword"
#      - "--save_schedule=:" # save for every 1 minute
#      - "--dir=/data"
#      - "--dbfilename=dump.rdb"
#      - "--vmodule=main_service=2"
#    networks:
#      - app_test_network
#    deploy:
#      mode: replicated
#      replicas: 1
#      placement:
#        max_replicas_per_node: 1
#    <<: *sysctls-config
#    <<: *logging-local

  app_laravel:
    build:
      context: src
      dockerfile: Dockerfile
    restart: always
    image: fannyfan/laravel-redis-dragonfly:app_v1
    command: ["./init-octane.sh"]
    ports:
      - 8000:8000
    environment:
      - HORIZON_FAST_WORKERS_COUNT=5
      - HORIZON_SLOW_WORKERS_COUNT=5
      - OCTANE_WORKERS_COUNT=5
      - OCTANE_TASK_WORKERS_COUNT=1
      - OCTANE_PORT=8000
      - OCTANE_HOST=app
      - REDIS_HOST=redis_master
      - REDIS_PASSWORD=redistestpassword
      - REDIS_PORT=6379
    networks:
      - app_test_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
    <<: *sysctls-config
    <<: *logging-local

  app_laravel_horizon:
    image: fannyfan/laravel-redis-dragonfly:app_v1
    command: ["./init-horizon.sh"]
    restart: always
    depends_on:
      - redis_master
    environment:
      - HORIZON_FAST_WORKERS_COUNT=5
      - HORIZON_SLOW_WORKERS_COUNT=5
      - OCTANE_WORKERS_COUNT=5
      - OCTANE_TASK_WORKERS_COUNT=1
      - OCTANE_PORT=8000
      - OCTANE_HOST=app
      - REDIS_HOST=redis_master
      - REDIS_PASSWORD=redistestpassword
      - REDIS_PORT=6379
    networks:
      - app_test_network
    deploy:
      mode: replicated
      replicas: 2
      placement:
        max_replicas_per_node: 1
    <<: *sysctls-config
    <<: *logging-local
```

**Expected behavior**
1. Open `http://127.0.0.1:8000/horizon` and check that horizon status is **Active**.
2. Open in browser `http://127.0.0.1:8000/api/test` or run command `docker run --rm --net=app_test_network ghcr.io/six-ddc/plow http://app_laravel:8000/api/test -c 1 -d 1s`
3. Open `http://127.0.0.1:8000/horizon/jobs/completed` and see that jobs are completed.
4. Connect to redis_master container, run `redis-cli -a redistestpassword` and `zrange laravel_horizon:completed_jobs 0 -1` to see completed jobs. 
5. Stop all containers, comment in docker-compose.yml **redis** and uncomment **dragonfly**. Rerun containers and repeat all previous steps. 
6. Using `dragonfly ` all jobs for some reasong hang up in `pending` state and never started..

**Screenshots**
Using `redis`:

image
image

Using `dragonflydb`:

image

**Environment (please complete the following information):**
- Docker  Version: 20.10.21
- dragonflydb 0.14

### PR DESCRIPTION
**Pull request by dranikpg**
Fixes #713 

Fix issue with:
* ZRANGE LIMIT doesnt work with negative count
* `unpack` in lua is not defined

### CODE REVIEW

File: src/server/zset_family.cc [hunk 1]
```diff
@@ -265,6 +265,10 @@ void IntervalVisitor::operator()(ZSetFamily::TopNScored sc) {
 }
 
 void IntervalVisitor::ActionRange(unsigned start, unsigned end) {
+  if (params_.limit == 0)
+    return;
+  start += params_.offset;
+  end = static_cast<uint32_t>(min(1ULL * start + params_.limit - 1, 1ULL * end));
```
Comment (romange) [inline src/server/zset_family.cc:271]: what line 271 does?

Comment (dranikpg) [reply src/server/zset_family.cc:272]: Calculates new end if limit is set (< INT MAX), added a comment above

File: src/core/interpreter_test.cc [hunk 2]
```diff
@@ -321,4 +321,9 @@ TEST_F(InterpreterTest, Modules) {
   EXPECT_EQ("str(\x1\x2test)", ser_.res);
 }
 
+TEST_F(InterpreterTest, OutdatedGlobals) {
+  // Check table.unpack is accessable as a global.
+  EXPECT_TRUE(Execute("return unpack{1,2,3}"));
```
[the remark this answers is not in the document]
Comment (dranikpg) [reply src/core/interpreter_test.cc:329]: > can you add what EXPECT_EQ(...,ser_.res) too?

I added a simple one, no reason to do functional testing because we need just to export a global alias

**Review by romange — APPROVED** [review]
