### PR TITLE
fix: add missing memory tracking on streams

### LINKED ISSUE #6487: Dragonfly crashes on XTRIM
Traffic log: 

[traffic.tar.gz](https://github.com/user-attachments/files/24911032/traffic.tar.gz)

```
./traffic-replay -ignore-parse-errors run traffic/traffic*
```

```
F20260128 14:30:59.002662 38428 stream_family.cc:39] Check failed: pv.MallocUsed() != 0 
*** Check failure stack trace: ***
    @     0x5ffba6207193  google::LogMessage::Fail()
    @     0x5ffba62070d9  google::LogMessage::SendToLog()
    @     0x5ffba620688c  google::LogMessage::Flush()
    @     0x5ffba620a83a  google::LogMessageFatal::~LogMessageFatal()
    @     0x5ffba5477929  dfly::StreamMemTracker::UpdateStreamSize()
    @     0x5ffba5482fd4  dfly::(anonymous namespace)::OpTrim()
    @     0x5ffba548e793  _ZZN4dfly8CmdXTrimEN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPNS_14CommandContextEENKUlPNS_11TransactionEPNS_11EngineShardEE_clESC_SE_
    @     0x5ffba5495749  _ZZN4dfly11Transaction18ScheduleSingleHopTIRZNS_8CmdXTrimEN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPNS_14CommandContextEEUlPS0_PNS_11EngineShardEE_EEDTclfp_fpTLDnEEEOT_ENKUlSD_SF_E_clESD_SF_
    @     0x5ffba54a6fcb  _ZSt13__invoke_implIN6facade8OpStatusERKZN4dfly11Transaction18ScheduleSingleHopTIRZNS2_8CmdXTrimEN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPNS2_14CommandContextEEUlPS3_PNS2_11EngineShardEE_EEDTclfp_fpTLDnEEEOT_EUlSG_SI_E_JSG_SI_EESM_St14__invoke_otherOT0_DpOT1_
    @     0x5ffba54a5863  _ZSt8__invokeIRKZN4dfly11Transaction18ScheduleSingleHopTIRZNS0_8CmdXTrimEN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPNS0_14CommandContextEEUlPS1_PNS0_11EngineShardEE_EEDTclfp_fpTLDnEEEOT_EUlSE_SG_E_JSE_SG_EENSt15__invoke_resultISK_JDpT0_EE4typeESL_DpOSQ_
    @     0x5ffba54a33e2  _ZSt6invokeIRKZN4dfly11Transaction18ScheduleSingleHopTIRZNS0_8CmdXTrimEN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPNS0_14CommandContextEEUlPS1_PNS0_11EngineShardEE_EEDTclfp_fpTLDnEEEOT_EUlSE_SG_E_JSE_SG_EENSt13invoke_resultISK_JDpT0_EE4typeESL_DpOSQ_
    @     0x5ffba549f8f5  _ZN4absl12lts_2025051219functional_internal12InvokeObjectIZN4dfly11Transaction18ScheduleSingleHopTIRZNS3_8CmdXTrimENS0_4SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPNS3_14CommandContextEEUlPS4_PNS3_11EngineShardEE_EEDTclfp_fpTLDnEEEOT_EUlSF_SH_E_NS4_14RunnableResultEJSF_SH_EEET0_NS1_7VoidPtrEDpNS1_8ForwardTIT1_E4typeE
    @     0x5ffba5bf8ad4  absl::lts_20250512::FunctionRef<>::operator()()
    @     0x5ffba5be4cf5  dfly::Transaction::RunCallback()
    @     0x5ffba5bea21a  dfly::Transaction::ScheduleInShard()
    @     0x5ffba5beab2d  dfly::Transaction::ScheduleBatchInShard()
    @     0x5ffba5c01e3b  std::__invoke_impl<>()
    @     0x5ffba5c00bca  _ZSt10__invoke_rIvRPFvvEJEENSt9enable_ifIX16is_invocable_r_vIT_T0_JDpT1_EEES4_E4typeEOS5_DpOS6_
    @     0x5ffba5c0029f  std::_Function_handler<>::_M_invoke()
    @     0x5ffba5144632  std::function<>::operator()()
    @     0x5ffba6006580  util::fb2::FiberQueue::Run()
    @     0x5ffba5c89de7  _ZZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEENKUlvE_clEv
    @     0x5ffba5c8af6f  _ZSt13__invoke_implIvZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @     0x5ffba5c8ad12  _ZSt8__invokeIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_JEENSt15__invoke_resultIT_JDpT0_EE4typeEOS8_DpOS9_
    @     0x5ffba5c8ab20  _ZSt12__apply_implIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_St5tupleIJEEJEEDcOT_OT0_St16integer_sequenceImJXspT1_EEE
    @     0x5ffba5c8ab5a  _ZSt5applyIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_St5tupleIJEEEDcOT_OT0_
    @     0x5ffba5c8abd7  _ZN4util3fb26detail15WorkerFiberImplIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_JEE4run_EON5boost7context5fiberE
    @     0x5ffba5c8a745  _ZZN4util3fb26detail15WorkerFiberImplIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_JEEC4INS0_19FixedStackAllocatorEEES8_NS0_13FiberPriorityERKN5boost7context12preallocatedEOT_OS9_ENKUlONSF_5fiberEE_clESN_
    @     0x5ffba5c8b8e4  _ZSt13__invoke_implIN5boost7context5fiberERZN4util3fb26detail15WorkerFiberImplIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_JEEC4INS4_19FixedStackAllocatorEEESC_NS4_13FiberPriorityERKNS1_12preallocatedEOT_OSD_EUlOS2_E_JS2_EESL_St14__invoke_otherOT0_DpOT1_
    @     0x5ffba5c8b70f  _ZSt8__invokeIRZN4util3fb26detail15WorkerFiberImplIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_JEEC4INS1_19FixedStackAllocatorEEES9_NS1_13FiberPriorityERKN5boost7context12preallocatedEOT_OSA_EUlONSG_5fiberEE_JSN_EENSt15__invoke_resultISK_JDpT0_EE4typeESL_DpOSS_
    @     0x5ffba5c8b5e5  _ZSt6invokeIRZN4util3fb26detail15WorkerFiberImplIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_JEEC4INS1_19FixedStackAllocatorEEES9_NS1_13FiberPriorityERKN5boost7context12preallocatedEOT_OSA_EUlONSG_5fiberEE_JSN_EENSt13invoke_resultISK_JDpT0_EE4typeESL_DpOSS_
    @     0x5ffba5c8b380  _ZN5boost7context6detail12fiber_recordINS0_5fiberEN4util3fb219FixedStackAllocatorEZNS5_6detail15WorkerFiberImplIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_JEEC4IS6_EESE_NS5_13FiberPriorityERKNS0_12preallocatedEOT_OSF_EUlOS3_E_E3runEPv
*** SIGABRT received at time=1769603459 on cpu 1 ***
PC: @     0x7d52fdd89b2c  (unknown)  pthread_kill
    @     0x5ffba6297f25         64  absl::lts_20250512::WriteFailureInfo()
    @     0x5ffba62981a2         96  absl::lts_20250512::AbslFailureSignalHandler()
    @     0x7d52fdd30330       1760  (unknown)
    @     0x7d52fdd3027e         32  raise
    @     0x7d52fdd138ff        192  abort
    @     0x5ffba6212360        176  google::DumpStackTraceAndExit()
    @     0x5ffba6207193         16  google::LogMessage::Fail()
    @     0x5ffba62070d9        160  google::LogMessage::SendToLog()
    @     0x5ffba620688c         80  google::LogMessage::Flush()
    @     0x5ffba620a83a         32  google::LogMessageFatal::~LogMessageFatal()
    @     0x5ffba5477929        192  dfly::StreamMemTracker::UpdateStreamSize()
    @     0x5ffba5482fd4        512  dfly::(anonymous namespace)::OpTrim()
    @     0x5ffba548e793        128  dfly::CmdXTrim()::{lambda()#1}::operator()()
    @     0x5ffba5495749         64  dfly::Transaction::ScheduleSingleHopT<>()::{lambda()#1}::operator()()
    @     0x5ffba54a6fcb         64  std::__invoke_impl<>()
    @     0x5ffba54a5863         64  std::__invoke<>()
    @     0x5ffba54a33e2         64  std::invoke<>()
    @     0x5ffba549f8f5         96  absl::lts_20250512::functional_internal::InvokeObject<>()
    @     0x5ffba5bf8ad4         64  absl::lts_20250512::FunctionRef<>::operator()()
    @     0x5ffba5be4cf5        240  dfly::Transaction::RunCallback()
    @     0x5ffba5bea21a        448  dfly::Transaction::ScheduleInShard()
    @     0x5ffba5beab2d         96  dfly::Transaction::ScheduleBatchInShard()
    @     0x5ffba5c01e3b         32  std::__invoke_impl<>()
    @     0x5ffba5c00bca         32  std::__invoke_r<>()
    @     0x5ffba5c0029f         32  std::_Function_handler<>::_M_invoke()
    @     0x5ffba5144632         32  std::function<>::operator()()
    @     0x5ffba6006580        240  util::fb2::FiberQueue::Run()
    @     0x5ffba5c89de7         32  dfly::TaskQueue::Start()::{lambda()#1}::operator()()
    @     0x5ffba5c8af6f         32  std::__invoke_impl<>()
    @     0x5ffba5c8ad12         32  std::__invoke<>()
    @     0x5ffba5c8ab20         32  std::__apply_impl<>()
    @     0x5ffba5c8ab5a         48  std::apply<>()
    @ ... and at least 8 more frames
```

### LINKED ISSUE #6495: Stream memory issues
Currently we have code `stream_family.cc` that `modifies the stream state` and we do not track its memory.

Examples are:

* `OpRange` when used with consumer groups
* `FindOrAdd` consumer which might add a consumer

### PR DESCRIPTION
**Pull request by kostasrim**
There are paths in stream family that did not track memory. Now they do.

resolves #6495 and fixes #6487

also integrates https://github.com/valkey-io/valkey/commit/c8bfd23d910708f40919c62d443839e080db9fc9

I used copilot to rewrite the tests

### CODE REVIEW

File: src/server/stream_family.cc [hunk 1]
```diff
@@ -2558,11 +2562,17 @@ void XReadBlock(ReadOpts* opts, Transaction* tx, SinkReplyBuilder* builder,
           return OpStatus::OK;
         }
       }
+      auto op_args = t->GetOpArgs(shard);
```
Comment (romange) [inline src/server/stream_family.cc]: can you explain this block? why do we do it here? is it related to `FindOrAddConsumer` above ?

Comment (kostasrim) [reply src/server/stream_family.cc]: We need the compact object to update the object size. We don't want to manually call `StreamMemTracker` from `FindOrAddConsumer` because some places wrap it similarly as here as for them, the memory tracking expands to a larger scope.

I wanted to push StreamTracker to FindOrAddConsumer IMO

Comment (romange) [reply src/server/stream_family.cc]: so do we call find twice? Can you please comment on it and say it's suboptimal that it is spread like this and ideally we would move all the object centric operations into a single function.

**Comment by kostasrim** [comment]
Stil this is not 100% complete https://github.com/dragonflydb/dragonfly/issues/6487

**Comment by kostasrim** [comment]
> Stil this is not 100% complete #6487

fixed.

File: src/server/stream_family.cc (hunk 1 above)
Comment (kostasrim) [reply src/server/stream_family.cc]: done!

File: src/server/stream_family.cc [hunk 2]
```diff
@@ -2080,14 +2082,16 @@ OpResult<int64_t> OpTrim(const OpArgs& op_args, std::string_view key, const Trim
...
-
   PrimeValue& pv = res_it->it->second;
   stream* s = (stream*)pv.RObjPtr();
 
+  StreamMemTracker mem_tracker;
+
   int64_t deleted_items_number = TrimStream(opts, s);
 
-  mem_tracker.UpdateStreamSize(pv);
+  if (s->length != 0) {
```
Comment (kostasrim) [inline src/server/stream_family.cc]: This is the fix for  #6487

Comment (kostasrim) [reply src/server/stream_family.cc]: one sec will also add a small unit test

Comment (kostasrim) [reply src/server/stream_family.cc]: I wrote a unit + properly fixed this. We should not initialize an empty stream with 0 bytes as trimming the hwole thing will cause the assertion trigger

File: src/server/stream_family.cc [hunk 3]
```diff
@@ -707,6 +708,7 @@ OpResult<streamID> OpAdd(const OpArgs& op_args, string_view key, const AddOpts&
   auto& it = add_res.it;
 
   StreamMemTracker mem_tracker;
+  absl::Cleanup on_exit([it, &mem_tracker]() mutable { mem_tracker.UpdateStreamSize(it->second); });
```
Comment (kostasrim) [inline src/server/stream_family.cc:711]: That's our fix for https://github.com/dragonflydb/dragonfly/issues/6487

File: src/server/stream_family_test.cc [hunk 4]
```diff
@@ -1318,4 +1318,223 @@ TEST_F(StreamFamilyTest, XDelNonExistentId) {
...
+  resp = Run({"XINFO", "STREAM", "x", "FULL"});
+  EXPECT_THAT(resp.GetVec()[17].GetVec()[0].GetVec(),
+              ElementsAre("name", "g1", "last-delivered-id", "8-0", "entries-read", IntArg(8),
+                          "lag", IntArg(0), "pel-count", _, "pending", _, "consumers", _));
+}
+
+// Regression test for memory tracking bug when trimming a stream to empty.
+// Previously, trimming to empty would cause MallocUsed() to become 0, triggering
+// a DCHECK failure in UpdateStreamSize that treats 0 as an invalid special value.
+TEST_F(StreamFamilyTest, TrimToEmpty) {
```
Comment (kostasrim) [inline src/server/stream_family_test.cc]: TODO (for me)
Polish this test, it won't crash as is.

File: src/server/stream_family.cc [hunk 5]
```diff
@@ -2080,14 +2082,16 @@ OpResult<int64_t> OpTrim(const OpArgs& op_args, std::string_view key, const Trim
...
   stream* s = (stream*)pv.RObjPtr();
 
+  StreamMemTracker mem_tracker;
+
   int64_t deleted_items_number = TrimStream(opts, s);
 
-  mem_tracker.UpdateStreamSize(pv);
+  if (s->length != 0) {
+    mem_tracker.UpdateStreamSize(pv);
+  }
```
[the remark this answers is not in the document]
Comment (kostasrim) [reply src/server/stream_family.cc]: yeah this is true, I left this accidentally while I was merging conflicts. Removed.
