### PR TITLE
fix: unblock transactions only if requirements are correct

### LINKED ISSUE #2294: Redis STREAM consumer group have duplicates
**Describe the bug**
Redis STREAM Consumer groups have duplicates

**To Reproduce**
1. Start `dragonflydb` with docker
2. Run 3 separate session of docker exec, `docker exec -ti <container> redis-cli -a <password>`
3. In session 1: `XGROUP CREATE pokenews pokenews-group 0 MKSTREAM`
4. In session 2: `XREADGROUP GROUP pokenews-group ash COUNT 1 BLOCK 0 STREAMS pokenews >`
5. In session 3: `XREADGROUP GROUP pokenews-group ash COUNT 1 BLOCK 0 STREAMS pokenews >`
6. In session 1: `XADD pokenews * pokemon entei`

both session 2 and session 3 receives the message.

**Expected behavior**
Only session 2 OR session 3 should receive the message, both of them are in the same consumer group

**Environment (please complete the following information):**
- Host OS: MacOS `13.4.1`
 - OS: ubuntu docker image
 - Containerized?: Docker, `ghcr.io/dragonflydb/dragonfly:v1.13.0-ubuntu`
 - Dragonfly Version: `1.13.0`

**Additional context**
None

### PR DESCRIPTION
**Pull request by BorysTheDev**
fixes #2294

bug: we unblocked XREADGROUP cmd even if we don't have new values

fix: added check with custom requirements for blocking commands

### CODE REVIEW

File: src/server/blocking_controller.cc [hunk 1]
```diff
@@ -275,24 +276,29 @@ void BlockingController::AwakeWatched(DbIndex db_index, string_view db_key) {
...
-  DCHECK_EQ(wq->state, WatchQueue::SUSPENDED);
-  wq->state = WatchQueue::ACTIVE;
-
   auto& queue = wq->items;
   ShardId sid = owner_->shard_id();
 
-  do {
-    WatchItem& wi = queue.front();
-    Transaction* head = wi.get();
+  for (auto wi_it = queue.begin(), wi_e = queue.end(); wi_it != wi_e; ++wi_it) {
```
Comment (romange) [inline src/server/blocking_controller.cc:289]: as I said before, I would like to preserve a simple and efficient case of lists, sorted sets notifying a single waiter and stop.

File: src/server/blocking_controller.cc [hunk 2]
```diff
@@ -275,24 +276,29 @@ void BlockingController::AwakeWatched(DbIndex db_index, string_view db_key) {
...
+    Transaction* head = wi_it->get();
+    // We check may the transaction be notified otherwise move it to the end of the queue
+    if (!wi_it->keyReadyChecker(owner_, context, head, key)) {
+      queue.push_back(std::move(*wi_it));
+      queue.pop_front();
```
Comment (romange) [inline src/server/blocking_controller.cc:294]: you pop the first item, then you advance the iterator. looks like you skip elements.
also, you do not create an infinite loop by iterating and pushing to the end at the same time?

File: src/server/container_utils.cc [hunk 3]
```diff
@@ -283,7 +283,15 @@ OpResult<string> RunCbOnFirstNonEmptyBlocking(Transaction* trans, int req_obj_ty
   auto wcb = [](Transaction* t, EngineShard* shard) { return t->GetShardArgs(shard->shard_id()); };
 
   *block_flag = true;
-  auto status = trans->WaitOnWatch(limit_tp, std::move(wcb));
+  const auto& keyChecker = [](EngineShard* owner, const DbContext& context, Transaction*,
+                              std::string_view key) -> bool {
+    auto [it, exp_it] = owner->db_slice().FindReadOnly(context, key);
+    (void)exp_it;
+    // Only LIST, ZSET and STREAM are allowed to block.
+    return IsValid(it) && (it->second.ObjType() == OBJ_LIST || it->second.ObjType() == OBJ_ZSET ||
```
Comment (romange) [inline src/server/container_utils.cc:291]: ` (it->second.ObjType() == OBJ_LIST || it->second.ObjType() == OBJ_ZSET || it->second.ObjType() == OBJ_STREAM)` does not add much since only those types notify in the first place. this condition is always true, imho

File: src/server/blocking_controller.cc (hunk 1 above)
Comment (BorysTheDev) [reply src/server/blocking_controller.cc:289]: I don't change the behaviour)

File: src/server/blocking_controller.cc (hunk 2 above)
Comment (BorysTheDev) [reply src/server/blocking_controller.cc:294]: no infinite loop and skipped elements, but the iterator can be invalidated. Thx

File: src/server/container_utils.cc (hunk 3 above)
Comment (BorysTheDev) [reply src/server/container_utils.cc:291]: it will be fixed

File: src/server/blocking_controller.cc (hunk 1 above)
Comment (BorysTheDev) [reply src/server/blocking_controller.cc]: Didn't get your message at first. let's check how this implementation works. I can implement your suggestion regarding different queues for list, zset and stream like an optimization,

File: src/server/blocking_controller.cc [hunk 4]
```diff
@@ -275,33 +268,40 @@ void BlockingController::AwakeWatched(DbIndex db_index, string_view db_key) {
...
 
-  DCHECK_EQ(wq->state, WatchQueue::SUSPENDED);
-  wq->state = WatchQueue::ACTIVE;
-
   auto& queue = wq->items;
   ShardId sid = owner_->shard_id();
 
-  do {
-    WatchItem& wi = queue.front();
+  std::deque<dfly::WatchItem> skipped;
```
Comment (dranikpg) [inline src/server/blocking_controller.cc:281]: I think it can be just a vector

File: src/server/blocking_controller.cc [hunk 5]
```diff
@@ -275,33 +268,40 @@ void BlockingController::AwakeWatched(DbIndex db_index, string_view db_key) {
...
-      // must handled when this transaction finished.
-      wq->notify_txid = owner_->committed_txid();
-      awakened_transactions_.insert(head);
-      break;
+    // We check may the transaction be notified otherwise move it to the end of the queue
+    if (wi.keyReadyChecker(owner_, context, head, key)) {
+      DVLOG(2) << "WQ-Pop " << head->DebugId() << " from key " << key;
+
+      if (head->NotifySuspended(owner_->committed_txid(), sid, key)) {
+        DCHECK_EQ(wq->state, WatchQueue::SUSPENDED);
```
Comment (dranikpg) [inline src/server/blocking_controller.cc:290]: But generally the DCHECK still applies for the function invocation in the outermost scope? 🤔

File: src/server/container_utils.cc [hunk 6]
```diff
@@ -283,7 +283,11 @@ OpResult<string> RunCbOnFirstNonEmptyBlocking(Transaction* trans, int req_obj_ty
   auto wcb = [](Transaction* t, EngineShard* shard) { return t->GetShardArgs(shard->shard_id()); };
 
   *block_flag = true;
-  auto status = trans->WaitOnWatch(limit_tp, std::move(wcb));
+  const auto& keyChecker = [req_obj_type](EngineShard* owner, const DbContext& context,
+                                          Transaction*, std::string_view key) -> bool {
+    return owner->db_slice().FindReadOnly(context, key, req_obj_type).ok();
+  };
+  auto status = trans->WaitOnWatch(limit_tp, std::move(wcb), keyChecker);
```
Comment (dranikpg) [inline src/server/container_utils.cc:290]: This lifetime extension is scary 😄 why not just auto keyChecker =

File: src/server/transaction.h [hunk 7]
```diff
@@ -84,6 +84,10 @@ using facade::OpStatus;
 //
 // ```
 
+// Check that the command can be run
+using KeyReadyChecker =
+    std::function<bool(EngineShard*, const DbContext& context, Transaction* tx, std::string_view)>;
+
```
Comment (dranikpg) [inline src/server/transaction.h:90]: what if we move it into the transaction class next to WaitKeysProvider?

Comment (dranikpg) [reply src/server/transaction.h:90]: Let's also extend the comment: `checks whether the touched key is valid for a blocking transaction watching it`

**Review by dranikpg — DISMISSED** [review]
I approve the approach, just some style comments 🙂

File: src/server/container_utils.cc (hunk 6 above)
Comment (BorysTheDev) [reply src/server/container_utils.cc:290]: there is no difference in this case)

**Review by dranikpg — DISMISSED** [review]

File: src/server/blocking_controller.cc [hunk 8]
```diff
@@ -20,12 +22,13 @@ using namespace std;
 
 struct WatchItem {
   Transaction* trans;
+  KeyReadyChecker keyReadyChecker;
```
Comment (romange) [inline src/server/blocking_controller.cc:25]: variable naming is not according to our styleguide

File: src/server/container_utils.cc [hunk 9]
```diff
@@ -283,7 +283,11 @@ OpResult<string> RunCbOnFirstNonEmptyBlocking(Transaction* trans, int req_obj_ty
   auto wcb = [](Transaction* t, EngineShard* shard) { return t->GetShardArgs(shard->shard_id()); };
 
   *block_flag = true;
-  auto status = trans->WaitOnWatch(limit_tp, std::move(wcb));
+  const auto keyChecker = [req_obj_type](EngineShard* owner, const DbContext& context, Transaction*,
```
Comment (romange) [inline src/server/container_utils.cc:286]: variable name

File: src/server/list_family.cc [hunk 10]
```diff
@@ -881,8 +881,12 @@ OpResult<string> BPopPusher::RunSingle(Transaction* t, time_point tp) {
 
   auto wcb = [&](Transaction* t, EngineShard* shard) { return ArgSlice{&this->pop_key_, 1}; };
 
+  const auto keyChecker = [](EngineShard* owner, const DbContext& context, Transaction*,
```
Comment (romange) [inline src/server/list_family.cc:884]: var name

File: src/server/stream_family.cc [hunk 11]
```diff
@@ -2817,7 +2817,27 @@ void XReadBlock(ReadOpts opts, ConnectionContext* cntx) {
   auto tp = (opts.timeout) ? chrono::steady_clock::now() + chrono::milliseconds(opts.timeout)
                            : Transaction::time_point::max();
 
-  if (auto status = cntx->transaction->WaitOnWatch(tp, std::move(wcb)); status != OpStatus::OK)
+  const auto& keyChecker = [&opts](EngineShard* owner, const DbContext& context, Transaction* tx,
```
Comment (romange) [inline src/server/stream_family.cc:2820]: curious why `const auto&` and not `const auto`? seems like unneeded complexity, since you introduce const reference to a temporary expression.

File: src/server/stream_family.cc [hunk 12]
```diff
@@ -2817,7 +2817,27 @@ void XReadBlock(ReadOpts opts, ConnectionContext* cntx) {
...
+
+    const CompactObj& cobj = (*res_it)->second;
+    stream* s = GetReadOnlyStream(cobj);
+    streamID last_id = s->last_id;
+    if (s->length) {
+      streamLastValidID(s, &last_id);
+    }
+
+    auto sitem = opts.stream_ids.at(key);
+    if (sitem.id.val.ms != UINT64_MAX && sitem.id.val.seq != UINT64_MAX)
```
Comment (romange) [inline src/server/stream_family.cc:2834]: can we move lines 2833-2834  before the line 2826?

**Review by romange — COMMENTED** [review]
looks good

File: src/server/stream_family.cc (hunk 11 above)
Comment (BorysTheDev) [reply src/server/stream_family.cc:2820]: there are no differences from my point of view, but I will update ir

**Review by romange — APPROVED** [review]
