### PR TITLE
fix: Correctly read container limits when running under k8s

### LINKED ISSUE #1683: Incorrect CGroup v1 Resource Detection
Let's assume that `cat /proc/1/cgroup` outputs:

```shell
...
5:cpu,cpuacct:/some_group
...
3:memory:/some_other_group
...
```

moreover, assume we are running under some container (e.g., Kube). Then it might be the case that the CGroup `/memory/some_group` doesn't exist, causing us to skip over reading memory values. On the other hand, the container's limits are *also* present in `/memory/memory.limit_in_bytes` (for v1 only!) (in fact, this is the system's memory limit so it applies globally).

The same thing of course can happen with CPU values.

---

This issue was raised by a Discord member, link [here](https://discord.com/channels/981533931486724126/1138402621389029419).

### PR DESCRIPTION
**Pull request by talbii**
Closes #1683.

---

Background: In k8s, the memory/CPU cgroups which are reported by `/proc/self/cgroup` do not exist, i.e., the path `/sys/fs/cgroup/<resource>/<k8s cgroup>` doesn't exist. This causes Dragonfly to not read container limits at all, hence missing potential limits set by the user.

Fix: Begin by first reading `/sys/fs/cgroup/<resource>/<limit>`, which, in words, means "read the resource limits of the system". Later the path `/sys/fs/cgroup/<resource>/<specific group>` is read, updating the limit if needed.

### CODE REVIEW

**Comment by talbii** [comment]
I would be happy if someone suggested a way to run Dragonfly under Kubernetes, as I'm rather noobish in that area :smile:

**Review by kostasrim — COMMENTED** [review]
looks good, have you tested this manually to see if there is an issue? (0 experience with k8 here)

**Comment by kostasrim** [comment]
> I would be happy if someone suggested a way to run Dragonfly under Kubernetes, as I'm rather noobish in that area 😄

hahaha, I missed this and I explicitly asked for this! I am afraid I can't help much with k8 :(

File: src/server/dfly_main.cc [hunk 1]
```diff
@@ -547,7 +547,19 @@ error_code GetCGroupPath(string* memory_path, string* cpu_path) {
...
+  using absl::StrCat;
+
+  auto read_mem = [](string_view path, size_t* output) {
+    auto file = io::ReadFileToString(path);
+    DVLOG(1) << "container limits: read " << path << ": " << file.value_or("N/A");
+
+    size_t temp = numeric_limits<size_t>::max();
+
+    if (file.has_value() && !absl::StartsWith(*file, "max"))
+      CHECK(absl::SimpleAtoi(*file, &temp));
```
Comment (romange) [inline src/server/dfly_main.cc:559]: @talbii  given our past experience with parsing cgroups files, I would like to avoid using check-fails in this code and just give up on auto-deducing memory with printing errors where needed.

**Comment by romange** [comment]
Please expand in the commit message what was the bug and what has been changed. It's not really easy to understand what the fix is just by reading the code.

File: src/server/dfly_main.cc (hunk 1 above)
Comment (talbii) [reply src/server/dfly_main.cc:559]: great idea!

File: src/server/dfly_main.cc [hunk 2]
```diff
@@ -515,8 +515,10 @@ error_code GetCGroupPath(string* memory_path, string* cpu_path) {
   if (groups.size() == 1) {
     // for v2 we only read 0::<name>
     size_t pos = cgv.rfind(':');
-    if (pos == string::npos)
+    if (pos == string::npos) {
+      *memory_path = cgv;
```
Comment (talbii) [inline src/server/dfly_main.cc:519]: this is a bit hacky but I feel like it would save a bit of hassle in the future. Happy to hear some comments

(fyi: this is used in line 582)

File: src/server/dfly_main.cc [hunk 3]
```diff
@@ -557,68 +581,93 @@ void UpdateResourceLimitsIfInsideContainer(io::MemInfoData* mdata, size_t* max_t
...
-  DVLOG(1) << "memory.max: " << mmax.value_or("N/A");
+  // Read cgroup-specific limits
+  read_mem(StrCat(mem_path, "/memory.limit_in_bytes"), &mdata->mem_total);
+  read_mem(StrCat(mem_path, "/memory.max"), &mdata->mem_total);
+  read_mem(StrCat(mem_path, "/memory.high"), &mdata->mem_avail);
 
-  if (mmax && !absl::StartsWith(*mmax, "max")) {
-    CHECK(absl::SimpleAtoi(*mmax, &mdata->mem_total));
-  }
+  mdata->mem_avail = min(mdata->mem_avail, mdata->mem_total);
```
Comment (kostasrim) [inline src/server/dfly_main.cc:601]: Can the total memory ever be less than the available memory?

**Review by kostasrim — COMMENTED** [review]
Have you tested this? 

I have to look a little bit deeper on how control groups are managed by linux. I will come back to this PR, in the meantime when you get a chance reply to my questions!

File: src/server/dfly_main.cc (hunk 3 above)
Comment (talbii) [reply src/server/dfly_main.cc:601]: oh good catch! because `read_mem()` also updates via `min` I think this `min` is actually redundant!

File: src/server/dfly_main.cc (hunk 2 above)
Comment (talbii) [reply src/server/dfly_main.cc:519]: realistically this branch should never enter because that is simply the expected format of cgroups. this is assuming the function which reads is correct, but I think its a fair assumption :smile_cat: 

I guess originally I added that check as a sanity check. I will change this to `LOG(ERROR)` and exit, instead of returning.

**Comment by talbii** [comment]
> Have you tested this?
> 
> I have to look a little bit deeper on how control groups are managed by linux. I will come back to this PR, in the meantime when you get a chance reply to my questions!

if you have any issues feel free to contact internally :)

When I first introduced this I wrote a small guide for testing: https://github.com/dragonflydb/dragonfly/commit/e646476359113ae5793557b3e90ee2203ecace2a

File: src/server/dfly_main.cc (hunk 3 above)
Comment (talbii) [reply src/server/dfly_main.cc:601]: edit: wait no that is not right. If we set `memory.max` to `8G`, not set `memory.high`, and the memory has more than 8G of available memory then the assignment does `mem_avail = mem_total`.

On the other hand, if the available memory is less than what was set in `mem_total`, the assignment is `mem_avail = mem_total`.

So I don't think its possible to remove the `min()` here.

**Review by kostasrim — APPROVED** [review]
