### PR TITLE
fix: data race in save_stages_controller

### LINKED ISSUE #2644: race condition on `INFO ALL` && `BGSAVE`
We have a race condition when `INFO ALL` && `BGSAVE` is called concurrently. The problem is within `BGSAVE` command:

`ServerFamily::DoSave` :

```
    {
      std::lock_guard lk(save_mu_);
      if (save_controller_) {
        return GenericError{make_error_code(errc::operation_in_progress),
                            "SAVING - can not save database"};
      }    
      save_controller_ = make_unique<SaveStagesController>(detail::SaveStagesInputs{
          new_version, basename, trans, &service_, fq_threadpool_.get(), snapshot_storage_});
    }
  
    detail::SaveInfo save_info = save_controller_->Save();
```

and in `INFO ALL`: 

```
      lock_guard lk{save_mu_};
      if (save_controller_) {
        save_buffer_bytes = save_controller_->GetSaveBuffersSize();
```

The issue is that the initialization of the object `SaveController` is done within `save_controller_->Save()` which no longer holds a lock to the mutex. Therefore `GetSaveBufferSize()` access to local `snapshot_` is a race condition, because there is a modify read/write operation concurrently (INFO ALL is trying to access the member variable snapshots while save_controller is trying to initialize it). 

I think there other similar races in this path, so it should be checked as well.

### PR DESCRIPTION
**Pull request by kostasrim**
fixes #2644

* Initialize resources atomically to avoid race condition
* Finalize/cleanup resources atomically to avoid race condition
* Refactor SaveStagesController::Save

### CODE REVIEW

File: src/server/server_family.cc [hunk 1]
```diff
@@ -1300,25 +1300,40 @@ GenericError ServerFamily::DoSave(bool new_version, string_view basename, Transa
...
+    if (res) {
+      CHECK_EQ(res->error, true);
+      set_last_save_error(*res);
+      save_controller_.reset();
+      return res->error;
+    }
   }
 
-  detail::SaveInfo save_info = save_controller_->Save();
+  save_controller_->WaitAllSnapshots();
```
Comment (kostasrim) [inline src/server/server_family.cc:1329]: Bonus point because now the function clearly suggests what's happening. @romange we can turn this function async easily. We could add a background fiber for that, which would turn `BGSAVE` from synchronous to asynchronous. This is not a priority but since it was mentioned in the issues I am bringing it up :)

File: src/server/detail/save_stages_controller.cc [hunk 2]
```diff
@@ -164,8 +165,14 @@ SaveInfo SaveStagesController::Save() {
...
 
+  return {};
+}
+
+void SaveStagesController::RunSaveSteps() {
   RunStage(&SaveStagesController::SaveCb);
+}
 
+SaveInfo Finalize() {
   RunStage(&SaveStagesController::CloseCb);
```
Comment (kostasrim) [inline src/server/detail/save_stages_controller.cc:176]: This should be done atomically as well

**Review by dranikpg — DISMISSED** [review]
If to follow it fully, the mechanism behind `GetTotalBuffersSize()` is quite complicated

For DFS we dispatch immediately from `SaveStagesController` and assume we're placed on each shard correctly

For RDB we call `RdbSnapshot::Impl::GetSaveBuffersSize` transparently and dispatch only there on all the snapshot threads

So we have branching twice, but on different levels 🤯 

Left some nits

File: src/server/server_family.cc [hunk 3]
```diff
@@ -1300,25 +1300,41 @@ GenericError ServerFamily::DoSave(bool new_version, string_view basename, Transa
...
                           "SAVING - can not save database"};
     }
+
     save_controller_ = make_unique<SaveStagesController>(detail::SaveStagesInputs{
         new_version, basename, trans, &service_, fq_threadpool_.get(), snapshot_storage_});
+
+    auto res = save_controller_->InitResourcesAndStart();
+
+    if (res) {
+      CHECK_EQ(res->error, true);
```
Comment (romange) [inline src/server/server_family.cc:1322]: if this invariant won't hold will we reach UB? I do not think so.
If not, we should replace CHECK with DCHECK - to reduce the risk of crashing because of minor bugs.

File: src/server/server_family.cc [hunk 4]
```diff
@@ -1300,25 +1300,41 @@ GenericError ServerFamily::DoSave(bool new_version, string_view basename, Transa
...
     std::lock_guard lk(save_mu_);
     if (save_controller_) {
       return GenericError{make_error_code(errc::operation_in_progress),
                           "SAVING - can not save database"};
     }
+
     save_controller_ = make_unique<SaveStagesController>(detail::SaveStagesInputs{
         new_version, basename, trans, &service_, fq_threadpool_.get(), snapshot_storage_});
+
+    auto res = save_controller_->InitResourcesAndStart();
```
Comment (romange) [inline src/server/server_family.cc:1319]: Why not have "Init()" function that can fail and then keep `Save()` function that does Start and Wait as before?

File: src/server/server_family.cc (hunk 1 above)
Comment (romange) [reply src/server/server_family.cc:1329]: ok, this answers my first question.

File: src/server/detail/save_stages_controller.h [hunk 5]
```diff
@@ -71,10 +71,13 @@ class RdbSnapshot {
...
 struct SaveStagesController : public SaveStagesInputs {
   SaveStagesController(SaveStagesInputs&& input);
+  std::optional<SaveInfo> InitResourcesAndStart();
 
   ~SaveStagesController();
 
-  SaveInfo Save();
+  void WaitAllSnapshots();
+
+  SaveInfo Finalize();
```
[the remark this answers is not in the document]
Comment (romange) [reply src/server/detail/save_stages_controller.h:80]: I agree, the interface a bit non-intuitive. I also agree that this PR should not do lots of changes.

File: src/server/server_family.cc [hunk 6]
```diff
@@ -1300,25 +1300,41 @@ GenericError ServerFamily::DoSave(bool new_version, string_view basename, Transa
                         StrCat(GlobalStateName(state), " - can not save database")};
   }
 
+  auto set_last_save_error = [this](const auto& save_info) mutable {
+    last_save_info_.last_error = save_info.error;
+    last_save_info_.last_error_time = save_info.save_time;
+    last_save_info_.failed_duration_sec = save_info.duration_sec;
+  };
```
[the remark this answers is not in the document]
Comment (kostasrim) [reply src/server/server_family.cc:1307]: I agree and since it's a very quick change, I did it now :) The only todo I will leave is a major TODO :refactor :rofl:

File: src/server/detail/save_stages_controller.cc [hunk 7]
```diff
@@ -151,10 +151,11 @@ SaveStagesController::SaveStagesController(SaveStagesInputs&& inputs)
 SaveStagesController::~SaveStagesController() {
 }
 
-SaveInfo SaveStagesController::Save() {
+std::optional<SaveInfo> SaveStagesController::InitResourcesAndStart() {
   if (auto err = BuildFullPath(); err) {
     shared_err_ = err;
-    return GetSaveInfo();
+    SaveInfo save = GetSaveInfo();
+    return std::optional<SaveInfo>(std::move(save));
```
[the remark this answers is not in the document]
Comment (kostasrim) [reply src/server/detail/save_stages_controller.cc:158]: On my defense, I was experimenting with a false positive from you complete me. Basically I had it like this and I got a warning on Vim so I changed it because I was curious if the warning would go away (it didn't) and I left forgotten as is :eyes:

File: src/server/server_family.cc (hunk 3 above)
Comment (kostasrim) [reply src/server/server_family.cc:1322]: made it a DCHECK

File: src/server/detail/save_stages_controller.h (hunk 5 above)
[the remark this answers is not in the document]
Comment (kostasrim) [reply src/server/detail/save_stages_controller.h:80]: I added comments. I wanted to push a refactor as I wrote somewhere else but I thought for not it's best to only fix the issue (even if it's not perfect)

File: src/server/server_family.cc (hunk 4 above)
Comment (kostasrim) [reply src/server/server_family.cc:1319]: This is exactly what we do. But I assume you know this from: 

> ok, this answers my first question.

**Review by dranikpg — APPROVED** [review]
Please wait to see if Roman has any objections because I'm as usually an early-approver 😆

**Review by romange — APPROVED** [review]
