### PR TITLE
fix(server): Do not block admin-port commands

### LINKED ISSUE #2703: crash in migrate flow
Before migrating a connection we should join on connection-dispatch fiber.

see here for faulty run: https://github.com/dragonflydb/dragonfly/actions/runs/8203214807/job/22435576161#step:12:703

cc @adiholden 

```
30002➜ Check failure stack trace: ***
30002➜ 12:46:07.572312 32135 dragonfly_connection.cc:1411] Check failed: !dispatch_fb_.IsJoinable() 
30002➜ Check failure stack trace: ***
30002➜    @     0x556e17f1dea0  google::LogMessage::Fail()
30002➜    @     0x556e17f1dea0  google::LogMessage::Fail()
30002➜    @     0x556e17f25093  google::LogMessage::SendToLog()
30002➜    @     0x556e17f25093  google::LogMessage::SendToLog()
30002➜    @     0x556e17f1d857  google::LogMessage::Flush()
30002➜    @     0x556e17f1d857  google::LogMessage::Flush()
30002➜    @     0x556e17f1f1df  google::LogMessageFatal::~LogMessageFatal()
30002➜    @     0x556e17f1f1df  google::LogMessageFatal::~LogMessageFatal()
30002➜    @     0x556e17aa863f  facade::Connection::Migrate()
30002➜    @     0x556e17aa863f  facade::Connection::Migrate()
30002➜    @     0x556e178e4f7b  dfly::ClusterFamily::DflyMigrateFlow()
30002➜    @     0x556e178e4f7b  dfly::ClusterFamily::DflyMigrateFlow()
30002➜    @     0x556e178ea352  dfly::ClusterFamily::DflyMigrate()
30002➜    @     0x556e178ea352  dfly::ClusterFamily::DflyMigrate()
30002➜    @     0x556e179da32f  dfly::CommandId::Invoke()
30002➜    @     0x556e179da32f  dfly::CommandId::Invoke()
30002➜    @     0x556e177c986c  dfly::Service::InvokeCmd()
30002➜    @     0x556e177c986c  dfly::Service::InvokeCmd()
30002➜    @     0x556e177ce3b7  dfly::Service::DispatchCommand()
30002➜    @     0x556e177ce3b7  dfly::Service::DispatchCommand()
30002➜    @     0x556e17aaa059  facade::Connection::DispatchCommand()
30002➜    @     0x556e17aaa059  facade::Connection::DispatchCommand()
30002➜    @     0x556e17aaa350  facade::Connection::ParseRedis()
30002➜    @     0x556e17aaa350  facade::Connection::ParseRedis()
30002➜    @     0x556e17aad21a  facade::Connection::ConnectionFlow()
30002➜    @     0x556e17aad21a  facade::Connection::ConnectionFlow()
30002➜    @     0x556e17aae26f  facade::Connection::HandleRequests()
30002➜    @     0x556e17aae26f  facade::Connection::HandleRequests()
30002➜    @     0x556e17ec8e2d  util::ListenerInterface::RunSingleConnection()
30002➜    @     0x556e17ec8e2d  util::ListenerInterface::RunSingleConnection()
```

### PR DESCRIPTION
**Pull request by chakaz**
There are a few use cases which cause a temporary block of connections:
* `CLIENT PAUSE` command
* replica takeover
* cluster config / migration

Before this PR, these commands interfered with replication / migration connections, which could cause delays and even deadlocks.

We do not want such internal connections to ever be blocked, and it's ok to assume they won't issue regular "data" commands. As such, this PR disables blocking any commands issued via an admin-port, and once merged we'll recommend issuing replication and cluster migration via the admin port.

Fixes #2703

### CODE REVIEW

File: src/facade/dragonfly_listener.cc [hunk 1]
```diff
@@ -429,8 +429,12 @@ DispatchTracker::DispatchTracker(absl::Span<facade::Listener* const> listeners,
 }
 
 void DispatchTracker::TrackOnThread() {
-  for (auto* listener : listeners_)
+  for (auto* listener : listeners_) {
+    if (listener->IsPrivilegedInterface()) {
```
Comment (BorysTheDev) [inline src/facade/dragonfly_listener.cc:433]: I think we  shouldn't check this in the dispatch tracker. It's better to provide listeners without admin port

File: src/facade/dragonfly_listener.cc [hunk 2]
```diff
@@ -429,8 +429,12 @@ DispatchTracker::DispatchTracker(absl::Span<facade::Listener* const> listeners,
 }
 
 void DispatchTracker::TrackOnThread() {
```
Comment (adiholden) [inline src/facade/dragonfly_listener.cc:431]: Note that DispatchTracker is also used on shutdown in Listener::PreShutdown() and in this flow I believe we should run on all listeners

**Comment by chakaz** [comment]
Yes, you are both right. I tried to save an allocation, but that's not worth it.

**Review by adiholden — APPROVED** [review]
