### PR TITLE
fix(server): lag is 0 when server not in stable state

### LINKED ISSUE #2923: Please report replication lag zero while full sync
We sometimes encounter false high replication lag alarms during updates as the lag is huge when starting full sync. Would it makes sense for dragonfly to report lag=0 while not in stable sync?

### PR DESCRIPTION
**Pull request by adiholden**
fixes #2923

### CODE REVIEW

File: src/server/dflycmd.cc [hunk 1]
```diff
@@ -690,11 +690,11 @@ std::vector<ReplicaRoleInfo> DflyCmd::GetReplicasRoleInfo() const {
       state = info->replica_state;
       // If the replica is not in stable sync, its lag is undefined, so we set it as max.
       if (state != SyncState::STABLE_SYNC) {
```
Comment (romange) [inline src/server/dflycmd.cc:692]: please fix the comment as well

**Review by romange — APPROVED** [review]
