### PR TITLE
fix(server): initialize replica acked lsn

### LINKED ISSUE #2235: Crash in master
Stack:

```
F20231130 15:01:55.881577  9246 dflycmd.cc:772] Check failed: lag >= 0
*** Check failure stack trace: ***
    @     0x55b3a8e1d4f1  google::LogMessage::Fail()
    @     0x55b3a8e1d437  google::LogMessage::SendToLog()
    @     0x55b3a8e1cc0c  google::LogMessage::Flush()
    @     0x55b3a8e20a84  google::LogMessageFatal::~LogMessageFatal()
    @     0x55b3a7e84c9c  _ZZNK4dfly7DflyCmd15ReplicationLagsEvENKUlPNS_11EngineShardEE_clES2_
    @     0x55b3a7e8b9af  _ZZNK4dfly14EngineShardSet18RunBriefInParallelIZNKS_7DflyCmd15ReplicationLagsEvEUlPNS_11EngineShardEE_ZNKS0_18RunBriefInParallelIS5_EEvOT_EUlS7_E_EEvS8_OT0_ENUlvE_clEv
    @     0x55b3a7eaf609  _ZN3fu27abi_4006detail10invocation6invokeIRZNK4dfly14EngineShardSet18RunBriefInParallelIZNKS4_7DflyCmd15ReplicationLagsEvEUlPNS4_11EngineShardEE_ZNKS5_18RunBriefInParallelISA_EEvOT_EUlSC_E_EEvSD_OT0_EUlvE_JEEEDTclcl7forwardISC_Efp_Espcl7forwardIT0_Efp0_EEESD_DpOSJ_
    @     0x55b3a7eadd32  _ZN3fu27abi_4006detail12type_erasure16invocation_table14function_traitIFvvEE16internal_invokerINS2_3boxILb0EZNK4dfly14EngineShardSet18RunBriefInParallelIZNKS9_7DflyCmd15ReplicationLagsEvEUlPNS9_11EngineShardEE_ZNKSA_18RunBriefInParallelISF_EEvOT_EUlSH_E_EEvSI_OT0_EUlvE_SaISM_EEELb1EE6invokeEPNS2_13data_accessorEm
    @     0x55b3a8d97b08  _ZNK3fu27abi_4006detail12type_erasure6tables6vtableINS1_8propertyILb0ELb0EJFvvEEEEE6invokeILm0EJPNS2_13data_accessorERKmEEEDcDpOT0_
    @     0x55b3a8d97c7f  _ZN3fu27abi_4006detail12type_erasure7erasureILb1ENS1_6configILb1ELb0ENS_14capacity_fixedILm16ELm8EEEEENS1_8propertyILb0ELb0EJFvvEEEEE6invokeILm0ERSB_JEEEDcOT0_DpOT1_
    @     0x55b3a8d97d10  fu2::abi_400::detail::type_erasure::invocation_table::operator_impl<>::operator()()
    @     0x55b3a8d83108  util::fb2::UringProactor::MainLoop()
    @     0x55b3a8bebda4  util::fb2::ProactorDispatcher::Run()
    @     0x55b3a8c2ce9b  util::fb2::detail::(anonymous namespace)::DispatcherImpl::Run()
    @     0x55b3a8c2bbb9  _ZZN4util3fb26detail12_GLOBAL__N_114DispatcherImplC4ERKN5boost7context12preallocatedEONS5_21basic_fixedsize_stackINS5_12stack_traitsEEEPNS1_9SchedulerEENKUlONS5_5fiberEE_clESG_
    @     0x55b3a8c3d1bd  _ZSt13__invoke_implIN5boost7context5fiberERZN4util3fb26detail12_GLOBAL__N_114DispatcherImplC4ERKNS1_12preallocatedEONS1_21basic_fixedsize_stackINS1_12stack_traitsEEEPNS5_9SchedulerEEUlOS2_E_JS2_EET_St14__invoke_otherOT0_DpOT1_
    @     0x55b3a8c3cf74  _ZSt8__invokeIRZN4util3fb26detail12_GLOBAL__N_114DispatcherImplC4ERKN5boost7context12preallocatedEONS6_21basic_fixedsize_stackINS6_12stack_traitsEEEPNS2_9SchedulerEEUlONS6_5fiberEE_JSG_EENSt15__invoke_resultIT_JDpT0_EE4typeEOSL_DpOSM_
    @     0x55b3a8c3cc9b  _ZSt6invokeIRZN4util3fb26detail12_GLOBAL__N_114DispatcherImplC4ERKN5boost7context12preallocatedEONS6_21basic_fixedsize_stackINS6_12stack_traitsEEEPNS2_9SchedulerEEUlONS6_5fiberEE_JSG_EENSt13invoke_resultIT_JDpT0_EE4typeEOSL_DpOSM_
    @     0x55b3a8c3c871  _ZN5boost7context6detail12fiber_recordINS0_5fiberERNS0_21basic_fixedsize_stackINS0_12stack_traitsEEEZN4util3fb26detail12_GLOBAL__N_114DispatcherImplC4ERKNS0_12preallocatedEOS6_PNSA_9SchedulerEEUlOS3_E_E3runEPv
    @     0x55b3a8c3c1a4  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberERNS0_21basic_fixedsize_stackINS0_12stack_traitsEEEZN4util3fb26detail12_GLOBAL__N_114DispatcherImplC4ERKNS0_12preallocatedEOS7_PNSB_9SchedulerEEUlOS4_E_EEEEvNS1_10transfer_tE
    @     0x7fd7e906f24f  make_fcontext
*** SIGABRT received at time=1701349316 on cpu 3 ***
PC: @     0x7fd7e80869fc  (unknown)  pthread_kill
    @     0x55b3a8ea26dd         64  absl::lts_20230802::WriteFailureInfo()
    @     0x55b3a8ea2937         96  absl::lts_20230802::AbslFailureSignalHandler()
    @     0x7fd7e8032520  (unknown)  (unknown)
./replication.sh: line 24:  9242 Aborted                 (core dumped) ~/dragonfly/build-dbg/dragonfly --proactor_threads=4 --dbfilename= --logtostdout

```

Core can be found [here](https://drive.google.com/drive/folders/1_Tg5Bog9JNUkTeVLHUQB6I2cP2eLmZlq?usp=sharing), while the debug symbols and sources are the same as https://github.com/dragonflydb/dragonfly/issues/2234

### PR DESCRIPTION
**Pull request by adiholden**
fixes #2235

### CODE REVIEW

File: src/server/dflycmd.h [hunk 1]
```diff
@@ -46,7 +46,7 @@ struct FlowInfo {
   DflyVersion version;
 
   std::optional<LSN> start_partial_sync_at;
-  uint64_t last_acked_lsn;
+  uint64_t last_acked_lsn = 0;
```
Comment (chakaz) [inline src/server/dflycmd.h:49]: If it's possible to use this class before initialization, shouldn't we also initialize `conn` and `version`?

**Review by kostasrim — APPROVED** [review]

**Review by chakaz — APPROVED** [review]
