### PR TITLE
fix(server): Dont apply memory limit when loading/replicating

### LINKED ISSUE #1708: bad_alloc on replica when master near maxmemory (cache_mode=true)
**Describe the bug**
Hey, I encountered a `bad_alloc` error when trying several failover scenarios and replicas have a problem syncing with the master when the master is near or at its configured `maxmemory` limit. We are using mostly SET, INCR and EXPIRE commands.

```
F20230816 18:27:38.024061     9 fiberqueue_threadpool.cc:50] Exception std::bad_alloc
*** Check failure stack trace: ***
    @     0x5bc6bec96d23  google::LogMessage::SendToLog()
    @     0x5bc6bec8f4e7  google::LogMessage::Flush()
    @     0x5bc6bec90e6f  google::LogMessageFatal::~LogMessageFatal()
    @     0x5bc6be724726  _ZN4util3fb210FiberQueue3RunEv.cold
    @     0x5bc6be86c6e2  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberENS0_21basic_fixedsize_stackINS0_12stack_traitsEEEZN4util3fb26detail15WorkerFiberImplIZN4dfly11EngineShardC4EPNS9_12ProactorBaseEbP9mi_heap_sEUlvE0_JEEC4IS7_EESt17basic_string_viewIcSt11char_traitsIcEERKNS0_12preallocatedEOT_OSI_EUlOS4_E_EEEEvNS1_10transfer_tE.lto_priv.0
    @     0x5bc6beab6d2f  make_fcontext
*** SIGABRT received at time=1692210458 on cpu 0 ***
PC: @     0x7bac064aa00b  (unknown)  raise
[failure_signal_handler.cc : 332] RAW: Signal 11 raised at PC=0x7bac06489941 while already in AbslFailureSignalHandler()
*** SIGSEGV received at time=1692210458 on cpu 0 ***
PC: @     0x7bac06489941  (unknown)  abort
```

**To Reproduce**
I managed to reproduce this locally as well, using the following steps:

1. Run 2 instances of dragonfly - 16379 (master) and 26379 (replica)
    - `docker run -p 16379:6379 --ulimit memlock=-1 docker.dragonflydb.io/dragonflydb/dragonfly:v1.8.0 --maxmemory=300mb --cache_mode=true`
    - `docker run -p 26379:6379 --ulimit memlock=-1 docker.dragonflydb.io/dragonflydb/dragonfly:v1.8.0 --maxmemory=300mb --cache_mode=true`
2. load data - random INCR keys until master hits maxmemory
    - `redis-benchmark -h localhost -p 16379 -n 10000000 -r 20000000 -t incr` 
this took about 5m for me)
3. attempt to configure replication
    - `redis-cli -u redis://localhost:26379 replicaof host.containers.internal 16379`
    - dragonfly replica will fail with `bad_alloc` error, and master with `io error system:103`

**Expected behavior**
Replica should successfully connect and enter stable sync with master. 

**Environment (please complete the following information):**
 - Containerized?: Yes, Docker locally and Kubernetes (GKE)
 - Dragonfly Version: 1.8.0

**Additional context**
Gist with repro and `INFO ALL` from a production (GKE kubernetes) environment
https://gist.github.com/eidam/b68ec6f2339a0347e9d70fb0c26e9263

### PR DESCRIPTION
**Pull request by adiholden**
No memory limit on loading from file or replicating.
When loading a snapshot created by the same server configuration (memory and
number of shards) we will create a different dash table segment directory tree, because the
tree shape is related to the order of entries insertion. Therefore when loading data from
snapshot or from replication the conservative memory checks might fail as the new tree might
have more segments. Because we dont want to fail loading a snapshot from the same server
configuration we disable this checks on loading and replication.

fixes #1708

### CODE REVIEW

File: src/server/db_slice.cc [hunk 1]
```diff
@@ -396,8 +397,23 @@ tuple<PrimeIterator, ExpireIterator, bool> DbSlice::AddOrFind2(const Context& cn
...
+  // memory limit. When loading a snapshot created by the same server configuration (memory and
+  // number of shards) we will create a different dash table segment directory tree, because the
+  // tree shape is related to the order of entries insertion. Therefore when loading data from
+  // snapshot or from replication the conservative memory checks might fail as the new tree might
+  // have more segments. Because we dont want to fail loading a snapshot from the same server
+  // configuration we disable this checks on loading and replication.
+  bool apply_memory_limit =
+      !owner_->IsReplica() && !(ServerState::tlocal()->gstate() == GlobalState::LOADING);
+
+  PrimeEvictionPolicy evp{cntx,
```
Comment (royjacobson) [inline src/server/db_slice.cc:411]: Is this something we'll need to adjust when executing `REPLICAOF NO ONE` on a replica?

Comment (royjacobson) [reply src/server/db_slice.cc:411]: ah, nvm

**Review by royjacobson — APPROVED** [review]
lgtm

File: src/server/db_slice.cc [hunk 2]
```diff
@@ -396,8 +397,23 @@ tuple<PrimeIterator, ExpireIterator, bool> DbSlice::AddOrFind2(const Context& cn
...
+                          (bool(caching_mode_) && !owner_->IsReplica()),
+                          int64_t(memory_budget_ - key.size()),
+                          ssize_t(soft_budget_limit_),
+                          this,
+                          apply_memory_limit};
 
   // If we are over limit in non-cache scenario, just be conservative and throw.
   if (!caching_mode_ && evp.mem_budget() < 0) {
```
Comment (adiholden) [inline src/server/db_slice.cc:419]: @romange Redis does not limit memory when loading rdb file, as I wrote in another PR comment. Do you think we should do the same? If I change this if to check apply_memory_limit we will not fail on memory limit when loading at all. Currently I removed only the conservative memory limit

Comment (adiholden) [reply src/server/db_slice.cc]: @romange Based on our chat, I updated the PR to not apply memory checks when replicating or loading

File: src/server/db_slice.cc [hunk 3]
```diff
@@ -88,9 +88,13 @@ class PrimeEvictionPolicy {
...
-                      DbSlice* db_slice)
-      : db_slice_(db_slice), mem_budget_(mem_budget), soft_limit_(soft_limit), cntx_(cntx),
-        can_evict_(can_evict) {
+                      DbSlice* db_slice, bool apply_memory_limit)
+      : db_slice_(db_slice),
+        mem_budget_(mem_budget),
+        soft_limit_(soft_limit),
+        cntx_(cntx),
+        can_evict_(can_evict),
+        apply_memory_limit_(apply_memory_limit) {
```
Comment (romange) [inline src/server/db_slice.cc:97]: instead of passing apply_memory_limit you can pass `mem_budget` as INT64_MAX

Comment (romange) [reply src/server/db_slice.cc:97]: apply_memory_limit parameter is not needed

Comment (adiholden) [reply src/server/db_slice.cc:97]: there is a problem with this solution as we use the evp.memory_budget() to update db_slice.memory_budget_ so if we pass INT64_MAX we will mess with the db_slice.memory_budget_

**Review by romange — APPROVED** [review]
