### PR TITLE
fix(facade): use WriteRef for large values in meta get response

### LINKED ISSUE #6654: Dragonfly crashes (memcache fuzzing) reply_builder.cc
[crash-000002.tar.gz](https://github.com/user-attachments/files/25361683/crash-000002.tar.gz)

`./dragonfly --port 6379 --memcached_port=11211 --logtostderr --proactor_threads 1 --dbfilename="" --max_bulk_len=1048576`

```
tar xzf crash-000002.tar.gz
cd crash-000002
python3 replay_crash.py crashes 000002 127.0.0.1 11211
```

```
F20260217 11:51:48.938702 49068 reply_builder.cc:149] Check failed: expected_buffer_cap <= kMaxBufferSize (8242 vs. 8192) 
*** Check failure stack trace: ***
    @     0x5555574ccfe5  google::LogMessage::Fail()
    @     0x5555574ccf2b  google::LogMessage::SendToLog()
    @     0x5555574cc6de  google::LogMessage::Flush()
    @     0x5555574d068a  google::LogMessageFatal::~LogMessageFatal()
    @     0x55555722d443  facade::SinkReplyBuilder::Flush()
    @     0x555557232bcd  facade::SinkReplyBuilder::WritePieces<>()
    @     0x55555722e28c  facade::MCReplyBuilder::SendValue()
    @     0x5555569726b4  _ZZN4dfly12_GLOBAL__N_111MGetGenericEN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPNS_14CommandContextEPKNS_7DbSlice12ExpireParamsEENKUlPN6facade16SinkReplyBuilderEE_clESI_
    @     0x55555697ae55  _ZN6facade13ParsedCommand9ReplyWithIZN4dfly12_GLOBAL__N_111MGetGenericEN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPNS2_14CommandContextEPKNS2_7DbSlice12ExpireParamsEEUlPNS_16SinkReplyBuilderEE_EEvOT_
    @     0x555556972f28  dfly::(anonymous namespace)::MGetGeneric()
    @     0x555556973305  dfly::(anonymous namespace)::CmdGAT()
    @     0x5555568244f9  _ZN3fu27abi_4006detail10invocation6invokeIRKPFvN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPN4dfly14CommandContextEEJSC_SF_EEEDTclcl7forwardIT_Efp_Espcl7forwardIT0_Efp0_EEEOSK_DpOSL_
    @     0x5555568197a8  fu2::abi_400::detail::type_erasure::invocation_table::function_trait<>::internal_invoker<>::invoke()
    @     0x555556bfc5bb  _ZNK3fu27abi_4006detail12type_erasure6tables6vtableINS1_8propertyILb0ELb0EJKFvN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPN4dfly14CommandContextEEEEEE6invokeILm0EJPKNS2_13data_accessorERKmSE_SH_EEEDcDpOT0_
    @     0x555556bfc654  _ZN3fu27abi_4006detail12type_erasure7erasureILb1ENS1_6configILb1ELb1ENS_16capacity_defaultEEENS1_8propertyILb0ELb0EJKFvN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPN4dfly14CommandContextEEEEEE6invokeILm0ERKSM_JSG_SJ_EEEDcOT0_DpOT1_
    @     0x555556bfc6d2  fu2::abi_400::detail::type_erasure::invocation_table::operator_impl<>::operator()()
    @     0x555556bf9747  dfly::CommandId::Invoke()
    @     0x555556bad54f  dfly::Service::InvokeCmd()
    @     0x555556bacad0  dfly::Service::DispatchCommand()
    @     0x555556baf3d5  dfly::Service::DispatchMC()
    @     0x555557205b52  facade::Connection::ExecuteMCBatch()
    @     0x5555571fd587  facade::Connection::ParseMemcache()
    @     0x5555571fe48d  facade::Connection::IoLoop()
    @     0x5555571fb2bd  facade::Connection::ConnectionFlow()
    @     0x5555571f8e00  facade::Connection::HandleRequests()
    @     0x555557407565  util::ListenerInterface::RunSingleConnection()
    @     0x5555574050e6  _ZZZN4util17ListenerInterface13RunAcceptLoopEvENKUlvE_clEvENKUlvE_clEv
    @     0x55555740ef2a  _ZSt13__invoke_implIvZZN4util17ListenerInterface13RunAcceptLoopEvENKUlvE_clEvEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @     0x55555740de00  _ZSt8__invokeIZZN4util17ListenerInterface13RunAcceptLoopEvENKUlvE_clEvEUlvE_JEENSt15__invoke_resultIT_JDpT0_EE4typeEOS5_DpOS6_
    @     0x55555740c900  _ZSt12__apply_implIZZN4util17ListenerInterface13RunAcceptLoopEvENKUlvE_clEvEUlvE_St5tupleIJEEJEEDcOT_OT0_St16integer_sequenceImJXspT1_EEE
    @     0x55555740c93a  _ZSt5applyIZZN4util17ListenerInterface13RunAcceptLoopEvENKUlvE_clEvEUlvE_St5tupleIJEEEDcOT_OT0_
    @     0x55555740c9bf  _ZN4util3fb26detail15WorkerFiberImplIZZNS_17ListenerInterface13RunAcceptLoopEvENKUlvE_clEvEUlvE_JEE4run_EON5boost7context5fiberE
*** SIGABRT received at time=1771321909 on cpu 0 ***
PC: @     0x7ffff74c9b2c  (unknown)  pthread_kill
    @     0x55555752c619         64  absl::lts_20250512::WriteFailureInfo()
    @     0x55555752c89d         96  absl::lts_20250512::AbslFailureSignalHandler()
    @     0x7ffff7470330       1776  (unknown)
    @     0x7ffff747027e         32  raise
    @     0x7ffff74538ff        192  abort
    @     0x5555574d80bc        176  google::DumpStackTraceAndExit()
    @     0x5555574ccfe5         16  google::LogMessage::Fail()
    @     0x5555574ccf2b        160  google::LogMessage::SendToLog()
    @     0x5555574cc6de         80  google::LogMessage::Flush()
    @     0x5555574d068a         32  google::LogMessageFatal::~LogMessageFatal()
    @     0x55555722d443        176  facade::SinkReplyBuilder::Flush()
    @     0x555557232bcd        368  facade::SinkReplyBuilder::WritePieces<>()
    @     0x55555722e28c        272  facade::MCReplyBuilder::SendValue()
    @     0x5555569726b4        208  dfly::(anonymous namespace)::MGetGeneric()::{lambda()#1}::operator()()
    @     0x55555697ae55         80  facade::ParsedCommand::ReplyWith<>()
    @     0x555556972f28        432  dfly::(anonymous namespace)::MGetGeneric()
    @     0x555556973305        128  dfly::(anonymous namespace)::CmdGAT()
    @     0x5555568244f9         64  fu2::abi_400::detail::invocation::invoke<>()
    @     0x5555568197a8         96  fu2::abi_400::detail::type_erasure::invocation_table::function_trait<>::internal_invoker<>::invoke()
    @     0x555556bfc5bb        112  fu2::abi_400::detail::type_erasure::tables::vtable<>::invoke<>()
    @     0x555556bfc654        112  fu2::abi_400::detail::type_erasure::erasure<>::invoke<>()
    @     0x555556bfc6d2         80  fu2::abi_400::detail::type_erasure::invocation_table::operator_impl<>::operator()()
    @     0x555556bf9747         48  dfly::CommandId::Invoke()
    @     0x555556bad54f        512  dfly::Service::InvokeCmd()
    @     0x555556bacad0        496  dfly::Service::DispatchCommand()
    @     0x555556baf3d5        528  dfly::Service::DispatchMC()
    @     0x555557205b52        192  facade::Connection::ExecuteMCBatch()
    @     0x5555571fd587         48  facade::Connection::ParseMemcache()
    @     0x5555571fe48d        320  facade::Connection::IoLoop()
    @     0x5555571fb2bd        352  facade::Connection::ConnectionFlow()
    @     0x5555571f8e00        640  facade::Connection::HandleRequests()
    @     0x555557407565        288  util::ListenerInterface::RunSingleConnection()
    @ ... and at least 13 more frames
```

### PR DESCRIPTION
**Pull request by vyavdoshenko**
Meta gets response path in MCReplyBuilder::SendValue wrote the entire value inline via WritePieces, exceeding kMaxBufferSize (8192) for values >8KB. The non-meta path already handled this correctly. Split the write to use WriteRef for large values, matching the non-meta path.

Fixes #6654

### CODE REVIEW

File: src/server/string_family_test.cc [hunk 1]
```diff
@@ -986,6 +987,28 @@ TEST_F(StringFamilyTest, GatViaRedisProtocol) {
   EXPECT_THAT(resp, ErrArg("memcache-only"));
 }
 
+// Meta get with large value should not crash due to buffer overflow.
+TEST_F(StringFamilyTest, MetaGetLargeValue) {
```
Comment (romange) [inline src/server/string_family_test.cc]: but what it is here and not in reply_builder_test.cc?

Comment (vyavdoshenko) [reply src/server/string_family_test.cc]: Moved to reply_builder_test.cc
