### PR TITLE
fix(server): reject negative numkeys in EVAL/EVALSHA to avoid CHECK abort

### LINKED ISSUE #7202: sigabrt in main_service.cc:2071
[crash-000000.tar.gz](https://github.com/user-attachments/files/26957492/crash-000000.tar.gz)

To reproduce:
  1. Extract the archive:
     `tar xzf crash-000000.tar.gz && cd crash-000000`
  2. Start Dragonfly with the exact flags from the fuzz run (repro.env):
```
     MEM_KB=$(grep '^MEM_LIMIT_KB=' repro.env | cut -d= -f2)
     readarray -t DF_FLAGS < <(grep -v '^#' repro.env | grep -v '^MEM_LIMIT_KB=' | grep -v '^$')
     (ulimit -v "$MEM_KB"; exec <path-to-dragonfly> "${DF_FLAGS[@]}") &
```
  3. Replay:
     `python3 replay_crash.py crashes 000000 127.0.0.1 6379`

The crash log:
```
F20260422 09:36:08.550323  4103 main_service.cc:2071] Check failed: absl::SimpleAtoi(ArgS(args, 1), &num_keys) 
*** Check failure stack trace: ***
    @     0xaaaaaccf6648  google::LogMessage::Fail()
    @     0xaaaaaccf6550  google::LogMessage::SendToLog()
    @     0xaaaaaccf5d50  google::LogMessage::Flush()
    @     0xaaaaaccf9a58  google::LogMessageFatal::~LogMessageFatal()
    @     0xaaaaac2d7670  dfly::Service::CallSHA()
    @     0xaaaaac2d74c0  dfly::Service::EvalSha()
    @     0xaaaaac2ddb64  _ZZN4dfly7Service8RegisterEPNS_15CommandRegistryEENKUlN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPNS_14CommandContextEE2_clESB_SD_
    @     0xaaaaac30fd30  _ZN3fu27abi_4006detail10invocation6invokeIRKZN4dfly7Service8RegisterEPNS4_15CommandRegistryEEUlN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPNS4_14CommandContextEE2_JSG_SI_EEEDTclcl7forwardIT_Efp_Espcl7forwardIT0_Efp0_EEEOSM_DpOSN_
    @     0xaaaaac309094  _ZN3fu27abi_4006detail12type_erasure16invocation_table14function_traitIKFvN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPN4dfly14CommandContextEEE16internal_invokerINS2_3boxILb1EZNSE_7Service8RegisterEPNSE_15CommandRegistryEEUlSD_SG_E2_SaISO_EEELb1EE6invokeEPKNS2_13data_accessorEmSD_SG_
    @     0xaaaaac326918  _ZNK3fu27abi_4006detail12type_erasure6tables6vtableINS1_8propertyILb0ELb0EJKFvN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPN4dfly14CommandContextEEEEEE6invokeILm0EJPKNS2_13data_accessorERKmSE_SH_EEEDcDpOT0_
    @     0xaaaaac3269b4  _ZN3fu27abi_4006detail12type_erasure7erasureILb1ENS1_6configILb1ELb1ENS_16capacity_defaultEEENS1_8propertyILb0ELb0EJKFvN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPN4dfly14CommandContextEEEEEE6invokeILm0ERKSM_JSG_SJ_EEEDcOT0_DpOT1_
    @     0xaaaaac326a30  fu2::abi_400::detail::type_erasure::invocation_table::operator_impl<>::operator()()
    @     0xaaaaac323fc0  dfly::CommandId::Invoke()
    @     0xaaaaac2d3b18  dfly::Service::InvokeCmd()
    @     0xaaaaac2d3104  dfly::Service::DispatchCommand()
    @     0xaaaaac2d4b84  dfly::Service::DispatchManyCommands()
    @     0xaaaaac9f8e18  facade::Connection::SquashPipeline()
    @     0xaaaaac9fa724  facade::Connection::AsyncFiber()
    @     0xaaaaac9fbe24  _ZZN6facade10Connection24LaunchAsyncFiberIfNeededEvENKUlvE_clEv
    @     0xaaaaaca07b88  _ZSt13__invoke_implIvZN6facade10Connection24LaunchAsyncFiberIfNeededEvEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @     0xaaaaaca07880  _ZSt8__invokeIZN6facade10Connection24LaunchAsyncFiberIfNeededEvEUlvE_JEENSt15__invoke_resultIT_JDpT0_EE4typeEOS4_DpOS5_
    @     0xaaaaaca074b4  _ZSt12__apply_implIZN6facade10Connection24LaunchAsyncFiberIfNeededEvEUlvE_St5tupleIJEEJEEDcOT_OT0_St16integer_sequenceImJXspT1_EEE
    @     0xaaaaaca074f8  _ZSt5applyIZN6facade10Connection24LaunchAsyncFiberIfNeededEvEUlvE_St5tupleIJEEEDcOT_OT0_
    @     0xaaaaaca07578  _ZN4util3fb26detail15WorkerFiberImplIZN6facade10Connection24LaunchAsyncFiberIfNeededEvEUlvE_JEE4run_EON5boost7context5fiberE
    @     0xaaaaaca0690c  _ZZN4util3fb26detail15WorkerFiberImplIZN6facade10Connection24LaunchAsyncFiberIfNeededEvEUlvE_JEEC4INS0_19FixedStackAllocatorEEESt17basic_string_viewIcSt11char_traitsIcEENS0_13FiberPriorityERKN5boost7context12preallocatedEOT_OS5_ENKUlONSF_5fiberEE_clESN_
    @     0xaaaaaca08578  _ZSt13__invoke_implIN5boost7context5fiberERZN4util3fb26detail15WorkerFiberImplIZN6facade10Connection24LaunchAsyncFiberIfNeededEvEUlvE_JEEC4INS4_19FixedStackAllocatorEEESt17basic_string_viewIcSt11char_traitsIcEENS4_13FiberPriorityERKNS1_12preallocatedEOT_OS9_EUlOS2_E_JS2_EESL_St14__invoke_otherOT0_DpOT1_
    @     0xaaaaaca08340  _ZSt8__invokeIRZN4util3fb26detail15WorkerFiberImplIZN6facade10Connection24LaunchAsyncFiberIfNeededEvEUlvE_JEEC4INS1_19FixedStackAllocatorEEESt17basic_string_viewIcSt11char_traitsIcEENS1_13FiberPriorityERKN5boost7context12preallocatedEOT_OS6_EUlONSG_5fiberEE_JSN_EENSt15__invoke_resultISK_JDpT0_EE4typeESL_DpOSS_
    @     0xaaaaaca081d4  _ZSt6invokeIRZN4util3fb26detail15WorkerFiberImplIZN6facade10Connection24LaunchAsyncFiberIfNeededEvEUlvE_JEEC4INS1_19FixedStackAllocatorEEESt17basic_string_viewIcSt11char_traitsIcEENS1_13FiberPriorityERKN5boost7context12preallocatedEOT_OS6_EUlONSG_5fiberEE_JSN_EENSt13invoke_resultISK_JDpT0_EE4typeESL_DpOSS_
    @     0xaaaaaca07f50  _ZN5boost7context6detail12fiber_recordINS0_5fiberEN4util3fb219FixedStackAllocatorEZNS5_6detail15WorkerFiberImplIZN6facade10Connection24LaunchAsyncFiberIfNeededEvEUlvE_JEEC4IS6_EESt17basic_string_viewIcSt11char_traitsIcEENS5_13FiberPriorityERKNS0_12preallocatedEOT_OSB_EUlOS3_E_E3runEPv
    @     0xaaaaaca07c7c  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberEN4util3fb219FixedStackAllocatorEZNS6_6detail15WorkerFiberImplIZN6facade10Connection24LaunchAsyncFiberIfNeededEvEUlvE_JEEC4IS7_EESt17basic_string_viewIcSt11char_traitsIcEENS6_13FiberPriorityERKNS0_12preallocatedEOT_OSC_EUlOS4_E_EEEEvNS1_10transfer_tE
    @     0xfffff7f90a40  make_fcontext
    @     0xfffff7f90a40  make_fcontext
*** SIGABRT received at time=1776839768 on cpu 0 ***
PC: @     0xfffff7537608  (unknown)  (unknown)
    @     0xaaaaacd592a0         64  absl::lts_20250512::WriteFailureInfo()
    @     0xaaaaacd595b8         96  absl::lts_20250512::AbslFailureSignalHandler()
    @     0xfffff7ffa7d0       4752  (unknown)
    @     0xfffff74ecb3c         64  raise
    @     0xfffff74d7e00        192  abort
    @     0xaaaaacd01b60        208  google::DumpStackTraceAndExit()
    @     0xaaaaaccf6648         16  google::LogMessage::Fail()
    @     0xaaaaaccf6550        144  google::LogMessage::SendToLog()
    @     0xaaaaaccf5d50         80  google::LogMessage::Flush()
    @     0xaaaaaccf9a58         32  google::LogMessageFatal::~LogMessageFatal()
    @     0xaaaaac2d7670        224  dfly::Service::CallSHA()
    @     0xaaaaac2d74c0        144  dfly::Service::EvalSha()
    @     0xaaaaac2ddb64         48  dfly::Service::Register()::{lambda()#4}::operator()()
    @     0xaaaaac30fd30         64  fu2::abi_400::detail::invocation::invoke<>()
    @     0xaaaaac309094         64  fu2::abi_400::detail::type_erasure::invocation_table::function_trait<>::internal_invoker<>::invoke()
    @     0xaaaaac326918         96  fu2::abi_400::detail::type_erasure::tables::vtable<>::invoke<>()
    @     0xaaaaac3269b4        176  fu2::abi_400::detail::type_erasure::erasure<>::invoke<>()
    @     0xaaaaac326a30         32  fu2::abi_400::detail::type_erasure::invocation_table::operator_impl<>::operator()()
    @     0xaaaaac323fc0         80  dfly::CommandId::Invoke()
    @     0xaaaaac2d3b18        512  dfly::Service::InvokeCmd()
    @     0xaaaaac2d3104        528  dfly::Service::DispatchCommand()
    @     0xaaaaac2d4b84        720  dfly::Service::DispatchManyCommands()
    @     0xaaaaac9f8e18        272  facade::Connection::SquashPipeline()
    @     0xaaaaac9fa724        336  facade::Connection::AsyncFiber()
    @     0xaaaaac9fbe24         32  facade::Connection::LaunchAsyncFiberIfNeeded()::{lambda()#1}::operator()()
    @     0xaaaaaca07b88         32  std::__invoke_impl<>()
    @     0xaaaaaca07880         32  std::__invoke<>()
    @     0xaaaaaca074b4         48  std::__apply_impl<>()
    @     0xaaaaaca074f8         48  std::apply<>()
    @     0xaaaaaca07578         96  util::fb2::detail::WorkerFiberImpl<>::run_()
    @     0xaaaaaca0690c         64  util::fb2::detail::WorkerFiberImpl<>::WorkerFiberImpl<>()::{lambda()#1}::operator()()
    @     0xaaaaaca08578         80  std::__invoke_impl<>()
    @ ... and at least 4 more frames
Aborted
```

### PR DESCRIPTION
**Pull request by vyavdoshenko**
`EVALSHA <sha> -0 ...` aborted the server via `CHECK` in `Service::CallSHA`. `EvalValidator` parsed `numkeys` as `int32_t` (which accepts `"-0"` as `0`), while `CallSHA` re-parsed it as `uint32_t` (which rejects a leading `-`), tripping `CHECK(absl::SimpleAtoi(..., &num_keys))`.

Changes:
- Align `EvalValidator` to parse `numkeys` as `uint32_t`, matching the parsing in `Service::CallSHA`. Removes the now-redundant `num_keys < 0` guard - negatives are rejected by `SimpleAtoi<uint32_t>` directly.
- Add regression test `DflyEngineTest.EvalShaNegativeZeroNumKeys` covering both `EVAL` and `EVALSHA`.

Fixes #7202

### CODE REVIEW

**Review by dranikpg — DISMISSED** [review]

File: src/server/main_service.cc [hunk 1]
```diff
@@ -503,12 +503,12 @@ bool IsSHA(string_view str) {
...
   string_view num_keys_str = ArgS(args, 1);
-  int32_t num_keys;
+  uint32_t num_keys;
 
-  if (!absl::SimpleAtoi(num_keys_str, &num_keys) || num_keys < 0)
+  if (!absl::SimpleAtoi(num_keys_str, &num_keys))
     return ErrorReply{facade::kInvalidIntErr};
 
-  if (unsigned(num_keys) > args.size() - 2)
+  if (num_keys > args.size() - 2)
```
Comment (BorysTheDev) [inline src/server/main_service.cc]: try to use CmdArgParser

Comment (vyavdoshenko) [reply src/server/main_service.cc]: fixed

**Review by dranikpg — APPROVED** [review]

**Review by BorysTheDev — APPROVED** [review]
