### PR TITLE
fix: prevent OOM crash in FT.CREATE with huge PREFIX/STOPWORDS count

### LINKED ISSUE #7045: Out of memory abort
[crash-000000.tar.gz](https://github.com/user-attachments/files/26415816/crash-000000.tar.gz)

To reproduce:
  1. Extract the archive:
     `tar xzf crash-000000.tar.gz && cd crash-000000`
  2. Start Dragonfly with the exact flags from the fuzz run (repro.env):
```
     MEM_KB=$(grep '^MEM_LIMIT_KB=' repro.env | cut -d= -f2)
     readarray -t DF_FLAGS < <(grep -v '^#' repro.env | grep -v '^MEM_LIMIT_KB=' | grep -v '^$')
     (ulimit -v "$MEM_KB"; exec ./build-dbg/dragonfly "${DF_FLAGS[@]}") &
```
  3. Replay:
     `python3 replay_crash.py crashes 000000 127.0.0.1 6379`

```
E20260401 19:00:51.939579  1041 generic_family.cc:1995] Unsupported option src
E20260401 19:00:54.014559  1041 generic_family.cc:1995] Unsupported option $.*
mimalloc: warning: thread 0x77C0ECE526C0: unable to allocate OS memory (error: 12 (0x0C), addr: 0x00000000, size: 0x2E90F400000 bytes, align: 0x2000000, commit: 1, allow large: 1)
mimalloc: warning: thread 0x77C0ECE526C0: unable to allocate OS memory (error: 12 (0x0C), addr: 0x00000000, size: 0x2E90F400000 bytes, align: 0x2000000, commit: 1, allow large: 1)
mimalloc: error: thread 0x77C0ECE526C0: unable to allocate memory (3199999999968 bytes)
mimalloc: error: thread 0x77C0ECE526C0: out of memory in 'new'*** SIGABRT received at time=1775059258 on cpu 0 ***
PC: @     0x77c0ed071b2c  (unknown)  pthread_kill
    @     0x63f644136f55         64  absl::lts_20250512::WriteFailureInfo()
    @     0x63f6441371d9         96  absl::lts_20250512::AbslFailureSignalHandler()
    @     0x77c0ed018330       1792  (unknown)
    @     0x77c0ed01827e         32  raise
    @     0x77c0ecffb8ff        192  abort
    @     0x63f643f52d78  850004464  mi_heap_try_new.cold
    @ ... and at least 2 more frames
```

### PR DESCRIPTION
**Pull request by vyavdoshenko**
Fix unbounded memory allocation in FT.CREATE when a user-supplied count in PREFIX or STOPWORDS is larger than available arguments.

Fixes #7045

### CODE REVIEW

File: src/server/search/search_family.cc [hunk 1]
```diff
@@ -227,19 +227,30 @@ ParseResult<bool> ParseOnOption(CmdArgParser* parser, DocIndex* index) {
...
+  for (; i < count && parser->HasNext(); i++) {
     index->prefixes.push_back(parser->Next<std::string>());
   }
+  // If fewer prefixes were consumed than promised, trigger an out-of-bounds error.
+  // This prevents unbounded loops for huge user-supplied counts while
+  // preserving the existing syntax-error behavior for mismatched counts.
+  if (i < count) {
+    parser->Next();  // triggers OUT_OF_BOUNDS
+  }
   return true;
```
Comment (dranikpg) [inline src/server/search/search_family.cc:240]: I remember we have a place like this, I'll create a ParseArray() functioin later

**Review by dranikpg — APPROVED** [review]
