### PR TITLE
fix(server): do not print warning on replica stop/ takeover

### LINKED ISSUE #2481: Remove cancelled replication warning when `repltakeover` succeeds
When `repltakeover` command succeeds it prints the following warning in the logs:

```
W20240125 13:33:56.858635  1302 replica.cc:237] Error stable sync with ... generic:125 Operation canceled
```

This is misleading. `Stable sync` failed because we cancelled the operation and the instance is no longer a replica. We can remove this warning from the `repltakeover` case.

### PR DESCRIPTION
**Pull request by adiholden**
fixes #2481

### CODE REVIEW

File: src/server/replica.cc [hunk 1]
```diff
@@ -234,9 +234,11 @@ void Replica::MainReplicationFb() {
     else
       ec = ConsumeRedisStream();
 
-    LOG(WARNING) << "Error stable sync with " << server().Description() << " " << ec << " "
-                 << ec.message();
     state_mask_.fetch_and(R_ENABLED);
+    if (state_mask_.load() & R_ENABLED) {  // replication was not stopped.
```
Comment (romange) [inline src/server/replica.cc:238]: just use the return value from fetch_and

**Review by kostasrim — APPROVED** [review]
