### PR TITLE
fix: correctly set batching mode during pubsub

### LINKED ISSUE #935: Connection drop on QUIT when busy
The connection is simply dropped when there are commands in the pipeline. Reproduce with a simple nc(1) session as follows.

```
% echo 'subscribe foo\nunsubscribe foo\nquit\n'| nc localhost 6379
% 
```

The server must respond to all three commands before closing the connection.

### PR DESCRIPTION
**Pull request by romange**
Previously we set batch mode when dispatch queue is not empty but dispatch queue could contain other async messages related to pubsub or monitor. Now we enable batching only if there are more pipeline commands in the queue. 

Fixes #935.

### CODE REVIEW

File: src/facade/reply_builder.cc [hunk 1]
```diff
@@ -47,13 +47,19 @@ void SinkReplyBuilder::Send(const iovec* v, uint32_t len) {
...
+      total_size += v[i].iov_len;
+    }
+
+    if (total_size < 8192) {  // Allow batching with up to 8K of data.
+      for (unsigned i = 0; i < len; ++i) {
+        std::string_view src((char*)v[i].iov_base, v[i].iov_len);
+        DVLOG(2) << "Appending to stream " << src;
+        batch_.append(src.data(), src.size());
+      }
+      return;
```
Comment (dranikpg) [inline src/facade/reply_builder.cc:61]: I'd maybe move this magic number to a constant somewhere

**Review by dranikpg — APPROVED** [review]

File: src/facade/reply_builder.cc (hunk 1 above)
Comment (romange) [reply src/facade/reply_builder.cc:61]: will do in the next pr
