### PR TITLE
fix: validate stream command arguments to prevent crashes

### LINKED ISSUE #6714: Dragonfly crashes
[crash-000000.tar.gz](https://github.com/user-attachments/files/25493658/crash-000000.tar.gz)

```
tar xzf crash-000000.tar.gz
cd crash-000000
python3 replay_crash.py crashes 000000
```

```
F20260223 17:23:59.207649 34398 init.cc:28] [/home/builder/dragonfly/build/_deps/abseil_cpp-src/absl/types/span.h:335]: assert(false && "i < size()") failed!
*** Check failure stack trace: ***
    @     0x5f63f3e878c5  google::LogMessage::Fail()
    @     0x5f63f3e8780b  google::LogMessage::SendToLog()
    @     0x5f63f3e86fbe  google::LogMessage::Flush()
    @     0x5f63f3e8af6a  google::LogMessageFatal::~LogMessageFatal()
    @     0x5f63f2ede46a  __assert_fail
    @     0x5f63f2f2574c  _ZZNK4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEixEmENKUlvE_clEv
    @     0x5f63f2f25796  absl::lts_20250512::Span<>::operator[]()
    @     0x5f63f2f23966  facade::ArgS()
    @     0x5f63f3482098  dfly::CmdXPending()
    @     0x5f63f31d95d5  _ZN3fu27abi_4006detail10invocation6invokeIRKPFvN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPN4dfly14CommandContextEEJSC_SF_EEEDTclcl7forwardIT_Efp_Espcl7forwardIT0_Efp0_EEEOSK_DpOSL_
    @     0x5f63f31ce884  fu2::abi_400::detail::type_erasure::invocation_table::function_trait<>::internal_invoker<>::invoke()
    @     0x5f63f35aca2b  _ZNK3fu27abi_4006detail12type_erasure6tables6vtableINS1_8propertyILb0ELb0EJKFvN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPN4dfly14CommandContextEEEEEE6invokeILm0EJPKNS2_13data_accessorERKmSE_SH_EEEDcDpOT0_
    @     0x5f63f35acac4  _ZN3fu27abi_4006detail12type_erasure7erasureILb1ENS1_6configILb1ELb1ENS_16capacity_defaultEEENS1_8propertyILb0ELb0EJKFvN4absl12lts_202505124SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEEPN4dfly14CommandContextEEEEEE6invokeILm0ERKSM_JSG_SJ_EEEDcOT0_DpOT1_
    @     0x5f63f35acb42  fu2::abi_400::detail::type_erasure::invocation_table::operator_impl<>::operator()()
    @     0x5f63f35a9bb3  dfly::CommandId::Invoke()
    @     0x5f63f355d933  dfly::Service::InvokeCmd()
    @     0x5f63f371cd87  dfly::MultiCommandSquasher::SquashedHopCb()
    @     0x5f63f371d2fe  _ZZN4dfly20MultiCommandSquasher15ExecuteSquashedEPN6facade17RedisReplyBuilderEENUlvE_clEv
    @     0x5f63f372151e  _ZSt13__invoke_implIvRZN4dfly20MultiCommandSquasher15ExecuteSquashedEPN6facade17RedisReplyBuilderEEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @     0x5f63f37213ac  _ZSt10__invoke_rIvRZN4dfly20MultiCommandSquasher15ExecuteSquashedEPN6facade17RedisReplyBuilderEEUlvE_JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EES8_E4typeEOS9_DpOSA_
    @     0x5f63f3721110  _ZNSt17_Function_handlerIFvvEZN4dfly20MultiCommandSquasher15ExecuteSquashedEPN6facade17RedisReplyBuilderEEUlvE_E9_M_invokeERKSt9_Any_data
    @     0x5f63f2ee13a2  std::function<>::operator()()
    @     0x5f63f3e16a6c  util::fb2::FiberQueue::Run()
    @     0x5f63f39d91fd  _ZZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEENKUlvE_clEv
    @     0x5f63f39da3b5  _ZSt13__invoke_implIvZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @     0x5f63f39da13a  _ZSt8__invokeIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_JEENSt15__invoke_resultIT_JDpT0_EE4typeEOS8_DpOS9_
    @     0x5f63f39d9f48  _ZSt12__apply_implIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_St5tupleIJEEJEEDcOT_OT0_St16integer_sequenceImJXspT1_EEE
    @     0x5f63f39d9f82  _ZSt5applyIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_St5tupleIJEEEDcOT_OT0_
    @     0x5f63f39d9fff  _ZN4util3fb26detail15WorkerFiberImplIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_JEE4run_EON5boost7context5fiberE
    @     0x5f63f39d9b7d  _ZZN4util3fb26detail15WorkerFiberImplIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_JEEC4INS0_19FixedStackAllocatorEEES8_NS0_13FiberPriorityERKN5boost7context12preallocatedEOT_OS9_ENKUlONSF_5fiberEE_clESN_
    @     0x5f63f39dacf6  _ZSt13__invoke_implIN5boost7context5fiberERZN4util3fb26detail15WorkerFiberImplIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_JEEC4INS4_19FixedStackAllocatorEEESC_NS4_13FiberPriorityERKNS1_12preallocatedEOT_OSD_EUlOS2_E_JS2_EESL_St14__invoke_otherOT0_DpOT1_
    @     0x5f63f39dab21  _ZSt8__invokeIRZN4util3fb26detail15WorkerFiberImplIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_JEEC4INS1_19FixedStackAllocatorEEES9_NS1_13FiberPriorityERKN5boost7context12preallocatedEOT_OSA_EUlONSG_5fiberEE_JSN_EENSt15__invoke_resultISK_JDpT0_EE4typeESL_DpOSS_
*** SIGABRT received at time=1771860239 on cpu 5 ***
PC: @     0x7d5d0074cb2c  (unknown)  pthread_kill
    @     0x5f63f3ee6ef5         64  absl::lts_20250512::WriteFailureInfo()
    @     0x5f63f3ee7179         96  absl::lts_20250512::AbslFailureSignalHandler()
    @     0x7d5d006f3330       1776  (unknown)
    @     0x7d5d006f327e         32  raise
    @     0x7d5d006d68ff        192  abort
    @     0x5f63f3e9299c        176  google::DumpStackTraceAndExit()
    @     0x5f63f3e878c5         16  google::LogMessage::Fail()
    @     0x5f63f3e8780b        160  google::LogMessage::SendToLog()
    @     0x5f63f3e86fbe         80  google::LogMessage::Flush()
    @     0x5f63f3e8af6a         32  google::LogMessageFatal::~LogMessageFatal()
    @     0x5f63f2ede46a        160  __assert_fail
    @     0x5f63f2f2574c         32  absl::lts_20250512::Span<>::operator[]()::{lambda()#1}::operator()()
    @     0x5f63f2f25796         48  absl::lts_20250512::Span<>::operator[]()
    @     0x5f63f2f23966         64  facade::ArgS()
    @     0x5f63f3482098        480  dfly::CmdXPending()
    @     0x5f63f31d95d5         64  fu2::abi_400::detail::invocation::invoke<>()
    @     0x5f63f31ce884         96  fu2::abi_400::detail::type_erasure::invocation_table::function_trait<>::internal_invoker<>::invoke()
    @     0x5f63f35aca2b        112  fu2::abi_400::detail::type_erasure::tables::vtable<>::invoke<>()
    @     0x5f63f35acac4        112  fu2::abi_400::detail::type_erasure::erasure<>::invoke<>()
    @     0x5f63f35acb42         80  fu2::abi_400::detail::type_erasure::invocation_table::operator_impl<>::operator()()
    @     0x5f63f35a9bb3         48  dfly::CommandId::Invoke()
    @     0x5f63f355d933        512  dfly::Service::InvokeCmd()
    @     0x5f63f371cd87       1216  dfly::MultiCommandSquasher::SquashedHopCb()
    @     0x5f63f371d2fe        208  dfly::MultiCommandSquasher::ExecuteSquashed()::{lambda()#1}::operator()()
    @     0x5f63f372151e         32  std::__invoke_impl<>()
    @     0x5f63f37213ac         32  std::__invoke_r<>()
    @     0x5f63f3721110         32  std::_Function_handler<>::_M_invoke()
    @     0x5f63f2ee13a2         32  std::function<>::operator()()
    @     0x5f63f3e16a6c        240  util::fb2::FiberQueue::Run()
    @     0x5f63f39d91fd         32  dfly::TaskQueue::Start()::{lambda()#1}::operator()()
    @     0x5f63f39da3b5         32  std::__invoke_impl<>()
    @     0x5f63f39da13a         32  std::__invoke<>()
    @ ... and at least 10 more frames
[1]    34392 IOT instruction (core dumped)  ./dragonfly --dbfilename= --logtostderr 2>&1
```

Found in PR check: https://github.com/dragonflydb/dragonfly/actions/runs/22307615686/job/64530799451?pr=6703

### PR DESCRIPTION
**Pull request by vyavdoshenko**
Fix two crashes found by the fuzzer.

1. XPENDING with missing group name — arity was -2 (min 1 arg), but the handler unconditionally accesses the second argument. Changed arity to -3.

2. XREADGROUP with empty consumer name — empty string passed validation but hit `CHECK(!name.empty())` in StreamCreateConsumer. Added an early check in ParseReadArgsOrReply. (This crash was found by fuzzing the CI action in this PR)

Fixes #6714

### CODE REVIEW

File: src/server/stream_family.cc [hunk 1]
```diff
@@ -2258,6 +2258,10 @@ std::optional<ReadOpts> ParseReadArgsOrReply(CmdArgList args, bool read_group,
     id_indx++;
     opts.group_name = ArgS(args, id_indx);
     opts.consumer_name = ArgS(args, ++id_indx);
+    if (opts.consumer_name.empty()) {
+      builder->SendError("consumer name can't be empty", kSyntaxErr);
```
Comment (romange) [inline src/server/stream_family.cc]:
```suggestion
      builder->SendError("consumer name can't be empty", kSyntaxErrType);
```

**Review by romange — APPROVED** [review]
