### PR TITLE
fix(json_family): Remove expiry of existing keys in JSON.SET

### LINKED ISSUE #5653: Dragonfly Crash After Changing Record Type to JSON and Setting TTL
**Describe the bug**
Dragonfly crashes when attempting to set a TTL on a key after its data type has been changed from a string to a JSON object. 

**To Reproduce**
1. Start Dragonfly:`docker run --rm -p 6379:6379 --ulimit memlock=-1  docker.dragonflydb.io/dragonflydb/dragonfly:latest`
2. Connect to Dragonfly: `redis-cli`
3. Execute the following Redis commands in sequence:
```
SET test foo EX 100    # Set 'test' as a string with a 100-second TTL
JSON.SET test $ '{}'   # Change 'test' to a JSON object
EXPIRE test 100        # Attempt to set a 100-second TTL (CRASH OCCURS HERE)
```
Error Logs:
```
I20250811 12:26:02.859664     1 init.cc:127] dragonfly running in opt mode.
I20250811 12:26:02.859730     1 dfly_main.cc:757] Starting dragonfly df-v1.32.0-960ddf41c41ce27d5c038856957b4d740629f94b
                   .--::--.                   
   :+*=:          =@@@@@@@@=          :+*+:   
  %@@@@@@%*=.     =@@@@@@@@-     .=*%@@@@@@#  
  @@@@@@@@@@@@#+-. .%@@@@#. .-+#@@@@@@@@@@@%  
  -@@@@@@@@@@@@@@@@*:#@@#:*@@@@@@@@@@@@@@@@-  
    :+*********####-%@%%@%-####********++.    
   .%@@@@@@@@@@@@@%:@@@@@@:@@@@@@@@@@@@@@%    
   .@@@@@@@@%*+-:   =@@@@=  .:-+*%@@@@@@@%.   
     =*+-:           ###*          .:-+*=     
                     %@@%                     
                     *@@*                     
                     +@@=                     
                     :##:                     
                     :@@:                     
                      @@                      
                      ..                      
* Logs will be written to the first available of the following paths:
/tmp/dragonfly.*
./dragonfly.*
* For the available flags type dragonfly [--help | --helpfull]
* Documentation can be found at: https://www.dragonflydb.io/docs
I20250811 12:26:02.859808     1 dfly_main.cc:799] maxmemory has not been specified. Deciding myself....
I20250811 12:26:02.859820     1 dfly_main.cc:808] Found 7.29GiB available memory. Setting maxmemory to 5.83GiB
W20250811 12:26:02.859839     1 dfly_main.cc:380] Weird error 1 switching to epoll
I20250811 12:26:02.860366     1 proactor_pool.cc:149] Running 4 io threads
I20250811 12:26:02.862628     1 server_family.cc:1073] Host OS: Linux 6.8.0-50-generic aarch64 with 4 threads
I20250811 12:26:02.862906     1 snapshot_storage.cc:186] Load snapshot: Searching for snapshot in directory: "/data"
W20250811 12:26:02.862937     1 server_family.cc:1173] Load snapshot: No snapshot found
I20250811 12:26:02.875483    12 listener_interface.cc:102] sock[11] AcceptServer - listening on 0.0.0.0:6379
F20250811 12:27:01.479359    14 db_slice.cc:948] Check failed: db.expire.Insert(main_it->first.AsRef(), ExpirePeriod(delta)).second 
*** Check failure stack trace: ***
    @     0xc304ad11ee2c  google::LogMessage::SendToLog()
    @     0xc304ad117d10  google::LogMessage::Flush()
    @     0xc304ad11964c  google::LogMessageFatal::~LogMessageFatal()
    @     0xc304acb91d54  dfly::DbSlice::AddExpire()
    @     0xc304acb9c84c  dfly::DbSlice::UpdateExpire()
    @     0xc304ac560da4  dfly::(anonymous namespace)::OpExpire()
    @     0xc304ac56116c  _ZN4absl12lts_2025051219functional_internal12InvokeObjectIZN4dfly13GenericFamily6ExpireENS0_4SpanIKSt17basic_string_viewIcSt11char_traitsIcEEEERKNS3_14CommandContextEEUlPNS3_11TransactionEPNS3_11EngineShardEE_NSF_14RunnableResultEJSG_SI_EEET0_NS1_7VoidPtrEDpNS1_8ForwardTIT1_E4typeE
    @     0xc304acbd01c8  dfly::Transaction::RunCallback()
    @     0xc304acbd09b0  dfly::Transaction::ScheduleInShard()
    @     0xc304acbd29a8  dfly::Transaction::ScheduleBatchInShard()
    @     0xc304acd7e3c0  util::fb2::FiberQueue::Run()
    @     0xc304acc222fc  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberEN4util3fb219FixedStackAllocatorEZNS6_6detail15WorkerFiberImplIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_JEEC4IS7_EESF_NS6_13FiberPriorityERKNS0_12preallocatedEOT_OSG_EUlOS4_E_EEEEvNS1_10transfer_tE
    @     0xc304ace43dec  make_fcontext
*** SIGABRT received at time=1754915221 on cpu 3 ***
PC: @     0xfc42d172f1f0  (unknown)  (unknown)
    @     0xc304ad177784        464  absl::lts_20250512::AbslFailureSignalHandler()
    @     0xfc42d19ac8f8       4960  (unknown)
    @     0xfc42d16ea67c        208  gsignal
    @     0xfc42d16d7130         32  abort
    @     0xc304ad1248ec        336  google::DumpStackTraceAndExit()
    @     0xc304ad11830c        192  google::LogMessage::Fail()
    @     0xc304ad11ee2c         16  google::LogMessage::SendToLog()
    @     0xc304ad117d10        208  google::LogMessage::Flush()
    @     0xc304ad11964c         80  google::LogMessageFatal::~LogMessageFatal()
    @     0xc304acb91d54         16  dfly::DbSlice::AddExpire()
    @     0xc304acb9c84c        256  dfly::DbSlice::UpdateExpire()
    @     0xc304ac560da4        192  dfly::(anonymous namespace)::OpExpire()
    @     0xc304ac56116c        496  absl::lts_20250512::functional_internal::InvokeObject<>()
    @     0xc304acbd01c8         96  dfly::Transaction::RunCallback()
    @     0xc304acbd09b0        288  dfly::Transaction::ScheduleInShard()
    @     0xc304acbd29a8        592  dfly::Transaction::ScheduleBatchInShard()
    @     0xc304acd7e3c0         96  util::fb2::FiberQueue::Run()
    @     0xc304acc222fc        304  boost::context::detail::fiber_entry<>()
[failure_signal_handler.cc : 377] RAW: Signal 5 raised at PC=0xfc42d16d71ec while already in AbslFailureSignalHandler()
*** SIGTRAP received at time=1754915221 on cpu 3 ***
PC: @     0xfc42d16d71ec  (unknown)  abort
    @     0xc304ad177784        464  absl::lts_20250512::AbslFailureSignalHandler()
    @     0xfc42d19ac8f8       4960  (unknown)
    @     0xc304ad1248ec        336  google::DumpStackTraceAndExit()
    @     0xc304ad11830c        192  google::LogMessage::Fail()
    @     0xc304ad11ee2c         16  google::LogMessage::SendToLog()
    @     0xc304ad117d10        208  google::LogMessage::Flush()
    @     0xc304ad11964c         80  google::LogMessageFatal::~LogMessageFatal()
    @     0xc304acb91d54         16  dfly::DbSlice::AddExpire()
    @     0xc304acb9c84c        256  dfly::DbSlice::UpdateExpire()
    @     0xc304ac560da4        192  dfly::(anonymous namespace)::OpExpire()
    @     0xc304ac56116c        496  absl::lts_20250512::functional_internal::InvokeObject<>()
    @     0xc304acbd01c8         96  dfly::Transaction::RunCallback()
    @     0xc304acbd09b0        288  dfly::Transaction::ScheduleInShard()
    @     0xc304acbd29a8        592  dfly::Transaction::ScheduleBatchInShard()
    @     0xc304acd7e3c0         96  util::fb2::FiberQueue::Run()
    @     0xc304acc222fc        304  boost::context::detail::fiber_entry<>()
```

Expected Behavior:

The EXPIRE test 100 command should successfully set a TTL of 100 seconds for the test key, even after its data type has been changed to JSON.

Actual Behavior:

Dragonfly crashes after executing the EXPIRE test 100 command, following the sequence of commands outlined above.

**Environment (please complete the following information):**
 - OS: Linux / Darwin (Production / Local Development)
 - Containerized?: Kubernetes / Docker
 - Dragonfly Version: v1.31.2, also occurs with latest version v1.32.0

**Additional context**
The issue does not occur when changing a record from JSON to a string and then setting the TTL. 
The following sequence works without error:
```
JSON.SET test $ '{}'    # Set 'test' as a JSON object
EXPIRE test 100         # Set a 100-second TTL
SET test foo EX 100     # Change 'test' to a string with a 100-second TTL (No crash)
```

### PR DESCRIPTION
**Pull request by mkaruza**
If key exists and it has expiry after we use JSON.SET expiry object will not be removed. Now when creating JSON object with same name remove previous expiry object if it exists.

Fixes #5653

### CODE REVIEW

File: src/server/json_family_test.cc [hunk 1]
```diff
@@ -3226,4 +3226,15 @@ TEST_F(JsonFamilyTest, JsonKeysWithDots) {
...
+  auto resp = Run({"SET", "key", "foo", "EX", "1000"});
+  ASSERT_THAT(resp, "OK");
+  resp = Run({"JSON.SET", "key", "$", "{}"});
+  ASSERT_THAT(resp, "OK");
+  resp = Run({"EXPIRE", "key", "100"});
+  ASSERT_THAT(resp, IntArg(1));
+  resp = Run({"TTL", "key"});
+  EXPECT_THAT(resp.GetInt(), 100);
+}
+
```
Comment (BorysTheDev) [inline src/server/json_family_test.cc]: I don't see the check of the behavior that you declare

Comment (kostasrim) [reply src/server/json_family_test.cc]: Run({"EXPIRE", "key", "100"}); 

Should crash here

Comment (kostasrim) [inline src/server/json_family_test.cc]:
```suggestion
  auto resp = Run("SET key foo EX 1000");
  resp = Run("JSON.SET key $ {}");
}

```

Comment (kostasrim) [reply src/server/json_family_test.cc]: notice now `Run()` accepts a `string view` of the full command. 

No need to split it in multiple sub strings. I added that constructor recently!

Comment (mkaruza) [reply src/server/json_family_test.cc]: @BorysTheDev as @kostasrim pointed it crashes at that point when you update EXPIRE of object

File: src/server/json_family.cc [hunk 2]
```diff
@@ -505,6 +505,8 @@ OpStatus SetFullJson(const OpArgs& op_args, string_view key, string_view json_st
     return OpStatus::INVALID_JSON;
   }
 
+  op_args.GetDbSlice().RemoveExpire(op_args.db_cntx.db_index, it_res->it);
```
Comment (BagritsevichStepan) [inline src/server/json_family.cc:508]: The fix itself is correct, but according to what I got from ChatGPT, each JSON command that modifies the JSON should remove the TTL. So, maybe we need to add this to other commands too. I’m not sure if this is correct, and I will verify/fix it after my vacation

File: src/server/json_family_test.cc (hunk 1 above)
Comment (BorysTheDev) [reply src/server/json_family_test.cc]: @mkaruza @kostasrim in the description, I see "Remove expiry of existing keys in JSON.SET" so I wait to see the next check
```
resp = Run({"JSON.SET", "key", "$", "{}"});
  resp = Run({"TTL", "key"});
  EXPECT_THAT(resp.GetInt(), -1);
```

File: src/server/json_family.cc (hunk 2 above)
Comment (BagritsevichStepan) [reply src/server/json_family.cc:508]: I have created ticket for this: #5671

File: src/server/json_family_test.cc (hunk 1 above)
Comment (mkaruza) [reply src/server/json_family_test.cc]: Will add that case also
