### PR TITLE
fix(replication): Correctly replicate commands even when OOM

### LINKED ISSUE #2381: Dragonfly replica inconsistent with master data
**Describe the bug**
When master executes a write command the command is send to replica (journal change). If the callback on master side returns error we still send it to replica which can result in inconsistency between master and replica. f.e if master returned with oom when executing the command replica will still execute the command. 

**To Reproduce**
```python
@pytest.mark.asyncio
async def test_policy_based_eviction_propagation(df_local_factory, df_seeder_factory):
    master = df_local_factory.create(
        proactor_threads=1,
        cache_mode="true",
        maxmemory="256mb",
        enable_heartbeat_eviction="false"
    )
    replica = df_local_factory.create(proactor_threads=1)
    df_local_factory.start_all([master, replica])
    df_local_factory.start_all([master])

    c_master = master.client()
    c_replica = replica.client()

    await c_master.execute_command("DEBUG POPULATE 6000 size 44000")

    await c_replica.execute_command(f"REPLICAOF localhost {master.port}")
    await wait_available_async(c_replica)

    seeder = df_seeder_factory.create(port=master.port, keys=500, val_size=1000, stop_on_failure=False)
    await seeder.run(target_deviation=0.1)

    info = await c_master.info("stats")
    assert info["evicted_keys"] > 0, "Weak testcase: policy based eviction was not triggered."

    await check_all_replicas_finished([c_replica], c_master)
    keys_master = await c_master.execute_command("keys *")
    keys_replica = await c_replica.execute_command("keys *")
    
    assert set(keys_master) != set(keys_replica):
    await disconnect_clients(c_master, *[c_replica])
```

**Expected behavior**
master will not replicate a command that returned error on callback execution

### PR DESCRIPTION
**Pull request by chakaz**
Before this change, OOM in shard callbacks could have led to data inconsistency between the master and the replica. For example, commands which mutated data on 1 shard but failed on another, like `LMOVE`.

After this change, callbacks that result in an OOM will correctly replicate their work (none, partial or complete) to replicas.

Note that `MSET` and `MSETNX` required special handling, in that they are the only commands that can _create_ multiple keys, and so some of them can fail.

Fixes #2381

### CODE REVIEW

File: src/server/transaction.cc [hunk 1]
```diff
@@ -1477,14 +1481,22 @@ void Transaction::LogAutoJournalOnShard(EngineShard* shard) {
...
-    return;
-
   auto journal = shard->journal();
   if (journal == nullptr)
     return;
 
+  if (result.status != OpStatus::OK) {
+    // We log NOOP even for NO_AUTOJOURNAL commands because the non-success status could have been
+    // due to OOM in a single shard, while other shards succeeded
+    journal->RecordEntry(txid_, journal::Op::NOOP, db_index_, unique_shard_cnt_,
```
Comment (adiholden) [inline src/server/transaction.cc:1491]: Check out JournalStreamer::Start.
It does not replicate NOOP, but instead today we use this to trigger journal writes to sink.  so this will not get to replica , did you run your tests with the flag  enable_multi_shard_sync set to true ? I think this will fail

File: src/server/string_family.cc [hunk 2]
```diff
@@ -338,21 +338,38 @@ int64_t AbsExpiryToTtl(int64_t abs_expiry_time, bool as_milli) {
...
     OpResult<optional<string>> res = sg.Set(params, args[i], args[i + 1]);
     if (res.status() != OpStatus::OK) {  // OOM for example.
-      return res.status();
+      success->store(false);
+      break;
     }
   }
 
-  return OpStatus::OK;
+  if (auto journal = op_args.shard->journal(); journal) {
```
Comment (adiholden) [inline src/server/string_family.cc:357]: can you use RecordJournal from common.h 
note that you should not allow await (preemt in the callback) when you write to journal from the callback

File: tests/dragonfly/replication_test.py [hunk 3]
```diff
@@ -1919,3 +1919,41 @@ async def test_heartbeat_eviction_propagation(df_local_factory):
     keys_replica = await c_replica.execute_command("keys *")
     assert set(keys_master) == set(keys_replica)
     await disconnect_clients(c_master, *[c_replica])
+
+
+@pytest.mark.asyncio
+async def test_policy_based_eviction_propagation(df_local_factory, df_seeder_factory):
```
Comment (adiholden) [inline tests/dragonfly/replication_test.py:1925]: We have this test above, I asked Yue on his PR to add it and mark it as skip. You can remove remove his test.
Note that there is unsupported_types in seeder in his test because another bug that Kostas fixed

File: src/server/transaction.cc (hunk 1 above)
Comment (chakaz) [reply src/server/transaction.cc:1491]: Nice catch.
How about I'll send a `PING`, but mark the opcode as `COMMAND` instead? Do you see any problem with that?

Comment (chakaz) [reply src/server/transaction.cc:1491]: btw it does pass with `--df enable_multi_shard_sync=true`

File: src/server/string_family.cc [hunk 4]
```diff
@@ -338,21 +338,37 @@ int64_t AbsExpiryToTtl(int64_t abs_expiry_time, bool as_milli) {
...
+    journal::Entry::Payload payload;
+    if (i == 0) {
+      // All shards must record the tx was executed for the replica to execute it, so we send a PING
+      // in case nothing was changed
+      payload = make_pair("PING", ArgSlice());
+    } else {
+      // journal [0, i)
+      payload = make_pair("MSET", ArgSlice(&args[0], i));
+    }
+    tx->LogJournalOnShard(op_args.shard, std::move(payload), tx->GetUniqueShardCnt(), false, false);
```
Comment (adiholden) [inline src/server/string_family.cc:370]: I see that you still dont use RecordJournal function. why?

File: src/server/transaction.cc (hunk 1 above)
Comment (adiholden) [reply src/server/transaction.cc:1491]: I think PING is ok.
Oh I see that the test is using proactor_threads=1 so there is only one shard.
Lets change the test to run on 2 shards. you will need to increase the max memory size as well

File: src/server/string_family.cc (hunk 4 above)
Comment (chakaz) [reply src/server/string_family.cc:370]: I left this for later and did it now :)

File: tests/dragonfly/replication_test.py (hunk 3 above)
Comment (chakaz) [reply tests/dragonfly/replication_test.py:1879]: it messes up the diff, but the change is really only adding the test below

File: src/server/transaction.cc (hunk 1 above)
Comment (adiholden) [reply src/server/transaction.cc:1481]: I still see the test with proactor_threads=1, can you change it ? see my comment above

Comment (chakaz) [reply src/server/transaction.cc:1481]: Sorry, I forgot about it :(
Done now.

**Review by adiholden — APPROVED** [review]
