### PR TITLE
fix(tiering): wait for IO before test teardown

### LINKED ISSUE #3078: tiering tests: wait for cleanup before dropping
https://github.com/dragonflydb/dragonfly/actions/runs/9228297378/job/25392041014?pr=3076

Tests segfault because the disk storage is dropped before the delete finishes

### PR DESCRIPTION
**Pull request by dranikpg**
Fixes #3078 

The better way would be to wait for all SQE to be handled... but this works too

### CODE REVIEW

File: src/server/tiered_storage_test.cc [hunk 1]
```diff
@@ -47,6 +47,15 @@ class TieredStorageTest : public BaseFamilyTest {
 
     BaseFamilyTest::SetUp();
   }
+
+  void TearDown() override {
+    TieredStats stats;
+    do {
+      util::ThisFiber::SleepFor(20ms);
```
Comment (romange) [inline src/server/tiered_storage_test.cc:54]: fine but what about production use-case? if we shutdown with io requests in flight we may get random segfaults

**Review by romange — APPROVED** [review]

**Comment by dranikpg** [comment]
You're right, let's try this

File: src/server/tiering/disk_storage.cc [hunk 2]
```diff
@@ -77,6 +76,10 @@ std::error_code DiskStorage::Open(std::string_view path) {
 }
 
 void DiskStorage::Close() {
+  using namespace std::chrono_literals;
+  while (pending_ops_ > 0)
```
Comment (romange) [inline src/server/tiering/disk_storage.cc:80]: nit: it's a potential deadlock point. I suggest to use `LOG_EVERY_T` to at least bring visibility in case it gets stuck there.

**Review by romange — APPROVED** [review]

File: src/server/tiering/disk_storage.cc (hunk 2 above)
Comment (dranikpg) [reply src/server/tiering/disk_storage.cc:80]: Added to my to-do list, DEBUG STACKTRACE should point it out easily if it does

Comment (romange) [reply src/server/tiering/disk_storage.cc:80]: debug stacktrace won't work during the shutdown flow
